docs/apache-hive-catalog.md, docs/docker-image-details.md, docs/gravitino-server-config.md, docs/how-to-sign-releases.md, docs/how-to-test.md, docs/iceberg-rest-service.md, docs/index.md, docs/jdbc-mysql-catalog.md, docs/jdbc-postgresql-catalog.md, docs/lakehouse-iceberg-catalog.md, docs/manage-metadata-using-gravitino.md, docs/metrics.md, docs/overview.md, docs/security.md
Minor formating and changes to fit with the style guide.
For consistency.
Fix: # (issue)
N/A
local build
=> [Minor] Minor formating and changes to fit with the style guide.

README.md
Fix the wrong link in the `README.md`
If we don't have this pr,  It will report an error if we click the lick
No.
I click the link locally.
=> [MINOR] fix(docs): Fix the wrong link in the `README.md`

docs/apache-hive-catalog.md, docs/iceberg-rest-service.md, docs/jdbc-mysql-catalog.md, docs/jdbc-postgresql-catalog.md, docs/lakehouse-iceberg-catalog.md
1. add "Manage Metadata Using Gravitino" link to lakehouse iceberg document
2. merge info blocks
more user friendly
no
just docs
=> [MINOR] docs(lakehouse-iceberg):  improvement lakehouse iceberg document

docs/index.md
Fix link of REST API page
link of REST API page will be changed
no
no need
=> [MINOR] fix(docs): Fix link of REST API page

docs/getting-started.md, docs/how-to-build.md, docs/how-to-install.md
This is a follow-up work to change the docs to support multiple versions of JDK.
This is a subtask of supporting multiple JDKs for Gravitino.
Fix: #1181
No.
N/A
=> [#1181] feat(doc): Improve the doc to support multiple jdk version

docs/manage-metadata-using-gravitino.md, trino-connector/build.gradle.kts
- Add a description about parameter `cascade` when dropping the schema 
- Please provide more details on how to drop the table and clarify `dropTable` and `purgeTable` 
Make the document more user-friendly.
N/A
N/A
=> [Minor] docs: Add more details about dropping schema and tables

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/config/JdbcConfig.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/utils/DataSourceUtils.java, catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlSchemaOperations.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergConfig.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/ops/IcebergTableOps.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/utils/IcebergCatalogUtil.java, common/src/main/java/com/datastrato/gravitino/config/ConfigConstants.java, common/src/main/java/com/datastrato/gravitino/config/ConfigEntry.java, common/src/test/java/com/datastrato/gravitino/config/TestConfigEntry.java, server-common/src/main/java/com/datastrato/gravitino/server/auth/AuthenticationFilter.java, server-common/src/main/java/com/datastrato/gravitino/server/auth/OAuth2TokenAuthenticator.java, server-common/src/main/java/com/datastrato/gravitino/server/auth/OAuthConfig.java, server-common/src/main/java/com/datastrato/gravitino/server/web/JettyServerConfig.java, server/src/main/java/com/datastrato/gravitino/server/ServerConfig.java, server/src/main/java/com/datastrato/gravitino/server/web/ConfigServlet.java
Now, ConfigEntry lacks the ability of check config options. So we add the support of this feature referring to Spark.
Fix: #1221 
No.
Add new ut.
=> [#1221] improvement(common): Add the method `checkValue` for the ConfigEntry

docs/how-to-install.md, docs/iceberg-rest-service.md, docs/index.md, docs/jdbc-mysql-catalog.md, docs/jdbc-postgresql-catalog.md, docs/lakehouse-iceberg-catalog.md
This PR slightly changes the order the docs in index doc.
To make the document clearer.
No.
N/A
=> [MINOR] improve(doc): Improve the index to reorganize the order of the docs

NOTICE, NOTICE.bin
Update year in the NOTICE files. Other files should be updated as needed.
It's a new year.
Fix: # N/A
N/A
Built locally.
=> Happy new year!

docs/docker-image-details.md, web/README.md
Improve English and add warning that web UI only works in Chrome
Clarity and to improve users what browser to use.
N/A
Built locally.
=> [MINOR] doc: Improve English and add warning that web UI only works in Chrome

CONTRIBUTING.md
fix typo in URL
so user have correct URL
Fix: # N/A
N/A
checked URL in browser
=> [MINOR] fix typo in URL

README.md
Add note on supported platforms in README.
Make it clearer to users what OSs are supported.
N/A
N/A
=> [MINOR] Add note on supported build systems

integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/service/MysqlService.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/service/PostgreSqlService.java
add missing headers and license
Fix: #1267
N/A
N/A (no code change, only add missing license)
=> [#1267] fix: Add missing headers and license

README.md
Add badges to README file
Fix: #1346 
No
No need.
=> [#1346] improvement : Add badges

web/app/metalakes/MetalakeView.js, web/lib/store/metalakes/index.js
Rectify the issue of null being included in the requests.
Fix: #1001
N/A
N/A
=> [#1001] fix(UI): Fix null requests in the web UI

docs/how-to-use-the-playground.md
Gravitino 0.3.1 is released. We can remove the workaround in the playground.
Fix: #1432
No.
Manual test.
=> [#1432] improvement(doc): Remove the workaround in the playground

LICENSE.bin
as title
Address comment https://github.com/datastrato/gravitino/pull/1402#issuecomment-1886035763
No.
Review
=> [#1401] followup: Remove unnecessary Gradle Wrapper from LICENSE.bin

dev/docker/trino/conf/jvm.config, docs/docker-image-details.md
Increase jvm memory size for trino docker image.
Fix: #1452
NO
NO
=> [#1452] Improvement (docker) Increase jvm memory size for trino docker image.

api/src/main/java/com/datastrato/gravitino/rel/expressions/literals/Literals.java, api/src/main/java/com/datastrato/gravitino/rel/expressions/transforms/Transforms.java, api/src/main/java/com/datastrato/gravitino/rel/types/Decimal.java, api/src/main/java/com/datastrato/gravitino/rel/types/Types.java, api/src/test/java/com/datastrato/gravitino/rel/TestLiteral.java, api/src/test/java/com/datastrato/gravitino/rel/TestTransforms.java
Add Decimal class for holding decimal literal value
Fix: #1385 
yes, users now can use decimal literal conveniently
UTs added
=> [#1385] feat(api): Add Decimal class for holding decimal literal value

docs/docker-image-details.md
Modify the change log for new Docker images
Fix: #1463 
Just doc.
No need.
=> [#1463] improvement(doc): Modify the change log for new Docker images

docs/iceberg-rest-service.md, docs/index.md, docs/manage-metadata-using-gravitino.md, docs/trino-connector/installation.md
Fix some link and spelling mistakes.
For better user experiences
N/A.
N/A.
=> [MINOR] docs: Fix some mistakes in docs

docs/how-to-build.md, docs/how-to-test.md
Tone down language around the use of OrbStack and it is a paid product.
To not confuse users.
Fix: # N/A
No.
Built locally.
=> [Minor] Tone down language around the use of OrbStack

build.gradle.kts, gradle/libs.versions.toml
Add gradle task `taskTree` to show task dependencies tree. 
For better debugging and developement.
Fix: #1484
N/A.
Test locally.  you can use 
```
./gradlew {taskName} taskTree 
```
to show task dependencies tree. Here is an example
```
./gradlew assembleDistribution taskTree
```
The result:
```text
:assembleDistribution
+--- :assembleTrinoConnector
|    \--- :trino-connector:copyLibs
|         +--- :trino-connector:build
|         |    +--- :trino-connector:assemble
|         |    |    \--- :trino-connector:jar
|         |    |         +--- :trino-connector:classes
|         |    |         |    +--- :trino-connector:compileJava
|         |    |         |    |    \--- :clients:client-java-runtime:shadowJar
|         |    |         |    |         +--- :api:jar
|         |    |         | …
```
=> [#1484] improvement(*): Add support for listing task dependencies tree.

common/src/main/java/com/datastrato/gravitino/dto/rel/ColumnDTO.java, common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java, common/src/main/java/com/datastrato/gravitino/json/JsonUtils.java, common/src/test/java/com/datastrato/gravitino/json/TestDTOJsonSerDe.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/TableOperations.java
Add json serde for column default value
Fix: #1513 
no yet, there is currently no implementation for the catalog.
UTs added
=> [#1513] feat(common): Add json serde for column default value

core/src/main/java/com/datastrato/gravitino/proto/ProtoEntitySerDe.java
Fix ConcurrentModificationException  threw  in function `ProtoEntitySerDe:getProtoClass()`
Fix: #1495
NO
The TrinoQueryIT tester has been run successfully many times. However, before this change, it sometimes fails due to a ConcurrentModificationException
=> [#1495] fix(core): Change the HashMap to ConcurrentMap in ProtoEntitySerDe

docs/webui.md
Make it clearer what the default is.
User clarity.
Fix: # N/A
No
Build locally
=> [Minor] Make it clearer that no configuration needs to be done.

clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalCatalog.java, common/src/main/java/com/datastrato/gravitino/dto/rel/ColumnDTO.java
validate column default value before creating a table
Fix: #1522 
no
UT added
=> [#1522] feat(common): validate column default value before creating a table

web/app/(home)/MetalakeList.js
Fix Metalake list page table layout.
Fix: #1537
N/A
N/A
=> [#1537] fix(UI): Fix Metalake list page table layout

web/app/(home)/MetalakesView.js
English was not quite correct and one word over a line of text.
Looks nicer.
Fix: # (issue)
No.
Tested locally
=> [Minor] Fix text and make text fit in one line an a typical laptop screen

core/src/main/java/com/datastrato/gravitino/Entity.java, core/src/main/java/com/datastrato/gravitino/storage/EntityKeyEncoder.java, core/src/main/java/com/datastrato/gravitino/storage/NameMappingService.java, core/src/main/java/com/datastrato/gravitino/storage/kv/BinaryEntityKeyEncoder.java, core/src/main/java/com/datastrato/gravitino/storage/kv/KvEntityStore.java, core/src/main/java/com/datastrato/gravitino/storage/kv/KvGarbageCollector.java, core/src/main/java/com/datastrato/gravitino/storage/kv/KvNameMappingService.java, core/src/test/java/com/datastrato/gravitino/storage/kv/TestEntityKeyEncoding.java, core/src/test/java/com/datastrato/gravitino/storage/kv/TestKvEntityStorage.java
- Add decoder method to decode byte array to name identifier
- Add some detailed information if `NonEmptyEntityException` occurs
Make the log more clear and easy to debug.
Fix: #1597 
N/A.
UTs
=> [#1597] feat(core): Support entity decoder

web/LICENSE, web/LICENSE.bin, web/lib/utils/index.js
Update license to correctly list Vben.
Add needed information to files and LICENSEs
Fix: # N/A
No
Compiled locally.
=> [Minor] Add miing parts to license

web/LICENSE.bin, web/licenses/call-bind.txt, web/licenses/define-data-property.txt, web/licenses/gopd.txt, web/licenses/has-property-descriptors.txt, web/licenses/has-proto.txt, web/licenses/has-symbols.txt, web/licenses/lodash-es.txt, web/licenses/object-inspect.txt, web/licenses/qs.txt, web/licenses/set-function-length.txt
Checked and updated LICENSE and NOTICE files where needed. Also fixed a couple of duplicate lines and moved a couple out of sort order.
License compliance and to inform users.
Fix: #1625
N/A
Compiled locally.
=> [#1625] Update license information due to package manager change

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcDatabaseOperations.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/operation/MysqlDatabaseOperations.java, catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlSchemaOperations.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/TestMultipleJdbcLoad.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/TestMysqlDatabaseOperations.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/TestPostgreSqlSchemaOperations.java
Filtering out the display of jdbc system databases.
Fix: #1607 
NO
UT/IT
=> [#1607] feat(jdbc): Filtering out the display of jdbc system databases.

web/app/ui/metalakes/MetalakePath.js, web/app/ui/metalakes/MetalakeTree.js, web/app/ui/metalakes/MetalakeView.js, web/app/ui/metalakes/TableView.js, web/components/ColumnTypeChip.js, web/lib/store/metalakes/index.js
Improve tree view synchronization and add table loading.
https://github.com/datastrato/gravitino/assets/17310559/4e84481c-389a-4686-aa5c-2b7ade70aaf5
Fix: #1477 fix tree view sync
Fix: #1605 fix table data fill when error
Fix: #1606 add table fetch loading
Fix: #1619 dup of 1605
Fix: #1644 dup of 1605
N/A
N/A
=> [#1477] fix(web): fix tree view sync and add table loading

integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/TestMultipleJdbcLoad.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/CatalogMysqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/CatalogMysqlVersion5IT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/TestMysqlAbstractIT.java
add mysql 5.7 to  integerate IT
junit5 doesn't support class level ParameterizedTest, https://github.com/junit-team/junit5/issues/878 . so use a separate class.
Fix: #1367
No
integrate test
=> [#1367] test(mysql-jdbc):  add mysql 5.7 to  integerate IT

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcTableOperations.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/converter/MysqlTypeConverter.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/operation/MysqlTableOperations.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/TestMysqlTableOperations.java
Obtain MySQL table information in the form of metadata using the driver.
Fix: #1468
NO
UT/IT
=> [#1468] feat(jdbc): Obtain MySQL table information in the form of metadata using the driver.

api/src/main/java/com/datastrato/gravitino/file/Fileset.java, api/src/main/java/com/datastrato/gravitino/file/FilesetCatalog.java, catalogs/catalog-hadoop/build.gradle.kts, catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/HadoopCatalogOperations.java, catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/HadoopFileset.java, catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java, core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java, core/src/main/java/com/datastrato/gravitino/catalog/file/BaseFileset.java, core/src/main/java/com/datastrato/gravitino/meta/FilesetEntity.java, core/src/main/java/com/datastrato/gravitino/proto/FilesetEntitySerDe.java, core/src/main/java/com/datastrato/gravitino/storage/kv/BinaryEntityKeyEncoder.java, core/src/test/java/com/datastrato/gravitino/meta/TestEntity.java, core/src/test/java/com/datastrato/gravitino/proto/TestEntityProtoSerDe.java, meta/src/main/proto/gravitino_meta.proto
This PR proposes to add the fileset operation support for hadoop catalog.
This is a part of work to support fileset management in Gravitino
Fix: #1527 
No.
Add UTs to cover the codes.
=> [#1527] feat(hadoop-catalog): Add fileset support for hadoop catalog

web/app/ui/CreateMetalakeDialog.js, web/app/ui/metalakes/CreateCatalogDialog.js
Fix the issue of automatic data filling for the modal.
Fix: #1559
N/A
N/A
=> [#1559] fix(web): fix data cache when closing modal

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcCatalog.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcCatalogOperations.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcTablePropertiesMetadata.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/MysqlCatalog.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/MysqlTablePropertiesMetadata.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/operation/MysqlTableOperations.java, core/src/main/java/com/datastrato/gravitino/catalog/PropertyEntry.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/CatalogMysqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/TestMysqlTableOperations.java
Support mysql table properties.
Fix: #804 
Add mysql properties support.
UT/IT
=> [#804] feat(mysql): Support mysql table properties.

web/lib/provider/session.js, web/lib/utils/axios/checkStatus.ts
Fix OAuth mode redirect.
Fix: #1742
N/A
N/A
=> [#1742] fix(web): fix oauth mode redirect

core/src/main/java/com/datastrato/gravitino/storage/kv/KvBackend.java, core/src/main/java/com/datastrato/gravitino/storage/kv/KvEntityStore.java, core/src/main/java/com/datastrato/gravitino/storage/kv/KvGarbageCollector.java, core/src/main/java/com/datastrato/gravitino/storage/kv/KvRange.java, core/src/main/java/com/datastrato/gravitino/storage/kv/RocksDBKvBackend.java, core/src/main/java/com/datastrato/gravitino/storage/kv/TransactionalKvBackendImpl.java, core/src/test/java/com/datastrato/gravitino/storage/kv/TestKvGarbageCollector.java, core/src/test/java/com/datastrato/gravitino/storage/kv/TestRocksDBKvBackend.java, core/src/test/java/com/datastrato/gravitino/storage/kv/TestTransactionalKvBackend.java
Optimize interface `KvBackend` 
- Change method signature
- Optimize Java docs
- Add UT for `RocksDBKvBackend`
For better use experientce.
Fix: #1744 
N/A.
Add a new UT `TestRocksDBKvBackend`
=> [#1744] improvement:(core): Refine interface `KvBackend`

api/src/main/java/com/datastrato/gravitino/Namespace.java, catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogOperations.java, catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveTable.java, catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveTableOperations.java, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveTable.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcTable.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergTable.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/ErrorHandlers.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalCatalog.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalTable.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalCatalog.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalTable.java, common/src/main/java/com/datastrato/gravitino/dto/responses/PartitionNameListResponse.java, core/src/main/java/com/datastrato/gravitino/catalog/TableOperations.java, core/src/main/java/com/datastrato/gravitino/catalog/rel/BaseTable.java, core/src/main/java/com/datastrato/gravitino/catalog/rel/EntityCombinedTable.java, core/src/test/java/com/datastrato/gravitino/TestTable.java, core/src/test/java/com/datastrato/gravitino/catalog/rel/TestBaseTable.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/hive/CatalogHiveIT.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/ExceptionHandlers.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/PartitionOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestPartitionOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestTableOperations.java
Support list partition names for Hive catalog
Fix: #1673 
no
tests added
=> [#1673] feat(partition): Support list partition names for Hive catalog

GOVERNANCE.md, docs/apache-hive-catalog.md, docs/docker-image-details.md, docs/getting-started.md, docs/glossary.md
Have removed duplications, changed the formatting in a couple of places to make it easier to understand options, and simplified the text to make it easier to read.
=> [MINOR] improve(doc): text changes to improve readability

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcTable.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/converter/JdbcTypeConverter.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcTableOperations.java, catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/converter/SqliteTypeConverter.java, catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/operation/SqliteTableOperations.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/converter/MysqlTypeConverter.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/operation/MysqlTableOperations.java, catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/converter/PostgreSqlTypeConverter.java, catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlTableOperations.java
Obtain PostgreSQL table information in the form of metadata using the driver 
Fix: #1737
NO
UT/IT
=> [#1737] Improvement(postgresql): Obtain PostgreSQL table information in the form of metadata using the driver 

web/components/DetailsDrawer.js
=> [#1684] fix(web): fix special characters displays

web/app/ui/metalakes/MetalakeView.js, web/app/ui/metalakes/TableView.js, web/lib/store/metalakes/index.js, web/lib/utils/index.js
Fixing the problem caused by the placeholder.
Fix: #1780 
N/A
N/A
=> [#1780] fix(web): fix placeholder error

web/app/ui/MetalakeList.js, web/app/ui/TableHeader.js
Fix the metalake sorting.
1. Sort by Date
2. Full match
Fix: #1734 
Fix: #1688 
N/A
N/A
=> [#1734] fix(web): fix the metalake sorting

clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalTable.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalTable.java, common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java
Support addPartition for client
Fix: #1776 
no
UTs added
=> [#1776] feat(client): Support addPartition for client

web/app/layout.js, web/components/StyledToast.js, web/lib/utils/axios/checkStatus.ts
Modify favicon and define custom toast.
Fix: #1665
N/A
N/A
=> [#1665] improve(web): modified favicon and define custom toast

README.md
Add Open Source Security Foundation (OpenSSF) best practices badge
To show progress in getting the badge. Please do not close #662 as there is still work to do.
Fix: #662
No.
N/A
=> [#662] Add Open Source Security Foundation (OpenSSF) best practices badge

.github/workflows/auto-cherry-pick.yml
This is a minor fix to add auto cherry-pick support for branch 0.4 and 0.5.
For branch cut and release.
No.
N/A
=> [MINOR] Add auto cherry-pick support for branch-0.4 and 0.5

docs/jdbc-mysql-catalog.md, docs/jdbc-postgresql-catalog.md
1. update PG supported version
2. add warning messages not change gravitino id
3. add not support set MySQL scheme comment message
Fix: #1786 #1704 
no
no, just document
=> [#1786] docs(jdbc): improvement JDBC catalog document

web/README.md, web/package.json
Modified the usage document of web.
Fix: #1624
Fix: #1623
N/A
N/A
=> [#1624] improve(web): modified the usage document of web

docs/iceberg-rest-service.md
add Iceberg metrics store document
Fix: #1610 
no
just document
=> [#1610]  doc(lakehouse-iceberg): add Iceberg metrics store document

docs/manage-metadata-using-gravitino.md, docs/open-api/datatype.yaml
Add example for complex data type of column
Fix: #1651 
Fix: #1274 
no
no need
=> [#1651][#1274] docs: Add example for complex data type of column

core/src/main/java/com/datastrato/gravitino/catalog/rel/BaseTable.java
Rename the variable to avoid misunderstanding
Better code style.
Fix: #1868 
No.
UT.
=> [#1868] improvement: Rename the variable to avoid misunderstanding

catalogs/catalog-jdbc-mysql/build.gradle.kts, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/converter/MysqlTypeConverter.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/converter/TestMysqlTypeConverter.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/operation/TestMysqlTableOperations.java, catalogs/catalog-jdbc-postgresql/build.gradle.kts, catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/converter/PostgreSqlTypeConverter.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/converter/TestPostgreSqlTypeConverter.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/MysqlTableOperationsIT.java
Add unit testing for jdbc catalog and organize code
Fix: #1847 
NO
UT
=> [#1847] Improvement(mysql): Add unit testing for jdbc catalog and organize code.

core/src/test/java/com/datastrato/gravitino/lock/TestLockManager.java
Improve test `testConcurrentRead` to make it more reasonable.
`testConcurrentRead` will not succeed in a machine that does not support parallelism well, to keep the CI pass, we need to change the test accordingly.
Fix: #1861 
N/A.
N/A.
=> [#1861] improvement(core): Fix unstable tests about tree lock

web/LICENSE.bin, web/app/ui/MetalakeList.js, web/app/ui/metalakes/LeftContent.js, web/app/ui/metalakes/MetalakeTree.js, web/app/ui/metalakes/MetalakeView.js, web/app/ui/metalakes/TableView.js, web/app/ui/metalakes/page.js, web/lib/api/metalakes/index.js, web/lib/layout/navigation-events.js, web/lib/store/metalakes/index.js, web/lib/utils/index.js, web/licenses/antd.txt, web/package.json, web/pnpm-lock.yaml
Enhance the performance of the TreeView component.
https://github.com/datastrato/gravitino/assets/17310559/8be08223-a556-4355-9b50-bffa9a13bb57
Fix: #1710
Fix: #1839 
N/A
N/A
=> [#1710] improve(web): improve tree view performance

gradle.properties
Bump the version to 0.5.0-SNAPSHOT for main branch.
NO.
N/A
=> [MINOR] Bump the version to 0.5.0-SNAPSHOT

docs/apache-hive-catalog.md, docs/jdbc-mysql-catalog.md, docs/jdbc-postgresql-catalog.md, docs/lakehouse-iceberg-catalog.md, docs/manage-metadata-using-gravitino.md, docs/open-api/indexes.yaml, docs/open-api/tables.yaml, docs/table-partitioning-bucketing-sort-order-indexes.md
Upgrade doc for index, auto_increment, mysql_properties
Fix: #1798 
add index doc
NO
=> [#1798] Improvement(doc): Upgrade doc for index, auto_increment, mysql_properties

docs/expression.md, docs/table-partitioning-bucketing-sort-order-indexes.md
Add user doc of expression
Fix: #1134 
no
no need
=> [#1134] docs: Add user doc of expression

web/app/ui/metalakes/DetailsView.js, web/app/ui/metalakes/MetalakeTree.js, web/app/ui/metalakes/MetalakeView.js, web/app/ui/metalakes/RightContent.js, web/app/ui/metalakes/TableView.js, web/app/ui/metalakes/TabsContent.js, web/lib/store/metalakes/index.js, web/lib/utils/index.js
Improve the interaction of the TreeView component.
Fix: #1983
N/A
N/A
=> [#1983] improve(web): Improve TreeView component interaction

docs/manage-metadata-using-gravitino.md, docs/table-partitioning-bucketing-sort-order-indexes.md
Remove dtos in docs examples and fix some docs problems.
For better user experience.
Fix: #1986 
N/A.
N/A.
=> [#1986] improvement(docs): Fix some code issues in doc

docs/jdbc-mysql-catalog.md, docs/jdbc-postgresql-catalog.md
1. correct jdbc document capacity 
2. polish docuement
There're some errors in JDBC catalog
no
just document
=> [MINOR] docs(jdbc): polish jdbc document

docs/open-api/openapi.yaml, docs/open-api/partitions.yaml
Add OAS of partition management
Fix: #2018 
no
build doc task successfully
=> [#2018] docs: Add OAS of partition management

docs/docker-image-details.md
Add Docker image 0.4.0 change log
Fix: #1856
No.
Just doc.
=> [#1856] improvement(doc): Add Docker image 0.4.0 change log

docs/iceberg-rest-service.md
1. make it more clear about configuration and start Gravition server
2. add description to configurations.
suggested by user
No
just documents
=> [MINOR] docs(lakehouse-iceberg): polish Iceberg REST service document

docs/manage-table-partition-using-gravitino.md, docs/table-partitioning-bucketing-sort-order-indexes.md
Add user doc for partition management
Fix: #1859 
no
local tested
=> [#1859] docs: Add user doc for partition management

docs/apache-hive-catalog.md, docs/expression.md, docs/jdbc-mysql-catalog.md, docs/jdbc-postgresql-catalog.md, docs/lakehouse-iceberg-catalog.md, docs/manage-metadata-using-gravitino.md, docs/open-api/tables.yaml
Add doc for column default value
Fix: #1590 
no
no need
=> [#1590] docs: Add doc for column default value

server/src/main/java/com/datastrato/gravitino/server/web/VersioningFilter.java
optimize header parameter of VersioningFilter.java，use ACCEPT_VERSION_HEADER instead
Fix: #1968 
By hand.
=> [#1968] improvement(web): Optimize header parameter of VersioningFilter.java

web/lib/api/auth/index.js, web/lib/provider/session.js, web/lib/store/auth/index.js
Resolve OAuth CORS error
Fix: #1754
N/A
N/A
=> [#1754] fix(web): fix oauth CORS error

web/lib/store/metalakes/index.js
Fix data errors when updating and creating catalogs.
Fix: #2068
N/A
N/A
=> [#2068] fix(web): fix data errors when update and create catalog

web/app/ui/login/page.js, web/lib/store/auth/index.js
Reset the fields to fix login input typing error.
Fix: #2074
N/A
N/A
=> [#2074] fix(web): fix login input typing error

common/src/main/java/com/datastrato/gravitino/dto/requests/TableCreateRequest.java
replace stream.peek with map
Fix: #1958 
N/A
By hand
=> [#1958] improvement(common): replace stream.peek with map

docs/open-api/tables.yaml
fix example of JDBC in OAS
The example does not work
no
local test
=> [MINOR] docs: fix example of JDBC in OAS

web/app/ui/metalakes/DetailsView.js, web/components/DetailsDrawer.js
Fix comment rendering error as date.
dayjs non-strict check error
```js
dayjs('my test catalog 2').isValid()
// returned `true`
```
Fix: #2101
N/A
N/A
=> [#2101] fix(web): fix comment rendering as date error

.github/workflows/docker-image.yml
Update Docker latest tag for the branch which name is not the main
Fix: #2119
No.
By hand.
=> [#2119] improvement(build): Update Docker latest tag for the branch which name is not the main

catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogOperations.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/ops/IcebergTableOps.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/web/rest/IcebergTableOperations.java, common/src/main/java/com/datastrato/gravitino/Config.java, common/src/main/java/com/datastrato/gravitino/json/JsonUtils.java, core/src/main/java/com/datastrato/gravitino/StringIdentifier.java, core/src/main/java/com/datastrato/gravitino/catalog/BaseCatalog.java, core/src/main/java/com/datastrato/gravitino/lock/LockManager.java, core/src/main/java/com/datastrato/gravitino/lock/TreeLock.java, core/src/main/java/com/datastrato/gravitino/lock/TreeLockNode.java, core/src/main/java/com/datastrato/gravitino/utils/IsolatedClassLoader.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/lakehouse/iceberg/IcebergRESTServiceBaseIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoQueryIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/CommandExecutor.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/GravitinoITUtils.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/ProcessData.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/ChromeWebDriverProvider.java, server-common/src/main/java/com/datastrato/gravitino/server/auth/KerberosAuthenticator.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/CatalogConnectorManager.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/CatalogConnectorMetadata.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/CatalogInjector.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/hive/HiveConnectorAdapter.java
- improve log call for some class
- use printf style format strings rather than string concatenation
- remove unused log field
Fix: #1867 
Fix: #1872 
Fix: #1873 
Fix: #1875 
Fix: #1879  
Fix: #1911  
Fix: #1923  
Fix: #1924  
Fix: #1933  
Fix: #1957  
N/A
By hand
=> [#1867][#1872][#1873][#1875][#1879][#1911][#1923][#1924][#1933][#1957] Improvement: improve log call throughout the project

docs/manage-metadata-using-gravitino.md, docs/manage-table-partition-using-gravitino.md
use html entities
make the table clearer
no
local tested:
=> [MINOR] improve(docs): use html entities

core/src/main/java/com/datastrato/gravitino/lock/TreeLock.java
- Use Deque instead of Stack to improve TreeLock perf
- Optimize the logic of unlock method for better readability
Fix: #1966 
N/A
By hand
=> [#1966] improvement(core): improve TreeLock perf using Deque

catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/ToIcebergSortOrder.java, common/src/main/java/com/datastrato/gravitino/Config.java, core/src/main/java/com/datastrato/gravitino/utils/ClientPoolImpl.java
-  Abstract classes should have a protected constructor.
- ToIcebergSortOrder is a utility class, it should have a private constructor.
Fix: #1877 
Fix: #1880
Fix: #1961 
N/A
No
=> [#1877][#1880][#1961] Improvement: Optimize the constructor of some classes

common/src/main/java/com/datastrato/gravitino/json/JsonUtils.java
- initial ObjectMapper with lazy singleton approach
Fix: #1935 
N/A
By hand
=> [#1935] Improvement(common): improve ObjectMapper with lazy singleton approach

core/src/main/java/com/datastrato/gravitino/storage/kv/TransactionIdGeneratorImpl.java, core/src/test/java/com/datastrato/gravitino/storage/kv/TestTransactionIdGenerator.java
- make operator calculation clearer
- add ut
Fix: #2165 
N/A
UT
=> [#2165] Improvement(core): make operator calculation clearer

common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java
Make call the same as others.
Consistency and removes an error prone warning.
Fix: # N/A
No.
Build. locally.
=> [Minor] Fixed to be same as other builders

catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/dyn/TestDynFields.java
Added missing @Test annotation to run test.
To run test.
Fix: # N/A
N/A
Built locally.
=> [Minor] Missing @Test annotation

docs/how-to-use-the-playground.md
- fix formatting
Improve the table cell formatting
no
Local test
=> [MINOR] docs: fix formatting

core/src/main/java/com/datastrato/gravitino/metrics/MetricsSystem.java
- fix MetricsSystem annotation
Fix: #1929 
N/A
No
=> [#1929] Improvement: fix MetricsSystem annotation

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcDatabaseOperations.java
refactor JdbcDatabaseOperations#listDatabases
align the code
Fix: #2195
N/A
covered by existed tests
=> [#2195] Improvement: Refactor JdbcDatabaseOperations#listDatabases

api/src/main/java/com/datastrato/gravitino/rel/partitions/Partitions.java
Add missing @Override in several methods in Partitions.java
Address linter issues in #2157
Fix #2157
No.
=> [#2157] Improvement: Add missing @Override in several methods in Partitions.java

trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/GravitinoConnectorFactory.java
Fix a typo in comments of `GravitinoConnectorFactory.create`.
To make the documentation looks great !
Yes, but no breaking change, just typo fixed.
Nope, because no changes on code.
=> [MINOR] docs: fix typo in comments of GravitinoConnectorFactory.create

server/src/main/java/com/datastrato/gravitino/server/web/ConfigServlet.java
Add missing `@Override` in `ConfigServlet.java`
To improve the code quality.
Fix: #1882
No.
Covered by existing tests.
=> [#1882] Improvement: Add missing @Override in ConfigServlet.java

integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/CatalogMysqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java
Add missing `@Test` annotations
Fix: #2197
No
=> [#2197] Improvement: add missing @Test annotations

server/src/main/java/com/datastrato/gravitino/server/web/ConfigServlet.java
Add missing exception handling in `doGet` in `ConfigServlet.java`, namely `java.io.UnsupportedEncodingException`, `IllegalStateException`, `IOException`.
Improve exception handling 
Fix: #2178
No
=> [#2178] Improvement: Add missing exception handling in doGet in ConfigServlet.java

CONTRIBUTING.md
Add good first issue and updated text on working on an issue.
Make people aware of goof first issues and that they don't need to ask for permission to fix something.
Fix: # N/A
No
Build locally.
=> [Minor] doc: Add good first issue and updated text on working on an issue.

server-common/src/main/java/com/datastrato/gravitino/server/auth/KerberosConfig.java
Use config constant instead of hard coding numbers
Code in other places user them.
Fix: # N/A
No
Build locally.
=> [Minor] Use config constant instead of hard coding numbers

server-common/src/main/java/com/datastrato/gravitino/server/web/JettyServerConfig.java
- remove local variables for JettyServerConfig
Fix: #1931 
N/A
NO
=> [#1931] Improvement(server-common): remove local variables for JettyServerConfig

catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlTableOperations.java
Improved code by removing a few repeated strings
Easier to read and has less chance of mistakes.
Fix: # N/A
N/A
=> [Minor] Improved code by removing a few repeated strings

docs/how-to-use-the-playground.md
- fix formatting
Improve the table cell formatting
no
Local test
=> [MINOR] docs: fix formatting (#2177)

server/src/main/java/com/datastrato/gravitino/server/web/ConfigServlet.java
Log rather than throw exceptions
To fix a possible security issue.
Fix: #2216
No.
=> [#2216] Log rather than throw exceptions

dev/docker/hive/hive-dependency.sh
update HADOOP_DOWNLOAD_URL & add `-L` to `curl`
Fix: #2263
N/A
Local
=> [#2263] fix: fix bug in hadoop packages prepareration

clients/client-java/src/main/java/com/datastrato/gravitino/client/HTTPClient.java
- Add NPE check for HTTPClient
Fix: #2194 
N/A
By hand
=> [#2194] Improvement(clients): Add NPE check for HTTPClient

build.gradle.kts, catalogs/build.gradle.kts, clients/build.gradle.kts
- Add gradle build files for module `catalogs` and `clients`.
- Remove unnecessary logic to disable the build task for module `catalogs` and `clients`.
It's a bug need to fix.
Fix: #2121 
N/A.
Test and verify it locally.
=> [#2121] fix(build): Fix publish bugs when publish module `clients` and `catalogs`

build.gradle.kts, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/ops/TestIcebergTableUpdate.java, core/src/test/java/com/datastrato/gravitino/lock/TestLockManager.java, core/src/test/java/com/datastrato/gravitino/storage/kv/TestKvEntityStorage.java, core/src/test/java/com/datastrato/gravitino/storage/kv/TestKvNameMappingService.java, core/src/test/java/com/datastrato/gravitino/storage/kv/TestTransactionIdGenerator.java, core/src/test/java/com/datastrato/gravitino/storage/kv/TestTransactionalKvBackend.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoQueryITBase.java
All of these pass currently and generate no warnings, but a couple of others, e.g., Xlint:try do have issues.
Warn people about common errors.
Improve code quality.
Fix: #2265
N/A
Built locally.
=> [#2265] improve(build): Add more Xlint checks

dev/docker/build-docker.sh, dev/docker/doris/Dockerfile, dev/docker/doris/doris-dependency.sh, dev/docker/doris/start.sh, docs/docker-image-details.md
add Doris runtime environment 
Fix: #2221
NO
Local
=> [#2221] feat(docker): Gravitino Doris Docker image

integration-test/src/test/java/com/datastrato/gravitino/integration/test/container/TrinoITContainers.java
- remove unexpected log reference and use slf4j
Fix: #2303 
N/A
NO
=> [#2303] Improvement(integration-test): Fix unexpected log reference for TrinoITContainers.java

web/app/ui/MetalakeList.js
Fix sorting and filtering of the metalakes table.
Fix: #1735 
Fix: #2072
N/A
N/A
=> [#1735] fix(web): fix sorting and filtering of the metalakes table

common/src/main/java/com/datastrato/gravitino/config/ConfigConstants.java
- ConfigConstants updated as class and is not an interface
- Fix: #1881
- No
- ./gradlew build
=> [#1881] Improvement: ConfigConstants.java updated as class and is not an interface

core/src/main/java/com/datastrato/gravitino/catalog/BaseCatalog.java
- fix thread issue for BaseCatalog
Fix: #2285 
N/A
NO
=> [#2285] improvement(core): fix thread issue for BaseCatalog

common/src/main/java/com/datastrato/gravitino/config/ConfigConstants.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/GravitinoSplitManager.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/hive/HiveConnectorAdapter.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/iceberg/IcebergConnectorAdapter.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/jdbc/mysql/MySQLConnectorAdapter.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/jdbc/mysql/MySQLMetadataAdapter.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/jdbc/postgresql/PostgreSQLConnectorAdapter.java
Add missing `@Override` annotation in subclass method.
Used to identify overridden parent class methods.
Fix: [#1907](https://github.com/datastrato/gravitino/issues/1907)
No
`./gradlew :trino-connector:test 
`
=> [#1907] improvement(trino-connector): Add missing `@Override` annotation in subclass method

build.gradle.kts, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/miniHMS/MiniHiveMetastore.java, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/miniHMS/ScriptRunner.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/HTTPClient.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/SimpleTokenProvider.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestOAuth2TokenProvider.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestSimpleTokenProvider.java, core/src/main/java/com/datastrato/gravitino/storage/kv/KvEntityStore.java, core/src/main/java/com/datastrato/gravitino/storage/kv/KvNameMappingService.java, core/src/test/java/com/datastrato/gravitino/storage/kv/TestKvGarbageCollector.java, core/src/test/java/com/datastrato/gravitino/storage/kv/TestTransactionalKvBackend.java, integration-test/src/main/java/com/datastrato/gravitino/integration/test/util/ITUtils.java, integration-test/src/main/java/com/datastrato/gravitino/integration/test/util/OAuthMockDataProvider.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoQueryIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/ProcessData.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/rest/OAuth2OperationsIT.java, server-common/src/main/java/com/datastrato/gravitino/server/auth/KerberosAuthenticator.java, server-common/src/main/java/com/datastrato/gravitino/server/auth/OAuth2TokenAuthenticator.java, server-common/src/main/java/com/datastrato/gravitino/server/auth/SimpleAuthenticator.java, server-common/src/test/java/com/datastrato/gravitino/server/auth/TestOAuth2TokenAuthenticator.java, server-common/src/test/java/com/datastrato/gravitino/server/auth/TestSimpleAuthenticator.java
- close #2153 
Fix: #2153 
- no
=> [#2153] improvement: enable DefaultCharset error-prone check

api/src/main/java/com/datastrato/gravitino/rel/TableChange.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/utils/DataSourceUtils.java, common/src/main/java/com/datastrato/gravitino/config/ConfigConstants.java
change the assertion check to a if-else check.
java assertion can be disabled in all packages and classes and it is not a safe op.
Reference java document: https://docs.oracle.com/en/java/javase/21/docs/specs/man/java.html#standard-options-for-java
Fix: [#1887](https://github.com/datastrato/gravitino/issues/1887)
No
`./gradlew clean :api:test :catalogs:catalog-jdbc-common:test`
=> [#1887] improvement(catalog-jdbc-common)(api): Change assertion to be a if-else check

web/app/ui/CreateMetalakeDialog.js, web/app/ui/metalakes/CreateCatalogDialog.js, web/lib/store/metalakes/index.js
Improve creating and updating user experience.
If it had existed, it would not be closing now.
Fix: #2324 
N/A
N/A
=> [#2324] improve(web): improve creating and updating user experience

core/src/main/java/com/datastrato/gravitino/GravitinoEnv.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestCatalogOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestFilesetOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestMetalakeOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestPartitionOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestSchemaOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestTableOperations.java
Fix jetty server-related bugs that were introduced by the tree lock. 
Some tests may fail locally. 
Fix: #2361
N/A.
Existing tests can cover it.
=> [#2361] fix(test): Fix test bugs that were introuduced by tree lock

.github/workflows/docker-image.yml
Support to release Doris ci image using pipeline
Fix: #2302 
No.
I will test it after it is merged to master.
=> [#2302] dev: Support to release Doris ci image using pipeline

.github/workflows/docker-image.yml, dev/docker/build-docker.sh
Remove unused packages and then free enough disk space.
If we don't have this pr, we will encounter the error.
https://github.com/datastrato/gravitino/actions/runs/8076657520
No.
I have tested it by using https://github.com/datastrato/gravitino/actions/runs/8077266349/job/22067221802
=> [#2302][FOLLOWUP] dev: Fix the issue of disk space

web/app/ui/login/page.js, web/lib/api/auth/index.js, web/lib/layout/Logout.js, web/lib/provider/session.js, web/lib/store/auth/index.js, web/lib/utils/axios/checkStatus.ts, web/lib/utils/axios/index.ts
Remove refresh token and redirect to login page if token has expired.
Fix: #2099 
N/A
N/A
=> [#2099] fix(web): redirect to login page if token has expired

integration-test/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java
1. Enhancing code robustness.
2. Fix container network configuration error 
There are some versions of docker where this issue occurs
Fix: #1779
N/A
CI Passed
=> [#1779] fix(IT): Fix container network configuration error

.github/workflows/build.yml, .github/workflows/integration-test.yml
add spark-connector to auto trigger  CI
if only change spark connector code, CI are not triggered, like #2484 
no
existing UT
=> [MINOR] feat(spark-connector): add spark-connector to auto trigger  CI

build.gradle.kts, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/integration/test/CatalogHiveIT.java, catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlSchemaOperations.java, common/src/test/java/com/datastrato/gravitino/json/TestDTOJsonSerDe.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/SparkIT.java, server/src/main/java/com/datastrato/gravitino/server/web/VersioningFilter.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/ExceptionHandlers.java
Enable InlineFormatString error-prone check.
Fix: #2471
No
Existing integration tests.
=> [#2471] refactor: Enable InlineFormatString error-prone

integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/MetalakePageTest.java
Disable web e2e tests temporarily until the actions running error is fixed.
Fix: #2536
N/A
N/A
=> [#2536] hotfix(IT): disable web e2e tests temporarily until the actions running error is fixed

web/src/app/metalakes/metalake/rightContent/tabsContent/tableView/TableView.js
Fix catalog info not found issue
Fix: #2601
N/A
=> [#2601] fix(ui): fix catalog info not found issue

api/src/main/java/com/datastrato/gravitino/rel/expressions/FunctionExpression.java, api/src/main/java/com/datastrato/gravitino/rel/expressions/distributions/Distributions.java, api/src/main/java/com/datastrato/gravitino/rel/expressions/literals/Literals.java, api/src/main/java/com/datastrato/gravitino/rel/expressions/sorts/SortOrders.java, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/integration/test/CatalogHiveIT.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlVersion5IT.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergIT.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalTable.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalCatalog.java, common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java, gradle.properties, integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/hive/HiveMetadataAdapter.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/iceberg/IcebergMetadataAdapter.java
- remove TableDTO in the client
- convert TableDTO to Table in the client
Fix: #2628 
no
existing tests
=> [#2628] improvement(client): remove tableDTO in client

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/utils/DataSourceUtils.java, integration-test/src/test/resources/trino-ci-testset/testsets/lakehouse-iceberg/00007_varchar.sql, integration-test/src/test/resources/trino-ci-testset/testsets/lakehouse-iceberg/00007_varchar.txt
Change the schema name of some Iceberg test cases in `TrinoQueryIT`.
Iceberg uses Hive as the backend, chances are they two may running at the same time.
Fix: #2633 
N/A.
CI
=> [2633] fix:(integration-test):  Fix flaky test TrinoQueryIT

integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-mysql/00008_alter_catalog.txt
Fix the CI test failures on the main branch, because the previous pr it wasn't updated before merging.
Fix: #2682 
NO
UT
=> [#2682] fix (trino-connector): Fix failed to run alter_catalog_test

.github/workflows/backend-integration-test.yml, .github/workflows/frontend-integration-test.yml, LICENSE, NOTICE, dev/ci/util_free_space.sh
Free up disk space in github workflow, make Doris container start up successful
Fix: #2691 
N/A
UT
=> [#2691] feat(CI): free up disk space in github workflow

docs/manage-metadata-using-gravitino.md
change `detail` to `details`
URL error
no
no need
=> [MINOR] docs: fix error  URL of list catalog info

.github/workflows/cron-integration-test.yml
Setup crob job to run all ITs nightly.
Regularly run all ITs.
Fix: #2731 
N/A
CI
=> [#2731]improvement(IT): crob workflow for ITs

common/src/main/java/com/datastrato/gravitino/dto/authorization/GroupDTO.java, common/src/main/java/com/datastrato/gravitino/dto/requests/GroupAddRequest.java, common/src/main/java/com/datastrato/gravitino/dto/responses/GroupResponse.java, common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java, common/src/test/java/com/datastrato/gravitino/dto/responses/TestResponses.java, core/src/test/java/com/datastrato/gravitino/authorization/TestAccessControlManager.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/ExceptionHandlers.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/GroupOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestGroupOperations.java
Add the operations for the group
Fix: #2240 
Yes, I will add the document in the later pr.
Add a new UT.
=> [#2240] feat(server): Add the operations for the group

ROADMAP, build.gradle.kts
Add 2024 roadmap to give people an idea of what we are doing.
Add 2024 roadmap to give people an idea of what we are doing.
Fix: #2789
No
Build locally
=> [#2789] Add 2024 roadmap

docs/gravitino-server-config.md
Add configuration descriptions about the usage of tree lock. 
To improve docs. 
Fix: #2346 
N/A.
N/A.
=> [#2346] improvement(docs): Add configurations items about tree lock

web/src/components/StyledToast.js, web/src/configs/themeConfig.js
Add configuration file to manage common user interface variables.
`web/src/configs/themeConfig.js`
1. `toastDuration`: Modified toast message box duration to `4000` milliseconds.
Because the previous error message box wouldn't disappear on its own, in order to avoid confusing the users, we made the error message box disappear automatically after 4 seconds.
2. `toastPosition`: Modified the message box position, the default is `top-right`.
Fix: #2814
Fix: #2688
N/A
N/A
=> [#2814][#2688] improve(web): add configuration file to manage common user interface variables

integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/MetalakePageTest.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/pages/MetalakePage.java, web/src/app/rootLayout/Footer.js
Add test cases for end-to-end testing of the Metalake webpage.
- Refresh page
- Check`Datastrato` link
- Check `License` link
- Check `Documentation` link
- Check `Support` link
Fix: #2604 
Fix: #2606
N/A
IT/e2e
=> [#2604][#2606] improve(IT): add more test cases for e2e test of metalake page

build.gradle.kts, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/web/rest/IcebergTestBase.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestOAuth2TokenProvider.java, spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/catalog/GravitinoCatalogManager.java
- enable BadImport error-prone
- Importing nested classes/static methods/static fields with commonly-used names can make code harder to read, because it may not be clear from the context exactly which type is being referred to. Qualifying the name with that of the containing class can make the code clearer.
Fix: #2476
- no
- GitHub CI passed.
=> [#2476] refactor: enable BadImport error-prone

core/src/main/java/com/datastrato/gravitino/authorization/AccessControlManager.java, core/src/main/java/com/datastrato/gravitino/authorization/AdminManager.java, core/src/main/java/com/datastrato/gravitino/authorization/AuthorizationUtils.java, core/src/main/java/com/datastrato/gravitino/authorization/UserGroupManager.java, core/src/test/java/com/datastrato/gravitino/authorization/TestAccessControlManager.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/GroupOperations.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/UserOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestMetalakeAdminOperations.java
1. Add the check whether metalake exists for user and group.
2. Remove the metalake operation admin  code which throws no such metalake exception.
3. Remove the lock of operations and add a lock for AccessControlManager.
Fix #2835 
No.
Add new UT.
=> [#2835] improvement(server,core): Refactor the check code and lock for authorization module

catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/TestDorisAbstractIT.java
update doris path in TestDorisAbstractIT.
current path in code is error, cannot upload log in x86 env
use soft link instead. 
N/A
Mannal
=> [MINOR] fix: update doris path in TestDorisAbstractIT

catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/integration/test/TestJdbcAbstractIT.java, catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/converter/PostgreSqlTypeConverter.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/converter/TestPostgreSqlTypeConverter.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/PostgreSqlTableOperationsIT.java, docs/jdbc-postgresql-catalog.md
support array type for PG
Fix: #947 
No
IT and UT
=> [#947]feat(jdbc-postgresql): support array type for PG

catalogs/catalog-jdbc-doris/build.gradle.kts
Change the Doris CI image version from 0.1.1 to 0.1.2.
0.1.2 has several improvements to make the CI more stable. 
N/A.
N/A.
=> [MINOR] improvement(catalog-doris): Upgrade Doris CI image version to 0.1.2

integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/CatalogsPageTest.java
add test case of create kafka catalog
Fix: #2864
N/A
=> [#2864]test(web): add test case of create kafka catalog

docs/how-to-use-gvfs.md, docs/manage-fileset-metadata-using-gravitino.md
Improve the language used in the documents.
For clarity and understanding.
Fix: # N/A
No
N/A
=> [Minor] improve docs

LICENSE, LICENSE.bin, catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/embedded/KafkaClusterEmbedded.java, catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/embedded/KafkaEmbedded.java, catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/embedded/ZooKeeperEmbedded.java
fix incorrect LICENSE information of Kafka source code
Fix: #2800 #2801 
no
no need
=> [#2800][#2801] fix(license): fix incorrect LICENSE information of Kafka source code

catalogs/catalog-jdbc-doris/build.gradle.kts
Change the Doris CI image version from 0.1.2 to 0.1.3
0.1.3 remove log from container stdout, which is better for CI framework
N/A
N/A
=> [MINOR] improvement(catalog-doris): Upgrade Doris CI image version to 0.1.3

docs/manage-relational-metadata-using-gravitino.md
correct json body in create_table
HTTP request body is illegal, miss a dot in body
use this command may get an exception message
N/A
Mannal
=> [MINOR] docs: correct json body in create_table

catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/operation/MysqlTableOperations.java
use metaData.getTables instead of directly SQL
Fix: #2934
N/A
IT
=> [#2934] feat(catalog-mysql): use metaData.getTables instead of directly SQL

core/src/main/java/com/datastrato/gravitino/GravitinoEnv.java, core/src/main/java/com/datastrato/gravitino/catalog/FilesetDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/FilesetEventDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/FilesetOperationDispatcher.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/AlterFilesetEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/AlterFilesetFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/CreateFilesetEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/CreateFilesetFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/DropFilesetEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/DropFilesetFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/FilesetEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/FilesetFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/ListFilesetEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/ListFilesetFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/LoadFilesetEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/LoadFilesetFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/info/FilesetInfo.java, server/src/main/java/com/datastrato/gravitino/server/GravitinoServer.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/FilesetOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestFilesetOperations.java
* `CreateFilesetEvent`
* `AlterFilesetEvent`
* `DropFilesetEvent`
* `LoadFilesetEvent`
* `ListFilesetEvent`
* `CreateFilesetFailureEvent`
* `AlterFilesetFailureEvent`
* `DropFilesetFailureEvent`
* `LoadFilesetFailureEvent`
* `ListFilesetFailureEvent`
Fix: #2767 
no
existing tests
=> [#2767] feat(core): supports fileset event for event listener

api/src/main/java/com/datastrato/gravitino/authorization/SecurableObjects.java, common/src/main/java/com/datastrato/gravitino/dto/authorization/RoleDTO.java, common/src/main/java/com/datastrato/gravitino/dto/requests/RoleCreateRequest.java, common/src/main/java/com/datastrato/gravitino/dto/responses/RoleResponse.java, common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java, common/src/test/java/com/datastrato/gravitino/dto/responses/TestResponses.java, core/src/main/java/com/datastrato/gravitino/authorization/RoleManager.java, core/src/main/java/com/datastrato/gravitino/meta/RoleEntity.java, core/src/main/java/com/datastrato/gravitino/proto/RoleEntitySerDe.java, core/src/test/java/com/datastrato/gravitino/meta/TestEntity.java, core/src/test/java/com/datastrato/gravitino/proto/TestEntityProtoSerDe.java, core/src/test/java/com/datastrato/gravitino/storage/TestEntityStorage.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/ExceptionHandlers.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/RoleOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestRoleOperations.java
Add the operations for the role.
Fix: #2239 
Yes,  I will add the open api and the document in the later pr.
Add a new UT.
=> [#2239] feat(server): Add the role operation

core/src/main/java/com/datastrato/gravitino/GravitinoEnv.java, core/src/main/java/com/datastrato/gravitino/catalog/SchemaDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/SchemaEventDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/SchemaOperationDispatcher.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/AlterSchemaEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/AlterSchemaFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/CreateSchemaEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/CreateSchemaFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/DropSchemaEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/DropSchemaFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/ListSchemaEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/ListSchemaFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/LoadSchemaEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/LoadSchemaFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/SchemaEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/SchemaFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/info/SchemaInfo.java, server/src/main/java/com/datastrato/gravitino/server/GravitinoServer.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/SchemaOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestSchemaOperations.java
supports schema events for event listener system
Fix: #2769 
no
existing tests
=> [#2769] feat(core): supports schema event for event listener

trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/GravitinoPlugin.java
Add missing override annotation to overriding GravitinoPlugin method.
Methods that override Trino plugin should use the override annotation.
Fix: #2914 
No
ITs and UTs
=> [#2914] Improvement(trino-connector) Add missing override annotation to overriding GravitinoPlugin method.

core/src/main/java/com/datastrato/gravitino/GravitinoEnv.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/AlterMetalakeEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/AlterMetalakeFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/CreateMetalakeEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/CreateMetalakeFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/DropMetalakeEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/DropMetalakeFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/ListMetalakeEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/ListMetalakeFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/LoadMetalakeEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/LoadMetalakeFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/MetalakeEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/MetalakeFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/info/MetalakeInfo.java, core/src/main/java/com/datastrato/gravitino/metalake/MetalakeDispatcher.java, core/src/main/java/com/datastrato/gravitino/metalake/MetalakeEventDispatcher.java, core/src/main/java/com/datastrato/gravitino/metalake/MetalakeManager.java, server/src/main/java/com/datastrato/gravitino/server/GravitinoServer.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/MetalakeOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestMetalakeOperations.java
supports metalake event for event listener
Fix: #2821 
no
existing tests
=> [#2821] feat(core):  supports metalake event for event listener

rfc/rfc-1/rfc-1.md
Fix incorrect numbering in the document.
Fix incorrect numbering in the document.
No.
local.
=> [MINOR] Fix incorrect numbering in the document

.github/workflows/python-integration-test.yml
Disable the Python-related pipeline temporarily. 
Python pipeline issues cannot be resolved quickly. To avoid hindering development, we will temporarily disable Python-related pipelines. 
N/A.
N/A.
=> [HOTFIX] Fix(ci):  Disable Python-related pipeline temporarily

core/build.gradle.kts, core/src/main/java/com/datastrato/gravitino/listener/api/event/ListCatalogEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/ListCatalogFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/ListFilesetEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/ListFilesetFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/ListSchemaEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/ListSchemaFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/ListTableEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/ListTableFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/ListTopicEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/event/ListTopicFailureEvent.java, core/src/main/java/com/datastrato/gravitino/listener/api/info/FilesetInfo.java, core/src/main/java/com/datastrato/gravitino/listener/api/info/TableInfo.java, core/src/test/java/com/datastrato/gravitino/listener/DummyEventListener.java, core/src/test/java/com/datastrato/gravitino/listener/TestEventListenerManager.java, core/src/test/java/com/datastrato/gravitino/listener/api/event/TestCatalogEvent.java, core/src/test/java/com/datastrato/gravitino/listener/api/event/TestFilesetEvent.java, core/src/test/java/com/datastrato/gravitino/listener/api/event/TestMetalakeEvent.java, core/src/test/java/com/datastrato/gravitino/listener/api/event/TestSchemaEvent.java, core/src/test/java/com/datastrato/gravitino/listener/api/event/TestTableEvent.java, core/src/test/java/com/datastrato/gravitino/listener/api/event/TestTopicEvent.java
add test  for event 
Fix: #2980 
no
test patch
=> [#2980] test(core):  add  test for event listener

build.gradle.kts, web/build.gradle.kts
fix gradle build will update pnpm-lock.yaml
Fix: #3010
N/A
LOCAL
=> [#3010] fix(web): fix gradle build issue

common/build.gradle.kts
The proposal changes the task to the function and makes sure the function will not be skipped, also explicitly add the file to jar to make sure it will be executed every time.
Fix: #3012 
No.
Manual test.
=> [#3012] Fix(build): Fix compile issue after #2866 is merged

build.gradle.kts, catalogs/catalog-jdbc-doris/build.gradle.kts, catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/CatalogDorisIT.java
add Doris catalog integration test
Fix: #2877
N/A
IT
=> [#2877] test(catalog-jdbc-doris): add Doris catalog integration test

core/src/main/java/com/datastrato/gravitino/catalog/FilesetOperationDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/SchemaOperationDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/TableOperationDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/TopicOperationDispatcher.java, core/src/main/java/com/datastrato/gravitino/connector/capability/Capability.java, core/src/test/java/com/datastrato/gravitino/catalog/TestFilesetNormalizeDispatcher.java, core/src/test/java/com/datastrato/gravitino/catalog/TestSchemaNormalizeDispatcher.java, core/src/test/java/com/datastrato/gravitino/catalog/TestTableNormalizeDispatcher.java, core/src/test/java/com/datastrato/gravitino/catalog/TestTopicNormalizeDispatcher.java, core/src/test/java/com/datastrato/gravitino/connector/capability/TestCapability.java
- add name spec for entity name
Fix: #2952
yes, have more limitation in name now
added tests
=> [#2952] feat(core): support name spec capability

docs/jdbc-mysql-catalog.md
Fix incorrect document description
Fix: #2942 
no
no need
=> [#2942] docs(mysql-catalog): Fix incorrect document description

MAINTAINERS.md
Add PR review and merge policy into the doc to make it more clear.
Fix: #3067 
No
No
=> [#3067] feat(doc): Add PR review and merge policy doc

web/src/lib/utils/initial.js
Add web UI support for Doris catalog
Fix: #3048
N/A
Mannul
=> [#3048] feat(web): Add web UI support for Doris catalog

docs/index.md, docs/kafka-catalog.md, docs/manage-messaging-metadata-using-gravitino.md
This PR proposes to add docs for messaging catalog
Fix: #2774 
No
No
=> [#2774] feat(doc): Add docs for messaging catalog

docs/open-api/filesets.yaml, docs/open-api/openapi.yaml, docs/open-api/topics.yaml
Add OAS for messaging catalog
Fix: #2773 
no
no
=> [#2773] feat(doc): Add OAS for messaging catalog

api/src/main/java/com/datastrato/gravitino/exceptions/GravitinoRuntimeException.java, catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java, catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/BaseSchemaCatalog.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/FilesetCatalog.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalCatalog.java, core/src/main/java/com/datastrato/gravitino/catalog/CapabilityHelpers.java, core/src/main/java/com/datastrato/gravitino/catalog/FilesetNormalizeDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/SchemaNormalizeDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/TableNormalizeDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/TopicNormalizeDispatcher.java
only validate the name when creating
The constraints of the name spec may be more strict than the underlying catalog
Fix: #3101 
no
tests added
=> [#3101] fix(all): Only validate the name when creating

gradle.properties
Change version from `0.5.0` to `0.5.1-SNAPSHOT`
Release 0.5.0-RC1
N/A.
N/A.
=> [Minor] Change version from `0.5.0` to `0.5.1-SNAPSHOT`

docs/manage-table-partition-using-gravitino.md, docs/open-api/partitions.yaml, docs/open-api/tables.yaml
add docs and OAS for drop partition operation
Fix: #3140
no
no
=> [#3140] docs(partition): add docs and OAS for drop partition operation

gradle.properties
Change version back to 0.5.0
Change version back to 0.5.0
N/A
N/A
=> [Minor] Change version back to 0.5.0

docs/docker-image-details.md
Add the change log for 0.5.0 version image.
Fix: #3154
No.
Just a document.
=> [#3154] improvement(docs): Add the change log for 0.5.0 version image

gradle.properties
Change version to 0.5.1-SNAPSHOT
Change version to 0.5.1-SNAPSHOT
N/A.
N/A
=> [Minor] Change version to 0.5.1-SNAPSHOT

core/src/main/java/com/datastrato/gravitino/authorization/AuthorizationUtils.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/GroupMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/RoleMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/UserMetaService.java, core/src/test/java/com/datastrato/gravitino/authorization/TestAuthorizationUtils.java
add `checkUser`, `checkGroup`, `checkRole` in `NameIdentifier`
Fix: #3132 
N/A
ut
=> [#3132] improvement(core):  Use a more elegant validation of User, Group and Role NameIdentifier

integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/hive/SparkHiveCatalogIT.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/hive/HivePropertiesConverter.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/hive/TestHivePropertiesConverter.java
transform `hive` provider to `text` format
Fix: #3129 
no
add UT and IT
=> [#3129] fix(spark-connector): fix create table failed for using hive

clients/client-java/src/main/java/com/datastrato/gravitino/client/ErrorHandlers.java
String.format() change \n to %n
Fix: #3034 
no
no
=> [#3034] fix(client): use %n format

core/src/main/java/com/datastrato/gravitino/authorization/AuthorizationUtils.java
Fix: #3028
no
Use existing test cases in TestAuthorizationUtils.class
=> [#3028] fix incorrectly accessed static fields

docs/how-to-build.md
Fix the wrong sequence number issue in doc and improve the wording.
Fix: #3218
No.
N/A
=> [#3218]fix(doc): Fix the wrong sequence number issue in doc and improve the wording

docs/iceberg-rest-service.md
polish iceberg rest catalog document
- format table
- replace spark-shell with spark sql
- add `--package`
- add `;`
more user friendly
no
just document
=> [MINOR] docs(lakehouse-iceberg): polish iceberg rest catalog document

common/src/main/java/com/datastrato/gravitino/config/ConfigEntry.java, common/src/test/java/com/datastrato/gravitino/config/TestConfigEntryList.java, core/src/main/java/com/datastrato/gravitino/Configs.java, core/src/test/java/com/datastrato/gravitino/authorization/TestAccessControlManagerForPermissions.java
Fix the issue of method `checkValue` in the ConfigOption. If we use `checkValue` in the wrong position, it won't work.
Fix: #3216
No.
UT.
=> [#3216] fix(core): Fix the issue of method `checkValue` in the ConfigOption

docs/how-to-use-the-playground.md
Update playground docs for using simple catalog
Fix: #3234 
NO
NO
=> [#3234] improve (doc): Update playground docs for using simple catalog

core/src/test/java/com/datastrato/gravitino/catalog/TestFilesetNormalizeDispatcher.java, core/src/test/java/com/datastrato/gravitino/catalog/TestSchemaNormalizeDispatcher.java, core/src/test/java/com/datastrato/gravitino/catalog/TestTableNormalizeDispatcher.java, core/src/test/java/com/datastrato/gravitino/catalog/TestTopicNormalizeDispatcher.java
Removing Inheritance
Fix: #3227 
no
existing tests
=> [#3227] fix(UT): tests run repeatedly

catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlTableOperations.java
Added `@Override` annotation on getTableBuilder in PostgreSqlTableOperations
Fix: #3250
=> [#3250] improve(catalog-jdbc-pg): Added missing @Override annotation

catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlVersion12IT.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlVersion14IT.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlVersion15IT.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlVersion16IT.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/TestMultipleJDBCLoad.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/service/PostgreSqlService.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/TestMultipleJDBCLoad.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/MySQLContainer.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/PGImageName.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/PostgreSQLContainer.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/util/TestDatabaseName.java
This PR resolved #3066.
as #2813 described.
No.
Unit tests.
=> [#3066]: Improvement(IT): manage PostgreSQL containers in ContainerSuite

core/src/main/java/com/datastrato/gravitino/utils/IsolatedClassLoader.java
make catalog class non-shared
Fix: #3299
no
no
=> [#3299] fix(core): make catalog class non-shared

core/src/main/java/com/datastrato/gravitino/GravitinoEnv.java, core/src/main/java/com/datastrato/gravitino/catalog/CapabilityHelpers.java, core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java, core/src/main/java/com/datastrato/gravitino/catalog/OperationDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/PartitionDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/PartitionNormalizeDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/PartitionOperationDispatcher.java, core/src/test/java/com/datastrato/gravitino/TestTable.java, core/src/test/java/com/datastrato/gravitino/TestTableOperations.java, core/src/test/java/com/datastrato/gravitino/catalog/TestPartitionNormalizeDispatcher.java, core/src/test/java/com/datastrato/gravitino/catalog/TestPartitionOperationDispatcher.java, core/src/test/java/com/datastrato/gravitino/catalog/TestTopicNormalizeDispatcher.java, server/src/main/java/com/datastrato/gravitino/server/GravitinoServer.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/PartitionOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestPartitionOperations.java
- reuse the class loader of the catalog for partition operation
- add partition operation dispatcher
Fix: #2997 #2999 
no
tests added
=> [#2999][#2997] improvement(partition): add partition operation dispatcher

MAINTAINERS.md
Add table to list contributors
To make it easier to donate code to the ASF.
Fix: # N/A
No.
N/A
=> [MINOR] feat(doc): Update MAINTAINERS.md to list contribitors as well

catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/operation/DorisTableOperations.java
Output the alter status of table into the log
Fix: #3326
N/A
Manual, check log
=> [#3326] feat(jdbc-doris): output the alter status of table into the log

clients/client-python/gravitino/client/gravitino_admin_client.py, clients/client-python/gravitino/client/gravitino_metalake.py, clients/client-python/gravitino/dto/version_dto.py, clients/client-python/gravitino/name_identifier.py, clients/client-python/gravitino/namespace.py, clients/client-python/gravitino/typing.py, clients/client-python/gravitino/utils/http_client.py, clients/client-python/pylintrc, clients/client-python/tests/integration/integration_test_env.py
- Define naming style of each class, module, function and variable
- See `pylintrc` for detail settings
Fix: #3205 
No
No
=> [#3205] improvement(client-python): Apply naming convention to client-python

MAINTAINERS.md
Very minor, add shaofengshi (myself) into the maintainer list as Justin suggested.
Make the document up to date.
Fix: #3360
No
No change to code;
=> [#3360] minor, add shaofengshi to maintianer list

MAINTAINERS.md
Very minor, add qianxia (myself) to the maintainer list as Justin suggested.
Fix: #3360
N/A
No change to code
=> [#3360] add qianxia to maintainer list

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcTablePropertiesMetadata.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/BaseSchemaCatalog.java, common/src/main/java/com/datastrato/gravitino/Config.java, core/src/main/java/com/datastrato/gravitino/catalog/OperationDispatcher.java, core/src/main/java/com/datastrato/gravitino/storage/kv/TransactionalKvBackendImpl.java
Remove the tag `@VisibleForTesting` for some methods, as they are not just used in tests only.
Fix: #3080 
No.
Existing UTs.
=> [#3080] Improve(all): Removed @VisibleForTesting in several methods because they accessed from production code

catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/operation/DorisTableOperations.java, catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/DorisTableOperationsIT.java
support creating Doris table with partition
Fix: #3347 
no
IT
=> [#3347] improvement(jdbc-doris): support creating Doris table with partition

MAINTAINERS.md
=> [MINOR] docs: Update MAINTAINERS.md

web/src/lib/styles/globals.css
Disable link dragging.
Fix: #3291
N/A
N/A
=> [#3291] fix(web): disable link dragging

integration-test/build.gradle.kts, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/CatalogsPageDorisTest.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/CatalogsPageKafkaTest.java
Add test create doris catalog to the web e2e test
Fix: #3209
manual
---------
Add test create doris catalog to the web e2e test
Fix: #3209
N/A
manual
=> [#3209] test(web): doris web e2e test (#3230)

core/src/main/java/com/datastrato/gravitino/Configs.java, web/src/app/rootLayout/AppBar.js
Changed Configs interface to class since Configs doesn't include any methods but defines a lot of constants.
Fix: #2912 
No
manually
=> [#2912] improve(core): Using class not interface for `Configs`

api/src/test/resources/log4j2.properties, catalogs/catalog-hadoop/src/test/resources/log4j2.properties, catalogs/catalog-hive/src/test/resources/log4j2.properties, catalogs/catalog-jdbc-doris/src/test/resources/log4j2.properties, catalogs/catalog-jdbc-mysql/src/test/resources/log4j2.properties, catalogs/catalog-jdbc-postgresql/src/test/resources/log4j2.properties, catalogs/catalog-kafka/src/main/java/com/datastrato/gravitino/catalog/kafka/KafkaCatalogOperations.java, catalogs/catalog-kafka/src/main/resources/kafka.conf, catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java, catalogs/catalog-kafka/src/test/resources/log4j2.properties, catalogs/catalog-lakehouse-iceberg/src/test/resources/log4j2.properties, clients/client-java/src/test/java/resources/log4j2.properties, clients/client-java/src/test/resources/log4j2.properties, common/src/test/java/resources/log4j2.properties, core/src/test/resources/log4j2.properties, dev/docker/trino/conf/log4j2.properties, integration-test/src/test/resources/log4j2.properties, server/src/test/resources/log4j2.properties, spark-connector/spark-connector/src/test/resources/log4j2.properties
-  Transmit the real reason for the error to the user
- shorten timeout from 60s to 15s
- add thread info to the log
- add default timeout config to the conf file
Fix: #3249 
no
test added
=> [#3249] improvement(kafka-catalog): clarify error message and shorten timeout

web/src/app/rootLayout/AppBar.js
fix next/image component src issue
Fix: #3413
Before
After
smoke test
=> [#3413] fix(web): fix logo error

MAINTAINERS.md
* Add Sophie Sun(SophieTech88) to Contributors list in MAINTAINERS.md.
=> [MINOR]docs: Update MAINTAINERS.md for Sophie

MAINTAINERS.md
Add Eric Chang (unknowntpo) (me) to Contributors list.
c.c. @justinmclean
=> feat(MAINTAINERS.md): add Eric Chang (unknowntpo)

MAINTAINERS.md
Add charliecheng630 to Contributors list
Fix: #3361
=> [MINOR] docs: Update MAINTAINERS.md 

MAINTAINERS.md
use real names in Maintainer table
use maintainers' real name
no
no need
=> [MINOR] fix(maintainers): use real names in Maintainer table

MAINTAINERS.md
Remove people from Maintainers who no longer contribute to the project
People are no longer active.
Fix: # (issue)
N/A
N/A
=> [MINOR]doc: Remove people from Maintainers who no longer contribute to the project

clients/client-python/MANIFEST.in, clients/client-python/build.gradle.kts, clients/client-python/setup.py, docs/how-to-use-python-client.md, docs/how-to-use-the-playground.md
1. Update markdown file
2. Optimized Gradle script in the Python client module.
1. add missing Python tab switch params in the `how-to-use-python-client.md`
3. Optimized Gravitino Python client Gradle build script
Fix: #3422
N/A
CI Passed
=> [#3422]improve(doc, build): Set code tab switching params in the Python Client doc

catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/miniHMS/ScriptRunner.java
Remove Duplicate condition in ScriptRunner.
The `trimmedLine.length() < 1 || trimmedLine.startsWith("--")` condition already been judged.
NO.
Local.
=> [MINOR] improve: Remove Duplicate condition in ScriptRunner

web/src/app/metalakes/CreateMetalakeDialog.js, web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js, web/src/lib/utils/regex.js
Modified rules for create name field.
Fix: #3202
N/A
N/A
=> [#3202] improve(web): modified rules for create name field

web/src/configs/themeConfig.js, web/src/lib/provider/session.js, web/src/lib/store/auth/index.js, web/src/lib/utils/axios/checkStatus.ts, web/src/lib/utils/axios/index.ts
Improve the user experience of refreshing the oauth token.
Fix: #3009
When the user doesn't interact with the interface for 30 minutes, they will be brought back to the login page.
Local
=> [#3009] improve(web): improve the user experience of refreshing the oauth token

LICENSE
Fix file paths in LICENSE file.
So the license is correct.
Fix: #3576
N/A
N/A
=> [#3576] Correct file paths in LICENSE file

spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/catalog/BaseCatalog.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/catalog/TestTransformTableChange.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/SparkCommonIT.java
change table comment though table properties
Fix: #3137 
no
add ut and IT
=> [#3137] fix(spark-connector):  change table comment though table properties

common/src/main/java/com/datastrato/gravitino/config/ConfigConstants.java, core/src/main/java/com/datastrato/gravitino/Configs.java, core/src/main/java/com/datastrato/gravitino/metrics/source/MetricsSource.java, core/src/test/java/com/datastrato/gravitino/metrics/TestMetricsSystem.java, core/src/test/java/com/datastrato/gravitino/metrics/source/TestMetricsSource.java, docs/gravitino-server-config.md, server-common/src/main/java/com/datastrato/gravitino/server/web/HttpServerMetricsSource.java
using time sliding window to record timer metrics
Fix: #3152 
no
test in local env to check whether Pxx comes to 0 after a while
=> [#3152] feat(core): using time sliding window to record timer metrics

clients/client-python/requirements-dev.txt
As title, specify pylint version in order to avoid unexpected bugs in the future development.
Fix: #3558
No.
`./gradlew build -x test` or `./gradlew :clients:client-python:pylint` for for the convenience.
=> [#3558] fix(client-python): specified tests packages version

docs/spark-connector/spark-catalog-iceberg.md
update spark-iceberg connector document
Fix: https://github.com/datastrato/gravitino/issues/3595
=> [#3595] Improvement(spark-connector): update spark-iceberg connector document

web/LICENSE, web/src/lib/icons/svg/doris.svg, web/src/lib/icons/svg/hive.svg
mention license for svg files
Fix: #3579
N/A
N/A
=> [#3579] fix(license): mention license for svg files

catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HadoopUserImpersonationIT.java
Remove the drop metalake logic as somethings it will failed.
Improve CI stability.
Fix: #3638
N/A
Test locally.
=> [#3638] Fix UT HadoopUserImpersonationIT fails occasionally

docs/docker-image-details.md
Add the Docker image change log for 0.5.1
Fix: #3646
Just doc.
No need.
=> [#3646] doc: Add the Docker image change log for 0.5.1

.github/workflows/backend-integration-test.yml
skip unnecessary tests in backend
Fix: #3648 
no
no
=> [#3648] improvement(CI): skip unnecessary tests in backendIT

web/LICENSE, web/src/lib/icons/svg/doris.svg, web/src/lib/icons/svg/hive.svg
Thie fix is not correct.
No.
Exiting tests.
=> [MINOR] Revert "[#3579] fix(license): mention license for svg files (#3617)"

docs/how-to-build.md, docs/spark-connector/spark-connector.md
add multi spark and scala version for spark connector doc
Fix: #3600 
No
just document
=> [#3660] docs(spark-connector): add multi spark and scala version for spark connector doc

gradle.properties
change project version to 0.5.1 for release rc1
change project version to 0.5.1 for release rc1
no
existing tests
=> [MINOR] change project version to 0.5.1 for release rc1

gradle.properties
change project version to 0.5.2-SNAPSHOT
change project version to 0.5.2-SNAPSHOT
no
existing tests
=> [MINOR] change project version to 0.5.2-SNAPSHOT

catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/HadoopCatalogOperations.java, catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/kerberos/AuthenticationConfig.java, catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/kerberos/KerberosConfig.java, catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HadoopUserAuthenticationIT.java, catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HadoopUserImpersonationIT.java, docs/hadoop-catalog.md
Add document about user authentication for Hadoop catalog
To improve user experience.
Fix: #3658 
N/A
N/A.
=> [#3658] docs(hadoop-catalog): Add document about user authentication for Hadoop catalog

dev/docker/trino/Dockerfile, dev/docker/trino/conf/config.properties, dev/docker/trino/conf/jvm.config, docs/docker-image-details.md
Update Trino docker image to Trino-435
Fix: #3683 
NO
NO
=> [#3683] fix(docker): Update Trino docker image to Trino-435

server/src/main/java/com/datastrato/gravitino/server/web/rest/CatalogOperations.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/FilesetOperations.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/MetalakeOperations.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/PartitionOperations.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/SchemaOperations.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/TableOperations.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/TopicOperations.java
add logs for server requests and responses
Assist in problem localization
no
no need
=> [MINOR] improvement(log): add log for server

dev/docker/trino/Dockerfile, dev/docker/trino/conf/config.properties, dev/docker/trino/conf/jvm.config, docs/docker-image-details.md
Update Trino docker image to Trino-435
Fix: #3683 
NO
NO
=> [#3683] fix(docker): Update Trino docker image to Trino-435 

docs/spark-connector/spark-catalog-iceberg.md, spark-connector/spark-common/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConstants.java, spark-connector/spark-common/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConverter.java, spark-connector/spark-common/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/SparkIcebergTable.java, spark-connector/spark-common/src/test/java/com/datastrato/gravitino/spark/connector/iceberg/TestIcebergPropertiesConverter.java, spark-connector/spark-common/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/SparkCommonIT.java, spark-connector/spark-common/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/iceberg/SparkIcebergCatalogIT.java
disable Iceberg catalog cache
Fix: #3705 
no
add IT
=> [HOTFIX][#3705] fix(spark-connector): write data to Iceberg table failed if drop and recreate Iceberg table 

.gitignore, spark-connector/v3.3/spark/build.gradle.kts, spark-connector/v3.4/spark/build.gradle.kts, spark-connector/v3.5/spark/build.gradle.kts
remove metastored_db and derby.log after integration test
remove metastored_db and derby.log after integration test
no
existing tests
=> [MINOR] test(spark-connector): remove metastored_db and derby.log after integration test

clients/client-python/setup.py
Fix the Python version to 0.5.2.dev1 for developing.
No.
=> [MINOR] fix(client-python): Fix branch 0.5 python version to 0.5.2.dev1

clients/client-python/setup.py
Update the client python version to 0.6.0.dev1 to align with java version.
No.
Exiting tests.
=> [MINOR] Fix(client-python): Update the python version to 0.6.0.dev1

clients/client-python/setup.py, gradle.properties
change project version back after release tag
change project version back after release tag
no
existing tests
=> [MINOR] change project version back after release tag

docs/spark-connector/spark-catalog-iceberg.md
correct Iceberg document
correct Iceberg document
no
just document
=> [MINOR] docs(spark-connector): correct Iceberg document

build.gradle.kts
as title
Avoid printing abnormal log when building on windows
no
minor fix
=> [MINOR] Check docker-connector and orbstack only for macos

docs/spark-connector/spark-catalog-iceberg.md
polish iceberg doc
polish iceberg doc
no
just document
=> [MINOR] docs(spark-connector): polish iceberg doc

docs/docker-image-details.md
correct release version
correct release version
no
document
=> [MINOR] docs: correct release version

clients/client-python/gravitino/api/catalog_change.py, clients/client-python/pylintrc
Fix method-hidden issue to satisfy Pylint rule by adding `_` prefix to the variables in related class in `catalog_change.py`
Fix: #3768
No
=> [#3768] fix(client-python): fix method-hidden issue

integration-test/trino-it/docker-compose.yaml
Update hive image in the Trino docker environment
Fix: #3779
NO
Exists UT&IT
=> [#3779] improvement (trino-connector): Update hive image in the Trino docker environment

clients/client-python/gravitino/utils/http_client.py, clients/client-python/pylintrc
* Fix no-name-in-module and inconsistent-return-statements Pylint rule
Fix: #3771 
No
=> [#3771] improvement(client-python): Fix no-name-in-module and inconsistent-return-statements Pylint rule for client-python

.github/workflows/build.yml, .github/workflows/cron-integration-test.yml, .github/workflows/python-integration-test.yml
- upload logs of catalog
- add free up disk space
Fix: #3805
N/A
github workflow
=> [#3805] improvement(CI): upload logs of catalog and add free up disk space

clients/client-python/gravitino/dto/dto_converters.py, clients/client-python/gravitino/dto/metalake_dto.py, clients/client-python/pylintrc
Fix protected-access Pylint rule
Fix: #3770 
No
=> [#3770] Fix(client-python): fix protected-access issue

core/src/main/java/com/datastrato/gravitino/storage/kv/KvGarbageCollector.java, core/src/main/java/com/datastrato/gravitino/storage/relational/JDBCBackend.java, core/src/main/java/com/datastrato/gravitino/storage/relational/RelationalBackend.java, core/src/main/java/com/datastrato/gravitino/storage/relational/RelationalGarbageCollector.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/CatalogMetaMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/FilesetMetaMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/FilesetVersionMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/GroupMetaMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/GroupRoleRelMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/MetalakeMetaMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/RoleMetaMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/SchemaMetaMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/SecurableObjectMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/TableMetaMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/TopicMetaMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/UserMetaMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/UserRoleRelMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/CatalogMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/FilesetMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/GroupMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/MetalakeMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/RoleMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/SchemaMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/TableMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/TopicMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/UserMetaService.java, core/src/test/java/com/datastrato/gravitino/storage/kv/TestKvGarbageCollector.java, core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestGroupMetaService.java, core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestRoleMetaService.java, core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestUserMetaService.java
Timeline is one word. Line shouldn't start with upper letter.
Fix: #3813 
No.
grep  -R `TimeLine` *
No file.
=> [#3813] improvement: Fix the typo about timeline.

clients/client-python/scripts/generate_version.py
add license for Python version file
Fix: #3826 
no
build sucessfully
=> [#3826] fix(build): add license for Python version file

integration-test/src/test/resources/trino-ci-testset/testsets/hive/00002_alter_table.txt, integration-test/src/test/resources/trino-ci-testset/testsets/hive/00006_datatype.txt, integration-test/src/test/resources/trino-ci-testset/testsets/hive/00007_varchar.txt
Remove the hard code of the hdfs port in test result comparison 
Improve the trino test tool
Fix: #3641 
N/A
N/A
=> [#3641] improvement (trino-it): removed hdfs port in test result comparison

.github/workflows/backend-integration-test.yml, .github/workflows/build.yml, .github/workflows/cron-integration-test.yml, .github/workflows/flink-integration-test.yml, .github/workflows/frontend-integration-test.yml, .github/workflows/python-integration-test.yml, .github/workflows/spark-integration-test.yml, dev/ci/util_free_space.sh
- use gradle cache
- reuse intermediate compilation results
- remove unnecessary command
Fix: #3837 
no
CI passed
=> [#3837] improvement(CI): Optimize job of CI

api/src/main/java/com/datastrato/gravitino/rel/partitions/Partitions.java, common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java, common/src/test/java/com/datastrato/gravitino/dto/util/TestDTOConverters.java, core/src/test/java/com/datastrato/gravitino/catalog/TestTableNormalizeDispatcher.java
fix type cast issue in `DTOConverters`.
Fix: #3884 
No.
Not need.
=> [#3884] fix(common): fix type cast issue in `DTOConverters`

.github/workflows/cron-integration-test.yml
add flink and spark it logs
missing flink and spark it logs
no
existing tests
=> [MINOR] update flink&spark integration test logs for cron job

build.gradle.kts, catalogs/bundled-catalog/build.gradle.kts, catalogs/catalog-lakehouse-paimon/build.gradle.kts, catalogs/catalog-lakehouse-paimon/src/main/java/com/datastrato/gravitino/catalog/lakehouse/paimon/PaimonCatalog.java, catalogs/catalog-lakehouse-paimon/src/main/java/com/datastrato/gravitino/catalog/lakehouse/paimon/PaimonCatalogCapability.java, catalogs/catalog-lakehouse-paimon/src/main/java/com/datastrato/gravitino/catalog/lakehouse/paimon/PaimonCatalogOperations.java, catalogs/catalog-lakehouse-paimon/src/main/java/com/datastrato/gravitino/catalog/lakehouse/paimon/PaimonSchema.java, catalogs/catalog-lakehouse-paimon/src/main/java/com/datastrato/gravitino/catalog/lakehouse/paimon/PaimonTable.java, catalogs/catalog-lakehouse-paimon/src/main/resources/META-INF/services/com.datastrato.gravitino.CatalogProvider, catalogs/catalog-lakehouse-paimon/src/main/resources/core-site.xml.template, catalogs/catalog-lakehouse-paimon/src/main/resources/hdfs-site.xml.template, catalogs/catalog-lakehouse-paimon/src/main/resources/lakehouse-paimon.conf, gradle/libs.versions.toml, settings.gradle.kts
Based on https://github.com/datastrato/gravitino/pull/2746 contributed by @SteNicholas.
Add a basic code skeleton for Paimon catalog.
Fix: https://github.com/datastrato/gravitino/issues/3885
No.
Just build.
=> [#3885] feat(catalog-lakehouse-paimon): Add a basic code skeleton for Paimon catalog

catalogs/catalog-jdbc-doris/build.gradle.kts, dev/docker/doris/Dockerfile, dev/docker/doris/start.sh, docs/docker-image-details.md, integration-test/build.gradle.kts
- remove chmod in Doris Container start.sh
- add chmod in Doris Dockerfile
accelerate the startup speed for Doris Container
Fix: #3881
N/A
Manual
=> [#3881] fix(CI): move chmod to build stage to accelerate the startup speed for Doris

clients/client-python/gravitino/filesystem/gvfs.py, clients/filesystem-hadoop3/src/main/java/com/datastrato/gravitino/filesystem/hadoop/GravitinoVirtualFileSystemConfiguration.java, docs/how-to-use-gvfs.md
Increase the default cache time to 1 hour.
Fix: #3928
=> [#3928] improvement(filesystem): Increase default cache time to 1 hour

common/src/main/java/com/datastrato/gravitino/dto/messaging/TopicDTO.java
return a new instance when `build()` called
Fix: #3941 
no
by logic
=> [#3941] fix(common): Fix potential bug of TopicDTO

catalogs/catalog-lakehouse-paimon/build.gradle.kts, catalogs/catalog-lakehouse-paimon/src/main/java/com/datastrato/gravitino/catalog/lakehouse/paimon/PaimonCatalog.java, catalogs/catalog-lakehouse-paimon/src/main/java/com/datastrato/gravitino/catalog/lakehouse/paimon/PaimonCatalogPropertiesMetadata.java, catalogs/catalog-lakehouse-paimon/src/test/java/com/datastrato/gravitino/catalog/lakehouse/paimon/integration/test/CatalogPaimonBaseIT.java, catalogs/catalog-lakehouse-paimon/src/test/java/com/datastrato/gravitino/catalog/lakehouse/paimon/integration/test/CatalogPaimonFileSystemIT.java, catalogs/catalog-lakehouse-paimon/src/test/resources/log4j2.properties
Add a basic integrate test code skeleton for Paimon Catalog
Fix: https://github.com/datastrato/gravitino/issues/3890
No.
Basic ITs.
=> [#3890] feat(catalog-lakehouse-paimon): Add a basic integrate test code skeleton for Paimon Catalog

.github/workflows/frontend-integration-test.yml, spark-connector/v3.3/spark/build.gradle.kts, spark-connector/v3.4/spark/build.gradle.kts, spark-connector/v3.5/spark/build.gradle.kts
Fix the problem is that the log information cannot be written to the log file.
Fix: #3962 
It's a bug.
Test locally.
=> [#3962] fix(spark-connector): Fix the log problem for spark-connector

integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/CatalogsPageTest.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/AbstractWebIT.java
retry testClickCatalogLink at most 5 times
api data inconsistencies with test cast by the instability response
Fix: #3936
N/A
manual test
=> [#3936] web ci retry testClickCatalogLink at most 5 times

server/src/main/java/com/datastrato/gravitino/server/web/rest/CatalogOperations.java
Add metrics annotations for catalog operations, like we did for other operations.
Fix: #3923
=> [#3923] improvement(server): Add metrics annotations for catalog operations

core/src/main/java/com/datastrato/gravitino/EntityAlreadyExistsException.java, core/src/main/java/com/datastrato/gravitino/EntityStore.java, core/src/main/java/com/datastrato/gravitino/storage/kv/KvBackend.java, core/src/main/java/com/datastrato/gravitino/storage/kv/KvEntityStore.java, core/src/main/java/com/datastrato/gravitino/storage/kv/RocksDBKvBackend.java, core/src/main/java/com/datastrato/gravitino/storage/kv/TransactionalKvBackendImpl.java, core/src/main/java/com/datastrato/gravitino/storage/relational/JDBCBackend.java, core/src/main/java/com/datastrato/gravitino/storage/relational/RelationalBackend.java, core/src/main/java/com/datastrato/gravitino/storage/relational/RelationalEntityStore.java, core/src/main/java/com/datastrato/gravitino/storage/relational/converters/H2ExceptionConverter.java, core/src/main/java/com/datastrato/gravitino/storage/relational/converters/MySQLExceptionConverter.java, core/src/main/java/com/datastrato/gravitino/storage/relational/converters/SQLExceptionConverter.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/CatalogMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/FilesetMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/GroupMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/MetalakeMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/RoleMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/SchemaMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/TableMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/TopicMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/UserMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/utils/ExceptionUtils.java, core/src/test/java/com/datastrato/gravitino/storage/TestEntityStorage.java, core/src/test/java/com/datastrato/gravitino/storage/kv/TestRocksDBKvBackend.java, core/src/test/java/com/datastrato/gravitino/storage/memory/TestMemoryEntityStore.java, core/src/test/java/com/datastrato/gravitino/storage/relational/TestJDBCBackend.java, core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestGroupMetaService.java, core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestRoleMetaService.java, core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestSecurableObjects.java, core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestUserMetaService.java
Improve the throwing behavior of some SQL exceptions in EntityStore.
Fix: #3976 
Through the existing tests.
=> [#3976] improvement(core): Improve the exception behavior in entity store

flink-connector/src/main/java/com/datastrato/gravitino/flink/connector/PropertiesConverter.java, flink-connector/src/main/java/com/datastrato/gravitino/flink/connector/catalog/BaseCatalog.java, flink-connector/src/main/java/com/datastrato/gravitino/flink/connector/catalog/GravitinoCatalogManager.java, flink-connector/src/test/java/com/datastrato/gravitino/flink/connector/integration/test/FlinkCommonIT.java, flink-connector/src/test/java/com/datastrato/gravitino/flink/connector/integration/test/FlinkEnvIT.java, flink-connector/src/test/java/com/datastrato/gravitino/flink/connector/integration/test/hive/FlinkHiveCatalogIT.java
refactor: move the schema operation ITs to FlinkCommonIT
Fix: #3983 
- no
- ITs
=> [#3983] refactor: move the schema operation ITs to FlinkCommonIT

NOTICE, NOTICE.bin, web/NOTICE, web/NOTICE.bin
Update NOTICE files to comply with ASF policy.
To comply with ASF policy.
Fix: #4039
No.
Built and run non-integration tests locally.
=> [#4039] Update NOTICE files to ASF norms

README.md
Update README with ASF Incubator disclaimer and updated links and used Apache Gravitino where needed.
To comply with ASF policy
Fix: #4048
No
N/A - only changes a text file
=> [#4048] Update README with incubator disclaimer

.asf.yaml
Add dependabots and protected_tags.
Fix: #4066
No.
Verified after merging.
=> [#4066] improvment(build): Add dependabots and protected_tags

DISCLAIMER_WIP.txt, build.gradle.kts
Add work in progress disclaimer.
Required by ASF incubator policy.
Fix: #4074
N/A
N/A
=> [#4074] Add work in progress disclaimer.

docs/manage-metalake-using-gravitino.md, docs/manage-relational-metadata-using-gravitino.md
Fixed an incorrect Java example.
#4077 
Fix: # (issue)
No
No testing required
=> [#4077] improvement(docs): Fixed an incorrect Java example

CODE_OF_CONDUCT.md, CONTRIBUTING.md, GOVERNANCE.md, MAINTAINERS.md, SECURITY.md
Update project's current policies to be in line with ASF policy.
To comply with ASF policy.
Fix: #4073
No.
Built locally.
=> [#4073] Update policies to be in line with ASF policy.

CONTRIBUTING.md, build.gradle.kts, clients/client-python/setup.py, dev/docker/ranger/ranger-dependency.sh, docs/docker-image-details.md, docs/getting-started.md, docs/hadoop-catalog.md, docs/how-to-build.md, docs/how-to-install.md, docs/how-to-use-gvfs.md, docs/how-to-use-python-client.md, docs/how-to-use-the-playground.md, docs/index.md, docs/manage-table-partition-using-gravitino.md, docs/publish-docker-images.md, docs/trino-connector/installation.md, server-common/src/main/java/com/datastrato/gravitino/server/web/JettyServer.java, web/src/app/rootLayout/Footer.js
Change GitHub and resources to ASF ones. Still to fix are Docker and the documentation URL. But this can be merged now.
As we are now an ASF project.
Fix: #4064
No
Built locally with no issues.
=> [#4064] Fix GitHub and resources

integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoQueryTestTool.java
=> [#4135] fix(trino-connector):  Fix typo about Gravitino in trino-connector

docs/lakehouse-iceberg-catalog.md
Fixed an unreachable link.
Fix: #4155
No
No testing required
=> [#4155]fix(doc): Fixed an unreachable link

docs/trino-connector/supported-catalog.md
Fixed an incorrect description.
Fix: #4145
No
No testing required
=> [#4077] improvement(docs): Fixed an incorrect description and some incomplete examples

api/src/main/java/org/apache/gravitino/MetadataObjects.java, api/src/main/java/org/apache/gravitino/authorization/Privilege.java, api/src/main/java/org/apache/gravitino/authorization/Privileges.java, api/src/main/java/org/apache/gravitino/authorization/SecurableObjects.java, api/src/test/java/org/apache/gravitino/authorization/TestSecurableObjects.java, core/src/main/java/org/apache/gravitino/Entity.java, core/src/main/java/org/apache/gravitino/storage/relational/service/MetadataObjectService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java, core/src/test/java/org/apache/gravitino/storage/relational/service/TestSecurableObjects.java, server/src/main/java/org/apache/gravitino/server/web/rest/RoleOperations.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestRoleOperations.java
Remove privileges of metalakes. We use the ownership instead of metalake privileges.
Fix: #4128
Modify APIs. But this feature isn't released yet.
Existing UTs
=> [#4128] improvement(core): Remove privileges of metalakes

core/src/main/java/org/apache/gravitino/utils/ClientPoolImpl.java
=> [#4183] Updated notify to notifyAll

api/src/main/java/org/apache/gravitino/authorization/Privilege.java, api/src/main/java/org/apache/gravitino/authorization/Privileges.java, api/src/test/java/org/apache/gravitino/authorization/TestSecurableObjects.java, core/src/test/java/org/apache/gravitino/proto/TestEntityProtoSerDe.java, core/src/test/java/org/apache/gravitino/storage/relational/service/TestRoleMetaService.java, core/src/test/java/org/apache/gravitino/storage/relational/service/TestSecurableObjects.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestRoleOperations.java
Optimize the privileges of securable objects
Fix: #4140
No.
=> [#4140] improvement(core): Optimize the privileges of securable objects

common/src/main/java/org/apache/gravitino/dto/responses/CatalogListResponse.java, common/src/test/java/org/apache/gravitino/dto/responses/TestResponses.java
Add method `validate` in CatalogListResponse
Fix: #4197 
No.
Add the new ut.
=> [#4197] improvement(common): CatalogListResponse should implement the method validate

api/src/main/java/org/apache/gravitino/authorization/Privilege.java, api/src/main/java/org/apache/gravitino/authorization/Privileges.java
Optimize the privileges of access control
Fix: #4143
No need.
Exsiting tests.
=> [#4143] improvment(core): Optimize the privileges of access control

catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/utils/TypeUtils.java, catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/utils/TestTypeUtils.java
Support paimon CharType and VarBinaryType.
Fix: https://github.com/apache/gravitino/issues/4193
No.
Existing UTs.
=> [#4193] Improvement(catalogs-lakehouse-paimon): Support paimon CharType and VarBinaryType

api/src/main/java/org/apache/gravitino/Catalog.java, api/src/main/java/org/apache/gravitino/Schema.java, api/src/main/java/org/apache/gravitino/file/Fileset.java, api/src/main/java/org/apache/gravitino/messaging/Topic.java, api/src/main/java/org/apache/gravitino/rel/Table.java, api/src/main/java/org/apache/gravitino/tag/TagOperations.java, clients/client-java/src/main/java/org/apache/gravitino/client/BaseSchemaCatalog.java, clients/client-java/src/main/java/org/apache/gravitino/client/DTOConverters.java, clients/client-java/src/main/java/org/apache/gravitino/client/ErrorHandlers.java, clients/client-java/src/main/java/org/apache/gravitino/client/FilesetCatalog.java, clients/client-java/src/main/java/org/apache/gravitino/client/GenericFileset.java, clients/client-java/src/main/java/org/apache/gravitino/client/GenericSchema.java, clients/client-java/src/main/java/org/apache/gravitino/client/GenericTag.java, clients/client-java/src/main/java/org/apache/gravitino/client/GenericTopic.java, clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClient.java, clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClientBase.java, clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoMetalake.java, clients/client-java/src/main/java/org/apache/gravitino/client/MessagingCatalog.java, clients/client-java/src/main/java/org/apache/gravitino/client/MetadataObjectTagOperations.java, clients/client-java/src/main/java/org/apache/gravitino/client/RelationalCatalog.java, clients/client-java/src/main/java/org/apache/gravitino/client/RelationalTable.java, clients/client-java/src/main/java/org/apache/gravitino/client/SupportsTagOperations.java, clients/client-java/src/test/java/org/apache/gravitino/client/TestGenericTag.java, clients/client-java/src/test/java/org/apache/gravitino/client/TestGravitinoAdminClient.java, clients/client-java/src/test/java/org/apache/gravitino/client/TestGravitinoMetalake.java, clients/client-java/src/test/java/org/apache/gravitino/client/TestSupportTags.java, common/src/main/java/org/apache/gravitino/dto/SchemaDTO.java, common/src/main/java/org/apache/gravitino/dto/file/FilesetDTO.java, common/src/main/java/org/apache/gravitino/dto/tag/TagDTO.java
This PR proposes to add client side Java REST API for tag system.
This is a part of work for tag system.
Fix: #4172 
Yes.
UT added.
=> [#4172] feat(client-java): Add client side Java REST API for Tag System

catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/operation/DorisTableOperations.java, catalogs/catalog-jdbc-mysql/src/main/java/org/apache/gravitino/catalog/mysql/operation/MysqlTableOperations.java, catalogs/catalog-jdbc-postgresql/src/main/java/org/apache/gravitino/catalog/postgresql/operation/PostgreSqlTableOperations.java, clients/client-java/src/test/java/org/apache/gravitino/client/TestRelationalCatalog.java, common/src/main/java/org/apache/gravitino/dto/rel/partitions/ListPartitionDTO.java, common/src/main/java/org/apache/gravitino/dto/requests/FilesetUpdateRequest.java, common/src/main/java/org/apache/gravitino/dto/responses/MetadataObjectListResponse.java, common/src/main/java/org/apache/gravitino/dto/util/DTOConverters.java, common/src/test/java/org/apache/gravitino/dto/util/TestDTOConverters.java, core/src/main/java/org/apache/gravitino/meta/GroupEntity.java, core/src/main/java/org/apache/gravitino/meta/UserEntity.java, core/src/main/java/org/apache/gravitino/utils/Bytes.java, server/src/main/java/org/apache/gravitino/server/web/rest/MetalakeOperations.java
Correct the camel case naming issue and add missing Override annotations.
Better code readability, maintainability, and adherence to coding standards.
No.
No need.
=> [MINOR] fix: Correct the camel case naming issue and add missing @Override annotations

core/src/main/java/org/apache/gravitino/catalog/CatalogManager.java
Refine the comments within the `createCatalogWrapper` method.
Better readability.
No.
No need.
=> [MINOR] fix: Refine the comments within the createCatalogWrapper method

docs/manage-metalake-using-gravitino.md, docs/manage-relational-metadata-using-gravitino.md, docs/manage-table-partition-using-gravitino.md
Correct the mistakes in some documents.
Better readability & maintainability.
No.
Not necessary.
=> [MINOR] Correct the mistakes in some documents

catalogs/catalog-hive/src/main/java/org/apache/gravitino/catalog/hive/HiveTable.java
The local variable sd in the buildStorageDescriptor method of HiveTable.java has been renamed.
The local variable sd was hiding a class member, which could lead to potential bugs and confusion.
Fix: #4188
=> [#4188] Renamed local instance of StorageDescriptor in buildStorageDescriptor

integration-test/src/test/java/org/apache/gravitino/integration/test/trino/TrinoQueryIT.java, integration-test/src/test/java/org/apache/gravitino/integration/test/trino/TrinoQueryITBase.java, integration-test/src/test/java/org/apache/gravitino/integration/test/trino/TrinoQueryRunner.java, integration-test/src/test/java/org/apache/gravitino/integration/test/trino/TrinoQueryTestTool.java, integration-test/trino-it/init/trino/config/jvm.config, integration-test/trino-it/init/trino/config/log4j2.properties, integration-test/trino-it/init/trino/init.sh, integration-test/trino-it/launch.sh, integration-test/trino-test-tools/trino_test.sh, trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/CatalogConnectorManager.java, trino-connector/src/main/java/org/apache/gravitino/trino/connector/system/storedprocdure/AlterCatalogStoredProcedure.java, trino-connector/src/main/java/org/apache/gravitino/trino/connector/system/storedprocdure/CreateCatalogStoredProcedure.java, trino-connector/src/main/java/org/apache/gravitino/trino/connector/system/storedprocdure/DropCatalogStoredProcedure.java
1. Add more output log  for run the Trino Integration test.
2. Enable debug for TrinoQuery runner
3. Increase timeout for wait catalog to create.
Fix: #4238
NO
NO
=> [#4238] fix (trino-connector) Make the Trino connector test more stable and improve the logs

docs/flink-connector/flink-catalog-hive.md, docs/flink-connector/flink-connector.md, flink-connector/src/main/java/org/apache/gravitino/flink/connector/utils/PropertyUtils.java
- add flink connector doc
- add flink connector hive doc
Fix: #4269
- on
- no need
=> [#4269] doc(flink-connector): add flink connector doc

README.md
add TM symbol
ASF policy
Fix: # N/A
No
No
=> [Minor] add trademark symbol

api/src/main/java/org/apache/gravitino/tag/SupportsTags.java, clients/client-java/src/main/java/org/apache/gravitino/client/MetadataObjectTagOperations.java, integration-test/src/test/java/org/apache/gravitino/integration/test/TagIT.java, server/src/main/java/org/apache/gravitino/server/web/rest/TagOperations.java
This PR proposes to add integration tests for the current tag system, also fixes some corner issues during test.
These are necessary e2e tests to make sure tag system is worked.
Fix: #4237 
NO.
ITs to cover.
=> [#4237] test: Add integration tests for tag system

README.md
Seems :tm: doesn't work in titles
so tm symbol displays correctly
Fix: # N/A
N/A
N/A
=> [Minor] fix trademark symbol

catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/authentication/kerberos/KerberosClient.java, catalogs/catalog-hive/src/main/java/org/apache/gravitino/catalog/hive/HiveCatalogOperations.java, catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/PaimonCatalogPropertiesMetadata.java, catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/authentication/kerberos/KerberosClient.java, core/src/main/java/org/apache/gravitino/connector/BaseCatalog.java, iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/authentication/kerberos/KerberosClient.java, spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/iceberg/IcebergPropertiesConstants.java
Modifying declaration parts, removing calls that do not need to be used
 It shouldn't be used, but it's declared
Fix: #4185 
No
Check change code and existing code comparison
=> [#4185] improvement(core, catalogs): Change the @VisibleForTesting in production code to change usability

docs/manage-fileset-metadata-using-gravitino.md, docs/manage-tags-in-gravitino.md, docs/open-api/openapi.yaml, docs/open-api/tags.yaml, docs/open-api/topics.yaml
This PR proposes to add docs for tag system.
To let users know how to use tag system.
Fix: #4255 
No.
Manual test.
=> [#4255] feat(docs): Add docs for Tag System

clients/client-python/gravitino/auth/default_oauth2_token_provider.py, clients/client-python/gravitino/dto/responses/oauth2_error_response.py, clients/client-python/gravitino/exceptions/base.py, clients/client-python/gravitino/exceptions/handlers/oauth_error_handler.py, clients/client-python/gravitino/utils/http_client.py, clients/client-python/tests/unittests/auth/mock_base.py, clients/client-python/tests/unittests/auth/test_oauth2_token_provider.py
* Add OAuth Error Handler and related exceptions, UT in `client-python` based on `client-java`
Fix: #4173 
No
UT Added and test with `./gradlew client:client-python:test`
=> [#4173] improvement(client-python): Add OAuth Error Handler and related exceptions, test cases in client-python

docs/security.md
Add more documents to avoid users' misunderstanding
Fix: #4175
No.
Just document.
=> [#4175] fix(doc): Add more documents to avoid users' misunderstanding

web/src/components/StyledToast.js, web/src/lib/utils/axios/index.js
Refine network error msg
N/A
Fix: #2110
N/A
manually operated
=> [#2110] fix(ui): refine network error msg

clients/client-python/gravitino/exceptions/base.py, iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/utils/IcebergCatalogUtil.java, integration-test/build.gradle.kts
Run `gradle :web:build` first as some frontend test depends on web page.
Fix the bugs.
Fix: #3827 
N/A.
N/A
=> [#3827] fix(integration-test): Fix bugs about running frontend tests locally.

clients/client-python/.gitignore, clients/client-python/build.gradle.kts, clients/client-python/setup.py, docs/how-to-use-python-client.md
Publish Python client to Apache Gravitino official account at Pypi.org
+ https://pypi.org/project/apache-gravitino/
Fix: #4442
N/A
I publish a test version at the: https://pypi.org/project/apache-gravitino/
When this PR is merged, I will remove this template publish.
=> [#4442] feat(client-python): Publish Python client to Apache Gravitino official account

docs/lakehouse-paimon-catalog.md
Update Paimon Catalog doc, add the `AlterTable`, `partition` and `Index` related docs.
Fix: https://github.com/apache/gravitino/issues/4433
=> [#4433] Improvement(catalog-lakehouse-paimon): Update Paimon Catalog doc

.github/workflows/docker-image.yml, dev/docker/iceberg-rest-server/Dockerfile
support publish Gravitino Iceberg REST catalog server docker image
publish Gravitino Iceberg REST catalog server docker image is necessary before release.
no
verified by publish docker image
=> [MINOR] support publish Gravitino Iceberg REST catalog server docker image

catalogs/catalog-hadoop/build.gradle.kts, catalogs/catalog-hive/build.gradle.kts, catalogs/catalog-jdbc-doris/build.gradle.kts, catalogs/catalog-jdbc-mysql/build.gradle.kts, catalogs/catalog-jdbc-postgresql/build.gradle.kts, catalogs/catalog-kafka/build.gradle.kts, catalogs/catalog-lakehouse-iceberg/build.gradle.kts, catalogs/catalog-lakehouse-paimon/build.gradle.kts, iceberg/iceberg-rest-server/build.gradle.kts
change some configuration file permission from 644 to 755
Fix: #4478 
no
check the permission
=> [#4478] feat(conf): unify the configuration file permission to 755

bin/gravitino-iceberg-rest-server.sh, bin/gravitino.sh
improve message when start server failed
Fix: #4441
no
start server
=> [#4441] feat(script): improve message when start  server failed

catalogs/catalog-jdbc-doris/src/test/java/org/apache/gravitino/catalog/doris/operation/TestDorisTablePartitionOperations.java, integration-test-common/src/test/java/org/apache/gravitino/integration/test/container/ContainerSuite.java, integration-test-common/src/test/java/org/apache/gravitino/integration/test/util/CloseContainerExtension.java, integration-test/src/test/java/org/apache/gravitino/integration/test/authorization/ranger/AbstractRangerIT.java, integration-test/src/test/java/org/apache/gravitino/integration/test/authorization/ranger/RangerHiveIT.java, integration-test/src/test/java/org/apache/gravitino/integration/test/client/AuditIT.java, integration-test/src/test/java/org/apache/gravitino/integration/test/client/MetalakeIT.java, integration-test/src/test/java/org/apache/gravitino/integration/test/web/rest/KerberosOperationsIT.java, integration-test/src/test/java/org/apache/gravitino/integration/test/web/rest/OAuth2OperationsIT.java, integration-test/src/test/java/org/apache/gravitino/integration/test/web/rest/VersionOperationsIT.java, integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/MetalakePageTest.java
- fix the wrong tag on the test class
Fix: #4463 
no
exit the Docker daemon and run the build command
=> [#4463] fix(tests): remove the wrong tag on test class

docs/flink-connector/flink-catalog-hive.md, docs/how-to-build.md, docs/lakehouse-paimon-catalog.md, docs/trino-connector/trino-connector.md
Fix doc typo issue
N/A
Fix: #4500 
N/A
N/A
=> [#4500] fix(docs) Fix doc typo issue

docs/apache-hive-catalog.md
Revise the compatibility description of the Hive catalog
Fix: #4503 
no
no need
=> [#4503] fix(doc): Revise the compatibility description of the Hive catalog

docs/flink-connector/flink-connector.md, docs/iceberg-rest-service.md, docs/lakehouse-paimon-catalog.md, docs/spark-connector/spark-catalog-iceberg.md
polish 0.6 document 
fix some errors and make document more user friendly
No
just document
=> [MINOR] docs: polish 0.6 document 

clients/client-java/src/main/java/org/apache/gravitino/client/ErrorHandlers.java, clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClient.java, clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoMetalake.java, common/src/main/java/org/apache/gravitino/dto/authorization/SecurableObjectDTO.java, integration-test/src/test/java/org/apache/gravitino/integration/test/authorization/AccessControlIT.java, integration-test/src/test/java/org/apache/gravitino/integration/test/authorization/OwnerIT.java, server/src/main/java/org/apache/gravitino/server/web/rest/RoleOperations.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestRoleOperations.java
Fix the deleting role issues with irregular name.
Add the e2e IT for access control
Fix the issue of null name issue about securable object in the client.
Use NoSuchMetadataObjectException instead of IlegallException for not existed securable object.
Fix: #3232
No.
Add some ITs
=> [#3232] fix(client): Fix the deleting role issues with irregular name

docs/manage-relational-metadata-using-gravitino.md
Add Paimon catalog information to the `manage-relational-metadata-using-gravitino.md` doc.
=> [Minor] improve(doc) : Update Paimon Catalog doc in `manage-relational-metadata-using-gravitino.md`

docs/open-api/owners.yaml
fix wrong indent in `owners.yaml`
these wrong indent will make openAPI to mdx failed
no
by hand
=> [MINOR] fix(openAPI): fix wrong indent in `owners.yaml`

docs/security/how-to-authenticate.md, docs/security/how-to-use-cors.md, docs/security/how-to-use-https.md
Fix the link and slug
Fix the link and link, otherwise the website can't show.
NO.
By hand.
=> [MINOR] fix(docs): Fix the link and slug

docs/jdbc-doris-catalog.md, docs/manage-table-partition-using-gravitino.md
Update some docs about partition management for Doris catalog.
=> [Minor] improve(doc): Update docs about partition management for Doris catalog

docs/security/how-to-authenticate.md, docs/security/how-to-use-https.md, docs/security/security.md
Optimize docs for the security part.
For a better user experience.
N/A.
N/A
=> [Minor] improvement(docs): Fix and polish docs.

catalogs/catalog-common/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergConstants.java, docs/iceberg-rest-service.md, iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/IcebergConfig.java, iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/utils/IcebergCatalogUtil.java, iceberg/iceberg-common/src/test/java/org/apache/gravitino/iceberg/common/utils/CustomCatalogForTest.java, iceberg/iceberg-common/src/test/java/org/apache/gravitino/iceberg/common/utils/TestIcebergCatalogUtil.java
support load custom catalog as backend
improvement: #4508
1. add a property key
1. add UT
2. manual test
=> [#4508]feat(iceberg) support load custom catalog as backend in the Iceberg REST service

.github/ISSUE_TEMPLATE/bug-report.yml
Add more release versions for bug report template
Just a minor.
No.
Test locally.
=> [MINOR] fix(misc): Add more release versions for bug report template

README.md, docs/how-to-build.md, docs/how-to-install.md
Add a pixel to get use stats on a couple of GitHub pages.
To test Matomo
Fix: # N/A
No)
Locally.
=> [Minor] Matomo test to see what (ASF approved) user stats we can obtain

LICENSE, dev/release/do-release.sh, dev/release/release-build.sh, dev/release/release-tag.sh, dev/release/release-util.sh
This PR proposes to add several release script to automate the release process.
Fix: #4417
No.
Local test.
=> [#4417] feat(build): Add release script to automate the release process

.github/workflows/backend-integration-test.yml, core/src/main/java/org/apache/gravitino/storage/relational/mapper/TagMetaMapper.java
Fix the backend type configuration. 
The configuration for the backend type is incorrect. 
N/A.
CI
=> [Minor] fix(CI): Fix CI pipeline configuration error.

.github/workflows/backend-integration-test.yml, core/src/main/java/org/apache/gravitino/storage/relational/mapper/TagMetaMapper.java
Fix the backend type configuration.
The configuration for the backend type is incorrect.
N/A
CI
=> [Minor] Fix CI pipeline configuration error

core/src/main/java/org/apache/gravitino/GravitinoEnv.java, core/src/main/java/org/apache/gravitino/SupportsRelationOperations.java, core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java, core/src/main/java/org/apache/gravitino/authorization/FutureGrantManager.java, core/src/main/java/org/apache/gravitino/authorization/PermissionManager.java, core/src/main/java/org/apache/gravitino/authorization/RoleManager.java, core/src/main/java/org/apache/gravitino/hook/CatalogHookDispatcher.java, core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/MetalakeMetaMapper.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/RoleMetaMapper.java, core/src/main/java/org/apache/gravitino/storage/relational/service/GroupMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/OwnerMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/UserMetaService.java, core/src/main/java/org/apache/gravitino/utils/NameIdentifierUtil.java, core/src/test/java/org/apache/gravitino/authorization/TestAccessControlManager.java, core/src/test/java/org/apache/gravitino/authorization/TestAccessControlManagerForPermissions.java, core/src/test/java/org/apache/gravitino/authorization/TestFutureGrantManager.java, core/src/test/java/org/apache/gravitino/storage/relational/service/TestRoleMetaService.java, server/src/main/java/org/apache/gravitino/server/web/rest/RoleOperations.java
If we want to push the privileges down the underlying system, we need to call methods of the underlying system authorization plugin.
Fix: #4460
No.
Add some test cases.
=> [#4460] feat(core): Add the method call of the authorizationPlugin 

README.md, docs/getting-started.md, docs/how-to-build.md, docs/how-to-install.md, docs/how-to-upgrade.md, docs/how-to-use-the-playground.md, docs/index.md
Remove URL parameter and add a coueple of more pages.
Track a few more useful pages. URL parameter didn't seem to work.
Fix: # N/A
No
N/A
=> [Minor] Remove URL parameter and add a coueple of more pages

docs/iceberg-rest-service.md, docs/lakehouse-iceberg-catalog.md, docs/spark-connector/spark-catalog-iceberg.md, gradle/libs.versions.toml, iceberg/iceberg-common/build.gradle.kts
remove S3 SDK jar from Gravitino Iceberg REST server 
Fix: #4630
no
tested on Iceberg REST server and Gravitino Iceberg catalog
=> [#4630] feat(iceberg): remove S3 SDK jar from Gravitino Iceberg REST server 

core/src/main/java/org/apache/gravitino/GravitinoEnv.java, core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java, core/src/main/java/org/apache/gravitino/authorization/FutureGrantManager.java, core/src/main/java/org/apache/gravitino/authorization/OwnerManager.java, core/src/main/java/org/apache/gravitino/authorization/PermissionManager.java, core/src/main/java/org/apache/gravitino/authorization/RoleManager.java, core/src/main/java/org/apache/gravitino/connector/BaseCatalog.java, core/src/test/java/org/apache/gravitino/authorization/TestFutureGrantManager.java, core/src/test/java/org/apache/gravitino/authorization/TestOwnerManager.java, server/src/main/java/org/apache/gravitino/server/web/rest/OwnerOperations.java
This is the follow-up pull request of #3963.
#3963 add authorization plugin to set owner. This pull request is to call them.
Fix: #3963
No.
Add new UT.
=> [#3963] feat(core): Call the method ownerset of authorization plugin 

docs/iceberg-rest-service.md
fix Iceberg REST service doc
Fix: #4646 
no
just document
=> [#4646] docs(iceberg): fix Iceberg REST service doc

.github/workflows/docker-image.yml
Fix the bugs about github environment for image_type
it's a bug.
N/A
test locally.
=> [Minor] fix(docker-image): Fix bugs in publishing Iceberg rest server docker image

NOTICE, NOTICE.bin, web/NOTICE, web/NOTICE.bin
Add the originator of Gravitino to the NOTICE file.
No.
N/A
=> [MINOR] Add originator of Gravitino to the NOTICE file

README.md
Fixed some phrasing and sentence structure.
For clarity.
Fix: # N/A
No
N/A
=> [Minor] Update README.md for clarity

catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogPropertiesMetadata.java, catalogs/catalog-hive/src/main/java/org/apache/gravitino/catalog/hive/HiveCatalogPropertiesMeta.java, catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/JdbcCatalogPropertiesMetadata.java, catalogs/catalog-kafka/src/main/java/org/apache/gravitino/catalog/kafka/KafkaCatalogPropertiesMetadata.java, catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergCatalogPropertiesMetadata.java, catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/PaimonCatalogPropertiesMetadata.java, core/src/main/java/org/apache/gravitino/connector/BaseCatalogPropertiesMetadata.java, core/src/main/java/org/apache/gravitino/connector/BasePropertiesMetadata.java
make catalog property metadata automatically add
catalog developer can now focus on the definition of catalog property metadata
Fix: #4675 
no
CI passed
=> [#4675] improvement(core): make catalog property metadata automatically add

docs/security/access-control.md
Fix the inconsistent privilege descriptions
Fix: #4701
Just docs.
NO.
=> [#4701] fix(docs): Fix the inconsistent privilege descriptions

trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/iceberg/IcebergCatalogPropertyConverter.java, trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/iceberg/IcebergConnectorAdapter.java, trino-connector/src/main/java/org/apache/gravitino/trino/connector/metadata/GravitinoCatalog.java
Fix  Iceberg JDBC backend tables can not found in Trino
Fix: #4712 
No
Manually test
=> [#4712] fix (trino-connector): Fix  Iceberg JDBC backend tables can not found in Trino

docs/how-to-build.md
Clarify and improve English.
For clarity.
Fix: # N/A
No
Build locally
=> [Minor] Update how-to-build.md

docs/how-to-use-python-client.md, docs/how-to-use-the-playground.md
Correct the playground document errors
Fix: #4739
No.
Just docs.
=> [#4739] fix(docs): Correct the playground document errors

DISCLAIMER_WIP.txt
Update the link address in DISCLAIMER_WIP.txt
The original link is not correct.
Fix: #4745 
No.
N/A
=> [#4745] fix(docs): Update the link address in DISCLAIMER_WIP.txt

dev/release/release-build.sh
This PR proposes to fix two small bugs in the release script:
1. Add the python Gravitino package to SVN.
2. Exclude several modules when publishing to Maven.
Improve the script.
No.
Manual verification.
=> [MINOR] fix(build): Fix some small bugs in the release script

docs/how-to-use-the-playground.md
Minor English changes.
Clarify a few words here and there. Use Apache in the first instance.
Fix: # N/A
No
Compiled locally.
=> [Minor] Minor English changes.

authorizations/authorization-ranger/build.gradle.kts
Exclude invalidate depends on JAR package in the Rangere authorization module.
```
-rw-r--r--  1 xun  staff   657952 Aug 29 11:27 commons-lang3-3.14.0.jar
-rw-r--r--  1 xun  staff   238400 Aug 29 11:27 commons-text-1.10.0.jar
-rw-r--r--  1 xun  staff  1621691 Aug 29 11:27 jersey-bundle-1.19.3.jar
-rw-r--r--  1 xun  staff   780664 Aug 29 11:27 jackson-mapper-asl-1.9.13.jar
-rw-r--r--  1 xun  staff    19936 Aug 29 11:27 jsr305-3.0.2.jar
-rw-r--r--  1 xun  staff   284220 Aug 29 11:27 commons-lang-2.6.jar
-rw-r--r--  1 xun  staff     4112 Aug 29 11:27 gethostname4j-1.0.0.jar
-rw-r--r--  1 xun  staff   126898 Aug 29 11:27 javax.ws.rs-api-2.1.1.jar
-rw-r--r--  1 xun  staff    16830 Aug 29 11:27 error_prone_annotations-2.21.1.jar
-rw-r--r--  1 xun  staff     2199 Aug 29 11:27 …
```
=> [#4678] improve(auth-ranger): Shrink Ranger authorization plugin package size

docs/how-to-use-the-playground.md
Jupiter -> Jupyter
Fix name
Fix: # N/A
No
N/A
=> [Minor] Jupiter -> Jupyter

docs/trino-connector/catalog-hive.md, docs/trino-connector/catalog-iceberg.md, docs/trino-connector/catalog-mysql.md, docs/trino-connector/catalog-postgresql.md, docs/trino-connector/development.md
Correct errors in the  Trino connector document
Fix: #4760 
No, update docs
No
=> [#4760] Improvement (docs): Correct errors in the  Trino connector document

docs/how-to-use-the-playground.md
Update the document of playground
Fix: #4767
Just update the document according to the latest playground document.
No.
Just documents.
=> [#4767] fix(docs): Update the document of playground

docs/manage-table-partition-using-gravitino.md
correct partiton doc
Fix: #4782 
no
no need
=> [#4782] fix(doc): correct partiton doc

docs/flink-connector/flink-connector.md, docs/spark-connector/spark-connector.md
Fix Spark and Flink download link
no
document
=> [MINOR] Fix Spark and Flink download link

integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/MetalakePageTest.java, web/src/app/rootLayout/Footer.js
link the apache website instead of a company websit
The latest docs will release at apache website
Fix: #4737
N/A
N/A
=> [#4737] improvement(ui): update documentation link

docs/docker-image-details.md, docs/how-to-build.md, docs/how-to-use-python-client.md
This PR fixes several typos in docs.
To make the docs correct.
Fix: #4764 
No.
N/A
=> [#4764] fix(docs): Fix several typos in docs

integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/MetalakePageTest.java, integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/pages/MetalakePage.java, web/src/app/rootLayout/Footer.js
Fix copyright and footer name.
As the ASF is the collective copyright owner.
Fix: # N/A
No.
Compiled locally.
=> [Minor] fix footer

docs/open-api/catalogs.yaml, docs/open-api/datatype.yaml, docs/open-api/expression.yaml, docs/open-api/filesets.yaml, docs/open-api/groups.yaml, docs/open-api/indexes.yaml, docs/open-api/metalakes.yaml, docs/open-api/openapi.yaml, docs/open-api/owners.yaml, docs/open-api/partitioning.yaml, docs/open-api/partitions.yaml, docs/open-api/permissions.yaml, docs/open-api/roles.yaml, docs/open-api/schemas.yaml, docs/open-api/tables.yaml, docs/open-api/tags.yaml, docs/open-api/topics.yaml, docs/open-api/users.yaml
format license headers for open api yaml files
ci check failed on gravitino-site
Fix: #4805
N/A
N/A
=> [#4805] format license headers for open api yaml files

docs/trino-connector/catalog-hive.md
Fix the error in the example SQL.
For a better user experience. 
N/A
N/A.
=> [Minor] fix(docs): Fix docs mistake for partitioned table created by Trino

docs/how-to-build.md
Remove single space to fix broken link
So link works.
Fix: # N/A
N/A
N/A
=> [MINOR] fix broken link

docs/iceberg-rest-service.md, docs/manage-relational-metadata-using-gravitino.md, docs/spark-connector/spark-connector.md
polish document for spark connector and Iceberg REST server
Fix: # (issue)
no
just document
=> [MINOR] docs: polish document for spark connector and Iceberg REST server

docs/getting-started.md, docs/how-to-build.md, docs/index.md
fix md links issue
N/A
Fix: # (issue)
N/A
N/A
=> [MINOR] docs: fix md links issue

web/integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/pages/MetalakePage.java
fix testCheckLinkDocs test case issue
The test case testCheckLinkDocs failed
Fix: #4914
N/A
=> [#4914] fix(web): fix testCheckLinkDocs test case issue

.github/workflows/access-control-integration-test.yml, .github/workflows/backend-integration-test-action.yml, .github/workflows/backend-integration-test.yml, .github/workflows/build.yml, .github/workflows/flink-integration-test-action.yml, .github/workflows/flink-integration-test.yml, .github/workflows/frontend-integration-test.yml, .github/workflows/python-integration-test.yml, .github/workflows/spark-integration-test-action.yml, .github/workflows/spark-integration-test.yml, .github/workflows/trino-integration-test.yml, authorizations/authorization-ranger/build.gradle.kts, build.gradle.kts, catalogs/catalog-hadoop/build.gradle.kts, catalogs/catalog-hive/build.gradle.kts, catalogs/catalog-jdbc-doris/build.gradle.kts, catalogs/catalog-jdbc-mysql/build.gradle.kts, catalogs/catalog-jdbc-postgresql/build.gradle.kts, catalogs/catalog-kafka/build.gradle.kts, catalogs/catalog-lakehouse-iceberg/build.gradle.kts, catalogs/catalog-lakehouse-paimon/build.gradle.kts, docs/how-to-test.md, flink-connector/flink/build.gradle.kts, iceberg/iceberg-rest-server/build.gradle.kts, spark-connector/spark-common/build.gradle.kts, spark-connector/v3.3/spark/build.gradle.kts, spark-connector/v3.4/spark/build.gradle.kts, spark-connector/v3.5/spark/build.gradle.kts, web/integration-test/build.gradle.kts
- optimize CI jobs trigger conditions to remove unnecessary jobs
- reduce job number of FlinkIT and SparkIT on PR
- fix skipUTs does not work
Fix: #4811 
no
CI passed
=> [#4811] improvement(CI): optimize CI jobs trigger conditions

catalogs/catalog-hive/src/test/java/org/apache/gravitino/catalog/hive/integration/test/ProxyCatalogHiveIT.java
Add the integration test for client withSimpleAuth(String)
Fix: #4922 
No.
Add more test cases.
=> [#4922] improvement(test): Add the integration test for client withSimpleAuth(String)

docs/trino-connector/installation.md
Found a misspelling in document.
Fix: doc misspelling
no
just document
=> [Minor] docs: Fix doc misspelling

NOTICE
Removed duplicated information as there is no need to repeat any information
To comply with ASF policy.
Fix: # N/A
None
N/A
=> [Minor] Update NOTICE

clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClient.java, clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoMetalake.java, clients/client-java/src/test/java/org/apache/gravitino/client/TestUserGroup.java, common/src/main/java/org/apache/gravitino/dto/responses/UserListResponse.java, common/src/main/java/org/apache/gravitino/dto/util/DTOConverters.java, core/src/main/java/org/apache/gravitino/EntityStore.java, core/src/main/java/org/apache/gravitino/authorization/AccessControlDispatcher.java, core/src/main/java/org/apache/gravitino/authorization/AccessControlManager.java, core/src/main/java/org/apache/gravitino/authorization/UserGroupManager.java, core/src/main/java/org/apache/gravitino/hook/AccessControlHookDispatcher.java, core/src/main/java/org/apache/gravitino/meta/UserEntity.java, core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java, core/src/main/java/org/apache/gravitino/storage/relational/RelationalBackend.java, core/src/main/java/org/apache/gravitino/storage/relational/RelationalEntityStore.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/UserMetaBaseSQLProvider.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/UserMetaMapper.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/UserMetaSQLProviderFactory.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/h2/UserMetaH2Provider.java, core/src/main/java/org/apache/gravitino/storage/relational/po/ExtendedUserPO.java, core/src/main/java/org/apache/gravitino/storage/relational/service/SupportsDesiredFields.java, core/src/main/java/org/apache/gravitino/storage/relational/service/SupportsDesiredFieldsHandlers.java, core/src/main/java/org/apache/gravitino/storage/relational/service/UserMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/utils/POConverters.java, core/src/test/java/org/apache/gravitino/authorization/TestAccessControlManager.java, core/src/test/java/org/apache/gravitino/storage/relational/TestJDBCBackend.java, core/src/test/java/org/apache/gravitino/storage/relational/service/TestUserMetaService.java, integration-test/src/test/java/org/apache/gravitino/integration/test/authorization/AccessControlIT.java, server/src/main/java/org/apache/gravitino/server/web/rest/UserOperations.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestUserOperations.java
Add the list operation of the user
Fix: #3348
I will add the document later.
Add the new ut.
=> [#3348] feat(core,server): Add the list operation of the user

docs/manage-metalake-using-gravitino.md
Fix API description issue
Fix: # (issue)
No
Just document
=> Fix API description issue

LICENSE.rest, NOTICE.rest, build.gradle.kts
Add LICENSE and NOTICE files for Iceberg REST binary
To comply with ASF policy.
Fix: #5010
N/A
compiled locally
=> [#5010] Add LICENSE and NOTICE files for Iceberg REST binary

clients/client-java/src/main/java/org/apache/gravitino/client/MetadataObjectTagOperations.java, clients/client-java/src/test/java/org/apache/gravitino/client/TestSupportTags.java, docs/manage-tags-in-gravitino.md, docs/open-api/openapi.yaml, docs/open-api/tags.yaml, server/src/main/java/org/apache/gravitino/server/web/rest/MetadataObjectTagOperations.java, server/src/main/java/org/apache/gravitino/server/web/rest/TagOperations.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestMetadataObjectTagOperations.java
Move tag related about metadata object API to object path
Fix: #5000
Modified the document
Modified the UT.
=> [#5000] improvement(server): Move tag object API to object path

clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClient.java, clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoMetalake.java, clients/client-java/src/test/java/org/apache/gravitino/client/TestUserGroup.java, common/src/main/java/org/apache/gravitino/dto/responses/GroupListResponse.java, common/src/main/java/org/apache/gravitino/dto/util/DTOConverters.java, core/src/main/java/org/apache/gravitino/authorization/AccessControlDispatcher.java, core/src/main/java/org/apache/gravitino/authorization/AccessControlManager.java, core/src/main/java/org/apache/gravitino/authorization/UserGroupManager.java, core/src/main/java/org/apache/gravitino/hook/AccessControlHookDispatcher.java, core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/GroupMetaMapper.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/GroupMetaSQLProviderFactory.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/GroupMetaBaseSQLProvider.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/h2/GroupMetaH2Provider.java, core/src/main/java/org/apache/gravitino/storage/relational/po/ExtendedGroupPO.java, core/src/main/java/org/apache/gravitino/storage/relational/service/GroupMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/utils/POConverters.java, core/src/test/java/org/apache/gravitino/authorization/TestAccessControlManager.java, core/src/test/java/org/apache/gravitino/storage/relational/service/TestGroupMetaService.java, integration-test/src/test/java/org/apache/gravitino/integration/test/authorization/AccessControlIT.java, server/src/main/java/org/apache/gravitino/server/web/rest/GroupOperations.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestGroupOperations.java
Supports to list groups.
Fix: #4873 
I will add the document later.
UT.
=> [#4873] feat(core,server): Supports to list group (#4879)

docs/open-api/groups.yaml, docs/open-api/openapi.yaml, docs/open-api/permissions.yaml, docs/open-api/roles.yaml, docs/open-api/tags.yaml, docs/open-api/users.yaml, docs/security/access-control.md
Add the documents about access control.
Fix: #5033
No.
Just docs.
=> [#5033] improvement(docs): Add the documents about access control

docs/open-api/openapi.yaml
Change the version of OPENAPI
Fix: #5045 
No need.
No need.
=> [#5045] improvement(docs): Change the version of OpenAPI

api/src/main/java/org/apache/gravitino/authorization/Privilege.java, api/src/main/java/org/apache/gravitino/authorization/Privileges.java, api/src/test/java/org/apache/gravitino/authorization/TestSecurableObjects.java, common/src/main/java/org/apache/gravitino/dto/authorization/PrivilegeDTO.java, common/src/main/java/org/apache/gravitino/dto/util/DTOConverters.java, core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java, server/src/main/java/org/apache/gravitino/server/web/rest/RoleOperations.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestRoleOperations.java
Add the check of privileges
Fix: #5054
No
Add some UTs
=> [#5054] improvement(api,server): Add the check of privileges

dev/release/release-build.sh, dev/release/release-tag.sh, dev/release/release-util.sh
- improve release script
Support for repeatable execution
no
by-hand
=> [MINOR] improvement(release): improve release script

docs/docker-image-details.md, docs/open-api/openapi.yaml
Add docker image change log for 0.6.1
Just a minor.
No.
No need. Just doc.
=> [MINOR] improvment(docs): Add docker image change log for 0.6.1-incubating

core/src/main/java/org/apache/gravitino/catalog/TableOperationDispatcher.java, core/src/main/java/org/apache/gravitino/meta/ColumnEntity.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/TableColumnBaseSQLProvider.java, core/src/main/java/org/apache/gravitino/storage/relational/po/ColumnPO.java, core/src/main/java/org/apache/gravitino/storage/relational/service/TableColumnMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/utils/POConverters.java, core/src/test/java/org/apache/gravitino/TestColumn.java, core/src/test/java/org/apache/gravitino/catalog/TestTableNormalizeDispatcher.java, core/src/test/java/org/apache/gravitino/catalog/TestTableOperationDispatcher.java, core/src/test/java/org/apache/gravitino/connector/TestCatalogOperations.java, core/src/test/java/org/apache/gravitino/meta/TestColumnEntity.java, core/src/test/java/org/apache/gravitino/storage/TestEntityStorage.java, core/src/test/java/org/apache/gravitino/storage/relational/service/TestTableColumnMetaService.java, core/src/test/java/org/apache/gravitino/storage/relational/utils/TestPOConverters.java, scripts/h2/schema-0.7.0-h2.sql, scripts/h2/upgrade-0.6.0-to-0.7.0-h2.sql, scripts/mysql/schema-0.7.0-mysql.sql, scripts/mysql/upgrade-0.6.0-to-0.7.0-mysql.sql, scripts/postgresql/schema-0.7.0-postgresql.sql
This is a follow-up PR to support storing position for column entity.
for future use.
Fix: #5159 
No.
UTs.
=> [#5159] core(feat): Add position support for column entity

catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopS3CatalogIT.java, clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/integration/test/GravitinoVirtualFileSystemS3IT.java
Fix test error in https://github.com/apache/gravitino/actions/runs/11439368368/job/31822894542?pr=5186
It's a fix for IT.
N/A
UTs & ITs
=> [Minor] fix(test): Fix UT error introduced by failuring to rebase code in time

core/src/main/java/org/apache/gravitino/metalake/MetalakeManager.java, core/src/test/java/org/apache/gravitino/metalake/TestMetalakeManager.java
Fix the audit info of metalake.
Fix: #5210
Audit info changed.
Add a UT.
=> [#5210] fix(core): Fix the audit info of metalake

catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/JdbcCatalogOperations.java, catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergCatalogOperations.java
[#5172]fix bug:Iceberg catalog audit user is not correct
Fix: #5172 
No
No need
=> [#5172]fix bug:Iceberg catalog audit user is not correct

catalogs/catalog-hive/src/test/java/org/apache/gravitino/catalog/hive/TestFetchFileUtils.java
Increase the max_retries to prevent timeout
Fix: #5213
No. only the UT was changed.
`./gradlew :catalogs:catalog-hive:test`
=> [#5213] Improvement: Fix the flaky test

web/web/src/app/metalakes/metalake/rightContent/CreateFilesetDialog.js, web/web/src/app/metalakes/metalake/rightContent/RightContent.js, web/web/src/app/metalakes/metalake/rightContent/tabsContent/tableView/TableView.js, web/web/src/lib/api/filesets/index.js, web/web/src/lib/store/metalakes/index.js
Add ui support for creating, editing, viewing, and deleting fileset
N/A
Fix: #5168
Fix: #5169
Fix: #5170
N/A
manually
=> [#5168][#5169][#5170] Feature(web): Add ui support for creating, editing, viewing, and deleting fileset

api/src/main/java/org/apache/gravitino/exceptions/NonEmptyCatalogException.java, api/src/main/java/org/apache/gravitino/exceptions/NonEmptyMetalakeException.java, clients/client-java/src/main/java/org/apache/gravitino/client/ErrorHandlers.java, clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoMetalake.java, clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/MetalakeIT.java, common/src/main/java/org/apache/gravitino/dto/requests/MetalakeSetRequest.java, core/src/main/java/org/apache/gravitino/catalog/CatalogManager.java, core/src/main/java/org/apache/gravitino/metalake/MetalakeManager.java, core/src/main/java/org/apache/gravitino/metalake/MetalakeNormalizeDispatcher.java, core/src/test/java/org/apache/gravitino/metalake/TestMetalakeManager.java, server/src/main/java/org/apache/gravitino/server/web/rest/ExceptionHandlers.java
- fix list metalakes missing in-use property
- fix NPE when null properties
list metalakes will show metalake details by default so need put in-use property in it
Fix: #5240 
Fix: #5237
no
tests added
=> [#5237][#5240] fix(metalake): fix list metalakes missing in-use property

clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/TagIT.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/TagMetadataObjectRelBaseSQLProvider.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/TagMetadataObjectRelPostgreSQLProvider.java
This PR fixes the tag relation unexpected deletion issue. Previously we deleted other unrelated tag relations under the metalake, which will make the associated tag list fail. So this PR will fix this issue.
To fix the tag unexpectedly deleted issue.
Fix: #4817 
No.
Add new IT to fix this issue.
=> [#4817] fix(core): Fix unexpected tag delete issue

docs/manage-fileset-metadata-using-gravitino.md, docs/manage-messaging-metadata-using-gravitino.md, docs/manage-metalake-using-gravitino.md, docs/manage-relational-metadata-using-gravitino.md, docs/open-api/catalogs.yaml, docs/open-api/metalakes.yaml, docs/open-api/openapi.yaml
refine docs for deleting metalake and catalog
Fix: #5217 
yes, user docs changed
setup the gravitino-site locally
=> [#5217] docs(metalake-catalog): refine docs for deleting metalake and catalog

api/src/main/java/org/apache/gravitino/rel/expressions/transforms/Transforms.java, api/src/test/java/org/apache/gravitino/rel/TestTransforms.java
fix call bucketTransform arguments failed
Fix: #4913 
no
tests added
=> [#4913] fix(API): fix call bucketTransform arguments failed

dev/release/release-build.sh, dev/release/release-tag.sh, dev/release/update-java-doc-version.sh
- remove upload Python packages to RELEASE_STAGING
- update the docs version when preparing release
improve the release script
no
by hand
=> [MINOR] improvement(release): update docs version when release

web/web/src/components/DetailsDrawer.js
improvement scroll bar on the catalog detail page ellipsis display
Fix: #4641
N/A
manually
=> [#4641] fix(web): improvement scroll bar on the catalog detail page ellipsis display

core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java
fix spelling in error messages
fix spelling in error messages
Fix: # N/A
N/A
compiled locally
=> [Minor] fix spelling in error messages

api/src/main/java/org/apache/gravitino/MetadataObject.java, authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerMetadataObject.java
fix spelling th -> the
to fix spelling
Fix: # N/A
N/A
N/A - just changes to comments
=> [Minor] fix spelling th -> the

docs/how-to-use-the-playground.md
Update playground doc according to latest changes
Align doc
N/A
N/A
=> [Minor] Update playground doc

docs/manage-metalake-using-gravitino.md, docs/manage-relational-metadata-using-gravitino.md
fix wrong name of in-use key
Fix: #5308 
no
no need
=> [#5308] fix(docs): fix wrong key name of inUse parameter

docs/trino-connector/supported-catalog.md
Align the gravitino type in trino-connector doc with programming guides doc 
Fix:#5150 
Update docs
No
=> [#5150] fix (doc): Align the gravitino type in trino-connector doc 

catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/PaimonCatalogPropertiesMetadata.java, catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/PaimonConfig.java, catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/utils/CatalogUtils.java, catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/integration/test/CatalogPaimonBaseIT.java, catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/integration/test/CatalogPaimonJdbcIT.java, catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/integration/test/CatalogPaimonMultipleJDBCLoadIT.java, catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/utils/TestCatalogUtils.java, docs/lakehouse-paimon-catalog.md, integration-test-common/src/test/java/org/apache/gravitino/integration/test/util/TestDatabaseName.java
add jdbc-driver to Paimon JDBC catalog backend configuration
Fix: https://github.com/apache/gravitino/issues/5214
updated the related doc
New IT and modified UT.
=> [#5214] Improvement(catalog-lakehouse-paimon): add jdbc-driver to Paimon JDBC catalog backend configuration

docs/jdbc-oceanbase-catalog.md
Add doc for OceanBase JDBC Catalog.
Fix: #5262 
No
=> [#5262] feat(oceanbase-catalog): Add doc for OceanBase JDBC Catalog

web/web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js, web/web/src/lib/utils/initial.js
1. Add jdbc-driver properties for Paimon JDBC
3. fix update paimon catalog issue
N/A
Fix: #5318
Fix: #5311
Fix: #5328
N/A
manually
=> [#5318][#5311][#5328] improvement(web): Add jdbc-driver properties for Paimon JDBC and fix jdbc issue

web/web/src/components/DetailsDrawer.js
=> [#5344] improvement(web): Show the type and storage location msg for fileset

authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java, authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerHelper.java, authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveIT.java, authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerITEnv.java
Currently, RangerAuthorizationPlugin only supports allow privilege. So we need support to deny privilege.
Fix: #4614
N/A
Added some ITs
=> [#4614] feat(auth-ranger): Support deny privilege in the RangerAuthorizationPlugin

web/web/src/app/metalakes/metalake/rightContent/CreateSchemaDialog.js
=> [#5360] Improvement(web): hidden commont and property element for oceanbase schema

authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerHelper.java, authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerITEnv.java
Revert unnecessary changes for branch 0.7
Just a minor.
No.
I use the command git diff main branch-0.7.
=> [MINOR] improvement(authorization-plugin): Revert unnecessary changes for branch 0.7

web/web/src/app/metalakes/metalake/rightContent/tabsContent/TabsContent.js, web/web/src/app/metalakes/metalake/rightContent/tabsContent/dynamicIframe/DynamicIframe.js, web/web/src/lib/styles/globals.css
=> fileset mock ui

docs/docker-image-details.md, docs/gravitino-server-config.md, docs/index.md
Fix the doc bug and add some missing doc links.
Fix: #5419 
No.
Local verification.
=> [#5419] fix(doc): Fix the doc bug and add some missing doc links

web/web/src/lib/utils/initial.js
refine hms catalog-backend input ui to selection
N/A
Fix: #5456
N/A
manually
=> [#5456] improvement(web): refine hms catalog-backend input ui to selection

web/web/src/app/metalakes/metalake/rightContent/tabsContent/dynamicIframe/DynamicIframe.js
fix rat ci of fileset mock ui
N/A
N/A
=> [MINOR] Fix CI RAT

clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListColumns.java
Add column title row to table column output.
So it's easier for a user to understand the output.
Fix: #5333
N/A
Compiled and tested locally.
=> [#5333] Add column title row to table column output in Gravitino CLI

.github/workflows/backend-integration-test.yml, .github/workflows/build.yml
Add client CLI to github action yaml file.
To make integration test run when CLI code changes happen.
Fix: #5513
No
N/A Unable to test locally.
=> [#5513] Add client CLI to github action yaml file

core/src/main/java/org/apache/gravitino/listener/TableEventDispatcher.java, core/src/main/java/org/apache/gravitino/listener/api/event/AlterTablePreEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/CreateTablePreEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/DropTablePreEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/ListTablePreEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/LoadTablePreEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/PurgeTablePreEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/TablePreEvent.java, core/src/test/java/org/apache/gravitino/listener/DummyEventListener.java, core/src/test/java/org/apache/gravitino/listener/api/event/TestTableEvent.java, docs/gravitino-server-config.md
add table pre event to event listener
Fix: #5319 
no
add UT
=> [#5319] feat(core): add table pre event to Gravitino event

LICENSE, dev/release/check-license.sh
This script checks if all the files mentioned in the LICENSE file are present in the project.
Besides highlighting the missing files, it will display possible locations for any new files.
This script adds text like [NOT FOUND] --> "new/path/to/the/file" in the end of the line where the file is missing.
With the output of this script, you can update the LICENSE file with the correct file paths.
new file: 
./dev/release/check-license.sh   (script for checking the missing files)
modified:
./LICENSE    (remove missing files or replace them with the newly found files)
Some code paths listed in LICENSE file are already outdated due to the refactoring of the codes.
We need to update the path to reflect the actual one.
No
```bash
./check-license.sh
```
This script adds [NOT FOUND] --> …
=> [#5540] Improvement(dev/release): Update the `LICENSE` file to fix the wrong path problem

ROADMAP.md
Update roadmap as it is out of date.
Give people an idea of what the project is working on and future plans.
Fix: # N/A
N/A
N/A
=> [Minor] Update ROADMAP.md

docs/gravitino-server-config.md
fix docs `name undefined` issue
N/A
N/A
N/A
=> [MINOR] fix(doc): fix docs build issue

docs/how-to-use-the-playground.md
Just a couple of minor language changes.
For clarity.
Fix: # N/A
No.
N/A
=> [Minor] Improved English for how-to-use-the-playground.md

core/src/main/java/org/apache/gravitino/listener/CatalogEventDispatcher.java, core/src/main/java/org/apache/gravitino/listener/api/event/AlterCatalogPreEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/CatalogPreEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/CreateCatalogPreEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/DropCatalogPreEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/ListCatalogPreEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/LoadCatalogPreEvent.java, core/src/test/java/org/apache/gravitino/listener/api/event/TestCatalogEvent.java, docs/gravitino-server-config.md
Add catalog pre event to event listener
Fixed : https://github.com/apache/gravitino/issues/5549
no
Added unit test
=> [#5549]feat(core):support catalog pre event for Gravitino server

iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergTableOperations.java, iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergTableRenameOperations.java, iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergCreateTableEvent.java, iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergCreateTableFailureEvent.java, iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergCreateTablePreEvent.java, iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergDropTableEvent.java, iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergDropTableFailureEvent.java, iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergDropTablePreEvent.java, iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergLoadTableEvent.java, iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergRenameTableEvent.java, iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergRenameTableFailureEvent.java, iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergRenameTablePreEvent.java, iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergTableExistsEvent.java, iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergUpdateTableEvent.java, iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergUpdateTableFailureEvent.java, iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergUpdateTablePreEvent.java, iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/service/rest/TestIcebergTableOperations.java
1. Add final to Iceberg table-related events and their members.
2. Modify the return codes in `IcebergTableOperations` and `IcebergTableRenameOperations` to align with the specification, and update the relevant unit tests.
Close: #5593
No
Unit test
=> [#5593] improvement(iceberg): Add final to Iceberg table event members, fix return codes for rename and exists operations

docs/how-to-build.md
Added clarity where needed. Change to use paragraphs for easier editing.
To make it easier to follow instructions.
Fix: # N/A
No
N/A
=> [Minor] doc: Improve how-to-build.md

CONTRIBUTING.md
A couple of very minor changes to make some things a little clearer.
For better user understanding.
Fix: # N/A
N/A
N/A
=> [Minor] Update CONTRIBUTING.md to improve clarity

iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/ops/IcebergCatalogWrapper.java, iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergNamespaceOperations.java, iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/service/rest/TestIcebergNamespaceOperations.java
schema exists interface for Iceberg REST server
Close: #5611
No
Unit test
=> [#5611] Improvement(iceberg): support schema exists interface for Iceberg REST server

clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoOptions.java
Minor improvements to Partition Gravitino CLI code.
Remove duplicate short command code and make the same style as other options.
Fix: # N/A
No
Tested locally
=> [Minor] improvement to Partition Gravitino CLI code

clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestCatalogCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestColumnCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestGroupCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestMetalakeCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestMetlakeCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestRoleCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestSchemaCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestTableCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestTagCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestUserCommands.java
Add CLI unit tests to check if the right command has been called.
To increate unit test coverage.
Fix: #5637
N/A
=> [#5637] Add CLI unit tests to check if the right command has been called.

catalogs/catalog-hive/src/test/java/org/apache/gravitino/catalog/hive/TestFetchFileUtils.java
disable TestFetchFileUtils test to reduce test failures
Fix: #5642 
no
existing tests
=> [#5642] test: disable TestFetchFileUtils test to reduce test failures

clients/cli/src/main/java/org/apache/gravitino/cli/ErrorMessages.java, clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoOptions.java, clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/CreateTag.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/DeleteTag.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/TagEntity.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UntagEntity.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestMain.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestTagCommands.java, docs/cli.md
Add and delete multiple tags at once in the Gravitino CLI 
Close: [(#5528)](https://github.com/apache/gravitino/issues/5528)
=> [#5528]Improvement[cli] Add and delete multiple tags at once in the Gravitino CLI

docs/how-to-install.md
Make a little clearer.
Fro clarity.
Fix: # N/A
No
N/A
=> [Minor] Update how-to-install.md

web/web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js, web/web/src/lib/utils/initial.js
- Capitalized display type values.
- Sorted the provider list alphabetically.
Fix: #5650
No.
Opened the "Create Catalog" dialog and verified the changes.
=> [#5650] improvement(web): create catalog page minor change

clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/CatalogIT.java, core/src/main/java/org/apache/gravitino/catalog/CatalogManager.java
drop the location of managed schemas and filesets when dropping a fileset catalog
Fix: #5465 
no
tests added
=> [#5465] fix(core): deleting location of managed sub-entities when deleting a fileset catalog

catalogs/catalog-hive/src/test/java/org/apache/gravitino/catalog/hive/integration/test/CatalogHiveIT.java
add test 'list-all-tables'  for the Hive catalog
Fix: #3783 
N/A
CI passed
=> [#3783] improvement(test): add test 'list-all-tables' for the Hive catalog

.asf.yaml
This PR updates the collaborator list to remove some existing committer's name and one new active contributor.
Update the collaborator list.
No.
N/A
=> [MINOR] improve(build): Update the ASF yaml file's collaborator list

clients/cli/build.gradle.kts, clients/cli/src/test/resources/log4j2.properties
Add `catalog-jdbc-postgresql` in the CLI Gradle build scripts.
Fix: #5724
N/A
CI Passed.
=> [#5724] fix(bug): testCatalogDetailsCommand() failed in the CI

api/src/main/java/org/apache/gravitino/credential/OSSTokenCredential.java, bundles/aliyun-bundle/build.gradle.kts, bundles/aliyun-bundle/src/main/java/org/apache/gravitino/oss/credential/OSSTokenProvider.java, bundles/aliyun-bundle/src/main/java/org/apache/gravitino/oss/credential/policy/Condition.java, bundles/aliyun-bundle/src/main/java/org/apache/gravitino/oss/credential/policy/Effect.java, bundles/aliyun-bundle/src/main/java/org/apache/gravitino/oss/credential/policy/Policy.java, bundles/aliyun-bundle/src/main/java/org/apache/gravitino/oss/credential/policy/Statement.java, bundles/aliyun-bundle/src/main/java/org/apache/gravitino/oss/credential/policy/StringLike.java, bundles/aliyun-bundle/src/main/resources/META-INF/services/org.apache.gravitino.credential.CredentialProvider, catalogs/catalog-common/src/main/java/org/apache/gravitino/credential/CredentialConstants.java, common/src/main/java/org/apache/gravitino/credential/CredentialPropertyUtils.java, common/src/test/java/org/apache/gravitino/credential/TestCredentialPropertiesUtils.java, core/src/main/java/org/apache/gravitino/credential/config/OSSCredentialConfig.java, docs/iceberg-rest-service.md, gradle/libs.versions.toml, iceberg/iceberg-rest-server/build.gradle.kts, iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/integration/test/IcebergRESTOSSIT.java
support Aliyun oss credential provider 
Fix: [# (5625)](https://github.com/apache/gravitino/issues/5625)
IcebergRESTOSSIT
=> [ #5625] feat(bundles) support Aliyun oss credential provider

web/web/src/app/metalakes/CreateMetalakeDialog.js, web/web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js, web/web/src/app/metalakes/metalake/rightContent/CreateFilesetDialog.js, web/web/src/app/metalakes/metalake/rightContent/CreateSchemaDialog.js, web/web/src/app/metalakes/metalake/rightContent/CreateTableDialog.js, web/web/src/app/metalakes/metalake/rightContent/CreateTopicDialog.js, web/web/src/app/metalakes/metalake/rightContent/RightContent.js, web/web/src/app/metalakes/metalake/rightContent/tabsContent/tableView/TableView.js, web/web/src/lib/api/topics/index.js, web/web/src/lib/store/metalakes/index.js
1. Support creating topic/editing topic/deleting topic/viewing topic
2. Fix issue with creating a table for hudi
3. [Improvement] Paimon catalog, schema properties can be set when backend is jdbc and hive
N/A
Fix: #5447, #5720, #5727
N/A
manually
=> [#5447][#5720][#5727] create topic, disable create table for hudi, enable schema properties and comment for partial paimon

api/src/main/java/org/apache/gravitino/credential/Credential.java, api/src/main/java/org/apache/gravitino/credential/GCSTokenCredential.java, api/src/main/java/org/apache/gravitino/credential/OSSTokenCredential.java, api/src/main/java/org/apache/gravitino/credential/S3SecretKeyCredential.java, api/src/main/java/org/apache/gravitino/credential/S3TokenCredential.java, api/src/main/resources/META-INF/services/org.apache.gravitino.credential.Credential, clients/client-java/src/main/java/org/apache/gravitino/client/BaseSchemaCatalog.java, clients/client-java/src/main/java/org/apache/gravitino/client/ErrorHandlers.java, clients/client-java/src/main/java/org/apache/gravitino/client/FilesetCatalog.java, clients/client-java/src/main/java/org/apache/gravitino/client/GenericFileset.java, clients/client-java/src/main/java/org/apache/gravitino/client/MetadataObjectCredentialOperations.java, clients/client-java/src/test/java/org/apache/gravitino/client/TestSupportCredentials.java, common/src/main/java/org/apache/gravitino/credential/CredentialFactory.java, common/src/main/java/org/apache/gravitino/dto/credential/CredentialDTO.java, common/src/main/java/org/apache/gravitino/dto/responses/CredentialResponse.java, common/src/main/java/org/apache/gravitino/dto/util/DTOConverters.java, common/src/test/java/org/apache/gravitino/credential/TestCredentialDTO.java, common/src/test/java/org/apache/gravitino/credential/TestCredentialFactory.java, common/src/test/java/org/apache/gravitino/credential/TestCredentialPropertiesUtils.java, core/src/test/java/org/apache/gravitino/credential/DummyCredentialProvider.java, iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/service/extension/DummyCredentialProvider.java
support credential client in Gravition java client
Fix: #5622 
no
add UT and test the overall flow in POC
=> [#5622] feat(client): support credential client in Gravition java client

web/web/src/lib/utils/initial.js
config oceanbase column types
N/A
Fix: #5815
N/A
manually
=> [#5815] fix(web): config oceanbase column types

web/integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/CatalogsPageKafkaTest.java, web/integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/CatalogsPageTest.java, web/integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/pages/CatalogsPage.java, web/web/src/app/metalakes/metalake/rightContent/CreateTableDialog.js, web/web/src/app/metalakes/metalake/rightContent/RightContent.js
Add e2e test case for creating schema/fileset/topic/table
we need to implement the created test case by simulating a click on the UI dialog box
Fix: #5796, #5797, #5798, #5799
N/A
local run e2e test
=> [#5796][#5798] Add e2e test case for creating schema/fileset/topic/table

bundles/aws-bundle/src/main/java/org/apache/gravitino/s3/credential/S3TokenProvider.java, catalogs/catalog-common/src/main/java/org/apache/gravitino/storage/S3Properties.java, core/src/main/java/org/apache/gravitino/credential/config/S3CredentialConfig.java, docs/iceberg-rest-service.md
Support config STS Endpoint for S3 in Rest Catalog
Support for On-premise S3 Deployment such as MinIO
Fixes: #5839 
1. Addition of property keys `s3-token-service-endpoint` for iceberg catalog.
=> [#5839] feat(core): support custom STS Endpoint for AWS S3

clients/cli/src/main/java/org/apache/gravitino/cli/commands/SetOwner.java
Add support for topic and fileset in set owner in Gravitino CLI
these entities can also have owners.
Fix: # N/A
No
Tested locally
=> [Minor] Add support for topic and fileset in set owner in Gravitino CLI

clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/SetOwner.java
Stop an error line being output in list columns CLI command.
It should not display an error.
Fix: # N/A
No
=> [Minor] Fix list column output in Gravitino CLI

clients/cli/src/main/java/org/apache/gravitino/cli/ErrorMessages.java
Explain to the user what is missing and how to fix it.
See above.
Fix: # N/A
No.
Locally.
=> [Minor] Improve missing name error message in Gravitino CLI

clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
Fix a merge issue in CLI.
It makes the main branch has compilation error.
Fix: #5884
No
Local compilation and CI.
=> fix compilation error in cli

build.gradle.kts, integration-test-common/src/test/java/org/apache/gravitino/integration/test/container/ContainerSuite.java, integration-test-common/src/test/java/org/apache/gravitino/integration/test/container/HiveContainer.java
Support Hive test container with SQL based auhtorization 
Fix: #5881 
Yes
Just a test code.
=> [#5881] test(authorization): Support Hive test container with SQL based auhtorization

api/src/main/java/org/apache/gravitino/model/ModelCatalog.java, catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogOperations.java, catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/SecureHadoopCatalogOperations.java, catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java, catalogs/catalog-model/build.gradle.kts, catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogImpl.java, catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogOperations.java, catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelImpl.java, catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelVersionImpl.java, catalogs/catalog-model/src/test/java/org/apache/gravtitino/catalog/model/TestModelCatalogOperations.java, core/src/main/java/org/apache/gravitino/catalog/ManagedSchemaOperations.java, core/src/main/java/org/apache/gravitino/catalog/ModelNormalizeDispatcher.java, core/src/main/java/org/apache/gravitino/catalog/ModelOperationDispatcher.java, core/src/main/java/org/apache/gravitino/catalog/SchemaOperationDispatcher.java, core/src/main/java/org/apache/gravitino/connector/BaseModel.java, core/src/main/java/org/apache/gravitino/connector/BaseModelVersion.java, core/src/main/java/org/apache/gravitino/utils/NameIdentifierUtil.java, core/src/main/java/org/apache/gravitino/utils/NamespaceUtil.java, scripts/h2/schema-0.8.0-h2.sql, scripts/h2/upgrade-0.7.0-to-0.8.0-h2.sql, scripts/mysql/schema-0.8.0-mysql.sql, scripts/mysql/upgrade-0.7.0-to-0.8.0-mysql.sql, scripts/postgresql/schema-0.8.0-postgresql.sql, scripts/postgresql/upgrade-0.7.0-to-0.8.0-postgresql.sql
This PR adds the model catalog implementation.
This is a part of work to support model management in Gravitino.
Fix: #5739 
No.
Added UTs to cover the changes.
=> [#5739] feat(model-catalog): Implement the model catalog logic

clients/cli/src/main/resources/column_help.txt, clients/cli/src/main/resources/fileset_help.txt, clients/cli/src/main/resources/group_help.txt, clients/cli/src/main/resources/role_help.txt, clients/cli/src/main/resources/schema_help.txt, clients/cli/src/main/resources/table_help.txt, clients/cli/src/main/resources/tag_help.txt, clients/cli/src/main/resources/topic_help.txt, clients/cli/src/main/resources/user_help.txt, docs/cli.md
Update help content and fix a few minor issues in the documentation
To provide more help to users.
Fix: #5568
No
=> [#5568] Update help content for Gravitino CLI

authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerBaseE2EIT.java, core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java, core/src/test/java/org/apache/gravitino/authorization/TestAccessControlManagerForPermissions.java, core/src/test/java/org/apache/gravitino/authorization/TestOwnerManager.java
Fix to grant privilege for the metalake
Fix: #5892 
No.
Add a UT.
=> [#5892] fix(auth): Fix to grant privilege for the metalake

docs/open-api/openapi.yaml, docs/open-api/owners.yaml
Fix the wrong possible values. Remove "COLUMN" from metadataObjectType possible values in get/set owner.
Fix: #5911
No.
Just documents.
=> [#5911] fix(docs): Fix the wrong possible values.

authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveE2EIT.java, core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java
Fix the issue of renaming catalogs or metalakes.
Fix: #5947
No.
Add UT.
=> [#5947] fix(auth): It will throw error if we enable authorization and  rename catalog (#5949)

docs/how-to-use-the-playground.md
Revert helm-chart related descriptions in `docs/how-to-use-the-playground.md`.
Make documentation match `README.md` of `apache/gravitino-playground` .
Yes, documentation is affacted.
Manually.
=> Minor (docs): Update how-to-use-the-playground.md document

server/src/main/java/org/apache/gravitino/server/GravitinoServer.java
move `server.initialize()` to try-catch block, so we can get the exception and output the  exception to log file
Fix: #6022 
NO
=> [#6022] refactor: Output the failed logs to `gravitino-server.log` file

docs/how-to-use-gvfs.md
Fix incorrect description of fileset in GVFS doc
Fix: #5981
NO
just a document
=> [#5981]fix(docs): Fix incorrect description of fileset in GVFS doc

core/src/main/java/org/apache/gravitino/catalog/SchemaOperationDispatcher.java, core/src/main/java/org/apache/gravitino/catalog/TableOperationDispatcher.java, core/src/main/java/org/apache/gravitino/utils/NameIdentifierUtil.java, server/src/main/java/org/apache/gravitino/server/web/rest/SchemaOperations.java, server/src/main/java/org/apache/gravitino/server/web/rest/TableOperations.java
Modify Schema and Table RESTful interface lock operations.
Fix: #6044
N/A
CI Passed.
=> [#6044] improve(lock): optimization tree lock when drop and load Table/Schema

common/src/main/java/org/apache/gravitino/dto/requests/RoleCreateRequest.java, server/src/main/java/org/apache/gravitino/server/web/rest/GroupOperations.java, server/src/main/java/org/apache/gravitino/server/web/rest/OwnerOperations.java, server/src/main/java/org/apache/gravitino/server/web/rest/PermissionOperations.java, server/src/main/java/org/apache/gravitino/server/web/rest/RoleOperations.java, server/src/main/java/org/apache/gravitino/server/web/rest/UserOperations.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestGroupOperations.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestOwnerOperations.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestPermissionOperations.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestRoleOperations.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestUserOperations.java
Add the check of requests related to authorization
Fix: #6060 
No.
Added UT.
=> [#6060] fix(core): Add the check of requests related to authorization

clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/authorization/AccessControlIT.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/GroupMetaBaseSQLProvider.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/UserMetaBaseSQLProvider.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/h2/GroupMetaH2Provider.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/h2/UserMetaH2Provider.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/GroupMetaPostgreSQLProvider.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/UserMetaPostgreSQLProvider.java, core/src/test/java/org/apache/gravitino/storage/relational/service/TestGroupMetaService.java, core/src/test/java/org/apache/gravitino/storage/relational/service/TestUserMetaService.java
Fix the issues of list user or group details
Fix: #6061
No.
Added UT.
=> [#6061] fix(core): Fix the issues of list user or group details

clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
remove duplicate if statement.
Looks like a merge issue.
Fix: # N/A
No.
tested locally
=> [Minor] fix duplicate/merge issue in Gravitino CLI model command

clients/cli/src/main/java/org/apache/gravitino/cli/ErrorMessages.java, clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/Main.java, clients/cli/src/main/java/org/apache/gravitino/cli/Privileges.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/Command.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/CreateTag.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/DeleteCatalog.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/DeleteMetalake.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/DeleteTag.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/GrantPrivilegesToRole.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/RegisterModel.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/RevokePrivilegesFromRole.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestCatalogCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestColumnCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestFilesetCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestMain.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestMetalakeCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestModelCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestSchemaCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestTableCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestTagCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestTopicCommands.java
Clean up the error messages.
Put them all in one place and made more consistent.
Fix: #6103
No
=> [#6103] Clean up error messages in Gravitino CLI

bundles/gcp/src/main/java/org/apache/gravitino/gcs/credential/GCSTokenProvider.java
add get bucket permission for GCS fileset operation
Fix: #6028 
no
run pass fileset IT
=> [#6028]  feat(core): add GCS get bucket permission for GCS fileset operation

clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestGroupCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestUserCommands.java
Refactor the validation logic of user and group.
Fix: #6106 
No
local test.
=> [#6106] fix(CLI): Refactor the validation logic of user and group

web/web/src/lib/store/metalakes/index.js
fix error when dropping model on ui 
N/A
Fix: #6154
N/A
manually
=> [#6154] web(ui): fix error when dropping model

clients/cli/src/main/java/org/apache/gravitino/cli/CommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/TableCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java
Refactor table commands in Gavitino CLI and Base class.
Fix: #6145
No
local test
=> [#6145] improve(CLI): Refactor table commands in Gavitino CLI

NOTICE, NOTICE.rest, web/web/NOTICE.bin
Update year as we are going to make a new release.
ASF/legal policy.
Fix: #N/A
No
N/A
=> [Minor] Update year in NOTICE files

clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/TopicCommandHandler.java
Refactor topic commands in Gavitino CLI
Fix: #6146 
No
local test.
=> [#6146] improve(CLI): Refactor topic commands in Gavitino CLI

docs/security/authorization-pushdown.md
Add document for chain authorization plugin
Fix: #6110 
Just document.
No need.
=> [#6110] doc(authz): Add document for chain authorization plugin (#6115)

clients/cli/src/main/java/org/apache/gravitino/cli/CommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/SchemaCommandHandler.java
Refactor schema commands in Gravitino CLI.
Fix: #6144
No
Local test
=> [#6144] improve(CLI): Refactor schema commands in Gravitino CLI

clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/OwnerCommandHandler.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestOwnerCommands.java
Refactor ownership commands in Gravitino CLI.
Fix: #6177 
No
local test.
=> [#6177] improve(CLI): Refactor ownership commands in Gravitino CLI

clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/UserCommandHandler.java
Refactor user commands and Base class in Gavitino CLI.
Fix: #6150 
No
local test.
=> [#6150] improve(CLI): Refactor user commands in Gavitino CLI

clients/client-python/LICENSE, clients/client-python/NOTICE, clients/client-python/build.gradle.kts, clients/client-python/licenses/kylinpy.txt
Add license and notice files.
As the release's content is different to that of Gravitino.
Fix: #6194
No
=> [#6194] Add python client license and notice file

docs/security/access-control.md
Fix the wrong document information about revoke roles from role
Fix: #6069 
No
local test.
=> [#6069] fix(docs): Fix  access-control.md

iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/metrics/IcebergMetricsManager.java
Correct the logger class in IcebergMetricsManager
Fix: #6275 
No
UT
=> [#6275] fix: incorrect logger class in IcebergMetricsManager

clients/cli/src/main/java/org/apache/gravitino/cli/outputs/TableFormat.java
Fix TableFormat properties.
Fix: #6273 
No
local test.
=> [#6273] improve(CLI): Fix TableFormat properties.

clients/cli/src/main/java/org/apache/gravitino/cli/FullName.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListEntityTags.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/TagEntity.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UntagEntity.java, clients/cli/src/main/java/org/apache/gravitino/cli/utils/FullNameUtil.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestFullNameUtil.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestFulllName.java
Add tag support to Models in Gravtitino CLI. currently, the CLI support following actions:
1. `UntagEntity`, 
2. `TagEntity`,  
3. `ListEntityTags`
Fix: #6242 
No
local test.
=> [#6242] improve(CLI): Add tag support to Models in Gravtitino CLI.

clients/cli/src/main/java/org/apache/gravitino/cli/AreYouSure.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestAreYouSure.java
Fix AreYouSure Scanner should close.
Fix: #6277 
No.
local test.
=> [#6277] improve(CLI): Fix AreYouSure Scanner should close.

docs/flink-connector/flink-catalog-paimon.md
rename `paimon_tabla_a ` to `paimon_table_a`
table name is wrong.
no
just document
=> [MINOR] docs(flink): fix flink paimon document

.gitignore
close #6267
Support jumping to the PR page and Issue page from IDE
=> [#6267] minor: Support jumping to the PR page and Issue page from IDE (#6269)

docs/spark-connector/spark-catalog-paimon.md
Add paimon spark connector doc
=> [MINOR] docs: Add paimon spark connector doc

docs/spark-connector/spark-connector.md
add Spark Paimon catalog to Spark connector index page
no
just document
=> [MINOR] docs: add Spark Paimon catalog to Spark connector index page

docs/open-api/catalogs.yaml
fix wrong catalog type values
the enum value of catalog type is wrong
no
CI pass
=> [MINOR] fix(open-api): fix wrong catalog type values

clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/TableCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/CreateTable.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/DeleteTable.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListIndexes.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListTableProperties.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListTables.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/RemoveTableProperty.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/SetTableProperty.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/TableAudit.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/TableCommand.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/TableDetails.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/TableDistribution.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/TablePartition.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/TableSortOrder.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateTableComment.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateTableName.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestTableCommands.java
Add table command context CLI.
Fix: #6419 
No
local test.
=> [#6419] improve(CLI): Add table command context CLI

clients/cli/src/main/java/org/apache/gravitino/cli/FilesetCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/CreateFileset.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/DeleteFileset.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/FilesetDetails.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListFilesetProperties.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListFilesets.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/RemoveFilesetProperty.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/SetFilesetProperty.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateFilesetComment.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateFilesetName.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestFilesetCommands.java
Add Fileset command context CLI
Fix: #6415 
No
local test
=> [#6415] improve(CLI): Add Fileset command context CLI

clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/ModelCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/DeleteModel.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/LinkModel.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListModel.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ModelAudit.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ModelDetails.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/RegisterModel.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestModelCommands.java
Add model command context CLI
Fix: #6417 
No
local test
=> [#6417] improve(CLI): Add model command context CLI

clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/TopicCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/CreateTopic.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/DeleteTopic.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListTopicProperties.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListTopics.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/RemoveTopicProperty.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/SetTopicProperty.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/TopicDetails.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateTopicComment.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestTopicCommands.java
Add stream command context CLI
Fix: #6418 
No
local test.
=> [#6418] improve(CLI): Add stream command context CLI

clients/cli/src/main/java/org/apache/gravitino/cli/ColumnCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/AddColumn.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ColumnAudit.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/DeleteColumn.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListColumns.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateColumnAutoIncrement.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateColumnComment.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateColumnDatatype.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateColumnDefault.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateColumnName.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateColumnNullability.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateColumnPosition.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestColumnCommands.java
Add column command context CLI
Fix: #6420 
No
local test.
=> [#6420] improve(CLI): Add column command context CLI

clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/TagCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/CreateTag.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/DeleteTag.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListAllTags.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListEntityTags.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListTagProperties.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/RemoveAllTags.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/RemoveTagProperty.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/SetTagProperty.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/TagDetails.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/TagEntity.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UntagEntity.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateTagComment.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateTagName.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestTagCommands.java
Add tags command context CLI
Fix: #6423 
No
local test
=> [#6423] improve(CLI): Add tags command context CLI

clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/GroupCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/UserCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/AddRoleToGroup.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/AddRoleToUser.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/CreateGroup.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/CreateUser.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/DeleteGroup.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/DeleteUser.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/GroupAudit.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/GroupDetails.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListGroups.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListUsers.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/RemoveAllRoles.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/RemoveRoleFromGroup.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/RemoveRoleFromUser.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UserAudit.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UserDetails.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestGroupCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestUserCommands.java
Add user and group command context CLI
Fix: #6421
No
local test.
=> [#6421] improve(CLI): Add user and group command context CLI

clients/cli/src/main/java/org/apache/gravitino/cli/CatalogCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/ColumnCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/CommandContext.java, clients/cli/src/main/java/org/apache/gravitino/cli/CommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/FilesetCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/GroupCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/MetalakeCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/ModelCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/OwnerCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/RoleCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/SchemaCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/SimpleCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/TableCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/TagCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/TopicCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/UserCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ClientVersion.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/ServerVersion.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestCommandContext.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestMetalakeCommands.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestSimpleCommands.java
Refactor getURL in CLI and add context to simple commands.
Fix: #6424 
No
local test.
=> [#6424] improve(CLI): Refactor getURL in CLI and add context to simple commands.

docs/iceberg-rest-service.md
multi catalog and view operation should shown in document side bars.
User could find multi catalog configuration easily
no
just document
=> [MINOR] docs: polish Iceberg REST server document

web/web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js
authentication.type of catalog property should send correct request to server
N/A
Fix: #6450
N/A
manually
=> [#6450] fix(web): fix authentication.type issue

web/web/src/components/DetailsDrawer.js
fix uri title of version detail
N/A
Fix: #6478
N/A
manually
=> [#6478] web(ui): fix uri title of version detail

api/src/main/java/org/apache/gravitino/MetadataObjects.java, clients/client-java/src/main/java/org/apache/gravitino/client/GenericModel.java, clients/client-java/src/main/java/org/apache/gravitino/client/GenericModelCatalog.java, clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/TagIT.java, docs/manage-tags-in-gravitino.md, docs/open-api/tags.yaml
This PR adds the tag support for model metadata.
This is to complement the tag support for model metadata.
Fix: #6222
No.
Add ITs in test.
(cherry picked from commit 4c5e9db46c83a105ff886e3e49e6ce04b323a5e6)
=> [#6222]feat(tag): Add tag support for model

.github/dependabot.yml
Add depedabot configuration to check gravitino and gravitino web UI dependencies.
So we know what to update.
Fix: #6509
No.
Unable to test locally.
=> [#6509] Add dependabot configuration

MAINTAINERS.md
Update unknowntpo's organization due to career change in MAINTAINERS.md.
Update unknowntpo's organization due to career change in MAINTAINERS.md.
Career change.
Fix: #(issue)
No.
None.
=> [Minor] Update unknowntpo's organization due to career change in MAINTAINERS.md

web/web/package.json, web/web/pnpm-lock.yaml
remove deprecated dependency @mui/x-tree-view
@mui/x-tree-view is deprecated in our project
Fix: #6608
N/A
local install and setup
=> [#6608] improvement(web): remove deprecated dependency @mui/x-tree-view

core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java, core/src/main/java/org/apache/gravitino/storage/relational/converters/H2ExceptionConverter.java, core/src/main/java/org/apache/gravitino/storage/relational/converters/MySQLExceptionConverter.java, core/src/main/java/org/apache/gravitino/storage/relational/converters/SQLExceptionConverterFactory.java
fix SQLExceptionConverterFactory of entity storage not close
Fix: #6506 
no
CI pass
=> [#6506] fix(core): fix SQLExceptionConverterFactory of entity storage not close

flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/catalog/BaseCatalog.java, flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/hive/GravitinoHiveCatalog.java, flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/iceberg/GravitinoIcebergCatalog.java
Invoke open and close through realCatalog in BaseCatalog 
Fix #6626
=> (#6626) imporvement: Invoke open and close through realCatalog in BaseCatalog

docs/getting-started/aws-remote-access.md, docs/getting-started/hive.md, docs/getting-started/index.md
=> [MINOR] fix(doc): Revise syntax errors in getting-started tutorial

catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java
add IT to cover altering catalog location
Fix: #6650 
no
test added
=> [#6650] improvement(test): add IT to cover altering catalog location

docs/how-to-build.md
Add note about known security vulnerabilities
Some users are using older versions of software used in conjunction with Gravitino than may contain known security vulnerabilities
Fix: #N/A
No.
Locally.
=> [MINOR] Add note about known security vulnerabilities.

catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogOperations.java, iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/utils/IcebergCatalogUtil.java
The warehouse location for Iceberg memory catalog backend is hard coded to '/tmp', make it configurable.
Fix: #6649 
no
test it whether works for S3 and local storage
=> [#6649] feat(iceberg): make warehouse configable for Iceberg memory catalog backend 

core/src/main/java/org/apache/gravitino/catalog/CatalogManager.java, core/src/test/java/org/apache/gravitino/catalog/TestCatalogManager.java
#6667 
Fix: #6667
no
add a new test testForceDropCatalog in TestCatalogManager
=> [#6667]fix(core):can force delete invalid catalog

bundles/aliyun-bundle/build.gradle.kts, bundles/aliyun/build.gradle.kts, bundles/aws-bundle/build.gradle.kts, bundles/aws/build.gradle.kts, bundles/azure-bundle/build.gradle.kts, bundles/azure/build.gradle.kts, bundles/gcp-bundle/build.gradle.kts, bundles/gcp/build.gradle.kts, catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogOperations.java
Remove log4j from Gravitino bundle jars
Fix: #6654 
no
build bundle jar and run with Iceberg REST server, the log is normal
=> [#6654] fix(bundle): remove log4j from Gravitino cloud bundle jars

docs/iceberg-rest-service.md
add Iceberg REST server URI in document
User could use IRC more easily
no
just document
=> [MINOR] docs:  add Iceberg REST server URI in document

core/src/main/java/org/apache/gravitino/GravitinoEnv.java
Add event listener support for Model system.
Fix: #6075 
No
local test.
=> [#6075] improvement(core): Add event listener support for Model system

.asf.yaml
Update the asf.yaml to add new collaborators.
To add active contributors to give them more permissions.
No.
No need.
=> [MINOR] Update the asf.yaml to add new collaborators

catalogs/catalog-lakehouse-iceberg/src/test/java/org/apache/gravitino/catalog/lakehouse/iceberg/integration/test/TestMultipleJDBCLoad.java, docs/iceberg-rest-service.md, iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/utils/IcebergCatalogUtil.java
Remove validation from Gravitino based on validation during iceberg catalog initialization
Fix: #6646
N/A
N/A
=> [#6646] fix(iceberg):  Delete the null value check for user and password in Iceberg JDBC catalog

api/src/main/java/org/apache/gravitino/file/Fileset.java, catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogOperations.java, catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopFilesetPropertiesMetadata.java, catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java, catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java, clients/client-python/gravitino/api/file/fileset.py, docs/hadoop-catalog.md, docs/manage-fileset-metadata-using-gravitino.md
support fileset location placeholder
Fix: #6680 
yes, user now can use placeholders in the location definition
tests added
=> [#6680] feat(fileset): support fileset location placeholder

.github/workflows/access-control-integration-test.yml, .github/workflows/backend-integration-test.yml, .github/workflows/build.yml, .github/workflows/cron-integration-test.yml, .github/workflows/flink-integration-test.yml, .github/workflows/frontend-integration-test.yml, .github/workflows/gvfs-fuse-build-test.yml, .github/workflows/python-integration-test.yml, .github/workflows/spark-integration-test.yml, .github/workflows/trino-integration-test.yml
update dorny/paths-filter@v2 to dorny/paths-filter@v3.0.2
update dorny/paths-filter@v2 to dorny/paths-filter@v3.0.2
no
CI pass
=> [MINOR] fix(CI): update dorny/paths-filter@v2 to dorny/paths-filter@v3.0.2

flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/paimon/FlinkPaimonCatalogIT.java, flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/paimon/FlinkPaimonHiveBackendIT.java, flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/paimon/FlinkPaimonHiveCatalogIT.java, flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/paimon/FlinkPaimonLocalFileSystemBackendIT.java
Fix: #6216 
FlinkPaimonHiveCatalogIT
=> [#6216] flink-connector: Add integration Tests for GravitinoPaimonCatalog with Catalog-backend as HiveMetaStore

api/src/main/java/org/apache/gravitino/authorization/Privilege.java, api/src/main/java/org/apache/gravitino/authorization/Privileges.java, api/src/main/java/org/apache/gravitino/authorization/SecurableObjects.java, api/src/test/java/org/apache/gravitino/authorization/TestSecurableObjects.java, clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/authorization/AccessControlIT.java, core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java, docs/security/access-control.md
Add privilege support for model
Fix: #6346
Added the doucments
UT.
=> [6346] feat(authz): Add privilege support for model

docs/flink-connector/flink-catalog-jdbc.md, docs/flink-connector/flink-connector.md
Add documentation for the GravitinoJdbcCatalog in Flink connector
close #6708
=> [#6708] docs: Add documentation for the GravitinoJdbcCatalog in Flink connector

clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/authorization/OwnerIT.java, core/src/main/java/org/apache/gravitino/GravitinoEnv.java, core/src/main/java/org/apache/gravitino/hook/ModelHookDispatcher.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/OwnerMetaSQLProviderFactory.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/OwnerMetaBaseSQLProvider.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/SecurableObjectBaseSQLProvider.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/TagMetadataObjectRelBaseSQLProvider.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/OwnerMetaPostgreSQLProvider.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/SecurableObjectPostgreSQLProvider.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/TagMetadataObjectRelPostgreSQLProvider.java, core/src/main/java/org/apache/gravitino/storage/relational/service/ModelMetaService.java, core/src/test/java/org/apache/gravitino/storage/relational/service/TestOwnerMetaService.java, core/src/test/java/org/apache/gravitino/storage/relational/service/TestSecurableObjects.java, core/src/test/java/org/apache/gravitino/storage/relational/service/TestTagMetaService.java
Support model hook dispatcher
Fix: #6704 
No.
Add IT.
=> [#6704] feat(authz): Support model hook dispatcher

catalogs/catalog-hive/src/main/java/org/apache/gravitino/catalog/hive/HiveProxyPlugin.java
Fix use catalog and show  databases  failed with krb cluster issue
Fix: #6777
No 
local test.
=> [#6777] fix(server,authn): Fix use catalog and show  databases  failed with krb cluster issue

authorizations/authorization-chain/src/test/java/org/apache/gravitino/authorization/chain/integration/test/TestChainedAuthorizationIT.java, authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationHDFSPlugin.java, authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerAuthorizationHDFSPluginIT.java, authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerFilesetIT.java
Support schema level for Ranger path based authz plugin
Fix: #6692
No.
Add UT.
=> [#6692] improvement(authz): Support schema level for Ranger path based authz plugin

.github/workflows/auto-cherry-pick.yml
Add auto cherry pick to branch-0.9
Prepare for branch 0.9
No.
No need.
=> [MINOR] build: Add auto cherry pick to branch-0.9

catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/operation/DorisTableOperations.java
use `show backends` to get the count of Doris Backend (BE) nodes
Fix: #6722
N/A
IT
Fix: #(issue)
=> [#6722] fix(jdbc-doris): use `show backends` to get the count of Doris BE nodes (#6884)

clients/filesystem-fuse/Cargo.toml
Update the version of fuse module
CI passed.
No.
No need.
=> [MINOR] build: Update the version of fuse module

api/src/main/java/org/apache/gravitino/exceptions/NoSuchLocationNameException.java, api/src/main/java/org/apache/gravitino/file/Fileset.java, api/src/main/java/org/apache/gravitino/file/FilesetCatalog.java, catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogOperations.java, catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogPropertiesMetadata.java, catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopFilesetPropertiesMetadata.java, catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopSchemaPropertiesMetadata.java, catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java, clients/client-python/gravitino/api/file/fileset.py, clients/client-python/gravitino/client/fileset_catalog.py, clients/client-python/gravitino/client/generic_fileset.py, clients/client-python/gravitino/dto/fileset_dto.py, clients/client-python/gravitino/exceptions/base.py
add multiple locations APIs for fileset
Fix: #6889 
no, not implement, just add new API
CI pass
=> [#6889] feat(fileset): add multiple locations APIs for fileset

catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogOperations.java, catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopFileset.java, catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopFilesetPropertiesMetadata.java, catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/SecureHadoopCatalogOperations.java, catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java, catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java, catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopUserImpersonationIT.java, clients/client-python/tests/integration/test_fileset_catalog.py, core/src/main/java/org/apache/gravitino/catalog/EntityCombinedFileset.java, core/src/main/java/org/apache/gravitino/catalog/FilesetNormalizeDispatcher.java, core/src/main/java/org/apache/gravitino/catalog/FilesetOperationDispatcher.java, core/src/main/java/org/apache/gravitino/connector/BaseFileset.java, core/src/main/java/org/apache/gravitino/hook/FilesetHookDispatcher.java, core/src/main/java/org/apache/gravitino/listener/FilesetEventDispatcher.java, core/src/main/java/org/apache/gravitino/listener/api/event/GetFileLocationEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/GetFileLocationFailureEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/GetFileLocationPreEvent.java, core/src/main/java/org/apache/gravitino/listener/api/info/FilesetInfo.java, core/src/main/java/org/apache/gravitino/storage/relational/service/SchemaMetaService.java, core/src/test/java/org/apache/gravitino/TestFileset.java, core/src/test/java/org/apache/gravitino/connector/TestCatalogOperations.java, core/src/test/java/org/apache/gravitino/listener/api/event/TestFilesetEvent.java, core/src/test/java/org/apache/gravitino/meta/TestEntityCombinedObject.java
support fileset multiple locations in the core and catalog module
Fix: #6892
no
tests added
=> [#6892] feat(core): support fileset multiple locations in core module

iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/authentication/kerberos/HiveBackendProxy.java
Fix use catalog and show  databases  failed with krb cluster for iceberg issue
Fix: #6871
No
local test.
steps:
1、curl -X POST -H "Accept: application/vnd.gravitino.v1+json"
-H "Content-Type: application/json" -d '{
"name": "iceberg_catalog",
"type": "RELATIONAL",
"comment": "iceberg catalog",
"provider": "lakehouse-iceberg",
"properties": {
"catalog-backend": "hive",
"warehouse": "/pathforhivetest",
"uri": "thrift://HMS HOST:9083",
"gravitino.bypass.hadoop.security.authentication": "kerberos",
"gravitino.bypass.hive.metastore.sasl.enabled": "true",
"gravitino.bypass.hive.metastore.kerberos.principal": "hive/HMS HOST@REALM",
"authentication.kerberos.keytab-uri": "PATH OF KEYTAB",
"authentication.kerberos.principal": "hive/HOST INSATANCE@REALM",
"authentication.type": "kerberos", …
=>  [#6871] fix(server,authn): Fix use catalog and show  databases  failed with krb cluster for iceberg issue

.asf.yaml
Enable GitHub Discussions
Enable GitHub Discussions
N/A
N/A
=> [MINOR] Enable GitHub Discussions

clients/client-python/gravitino/filesystem/gvfs.py, clients/client-python/gravitino/filesystem/gvfs_utils.py, clients/client-python/tests/unittests/test_gvfs_with_local.py, clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java, clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/GravitinoVirtualFileSystemUtils.java, clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/GravitinoMockServerBase.java, clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/TestGvfsBase.java
extract methods from gvfs to utils for reusing
Fix: #6604 
no
CI pass
=> [#6604] Improvement(GVFS): extract methods from gvfs to utils for reusing

clients/client-python/gravitino/filesystem/gvfs.py, clients/client-python/tests/unittests/test_gvfs_without_fileset.py, clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/FilesetPathNotFoundException.java, clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java, clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/GravitinoVirtualFileSystemConfiguration.java, clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/TestGvfsBase.java
Refactor the GVFS to handle fileset not created scenario and align with
FS semantics.
Fix: #6953 
no
tests added
=> [#6953] feat(GVFS): Refactor GVFS to handle fileset not existed scenario

.github/workflows/chart-test.yaml
Fix incorrect target branch variable in chart CI
Fix: #6971
N/A
CI
=> [#6971][followup] build: Fix incorrect target branch variable in chart CI

clients/client-python/gravitino/filesystem/gvfs_base_operations.py
fix python gvfs missing auto-create fileset dir
Fix: #6940 
no
existing tests
=> [#6940] fix(gvfs): fix python gvfs missing auto-create fileset dir

api/src/main/java/org/apache/gravitino/rel/types/Types.java, clients/client-python/gravitino/api/types/types.py
Update outdated comments for complex types.
Fix: #6875
No.
Existing UTs.
=> [#6875] fix: Update outdated comments for complex types

core/src/main/java/org/apache/gravitino/GravitinoEnv.java
Make it possible to obtain the eventListenerManager from GravitinoEnv
Fix: #7012
No
Manually test
=> [#7012] improve (core): Add eventListenerManager function in GravitinoEnv

dev/release/release-tag.sh
Update rust module in the release script
Fix: #7020 
No.
By hand.
=> [#7020] improvement(build): Update rust module in the release script

clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoVersion.java, clients/client-java/src/test/java/org/apache/gravitino/client/TestGravitinoVersion.java, clients/client-python/tests/unittests/test_gravitino_version.py
version parse supports complex suffix
Fix: #7029 
no
tests added
=> [#7029] improvement(version): version parse supports complex suffix

docs/security/credential-vending.md
add Iceberg cloud package to credential vending document
Fix: #6647 
no
just document
=> [#6647] docs(iceberg): add Iceberg cloud package information to credential vending document

docs/open-api/models.yaml
Update models.yaml.
Fix: minor
no.
local test.
=> [MINOR] docs(docs): Update models.yaml

authorizations/authorization-chain/src/test/java/org/apache/gravitino/authorization/chain/integration/test/TestChainedAuthorizationIT.java, authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationHDFSPlugin.java, authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java, authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerAuthorizationHDFSPluginIT.java, authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerBaseE2EIT.java, authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerFilesetIT.java, authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveE2EIT.java, authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveHdfsE2EIT.java, authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerIcebergE2EIT.java, authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerPaimonE2EIT.java
Add more test cases about Hdfs Ranger authz plugin
Fix: #6917
No.
Add more ITs.
=> [#6917] test(authz): Add more test cases about Hdfs Ranger authz plugin

dev/release/release-tag.sh
Update chart version in the release script
Fix: #7066 
No.
By hand.
=> [#7066] fix(build): Update chart version in the release script

conf/log4j2.properties.template
1. Fix unexpected output in gravitino-server.out
2. correct lineage output name
Fix: #7068 
no
Start Gravitino server, no unexpected output  in gravitino-server.out, and lineage log is outputed
=> [#7068] fix unexpected output in gravitino-server.out

docs/chart.md, docs/how-to-install.md
1. Some urls format are incorrect in chart.md
2. Add chart installation way in how to install.md
3. Remove some no required docs in chart.md
To fix the doc build issue
N/A
N/A
=> [MINOR] docs: Change doc for chart.md

docs/flink-connector/flink-catalog-jdbc.md, docs/manage-fileset-metadata-using-gravitino.md
Fix the errors of the document
Fix: #7091
No.
No.
=> [#7091] fix(docs): Fix the errors of the document

LICENSE, NOTICE.bin, build.gradle.kts, docs/open-api/lineage.yaml, lineage/src/test/java/org/apache/gravitino/lineage/source/TestLineageOperations.java
add OpenLineage license
missing OpenLineage license
no
just document
=> [MINOR] feat(license): add OpenLineage license

LICENSE, NOTICE, core/src/main/java/org/apache/gravitino/listener/api/event/AlterModelVersionFailureEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/AlterModelVersionPreEvent.java, core/src/main/java/org/apache/gravitino/listener/api/info/Either.java, core/src/test/java/org/apache/gravitino/listener/api/event/TestEither.java, dev/ci/chart_schema.yaml, dev/ci/lintconf.yaml, web/web/LICENSE.bin, web/web/licenses/call-bind-apply-helpers.txt, web/web/licenses/call-bound.txt, web/web/licenses/dunder-proto.txt, web/web/licenses/fast-color.txt, web/web/licenses/get-proto.txt, web/web/licenses/math-intrinstics.txt
Change the license header for the helm chart files.
Add the MIT licenses for web dependencies
Fix the license header for the `Either.java`
Fix: #7087
No.
By reivew.
=> [#7087] fix(license): Fix the licenses issues

web/web/src/app/metalakes/metalake/rightContent/LinkVersionDialog.js, web/web/src/app/metalakes/metalake/rightContent/RegisterModelDialog.js, web/web/src/app/metalakes/metalake/rightContent/tabsContent/tableView/TableView.js, web/web/src/lib/api/models/index.js, web/web/src/lib/store/metalakes/index.js, web/web/src/lib/utils/index.js
update model for UI
update model version for UI
N/A
Fix: #7106
N/A
manually
=> [#7106] subtask(web): support update model/model version for UI

docs/iceberg-rest-service.md
add Trino example for Iceberg REST catalog document
Useful for use Trino Iceberg REST catalog with Gravitino IRC
no
just document
=> [MINOR] doc(iceberg): add Trino example for Iceberg REST catalog

build.gradle.kts, clients/client-java-runtime/build.gradle.kts, clients/client-python/build.gradle.kts, common/build.gradle.kts, flink-connector/flink-runtime/build.gradle.kts, trino-connector/integration-test/build.gradle.kts
Improve and clarify error messages.
For clarity.
Fix: #(issue)
No.
=> [Minor] Improve error messages

dev/release/release-tag.sh
Fix the version of chart values
Fix: #7129
No.
By hand.
=> [#7129] fix(build): Fix the version of chart values

dev/charts/gravitino/Chart.yaml, dev/charts/gravitino/values.yaml
Fix the version in the values.yaml
Fix: #7129
No.
No need.
=> [#7129] fix(build): Fix the version in the values.yaml

dev/charts/gravitino/Chart.yaml, dev/charts/gravitino/values.yaml, docs/chart.md
1.   Update chart doc 
2.  Update chart default image tag
Show how to set image tag to user.
N/A
CI
=> [Minor] Update chart doc and chart default image tag

docs/open-api/models.yaml
Fix models.yaml
MINOR
Update openAPI docs.
local test.
=> [MINOR] fix(docs): Fix models.yaml

api/src/main/java/org/apache/gravitino/model/ModelVersionChange.java, api/src/test/java/org/apache/gravitino/model/TestModelVersionChange.java, catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogOperations.java, catalogs/catalog-model/src/test/java/org/apache/gravtitino/catalog/model/integration/test/ModelCatalogOperationsIT.java, clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoOptions.java, clients/cli/src/main/java/org/apache/gravitino/cli/ModelCommandHandler.java, clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateModelVersionAliases.java, clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateModelVersionUri.java, clients/cli/src/test/java/org/apache/gravitino/cli/TestModelCommands.java, clients/client-java/src/main/java/org/apache/gravitino/client/DTOConverters.java, clients/client-python/gravitino/api/model_version_change.py, clients/client-python/gravitino/client/generic_model_catalog.py, clients/client-python/gravitino/dto/requests/model_version_update_request.py, clients/client-python/gravitino/filesystem/gvfs_base_operations.py, clients/client-python/tests/integration/test_model_catalog.py, clients/client-python/tests/unittests/test_gravitino_version.py, common/src/main/java/org/apache/gravitino/dto/requests/ModelVersionUpdateRequest.java, core/src/test/java/org/apache/gravitino/connector/TestCatalogOperations.java, docs/manage-model-metadata-using-gravitino.md, docs/open-api/models.yaml
Backport of #7133 and  #7157  to branch-0.9. Support update aliases for model version and fix docs.
Backport.
no.
local test
=> [Backport-0.9] Support update aliases for model version

catalogs/hadoop-common/src/main/java/org/apache/gravitino/catalog/hadoop/fs/FileSystemUtils.java
fixes javadoc for :catalogs:hadoop-common
Fix: #7204
no
CI pass
=> [#7204] fix(javadoc): complete javaDoc for catalogs:hadoop-common

authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java, authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerHadoopSQLSecurableObject.java, authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerHelper.java
Added missing @param and @return Javadoc tags.
Fixes #7212
No.
- Ran `./gradlew :authorizations:authorization-ranger:javadoc` to confirm all Javadoc warnings were resolved.
- Ran `./gradlew clean build`
=> [#7212] improvement(javadoc): Fix Javadoc warnings in authorization-ranger module

catalogs/hive-metastore-common/src/main/java/org/apache/gravitino/hive/dyn/DynFields.java, catalogs/hive-metastore-common/src/main/java/org/apache/gravitino/hive/dyn/DynMethods.java
fix javadoc for :catalogs:hive-metastore-common
Fix: #7213
=> [#7213] fix: javadoc for :catalogs:hive-metastore-common

spark-connector/v3.3/spark-runtime/build.gradle.kts, spark-connector/v3.4/spark-runtime/build.gradle.kts, spark-connector/v3.5/spark-runtime/build.gradle.kts
Remove slf4j dependency from packaging to avoid conflicts with Spark.
Fixes https://github.com/apache/gravitino/issues/7287
Spark sometimes has no logs, and there is no slf4j implementation class available.
No.
=> [#7287] fix(spark-connector): remove slf4j dependency from packaging spark connector to avoid conflicts with Spark

api/src/main/java/org/apache/gravitino/exceptions/IllegalPolicyException.java, api/src/main/java/org/apache/gravitino/exceptions/NoSuchPolicyException.java, api/src/main/java/org/apache/gravitino/exceptions/PolicyAlreadyAppliedException.java, api/src/main/java/org/apache/gravitino/exceptions/PolicyAlreadyAssociatedException.java, api/src/main/java/org/apache/gravitino/exceptions/PolicyAlreadyExistsException.java, api/src/main/java/org/apache/gravitino/policy/Policy.java, api/src/main/java/org/apache/gravitino/policy/PolicyChange.java, api/src/main/java/org/apache/gravitino/policy/PolicyOperations.java, api/src/main/java/org/apache/gravitino/policy/SupportsPolicies.java
add APIs for policy operations
Fix: #7141 
no
no need
=> [#7141] feat(api): add APIs for policy operations

catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogOperations.java
updates the error message in `catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogOperations.java` to correctly display.
Fixes #7346
No.
- Ran `./gradlew clean build`.
=> [#7346] fix(catalogs): modify the error message in model catalog

catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/SecureHadoopCatalogOperations.java, catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java
Fix get file location with multiple locations.
Fix: #7371
No.
UT.
=> [#7371] fix(fileset): fix get file location with multiple locations

server-common/build.gradle.kts, server-common/src/main/java/org/apache/gravitino/server/authorization/MetadataIdConverter.java, server-common/src/test/java/org/apache/gravitino/server/authorization/TestMetadataIdConverter.java
Introduce the MetadataIdConverter for converting between metadata names and metadata id.
Fix: #6783
no
local test.
=> [#6783] feat(core): Introduce the MetadataIdConverter for converting between names and id

authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/reference/VList.java, clients/cli/src/main/java/org/apache/gravitino/cli/FullName.java
Fix some typos.
It's an improvement.
N/A
N/A
=> [MINOR]: fix some typo

web/web/src/app/login/page.js, web/web/src/lib/api/github/index.js, web/web/src/lib/store/auth/index.js, web/web/src/lib/utils/axios/index.js
The Gravitino web UI was refreshes constantly when using OAuth authentication
Fix: #7426
N/A
manually test
=> [#7426] fix(web): fix refresh by oauth mode

web/web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js
Not select provider for fileset catalog
N/A
Fix: #7423
N/A
manually
=> [#7423] subtask(web): Not select provider for fileset catalog

core/src/main/java/org/apache/gravitino/cache/CaffeineEntityCache.java, core/src/main/java/org/apache/gravitino/cache/EntityCacheWeigher.java, core/src/test/java/org/apache/gravitino/cache/TestCaffeineEntityCache.java
Fix UT for cache.
| Class                 | Change Description                                     | Purpose & Impact                                             |
| --------------------- | ------------------------------------------------------ | ------------------------------------------------------------ |
|    `CaffeineEntityCache`   | Replace `estimatedSize()` with `cacheIndex.size()`     | Ensure accurate and deterministic cache size reporting       |
| `EntityCacheWeigher`  | Make `MAX_WEIGHT` private and use `@VisibleForTesting` | Prevent misuse, expose only to test code via MockStatic      |
|                       | Relax constructor visibility to `protected`            |                                                              |
MINOR
no
local test.
=> [MINOR] fix(core): Fix UT for cache

docs/docker-image-details.md
Add 0.9.1 release
Just a minor.
No.
Code review
=> [MINOR] docs: Add 0.9.1 release

clients/client-python/gravitino/filesystem/gvfs_storage_handler.py, clients/client-python/tests/integration/test_gvfs_with_abs.py, clients/client-python/tests/integration/test_gvfs_with_abs_credential.py, clients/client-python/tests/integration/test_gvfs_with_gcs.py, clients/client-python/tests/integration/test_gvfs_with_gcs_credential.py, clients/client-python/tests/integration/test_gvfs_with_hdfs.py, clients/client-python/tests/integration/test_gvfs_with_oss.py, clients/client-python/tests/integration/test_gvfs_with_oss_credential.py, clients/client-python/tests/integration/test_gvfs_with_s3.py, clients/client-python/tests/integration/test_gvfs_with_s3_credential.py
Fix test errors in python gvfs client test with credential
It's bug.
Fix: #7432 
N/A.
Test locally.
=> [#7432] fix(client-python): Fix test error in TestGvfsWithS3 with credential

docs/security/access-control.md
Fix the docs about model privilege
Just a minor.
No.
Code review.
=> [MINOR] docs: Fix the docs about model privilege

trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/CatalogConnectorFactory.java, trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/CatalogConnectorManager.java, trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/DefaultCatalogConnectorFactory.java
Fix an exception thrown when the metalake  contains unsupported catalog provider
Fix: #7322 
No
ITs
=> [#7322] fix (trino-connector) : Fix an exception thrown when the metalake  contains unsupported catalog provider

iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/CatalogWrapperForREST.java
Fix placeholders error.
Just a minor.
No.
Code review.
=> [MINOR] Fix placeholders error

dev/charts/gravitino/Chart.yaml, dev/charts/gravitino/resources/config/gravitino.conf, dev/charts/gravitino/values.yaml
update Gravitino entity cache configuration to the gravitino.conf template
Fix: #7510 
no
local test.
=> [#7510] feat(*): update Gravitino entity cache configuration to the gravitino.conf template

catalogs/catalog-jdbc-common/src/test/java/org/apache/gravitino/catalog/jdbc/TestJdbcCatalogOperations.java, iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/ops/IcebergCatalogWrapper.java, iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/metrics/IcebergMetricsManager.java, spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/SparkTableChangeConverter.java, spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/plugin/GravitinoDriverPlugin.java, spark-connector/spark-common/src/test/java/org/apache/gravitino/spark/connector/integration/test/sql/SparkQueryRunner.java, spark-connector/spark-common/src/test/java/org/apache/gravitino/spark/connector/integration/test/sql/SparkSQLRegressionTest.java, spark-connector/v3.4/spark/src/main/java/org/apache/gravitino/spark/connector/SparkTypeConverter34.java
unifed code style, the boolean type check use ` if( exp ) or if( !exp ) rather than if ( exp == true ),  if (exp == false ) `
close #7596
No, just code style change
using existing tests
=> [#7596] style: update code style

core/src/main/java/org/apache/gravitino/utils/NameIdentifierUtil.java
clean up unused method in `NameIdentifierUtil` class
close issue #7588
No
using existing tests
=> [#7588] improvement : delete unused method

clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/authorization/ModelAuthorizationIT.java, server-common/src/main/java/org/apache/gravitino/server/authorization/MetadataFilterHelper.java, server-common/src/main/java/org/apache/gravitino/server/authorization/expression/AuthorizationExpressionConverter.java, server/src/main/java/org/apache/gravitino/server/web/filter/GravitinoInterceptionService.java, server/src/main/java/org/apache/gravitino/server/web/rest/ModelOperations.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestModelOperations.java, server/src/test/java/org/apache/gravitino/server/web/rest/authorization/TestModelAuthorizationExpression.java
Support Model Authorization
close: #7602
None
org.apache.gravitino.client.integration.test.authorization.ModelAuthorizationIT
org.apache.gravitino.server.web.rest.authorization.TestModelAuthorizationExpression
=> [#7602] feat(authz): Support Model Authorization

docs/manage-tags-in-gravitino.md, docs/security/access-control.md, docs/trino-connector/trino-connector.md
Fix catalog
So it correct
Fix: #N/A
None
N/A
=> [Minor] fix typo: catalog

core/src/main/java/org/apache/gravitino/utils/IsolatedClassLoader.java
classLoader set to null after closing
Fix: #7644 
no
code review
=> [#7644] improvement(core): classLoader set to null after closing

core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/PolicyMetaMapper.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/PolicyMetaSQLProviderFactory.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/PolicyVersionMapper.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/PolicyVersionSQLProviderFactory.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/PolicyMetaBaseSQLProvider.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/PolicyVersionBaseSQLProvider.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/PolicyMetaPostgreSQLProvider.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/PolicyVersionPostgreSQLProvider.java, core/src/main/java/org/apache/gravitino/storage/relational/po/PolicyMaxVersionPO.java, core/src/main/java/org/apache/gravitino/storage/relational/service/MetalakeMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/PolicyMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/utils/POConverters.java, core/src/main/java/org/apache/gravitino/utils/NameIdentifierUtil.java, core/src/test/java/org/apache/gravitino/storage/relational/TestJDBCBackend.java, core/src/test/java/org/apache/gravitino/storage/relational/service/TestPolicyMetaService.java
support CURD ops for policy in backend storage (part-3)
Fix: #7360 
no
tests added
=> [#7360] feat(policy): support CURD ops for policy in backend storage (part-3)

common/src/main/java/org/apache/gravitino/Version.java
Close stream in Version.java
Fix: #7704 
no
junit
=> [#7704] feat(common): Close stream in Version

api/src/main/java/org/apache/gravitino/job/JobHandle.java, api/src/main/java/org/apache/gravitino/job/JobTemplate.java, api/src/main/java/org/apache/gravitino/job/ShellJobTemplate.java, api/src/main/java/org/apache/gravitino/job/SparkJobTemplate.java, core/src/main/java/org/apache/gravitino/Configs.java, core/src/main/java/org/apache/gravitino/Entity.java, core/src/main/java/org/apache/gravitino/SupportsRelationOperations.java, core/src/main/java/org/apache/gravitino/job/JobManager.java, core/src/main/java/org/apache/gravitino/job/JobOperationDispatcher.java, core/src/main/java/org/apache/gravitino/meta/JobEntity.java, core/src/main/java/org/apache/gravitino/meta/JobTemplateEntity.java, core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java, core/src/main/java/org/apache/gravitino/utils/NameIdentifierUtil.java, core/src/main/java/org/apache/gravitino/utils/NamespaceUtil.java, core/src/test/java/org/apache/gravitino/job/TestJobManager.java
This is the first part of work to add the job framework for Job System in Gravitino.
Fix: #7504
No.
Add new UTs to cover the code.
=> [#7504] feat(core): Add the job framework for Job System (part-1)

build.gradle.kts, catalogs/catalog-jdbc-starrocks/build.gradle.kts, catalogs/catalog-jdbc-starrocks/src/main/java/org/apache/gravitino/catalog/starrocks/StarRocksCatalog.java, catalogs/catalog-jdbc-starrocks/src/main/java/org/apache/gravitino/catalog/starrocks/StarRocksCatalogCapability.java, catalogs/catalog-jdbc-starrocks/src/main/java/org/apache/gravitino/catalog/starrocks/StarRocksTablePropertiesMeta.java, catalogs/catalog-jdbc-starrocks/src/main/java/org/apache/gravitino/catalog/starrocks/converter/StarRocksColumnDefaultValueConverter.java, catalogs/catalog-jdbc-starrocks/src/main/java/org/apache/gravitino/catalog/starrocks/converter/StarRocksExceptionConverter.java, catalogs/catalog-jdbc-starrocks/src/main/java/org/apache/gravitino/catalog/starrocks/converter/StarRocksTypeConverter.java, catalogs/catalog-jdbc-starrocks/src/main/java/org/apache/gravitino/catalog/starrocks/operations/StarRocksDatabaseOperations.java, catalogs/catalog-jdbc-starrocks/src/main/java/org/apache/gravitino/catalog/starrocks/operations/StarRocksTableOperations.java, catalogs/catalog-jdbc-starrocks/src/main/java/org/apache/gravitino/catalog/starrocks/operations/StarRocksTablePartitionOperations.java, catalogs/catalog-jdbc-starrocks/src/main/resources/META-INF/services/org.apache.gravitino.CatalogProvider, catalogs/catalog-jdbc-starrocks/src/main/resources/jdbc-starrocks.conf, settings.gradle.kts
Add interfaces and related classes for StarRocks, implementation will be in the next PR. 
To support more catalogs.
Fix: #7667 
N/A.
Test locally.
=> [#7667] feat(starrocks-catalog): Add StarRocks catalog skeleton.

catalogs/catalog-jdbc-starrocks/src/main/java/org/apache/gravitino/catalog/starrocks/converter/StarRocksColumnDefaultValueConverter.java, catalogs/catalog-jdbc-starrocks/src/main/java/org/apache/gravitino/catalog/starrocks/operations/StarRocksTablePartitionOperations.java
add StarRocks Catalog Implement
To support StarRocks Catalog.
No
By E2E test, the test is in another pr
https://github.com/apache/gravitino/pull/7792
=> [#3302][Sub-Task] StarRocks catalog Partition ops

core/src/main/java/org/apache/gravitino/job/JobExecutorFactory.java, core/src/main/java/org/apache/gravitino/job/JobManager.java, core/src/main/java/org/apache/gravitino/job/local/LocalJobExecutor.java, core/src/main/java/org/apache/gravitino/job/local/LocalJobExecutorConfigs.java, core/src/main/java/org/apache/gravitino/job/local/LocalProcessBuilder.java, core/src/main/java/org/apache/gravitino/job/local/ShellProcessBuilder.java, core/src/test/java/org/apache/gravitino/job/local/TestLocalJobExecutor.java, core/src/test/resources/common.sh, core/src/test/resources/test-job.sh
Add the local job executor and shell process builder for Gravitino's job system.
Fix: #7743 
No.
Add UTs to cover the code.
=> [#7743]feat(core): Add Local job executor and shell processor builder

catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/config/JdbcConfig.java, catalogs/catalog-jdbc-starrocks/src/test/java/org/apache/gravitino/catalog/starrocks/integration/test/CatalogStarRocksIT.java, catalogs/catalog-jdbc-starrocks/src/test/java/org/apache/gravitino/catalog/starrocks/operation/TestStarRocks.java, catalogs/catalog-jdbc-starrocks/src/test/java/org/apache/gravitino/catalog/starrocks/operation/TestStarRocksDatabaseOperations.java, catalogs/catalog-jdbc-starrocks/src/test/java/org/apache/gravitino/catalog/starrocks/operation/TestStarRocksTableOperations.java, catalogs/catalog-jdbc-starrocks/src/test/java/org/apache/gravitino/catalog/starrocks/operation/TestStarRocksTablePartitionOperations.java, core/src/main/java/org/apache/gravitino/Config.java, core/src/main/java/org/apache/gravitino/config/ConfigConstants.java, docs/index.md, docs/jdbc-starrocks-catalog.md, integration-test-common/src/test/java/org/apache/gravitino/integration/test/container/ContainerSuite.java, integration-test-common/src/test/java/org/apache/gravitino/integration/test/container/StarRocksContainer.java
add StarRocks Catalog Implement
To support StarRocks Catalog.
No
By E2E test
=> [#3302][Sub-Task] StarRocks catalog E2E test

.asf.yaml
Modify the collaborators
@Abyss-lord @unknowntpo have become committer. I removed them from collaborators
I added @bharos . @bharos focused on OAuth development work now. It will be convenient for him to become the collaborator. 
No.
No need.
=> [MINOR] Modify the collaborators

core/src/main/java/org/apache/gravitino/job/local/LocalJobExecutor.java, core/src/test/java/org/apache/gravitino/job/local/TestLocalJobExecutor.java
Increase the timeout in LocalJobExecutor test to increase the stability.
To fix the flaky test.
No.
Rerun test tests.
=> [MINOR] fix(core): Increase the timeout to fix the flaky test

docs/trino-connector/supported-catalog.md
Document the usage constraints for trino.bypass.* properties
Fix: #7906
No
No
=> [#7906] docs(trino-connector): Document the usage constraints for trino.bypass.* properties

common/src/main/java/org/apache/gravitino/dto/job/JobTemplateDTO.java, common/src/main/java/org/apache/gravitino/dto/job/ShellJobTemplateDTO.java, common/src/main/java/org/apache/gravitino/dto/job/SparkJobTemplateDTO.java, common/src/main/java/org/apache/gravitino/dto/requests/JobTemplateRegisterRequest.java, common/src/main/java/org/apache/gravitino/dto/responses/JobTemplateListResponse.java, common/src/main/java/org/apache/gravitino/dto/responses/JobTemplateResponse.java, common/src/main/java/org/apache/gravitino/dto/util/DTOConverters.java, common/src/test/java/org/apache/gravitino/dto/job/TestJobTemplateDTO.java, common/src/test/java/org/apache/gravitino/dto/requests/TestJobTemplateRegisterRequest.java, core/src/main/java/org/apache/gravitino/GravitinoEnv.java, core/src/main/java/org/apache/gravitino/job/JobManager.java, core/src/main/java/org/apache/gravitino/job/JobOperationDispatcher.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/JobMetaPostgreSQLProvider.java, server/src/main/java/org/apache/gravitino/server/GravitinoServer.java, server/src/main/java/org/apache/gravitino/server/web/rest/ExceptionHandlers.java, server/src/main/java/org/apache/gravitino/server/web/rest/JobOperations.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestJobOperations.java
Add the job template related REST APIs for job system.
related to #7758   
No.
UTs to cover the code.
=> [#7758] feat(server): Add REST API for job system (part-1)

docs/security/access-control.md
Add document for enabling metadata authorization.
Fix: #6837 
None
None
=> [#6837] docs(authz): Add document for enabling metadata authorization.

common/src/main/java/org/apache/gravitino/dto/job/JobDTO.java, common/src/main/java/org/apache/gravitino/dto/requests/JobRunRequest.java, common/src/main/java/org/apache/gravitino/dto/responses/JobListResponse.java, common/src/main/java/org/apache/gravitino/dto/responses/JobResponse.java, server/src/main/java/org/apache/gravitino/server/web/rest/ExceptionHandlers.java, server/src/main/java/org/apache/gravitino/server/web/rest/JobOperations.java, server/src/main/java/org/apache/gravitino/server/web/rest/OperationType.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestJobOperations.java
Add the job related rest interface for Gravitino.
Fix: #7758 
No.
Added UTs.
=> [#7758] feat(server): Add the REST interface for job system - part2

docs/iceberg-rest-service.md
1.  #7444  add `warehouse` parameter to get catalog configuration,  add the document to replace the `prefix`
2. polish Iceberg REST docker image version
no
just document
=> [MINOR] docs(iceberg): polish Iceberg rest server document

clients/client-python/gravitino/api/expressions/transforms/__init__.py, clients/client-python/gravitino/api/expressions/transforms/transform.py, clients/client-python/gravitino/api/expressions/transforms/transforms.py, clients/client-python/tests/unittests/rel/test_transforms.py
Support transforms expression by implementing the following Java classes:
- Transform.java
- Transforms.java
To support transforms expression.
Fix: #5732
No
Unit tests
=> [#5732] feat(client-python): Support transforms expression

clients/cli/src/main/java/org/apache/gravitino/cli/FullName.java
fix typo
see above
Fix: #N/A
No
N/A
=> [Minor] fix typo

api/src/main/java/org/apache/gravitino/policy/PolicyChange.java, common/src/main/java/org/apache/gravitino/dto/policy/PolicyContentDTO.java, common/src/main/java/org/apache/gravitino/dto/policy/PolicyDTO.java, common/src/main/java/org/apache/gravitino/dto/requests/PolicyCreateRequest.java, common/src/main/java/org/apache/gravitino/dto/requests/PolicySetRequest.java, common/src/main/java/org/apache/gravitino/dto/requests/PolicyUpdateRequest.java, common/src/main/java/org/apache/gravitino/dto/requests/PolicyUpdatesRequest.java, common/src/main/java/org/apache/gravitino/dto/responses/PolicyListResponse.java, common/src/main/java/org/apache/gravitino/dto/responses/PolicyResponse.java, common/src/main/java/org/apache/gravitino/dto/util/DTOConverters.java, common/src/test/java/org/apache/gravitino/dto/policy/TestPolicyDTO.java, common/src/test/java/org/apache/gravitino/dto/requests/TestPolicyCreateRequest.java, common/src/test/java/org/apache/gravitino/dto/requests/TestPolicyUpdatesRequest.java, core/src/main/java/org/apache/gravitino/policy/PolicyManager.java, core/src/test/java/org/apache/gravitino/policy/TestPolicyManager.java, server/src/main/java/org/apache/gravitino/server/GravitinoServer.java, server/src/main/java/org/apache/gravitino/server/web/rest/ExceptionHandlers.java, server/src/main/java/org/apache/gravitino/server/web/rest/FilesetOperations.java, server/src/main/java/org/apache/gravitino/server/web/rest/PolicyOperations.java, server/src/main/java/org/apache/gravitino/server/web/rest/TableOperations.java, server/src/main/java/org/apache/gravitino/server/web/rest/TagOperations.java, server/src/main/java/org/apache/gravitino/server/web/rest/TopicOperations.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestPolicyOperations.java
implement the policy management on server-side
Fix: #7145 
yes, RESTFul APIs added
tests addded
=> [#7145] feat(policy): implement the policy management on server-side (part-1)

CONTRIBUTING.md
Update and rearranged contributing information linking to other documents.
For help onboarding new users.
Fix: #N/A
No code changes are involved.
Locally.
=> improved contributing

core/src/main/java/org/apache/gravitino/job/local/LocalJobExecutor.java
Fix the race issue in `LocalJobExecutor`.
Fix the bug.
N/A
N/A
=> [MINOR] fix(core): Fix the race issue in `LocalJobExecutor`

docs/trino-connector/catalog-mysql.md, integration-test-common/docker-script/init/mysql/init.sql, trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-mysql/00011_column_properties.sql, trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-mysql/00011_column_properties.txt, trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/JdbcColumnDefaultValueConverter.java, trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/mysql/MySQLConnectorAdapter.java, trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/mysql/MySQLMetadataAdapter.java, trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/mysql/MySQLPropertyMeta.java, trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/mysql/MysqlColumnDefaultValueConverter.java, trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/metadata/GravitinoColumn.java, trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/metadata/GravitinoTable.java, trino-connector/trino-connector/src/test/java/org/apache/gravitino/trino/connector/metadata/TestGravitinoColumn.java
Support create MySQL table with default value and auto-increment
Fix: #7848
no
local tests
=> [#7848] feat(trino-connector): Support create table with column properties in MySQL

common/src/main/java/org/apache/gravitino/dto/rel/PartitionUtils.java, common/src/test/java/org/apache/gravitino/dto/rel/TestPartitionUtils.java
This PR adds an empty or null check for the fieldName array for validateFieldExistence function. 
Fix: #7975 
No
=> [#7975] improvement(validateFieldExistence): empty or null check for fieldName

docs/security/authorization-pushdown.md
Correct a link in the authorization doc.
=> fix(docs): fix a url link in the authorization doc.

docs/iceberg-rest-service.md, docs/lakehouse-iceberg-catalog.md
add document about using multi JDBC catalog backends 
Fix: #2687 
no
just document
=> [#2687] docs(iceberg): add document about using multi JDBC catalog backends

core/src/main/java/org/apache/gravitino/storage/relational/database/H2Database.java
change H2 connection mode to AUTO_SERVER
Fix: #8107 
no
local tested
=> [#8107] improvement(H2): change H2 connection mode to AUTO_SERVER

clients/client-java/src/main/java/org/apache/gravitino/client/DTOConverters.java, clients/client-java/src/main/java/org/apache/gravitino/client/ErrorHandlers.java, clients/client-java/src/main/java/org/apache/gravitino/client/GenericPolicy.java, clients/client-java/src/main/java/org/apache/gravitino/client/GenericTag.java, clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClient.java, clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoMetalake.java, clients/client-java/src/test/java/org/apache/gravitino/client/TestGenericPolicy.java, clients/client-java/src/test/java/org/apache/gravitino/client/TestGravitinoMetalake.java
java client supports policy operations (part-1)
Fix: #7146
yes, new feature for java client
tests added
=> [#7146] feat(policy): java client supports policy operations (part-1)

trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/iceberg/IcebergCatalogPropertyConverter.java
Trino connector support rest backend  for Iceberg catalog
Fix: #5514
Yes
Manually test
=> [#5514] feat (trino-connector) Support rest backend  for Iceberg catalog

core/src/main/java/org/apache/gravitino/job/JobExecutorFactory.java, core/src/test/java/org/apache/gravitino/storage/relational/service/TestJobMetaService.java, docs/index.md, docs/manage-jobs-in-gravitino.md, docs/open-api/jobs.yaml, docs/open-api/openapi.yaml
Add the usage document and openapi document for job system.
Fix: #7961 
No.
No need.
=> [#7961] feat(doc): Add the doc for job system

api/src/main/java/org/apache/gravitino/stats/Statistic.java, common/src/main/java/org/apache/gravitino/dto/requests/StatisticsDropRequest.java, common/src/main/java/org/apache/gravitino/dto/requests/StatisticsUpdateRequest.java, common/src/main/java/org/apache/gravitino/dto/responses/StatisticListResponse.java, common/src/main/java/org/apache/gravitino/dto/responses/StatisticsListResponse.java, common/src/main/java/org/apache/gravitino/dto/stats/StatisticDTO.java, common/src/main/java/org/apache/gravitino/dto/util/DTOConverters.java, common/src/test/java/org/apache/gravitino/dto/stats/TestStatisticDTO.java, core/src/main/java/org/apache/gravitino/stats/StatisticManager.java, server/src/main/java/org/apache/gravitino/server/GravitinoServer.java, server/src/main/java/org/apache/gravitino/server/web/rest/ExceptionHandlers.java, server/src/main/java/org/apache/gravitino/server/web/rest/OperationType.java, server/src/main/java/org/apache/gravitino/server/web/rest/StatisticOperations.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestStatisticOperations.java
Add table statistics REST API
Fix: #7271
No.
Add UT.
=> [#7271] feat(server): Add table statistics REST API

web/web/src/app/metalakes/metalake/rightContent/LinkVersionDialog.js
RT
N/A
Fix: #7350
N/A
manually
=> [#7350] fix(web): fix model version aliases issue

catalogs/catalog-fileset/src/main/java/org/apache/gravitino/catalog/fileset/FilesetCatalogOperations.java, catalogs/catalog-fileset/src/test/java/org/apache/gravitino/catalog/fileset/TestFilesetCatalogOperations.java
polish error message for fileset default location
Fix: #7266 
no
CI pass
=> [#7266] improvement(fileset): polish error message for fileset default location

web/integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/pages/CatalogsPage.java, web/web/src/app/metalakes/metalake/rightContent/tabsContent/tableView/TableView.js
=> [#2993] improvement(web): display default value for table columns

clients/client-java/src/main/java/org/apache/gravitino/client/DTOConverters.java, clients/client-java/src/test/java/org/apache/gravitino/client/TestGenericModelCatalog.java, common/src/main/java/org/apache/gravitino/dto/model/ModelVersionDTO.java, common/src/main/java/org/apache/gravitino/dto/requests/ModelVersionLinkRequest.java, common/src/main/java/org/apache/gravitino/dto/requests/ModelVersionUpdateRequest.java, common/src/main/java/org/apache/gravitino/dto/responses/ModelVersionUriResponse.java, common/src/main/java/org/apache/gravitino/dto/util/DTOConverters.java, common/src/test/java/org/apache/gravitino/dto/model/TestModelVersionDTO.java, common/src/test/java/org/apache/gravitino/dto/responses/TestResponses.java, docs/open-api/models.yaml, server/src/main/java/org/apache/gravitino/server/web/rest/ModelOperations.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestModelOperations.java
Implement REST APIs for model version with multiple URIs.
Fix: #7436 
Yes.
UTs.
=> [#7436] feat(model): Implement REST APIs for model version with multiple URIs

clients/client-python/gravitino/api/expressions/indexes/__init__.py, clients/client-python/gravitino/api/expressions/indexes/index.py, clients/client-python/gravitino/api/expressions/indexes/indexes.py, clients/client-python/tests/unittests/rel/test_indexes.py
This PR is aimed at implementing the following classes corresponding to the Java client.
- `Index` in Index.java
- `Indexes` in Indexes.java
We need to support table partitioning, bucketing and sort ordering and indexes
#5199
No
Unit tests
=> [#5199] feat(client-python): add index and indexes

authorizations/authorization-common/src/main/java/org/apache/gravitino/authorization/common/PathBasedMetadataObject.java, authorizations/authorization-common/src/test/java/org/apache/gravitino/authorization/common/TestPathBasedMetadataObject.java
…Object
update equality check to primitive in PathBasedMetaDataObject from Object.equals to ==
Fix: #8197 
Unit testing
=> [#8197]Improvement: update equality check to primitive in PathBasedMetaDataObject

web/web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js, web/web/src/lib/utils/initial.js
RT
N/A
Fix: #8150
N/A
manually
=> [#8150] fix(web): support warehouse config for iceberberg catalog which catalog-backend is rest

dev/docker/gravitino/gravitino-dependency.sh, dev/docker/iceberg-rest-server/iceberg-rest-server-dependency.sh, docs/iceberg-rest-service.md, docs/lakehouse-iceberg-catalog.md, iceberg/iceberg-rest-server/build.gradle.kts, trino-connector/integration-test/trino-test-tools/download_jar.sh
upgrade iceberg version in document and docker image bundle jars 
Fix: #8153
no
testing s3,aws,azure,oss with Iceberg docker image locally.
=> [#8153] feat(iceberg): upgrade iceberg version in document and docker image bundle jars

server/src/main/java/org/apache/gravitino/server/web/rest/GroupOperations.java, server/src/main/java/org/apache/gravitino/server/web/rest/UserOperations.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestGroupOperations.java, server/src/test/java/org/apache/gravitino/server/web/rest/TestUserOperations.java
Add check when deleting users or groups to avoid orphan metalake
Fix: #7938
No.
Added UT.
=> [#7938] improvement: Add check when deleting users or groups to avoid orphan metalake

catalogs/catalog-hive/src/main/java/org/apache/gravitino/catalog/hive/HiveCatalogOperations.java, catalogs/catalog-hive/src/test/java/org/apache/gravitino/catalog/hive/TestHiveTable.java, catalogs/hive-metastore-common/src/main/java/org/apache/gravitino/hive/converter/HiveDataTypeConverter.java, docs/apache-hive-catalog.md
add validation for Hive struct data type
Fix: #4874 
no
tests added
=> [#4874] improvement(hive): add validation for Hive struct data type

.github/workflows/docker-image.yml, dev/docker/build-docker.sh, dev/docker/mcp-server/Dockerfile, dev/docker/mcp-server/mcp-server-dependency.sh, dev/docker/mcp-server/start-mcp-server.sh, docs/docker-image-details.md, docs/gravitino-mcp-server.md, docs/index.md
Add docker support for MCP server
Fix: #8112 
no
build local docker image and test with Cursor
=> [#8112] feat(mcp): Support Gravitino MCP server docker image

core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/FilesetVersionPostgreSQLProvider.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/PolicyVersionPostgreSQLProvider.java
fix Postgresql SQL syntax error
Fix: #8307
no
local tested
=> [#8307] fix(backend): fix Postgresql SQL syntax error

clients/cli/src/main/java/org/apache/gravitino/cli/commands/CreateCatalog.java
=> [Imp] Exit with correct error message in CreateCatalog.java 

server/src/main/java/org/apache/gravitino/server/web/rest/PolicyOperations.java
Fixed handlePolicyException paramaters in PolicyOperations.java
improvement for handlePolicyException
Fix: #8281 
No
Unit test
=> [#8281]Improvement(PolicyOperation): handle policy exception parameters

GETTING_STARTED.md, build.gradle.kts
Added a simple getting started to help newcomers.
Hopefully, this will help people and reduce and help improve first time contribitors.
Fix: #N/A
No
Locally
=> Added a simple getting started to help newcomers

docs/cli.md, docs/manage-model-metadata-using-gravitino.md, docs/model-catalog.md, docs/open-api/openapi.yaml
Update docs for usage of model version with multiple URIs.
Fix: #7439 
No.
No need.
=> [#7439] minor(doc): Update docs for usage of model version with multiple URIs

.github/workflows/auto-cherry-pick.yml
Add github action to auto cherry-pick commit to branch-1.0
Prepare for 1.0.0 release
No.
No.
=> [MINOR] Add github action to auto-cherrypick to branch-1.0

dev/release/release-tag.sh, mcp-server/pyproject.toml
Fix the release script to correctly update the version number. Also correct mcp module version number.
To release the Gravitino correctly.
No.
CI.
=> [MINOR] fix(release): Fix the release script issue

catalogs/catalog-jdbc-postgresql/src/main/java/org/apache/gravitino/catalog/postgresql/operation/PostgreSqlSchemaOperations.java
In PostgreSqlSchemaOperations.java fix potential resource leak 
Fix: #([8482](https://github.com/apache/gravitino/issues/8482))
N/A
N/A
=> [#8482] Improvement(catalog): In PostgreSqlSchemaOperations.java fix potential resource leak 

core/src/main/java/org/apache/gravitino/metrics/MetricNames.java, core/src/main/java/org/apache/gravitino/metrics/MetricsSystem.java, core/src/main/java/org/apache/gravitino/metrics/source/MetricsSource.java, core/src/main/java/org/apache/gravitino/metrics/source/RelationDatasourceMetricsSource.java, core/src/main/java/org/apache/gravitino/storage/relational/session/SqlSessionFactoryHelper.java, core/src/test/java/org/apache/gravitino/metrics/TestExtractMetricNameAndLabel.java, core/src/test/java/org/apache/gravitino/metrics/TestMetricsSystem.java
fix missing backend connection pool metrics 
Fix: #8558 
no
CI pass
=> [#8558] fix(metrics): fix missing backend connection pool metrics 

dev/charts/gravitino/Chart.yaml, dev/charts/gravitino/values.yaml
1. Change MySQL repository to bitnamilegacy
2. Verify Kubenetes 1.28 support
Fix: #8597
N/A
Chart testing CI
=> [#8597] Fix image not found

docs/gravitino-mcp-server.md, mcp-server/mcp_server/core/context.py, mcp-server/mcp_server/core/setting.py, mcp-server/mcp_server/main.py, mcp-server/uv.lock
1. Polish how to start mcp server by docker
2. change `--uri` to `--gravitino-uri`
make it more user friendly.
no
just document
=> [MINOR] docs(mcp): polish MCP server document

LICENSE.bin, core/build.gradle.kts, core/src/main/java/org/apache/gravitino/metrics/MethodMonitorAspect.java, core/src/main/java/org/apache/gravitino/metrics/MetricsSystem.java, core/src/main/java/org/apache/gravitino/metrics/Monitored.java, core/src/main/java/org/apache/gravitino/metrics/source/MetricsSource.java, core/src/main/java/org/apache/gravitino/storage/relational/service/CatalogMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/CommonMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/FilesetMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/GroupMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/JobMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/JobTemplateMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/MetadataObjectService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/MetalakeMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/ModelMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/ModelVersionMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/OwnerMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/PolicyMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/SchemaMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/StatisticMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/TableColumnMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/TableMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/TagMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/TopicMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/UserMetaService.java, gradle/libs.versions.toml
- introduce aspectj for metric annotation
- add metrics for backend meta service
Fix: #8596 
local tested:
=> [#8596] improvement(metrics): add metrics for backend meta service

catalogs/catalog-fileset/build.gradle.kts, catalogs/catalog-fileset/src/main/java/org/apache/gravitino/catalog/fileset/FilesetCatalogOperations.java, core/src/main/java/org/apache/gravitino/metrics/GravitinoSampleBuilder.java, core/src/main/java/org/apache/gravitino/metrics/MetricNames.java, core/src/main/java/org/apache/gravitino/metrics/MetricsSystem.java, core/src/main/java/org/apache/gravitino/metrics/source/CatalogMetricsSource.java, core/src/main/java/org/apache/gravitino/metrics/source/FilesetCatalogMetricsSource.java, core/src/main/java/org/apache/gravitino/metrics/source/MetricsSource.java, core/src/test/java/org/apache/gravitino/metrics/TestGravitinoSampleBuilder.java, docs/metrics.md, gradle/libs.versions.toml
- add a catalog metric name specification: 
- add metrics for fileset catalog
Fix: #8595
no
test added
=> [#8595] improvement(metrics): add metrics for fileset catalog

api/src/main/java/org/apache/gravitino/job/SparkJobTemplate.java, common/src/main/java/org/apache/gravitino/dto/job/SparkJobTemplateDTO.java, common/src/test/java/org/apache/gravitino/dto/job/TestJobTemplateDTO.java, core/src/main/java/org/apache/gravitino/job/local/LocalJobExecutorConfigs.java, core/src/main/java/org/apache/gravitino/job/local/LocalProcessBuilder.java, core/src/main/java/org/apache/gravitino/job/local/ShellProcessBuilder.java, core/src/main/java/org/apache/gravitino/job/local/SparkProcessBuilder.java, core/src/test/java/org/apache/gravitino/job/local/TestSparkProcessBuilder.java, docs/manage-jobs-in-gravitino.md
This PR adds the Spark process builder for local job executor, so users can run the Spark jobs in the local environment.
This is a part of the work of the job system
Fix: #7962
No.
UT and local tests.
=> [#7962]feat(core): Add spark process builder support for local job executor

docs/open-api/statistics.yaml
Fix the statistics list response
Just a minor.
No.
By hand.
=> [MINOR] fix(docs): Fix the statistics list response

catalogs/catalog-kafka/src/main/java/org/apache/gravitino/catalog/kafka/KafkaCatalogOperations.java
make topic creation synchronous
Fix: #4168
no
CI pass
=> [#4168] fix(kafka-catalog): make topic creation synchronous
