apache/gravitino

docs/apache-hive-catalog.md, docs/getting-started.md, docs/gravitino-server-config.md, docs/how-to-install.md, docs/how-to-test.md, docs/iceberg-rest-service.md, docs/index.md, docs/jdbc-mysql-catalog.md, docs/jdbc-postgresql-catalog.md, docs/lakehouse-iceberg-catalog.md, docs/manage-metadata-using-gravitino.md, docs/publish-docker-images.md, docs/security.md, docs/trino-connector/catalog-hive.md, docs/trino-connector/catalog-iceberg.md, docs/trino-connector/catalog-mysql.md, docs/trino-connector/catalog-postgresql.md, docs/trino-connector/index.md, docs/trino-connector/installation.md, docs/trino-connector/supported-catalog.md, docs/trino-connector/trino-connector.md
Add the `md` suffix for every link in the markdown
Fix: #1136
No
Tested in Docunausars and markdown locally.
=> [#1136] improvement(docs): Add the `md` suffix for every link in the markdown

CONTRIBUTING.md
Update `./gradlew spotlessApply` of Coding standards in `Contributing.md`.
There is no `grawdlew` file in project, which cause that developer could not follow coding standards.
No.
No.
=> [MINOR] fix(docs): fix ./gradlew spotlessApply of Coding standards

common/src/main/java/com/datastrato/gravitino/json/JsonUtils.java, common/src/test/java/com/datastrato/gravitino/dto/requests/TestTableUpdatesRequest.java
Position name supports upper-case when add a column for `FIRST` and `DEFAULT`.
Position name should support upper-case when add a column. For example, the correct value of position is first NOT FIRST currently.
```
curl -X PUT -H "Accept: application/vnd.gravitino.v1+json" -H "Content-Type: application/json" -d '{
"updates": [
{
"@type": "removeProperty",
"property": "key2"
}, {
"@type": "setProperty",
"property": "key3",
"value": "value3"
},
{
"@type": "addColumn",
"fieldName": [
"position"
],
"type": "varchar(20)",
"comment": "Position of user",
"position": "FIRST"
} 
]
}' http://localhost:8090/api/metalakes/metalake/catalogs/catalog/schemas/schema/tables/table
```
```
Unknown json column position: "FIRST" (through reference chain: …
```
=> [#1052] fix(common): position name should support upper-case when add a column

integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/lakehouse/iceberg/IcebergRESTHiveCatalogIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/lakehouse/iceberg/IcebergRESTJdbcCatalogIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/lakehouse/iceberg/IcebergRESTServiceBaseIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/lakehouse/iceberg/IcebergRESTServiceIT.java
1.  make getCatalogConfig abstract, Hive&Jdbc&Memory implement these interfaces.
2. remove `gravitino-docker-it` tag from IcebergRESTServiceIT.
After #711,  It takes too much time to test IcebergRESTServiceIT, there's no need to start the docker container for the memory catalog
Fix: #874 
no
existing UT
=> [#874]  refactor(lakehouse-iceberg) improve IcebergRESTServiceIT

docs/how-to-test.md, docs/iceberg-rest-service.md, docs/index.md
- Fix typo `Graviton` in `index.md` 
- Fix link mistakes in `index.md` and other sentence problems
To Improve the professionalism and rigor of documents 
Fixed #1166 
N/A.
N/A.
=> [#1166] fix(docs): Fix typos `graviton` and syntax problems in docs

web/build.gradle.kts
Optimize clean task of `build.gradle.kts` for web to delete `node_modules` folder which reduces space after gradle clean.
The `node_modules` folder contains libraries downloaded from npm that takes up a lot of space.
Fix: #877
No.
Test with gradle clean.
=> [#877] improvement(web): optimize clean task of build.gradle.kts for web to delete node_modules folder

common/src/main/java/com/datastrato/gravitino/dto/MetalakeDTO.java, core/src/main/java/com/datastrato/gravitino/StringIdentifier.java, core/src/main/java/com/datastrato/gravitino/meta/BaseMetalake.java, core/src/main/java/com/datastrato/gravitino/meta/MetalakeManager.java, core/src/main/java/com/datastrato/gravitino/storage/kv/KvGarbageCollector.java, core/src/test/java/com/datastrato/gravitino/meta/TestMetalakeManager.java, trino-connector/build.gradle.kts
Remove the `stringId` from metalake property map. 
`gravitino.identifier` is generated internally and should not be visible to users.  
Fix: #1047 
N/A
Existing UTs can cover it.
=> [#1047] improvement(core): Fix the issue of StringIdentifier in metalake property

catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlTableOperations.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/TestPostgreSqlTableOperations.java
Fix a bug where the same table name can be loaded under multiple schemas
Fix: #1171 
NO
UT
=> [#1171] bugfix(postgresql): Fix bug where the same table name can be loaded under multiple schemas.

core/src/test/java/com/datastrato/gravitino/catalog/TestCatalogManager.java, core/src/test/java/com/datastrato/gravitino/storage/kv/TestEntityKeyEncoding.java, core/src/test/java/com/datastrato/gravitino/storage/kv/TestKvNameMappingService.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/hive/CatalogHiveIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/CatalogMysqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/lakehouse/iceberg/CatalogIcebergIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/container/TrinoContainer.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java
Remove Junit5 annotation `Order` in test.
We need to remove sequence dependencies between test cases so that we can run them in parallelism. 
Fix: #995 
N/A
Only changes to the test code have been made.
=> [#995] improvement(test): Remove annotation Order to alleviate test sequence dependency

docs/security.md, server-common/src/main/java/com/datastrato/gravitino/server/auth/AuthenticationFilter.java
Modify the required value for the document `security.md`.
I modify some document mistakes by the way.
According the review https://github.com/datastrato/gravitino/pull/1191#discussion_r1431374330 , modify the required value. If a config option has a default value, this config option is not required.
No.
No need.
=> [MINOR] fix(docs): Modify the required value for the document `security.md`

docs/manage-metadata-using-gravitino.md
Fix a low-level error in the document `manage-metadata-using-gravitino`
Just fix error. 
N/A
N/A
=> [MINOR] fix(doc): Fix a JSON format error in doc manage-metadata-using-gravitino.md

dev/docker/tools/docker-connector.conf, integration-test/build.gradle.kts, integration-test/src/test/java/com/datastrato/gravitino/integration/test/container/BaseContainer.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/container/NetworksConflictTest.java
1. Added Docker network overlap detection
2. Reduced IP allocation ranges for lower conflict probability, Modified to `10.20.30.0/28` only allocate IP ranger `10.20.30.1` ~ `10.20.30.14`
3. Docker network only created on MacOS and default Docker server environment
Fix: #879, #925
N/A
CI
=> [#879][#925] Docker network Pool overlaps with other one on this address space

docs/how-to-use-the-playground.md
Modify the document according to the pr https://github.com/datastrato/gravitino-playground/pull/8
I will submit another pr to modify the document of website.
We should keep consistent.
No.
No.
=> [MINOR] fix(docs): Modify the document according to the README of playground

catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/operation/MysqlDatabaseOperations.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/TestJdbcAbstractIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/CatalogMysqlIT.java
- Allow dropping a database when `cascase` is `true`.
- If the database is not empty and `cascade` is `false`, disable the drop operation. 
Align the logic with Gravitino EntityStore.
Fix: #1231 
N/A
Add UT `testDropMySQLDatabase`
=> [#1231] Fix bugs in drop MySQL schemas

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcCatalogOperations.java, core/src/main/java/com/datastrato/gravitino/StringIdentifier.java, core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java, core/src/main/java/com/datastrato/gravitino/catalog/CatalogOperationDispatcher.java, core/src/main/java/com/datastrato/gravitino/meta/BaseMetalake.java, core/src/main/java/com/datastrato/gravitino/meta/MetalakeManager.java, core/src/test/java/com/datastrato/gravitino/TestStringIdentifier.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/CatalogMysqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlIT.java
Mysql&Postgres catalog store empty audit info fix.
Fix: #1253 
Users will receive audit information
IT
=> [#1253] bugfix(jdbc): fix jdbc catalog store empty audit info issue

docs/how-to-use-the-playground.md
In general, it is better to use more realistic data and don't use generic names ending in numbers. The SQL also needs to match the amount of data we have in the playground.
To provide a slightly more realistic example and make SQL easier to understand.
Fix: # N/A
N/A
Ran commands locally to test.
=> [Minor] Improve English, use better names and data, simplify SQL

catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergConfig.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergRESTService.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/web/IcebergObjectMapper.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/web/IcebergObjectMapperProvider.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/web/IcebergRestUtils.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/web/metrics/BlackHoleMetricsStore.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/web/metrics/DummyMetricsStore.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/web/metrics/IcebergMetricsFormatter.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/web/metrics/IcebergMetricsManager.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/web/metrics/IcebergMetricsStore.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/web/rest/IcebergTableOperations.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/web/metrics/MemoryMetricsStore.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/web/metrics/TestIcebergMetricsManager.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/web/rest/IcebergRestTestUtil.java
1. introduce `MetricsManager` to manage storages
2. introduce `IcebergMetricsFormatter` to format metrics, support JSON for now.
Fix: #1187
no
1. local env
=> [#1187] feat(lakehouse-iceberg): the basic framework of storing Iceberg metrics 

integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/hive/CatalogHiveIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/CatalogMysqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/lakehouse/iceberg/CatalogIcebergIT.java
Remove the usage of DTOs of partitioning, sort ordering and bucketing. 
We should not use DTOs when using Gravition java client. 
Fix: #1293 
N/A
Existing changes can cover it.
=> [#1293] improvement(IT): Change to use api method instead of DTOs

web/lib/layout/Footer.js
Fix the copyright year to be the year of the last release, not the current year.
The copyright year should not automatically update to the current year.
Fix: #1299
N/A
Built and tested locally in a browser.
=> [#1299] Fix the copyright year

dev/docker/tools/mac-docker-connector.sh
`mac-docker-connector.sh` uses `curl` instead of `wget` to download `docker-connector-darwin.tar.gz` for MacOS.
`curl` is installed by default and `wget` is not installed for MacOS. Therefore it's recommended to use `curl` instead of `wget` to download `docker-connector-darwin.tar.gz` for `mac-docker-connector.sh`.
Fix: #1306 
No.
Local test.
=> [#1306] improvement(dev): mac-docker-connector.sh uses curl instead of wget to download docker-connector-darwin.tar.gz

dev/docker/trino/conf/node.properties
Trino loss `node.id` configuration in the `node.properties` file.
```
root@ip-172-31-6-157:/# /usr/lib/trino/bin/run-trino
+ launcher_opts=(--etc-dir /etc/trino)
+ grep -s -q node.id /etc/trino/node.properties
+ launcher_opts+=("-Dnode.id=${HOSTNAME}")
+ exec /usr/lib/trino/bin/launcher run --etc-dir /etc/trino -Dnode.id=ip-172-31-6-157.ec2.internal
OpenJDK 64-Bit Server VM warning: Option UseBiasedLocking was deprecated in version 15.0 and will likely be removed in a future release.
Jan 02, 2024 2:33:42 PM io.airlift.log.Logger info
INFO: Java version: 17.0.8.1
2024-01-02T14:33:42.382Z	INFO	main	io.airlift.log.Logging	Logging to stderr
2024-01-02T14:33:42.383Z	INFO	main	Bootstrap	Loading configuration
2024-01-02T14:33:42.645Z	INFO	main	org.hibernate.validator.internal.util.Version …
```
=> [#1311] bugfix(docker): Unable to run datastrato/trino Docker in AWS

README.md, docs/apache-hive-catalog.md, docs/docker-image-details.md, docs/getting-started.md, docs/gravitino-server-config.md, docs/how-to-build.md, docs/how-to-install.md, docs/how-to-sign-releases.md, docs/how-to-test.md, docs/how-to-use-the-playground.md, docs/iceberg-rest-service.md, docs/index.md, docs/jdbc-mysql-catalog.md, docs/jdbc-postgresql-catalog.md, docs/lakehouse-iceberg-catalog.md, docs/manage-metadata-using-gravitino.md, docs/metrics.md, docs/overview.md, docs/publish-docker-images.md, docs/security.md, docs/table-partitioning-bucketing-sort-order.md, docs/webui.md
Fix minor grammar errors and English mistakes in documentation.
For clarity.
Fix: # N/A
N/A
Built locally.
=> Fix minor grammar errors and English mistakes in documentation.

web/app/(home)/MetalakeList.js, web/app/(home)/TableHeader.js
Fix the issue with the status cache after modifying Metalake.
1. rename a metalake
2. click `create metalake` button
It should be `create dialog`, but displays `update dialog`.
when click `create metalake` button, correctly display `create dialog`.
Fix: #1151 
N/A
N/A
=> [#1151] fix(UI): Fix status cache after modified a Metalake

web/app/metalakes/DetailsView.js, web/app/metalakes/TabsContent.js
Add `type` and `provider` properties in catalog details.
The current properties only shows in `details`. To display it in a tree list, advanced REST API support is required.
Fix: #1114 
N/A
N/A
=> [#1114] improve(UI): Add `type` and `provider` properties in catalog details

web/app/metalakes/DetailsView.js, web/app/metalakes/MetalakeView.js, web/lib/layout/Layout.js, web/lib/provider/client.js, web/lib/provider/index.js
The error occurred due to the failure to locate the correct variable object and its properties.
Resolve: use an empty string as a substitute.
Extra:
1. Initialize and reset the tree list when the metalake page is loaded.
2. Improve rendering of components check.
Fix: #1150 
N/A
N/A
=> [#1150] fix(UI): Fix details comment error and improve components check

.github/workflows/auto-cherry-pick.yml
Based on the document of [`github-cherry-pick-action`](https://github.com/marketplace/actions/github-cherry-pick-action#action-inputs), add token input to change the default token that the auto-cherry-pick workflow used.
> [!WARNING]  
> Need to add a PAT to the organization with the name `BOT_TOKEN`.
Automatically trigger CI for auto-cherry-pick workflow with a customized token, instead of the default `GITHUB_TOKEN`, which is prohibited from triggering another workflow.
Fix: #1282 
No user-facing change, but we should add a PAT to the organization with the name `BOT_TOKEN`.
N/A
=> [#1282] bugfix(CI) Automatically trigger CI for auto-cherry-pick workflow

integration-test/build.gradle.kts, integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java
Fix the failed 'drop catalog' test on Trino image gravitino-ci-trino:0.1.3.
Trino image gravitino-ci-trino:0.1.2 use the gravitino-trino-connector-0.3.0-SNAPSHOT.jar, it does not support drop catalog, so the  tester has made it compatible with this.
Trino image gravitino-ci-trino:0.1.3 use the gravitino-trino-connector-0.4.0-SNAPSHOT.jar, it support drop catalog. 
the test did not pass. 
Fix: #1328
NO
NO
=> [#1328] fix(trino-connector): Fix the failed 'drop catalog' test on Trino image gravitino-ci-trino:0.1.3.

dev/docker/build-docker.sh, dev/docker/trino/Dockerfile, docs/docker-image-details.md
Remove the Gravitino connector from the Trino CI image.
In CI, we will mount the Gravitino connector to the Trino CI image to test the latest code base, so we can fully test our PR. 
Fix: #1295
N/A
N/A
=> [#1295] improvement(CI): separate trino image for CI and users

api/src/main/java/com/datastrato/gravitino/rel/Column.java, api/src/main/java/com/datastrato/gravitino/rel/types/Types.java, api/src/test/java/com/datastrato/gravitino/rel/TestTransforms.java, common/src/main/java/com/datastrato/gravitino/dto/rel/ColumnDTO.java, common/src/main/java/com/datastrato/gravitino/dto/requests/TableCreateRequest.java, common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java, common/src/test/java/com/datastrato/gravitino/json/TestDTOJsonSerDe.java, core/src/main/java/com/datastrato/gravitino/catalog/rel/BaseColumn.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestTableOperations.java
Add column attribute autoIncrement of the increment interface.
Fix: #1277
UT
=> [#1277] feat(API): Add column attribute autoIncrement of the increment interface.

build.gradle.kts
Add RAT support for 2024 copyright header.
Otherwise, RAT check will fail.
Fix: #1369
N/A
=>  [#1369] Add RAT support for 2024 copyright header

integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/hive/HiveDataTypeTransformer.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/iceberg/IcebergDataTypeTransformer.java
1. Suppoort type 'Fixed' in Trino connector `GeneralDataTypeTransformer`
Fixed type is needed by Iceberg type.
Fix: #1317 
N/A
IT.
=> [#1317] fix(trino-connector): Support Fixed type conversion

web/app/metalakes/MetalakeView.js, web/lib/store/metalakes/index.js
Rectify the issue of null being included in the requests.
Fix: #1001
N/A
N/A
=> [#1001] fix(UI): Fix null requests in the web UI

web/app/metalakes/CreateCatalogDialog.js
Fix fields validation when create a catalog in the web UI.
Currently, after clicking submit, it will verify correctly based on the `provider` and specific `properties`.
Fix: #1350 
N/A
N/A
=> [#1350] fix(UI): Fix fields validation when create a catalog in the web UI

api/src/main/java/com/datastrato/gravitino/rel/expressions/Literal.java, api/src/main/java/com/datastrato/gravitino/rel/expressions/literals/Literal.java, api/src/main/java/com/datastrato/gravitino/rel/expressions/literals/Literals.java, api/src/main/java/com/datastrato/gravitino/rel/expressions/transforms/Transforms.java, api/src/test/java/com/datastrato/gravitino/rel/TestTransforms.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/ToIcebergSortOrder.java, common/src/main/java/com/datastrato/gravitino/dto/rel/expressions/LiteralDTO.java, common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java
- Add a Literals class for managing the Literal helper methods
- Make the old `Literal` API deprecated
Fix: #1380 
Yes, make the old `Literal` API deprecated
existing tests
=> [#1380] Add Literals class for managing the Literal helper methods

web/app/metalakes/CreateCatalogDialog.js
Fix cache values in the dialog when create a catalog.
Fix: #1273
N/A
N/A
=> [#1273] fix(UI): Fix cache values in the dialog when create a catalog

web/app/(home)/CreateMetalakeDialog.js, web/app/metalakes/CreateCatalogDialog.js
Fix update metalake error in the web UI.
The reason for the error is that the existing metalake is not set with `properties`, causing an error unable to find properties when deconstructing the `properties` of metalake.
The solution is to set an empty object to the `properties`.
1. existed metalake without `properties`
2. click `update metalake` icon button, and now the update pop-up will display correctly.
Fix: #1391
Fix: #1397
N/A
N/A
=> [#1391] fix(UI): Fix update metalake error in the web UI

web/app/metalakes/CreateCatalogDialog.js, web/lib/provider/session.js, web/lib/utils/axios/index.ts
Fix submitted the unnecessary fields when create a catalog.
if `provider` is `iceberg`, and `catalog-backend` is `hive`, the properties payload should not includes `jdbc-*`
1. request payload
2. response data
Fix: #1403
N/A
N/A
=> [#1403] fix(UI): Remove unnecessary fields when creating a catalog in the web UI

api/src/main/java/com/datastrato/gravitino/rel/expressions/literals/Literals.java, api/src/test/java/com/datastrato/gravitino/rel/TestLiteral.java
Add more static methods of Literal for Java client usage
Fix: #1383 
no, but users can use `Literal` more conveniently by Java client
UTs added
=> [#1383] Add more static methods of Literal for Java client usage

bin/common.sh
Print warning message instead of failing the bootstrap when using Java prior 8u151
Fix: #1405
Yes, users who want to use Java prior 8u151 to bootstrap Gravitino just get an warning message instead of failing.
Manually review
=> [#1405] Print warning message instead of failing the bootstrap when using Java prior 8u151

web/app/(home)/CreateMetalakeDialog.js, web/app/metalakes/CreateCatalogDialog.js
Filtering empty keys when operating create or update.
After adding an empty key, the API will prompt an error message, so we need to prevent this from happening at the frontend level.
Fix: #1428 
N/A
N/A
=> [#1428] improvement(UI): Filtering empty keys when create or update

api/src/main/java/com/datastrato/gravitino/rel/expressions/literals/Literals.java, api/src/main/java/com/datastrato/gravitino/rel/types/Type.java, api/src/main/java/com/datastrato/gravitino/rel/types/Types.java, api/src/test/java/com/datastrato/gravitino/rel/TestLiteral.java, api/src/test/java/com/datastrato/gravitino/rel/TestTypes.java
Add `NullType` for representing NULL values
Fix: #1384 
yes, users now can use null literal
UTs added
=> [#1384] feat(api): Add `NullType` for representing NULL values

LICENSE, gradlew
Update the `./gradlew` to extract the Gradle version and calculate the tag to download the exact version of `gradle-wrapper.jar`
Fix: #1401
No. It's devs only
Manually test, and pass GA.
With this patch, performing `./gradlew` command will download the exact version declared in `gradle/wrapper/gradle-wrapper.properties`
```
➜  gravitino git:(1401) ./gradlew clean
download https://raw.githubusercontent.com/gradle/gradle/v8.2.0/gradle/wrapper/gradle-wrapper.jar
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100 63375  100 63375    0     0  95041      0 --:--:-- --:--:-- --:--:-- 95014
```
=> [#1401] chore: Download the exact version of `gradle-wrapper.jar`

CONTRIBUTING.md
**What changes were proposed in this pull request?**
Fix #1422 
Change the link for [how to build] and [how to test], add the `.md` ending , and let the link be complete.
**Why are the changes needed?**
The original link was not complete, so when we click the link, it jumped to an error page in Github.
**Does this PR introduce any user-facing change?**
N/A
**How was this patch tested?**
N/A
=> [#1422] fix(doc): Update the CONTRIBUTING.MD to fix the link error

dev/docker/hive/hive-site.xml, docs/docker-image-details.md
Enable Impersonation of Hive Docker image.
Fix: #1447
No.
By hand. I ever builded a local image to test it.
=> [#1447] improvement: Enable impersonation of Hive Docker image

web/app/(home)/CreateMetalakeDialog.js, web/app/(home)/MetalakeList.js
Reword Metalakes Actions button list `Details`, `Update`, `Delete` to `Details`, `Edit`, `Delete` as per #1396  mentioned.
Fix #1396 
Yes, web UI changed
=> [#1396] improvement(UI): Reword update to edit

clients/client-java/src/test/java/com/datastrato/gravitino/client/TestHTTPClient.java
fix TestHTTPClient crash when port 1080 is using by another process.
Fix: #1474 
No.
No need.
=> [#1474] improvement(tests): Fix TestHTTPClient crashed for port conflict

catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogOperations.java, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveTable.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/ErrorHandlers.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalCatalog.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalCatalog.java, common/src/main/java/com/datastrato/gravitino/dto/responses/ErrorConstants.java, common/src/main/java/com/datastrato/gravitino/dto/responses/ErrorResponse.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/hive/CatalogHiveIT.java, server/src/main/java/com/datastrato/gravitino/server/web/Utils.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/ExceptionHandlers.java, server/src/test/java/com/datastrato/gravitino/server/web/TestUtils.java
fix  #1390  
- no
- Check whether a hive table is external when purge table
Fix: #1390 
- no
- added unit tests
=> [#1390]improvement(hive):Check whether a hive table is external when purge table

.github/workflows/build.yml
Modify the pipeline check logic in regards to code changes
Fix: #1079 
No.
Tested by own repo. https://github.com/qqqttt123/gravitino/pull/3
=> [#1079] improvement(CI): Modify the pipeline check logic in regards to code changes

api/src/main/java/com/datastrato/gravitino/rel/Column.java, api/src/test/java/com/datastrato/gravitino/rel/TestTransforms.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcColumn.java, catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/operation/SqliteTableOperations.java, catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/operation/TestJdbcTableOperations.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/operation/MysqlTableOperations.java, catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlTableOperations.java, common/src/main/java/com/datastrato/gravitino/dto/rel/ColumnDTO.java, core/src/main/java/com/datastrato/gravitino/catalog/rel/BaseColumn.java, core/src/test/java/com/datastrato/gravitino/TestColumn.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/TestJdbcAbstractIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/TestMysqlTableOperations.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/TestPostgreSqlTableOperations.java
- add `defaultValue()` in Column API
- remove the duplicate methods from the subclass.
Fix: #1392 
no
There is no specific implementation, so testing is not required.
=> [#1392] feat(api): add `defaultValue()` in Column API

web/app/(home)/DetailsDrawer.js, web/app/metalakes/DetailsView.js
Resolve the issue with the newline character in the comment field.
Fix: #1497
N/A
N/A
=> [#1497] fix(UI): Fix newline character in the `comment` field

build.gradle.kts
Change the build script to avoid generating build directory in project `catalogs` and `clients`
Make the project more formal and well designed.  
Fix: #1507 
N/A.
Test locally. after build
=> [#1507] improvement(clients, catalogs): Remove unnecessary build directory of project `catalogs` and `clients`

web/components/ConfirmDeleteDialog.js
Updated button name from 'Submit' to 'Delete'
To make the button look more specific to it's task.
Fix: #1486 
No
=> [#1486] fix: button text update

web/app/metalakes/LeftContent.js, web/app/metalakes/MetalakePath.js, web/app/metalakes/MetalakeTree.js, web/app/metalakes/TableView.js, web/components/ColumnTypeChip.js, web/lib/enums/columnTypeEnum.ts
Fix the tree view icon and add column type chip styles.
Fix: #1492
N/A
N/A
=> [#1492] fix(UI): Fix tree view icon and add column type chip styles

docs/how-to-use-the-playground.md
Add a table of TCP ports used by the playground docker containers.
Make it clearer to users that they might have issues if running local services on those ports.
Fix: # N/A
No
Build locally.
=> [Minor] Mention TCP port used by the playground docker containers

web/app/(home)/MetalakeList.js
Before:
After:
Fix: #1585
N/A
N/A
=> [#1585] improvement(UI): use browser title instead of tooltip of icon button

catalogs/catalog-jdbc-mysql/src/main/resources/jdbc-mysql.conf, catalogs/catalog-jdbc-postgresql/src/main/resources/jdbc-postgresql.conf
Change the connector between the key and value in the configuration file to an equal sign.
Fix: #1515
NO
NO
=> [#1515] fix(jdbc): The format of jdbc-mysql.conf and jdbc-postgresql.conf is not correct.

web/components/ColumnTypeChip.js
Add default type color for the tag in table.
For example, when the type is not found in the enums and it's a `string`, this tag is default gray.
Fix: #1540 
N/A
N/A
=> [#1540] fix(UI): Add default type color for the tag in table

web/WEB-INF/web.xml
When you refresh a Gravitino web page, It leads to a 404 error page.
We configured the `DefaultServlet` to handle the URL mapping. 
First, we mapped the `DefaultServlet` to the root path `/` so that when a user accesses `abc` it will be handled by the `DefaultServlet`. 
Then, we map the `DefaultServlet` to `*.html` so that when a user accesses `abc.html` it will also be handled by the `DefaultServlet`.
In this way, when the user accesses `abc`, it will actually be handled by the `DefaultServlet` and the request will be forwarded to `abc.html`. This realizes the effect of actually accessing `abc.html` when accessing the page `abc` without a suffix.
Fix: #1467 
N/A
Manually test passed.
=> [#1467] fix(web): The refresh of the UI will lead to 404

web/app/metalakes/DetailsView.js, web/app/metalakes/MetalakePath.js, web/app/metalakes/MetalakeTree.js, web/app/metalakes/MetalakeView.js, web/app/metalakes/TableView.js, web/lib/store/metalakes/index.js
Fix tree view expand and collapse.
Default:
Click to home page then click metalake:
Click to `hive_table_2` and click `hive_table_2` again:
Fix: #1501
Fix: #1502
Fix: #1476 
Fix: #1591 
N/A
N/A
=> [#1501] fix(UI): Fix tree view expand and collapse

web/app/(home)/DetailsDrawer.js, web/app/metalakes/DetailsView.js, web/components/EmptyText.js, web/lib/utils/date.js
Before:
drawer details:
tab details:
After:
drawer details:
tab details:
Fix: #1555
N/A
N/A
=> [#1555] improve(UI): improve empty field

catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveTable.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/hive/CatalogHiveIT.java
set empty string as default value of comment when creating table
Fix: #1544 
no
IT added
=> [#1544] fix(hive): fix null comment in hive table property

integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoQueryIT.java, integration-test/src/test/resources/trino-ci-testset/testsets/hive/00005_catalog.sql, integration-test/src/test/resources/trino-ci-testset/testsets/hive/00005_catalog.txt, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/CatalogInjector.java
Fix cannot create same name of catalog when the old catalog has deleted
Fix: #1259
NO
IT
=> [#1259] fix(trino-connector): Fix cannot create same name of catalog when the old catalog has deleted

web/app/(home)/MetalakeList.js
Before:
After:
Fix the layout issue of datagrid when the data is empty.
N/A
N/A
=> [MINOR]: fix(UI): fix no rows datagrid layout

catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogOperations.java, catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveColumn.java, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveTable.java
throw an exception, when the Hive catalog detects default values specified during table creation
Fix: #1557 
no
UT added
=> [#1557] feat(hive): Handle column default value in Hive catalog

web/lib/provider/session.js
Redirect to the homepage if the Gravitino server is not running.
When the Gravitino server is not running, web redirects to login page.
N/A
N/A
=> [MINOR] improve(web): redirect to homepage if the Gravitino server is not running

web/components/ColumnTypeChip.js, web/lib/enums/columnTypeEnum.ts
Fix the issue of clicking on the `table` in the tree list.
After: when clicked the `hive-schema-table` on the tree view.
Fix: #1611
N/A
N/A
=> [#1611] fix(web): fix click tree table error

build.gradle.kts, gradle.properties, gradle/libs.versions.toml, integration-test/build.gradle.kts
support specify scala versions, by two methods:
1. `gradle build -PscalaVersion=xx`
2. set `defaultScalaVersion` in gradle.properties
method2 will be overwrite  by method1 if both existing, 
and supports scala 2.12 for now.
spark hive connector just supports scala 2.12
Fix: #1530 
no
existing UTs
=> [#1530] feat(spark-connector): support specifying scala version to build and test Gravitino

api/src/main/java/com/datastrato/gravitino/rel/Table.java, api/src/main/java/com/datastrato/gravitino/rel/TableCatalog.java, api/src/main/java/com/datastrato/gravitino/rel/indexes/Index.java, api/src/main/java/com/datastrato/gravitino/rel/indexes/Indexes.java, catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogOperations.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcCatalogOperations.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergCatalogOperations.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalCatalog.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalCatalog.java, common/src/main/java/com/datastrato/gravitino/dto/rel/TableDTO.java, common/src/main/java/com/datastrato/gravitino/dto/rel/indexes/IndexDTO.java, common/src/main/java/com/datastrato/gravitino/dto/requests/TableCreateRequest.java, common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java, common/src/test/java/com/datastrato/gravitino/json/TestDTOJsonSerDe.java, core/src/main/java/com/datastrato/gravitino/catalog/CatalogOperationDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/rel/BaseTable.java, core/src/main/java/com/datastrato/gravitino/catalog/rel/EntityCombinedTable.java, core/src/test/java/com/datastrato/gravitino/TestCatalogOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestTableOperations.java
Provide the Index interface implementation of the Table to the user side
Fix: #1398 
Add table index impl.
NO
=> [#1398] feat(table): Add index api for tables.

catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergCatalogOperations.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergColumn.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/TestIcebergTable.java
When the Iceberg catalog detects default values specified during table creation, it should throw an exception
Fix: #1556 
no
UT added
=> [#1556] feat(iceberg): Iceberg catalog handle column default value

api/src/main/java/com/datastrato/gravitino/rel/Column.java, api/src/test/java/com/datastrato/gravitino/rel/TestColumn.java, api/src/test/java/com/datastrato/gravitino/rel/TestTransforms.java
Add `columnImpl` in API module
For client usage
Fix: #1630 
yes, the client now can use the helper method in `Column` API to get a column instance
UTs added
=> [#1630] feat(api): Add `columnImpl` in API module

catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/operation/MysqlTableOperations.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java, integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-mysql/00002_alter_table.sql, integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-mysql/00002_alter_table.txt, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/CatalogConnectorMetadata.java, web/package.json
Add `NOT NULL` key word in create table sentence if column type is NOT NULL.
We should support creating a table with not null columns.
Fix: #1632
N/A.
Add some ITs.
=> [#1632] fix(jdbc-mysql): Supporting create not null column for MySQL table.

web/components/ColumnTypeChip.js
Modified the display of the `type` field in the table.
Before:
After:
Complex types of `type` currently only display the main column type.
The details on how to display more specific information will be discussed in future iterations.
Fix: #1649
N/A
N/A
=> [#1649] fix(web): modified the display of the type field in the table

server/src/main/java/com/datastrato/gravitino/server/web/rest/ExceptionHandlers.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestExceptionHandlers.java
This PR optimize the error message to make it more meaningful to the UI.
Previously it outputs the exception class name, which is not meaningful to users. Now change to the actual error message like below:
```
Failed to operate table(s) [ADMINISTRABLE_ROLE_AUTHORIZATIONS] operation [LOAD] under schema [information_schema], reason [Failed to parse create table information_schema.ADMINISTRABLE_ROLE_AUTHORIZATIONS SQL]
```
The reason field is only the error message now.
To make the error message on UI more meaningful.
Fix: #1551 
No.
Local verify.
=> [#1551] improve(server): Optimize the error message

catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergTable.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/ops/IcebergTableOpsHelper.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/lakehouse/iceberg/CatalogIcebergIT.java
remove  reserveProperties logic from CreateTableRequest since reserved properties is handled by property system
1. when build IcebergTable,  comment equals to null is checked when comment added to properties .
```
if (null != comment) {
icebergTable.properties.putIfAbsent(ICEBERG_COMMENT_FIELD_NAME, comment);
}
```
2. when build CreateTableRequest, the previous implement remove all reserved properties from property map including comment,  and then add comment to map, the bug happens, not checking the null, but this overall  code is redundant
Fix: #1546 
no
add UT
=> [#1546] fix(lakehouse-iceberg): fix create Iceberg table failed if comment is null

web/app/ui/metalakes/TableView.js
Fix the clickable table path.
Before fix this isssue, it shows a error tip in development mode.
Fix error caused by missing parameters.
N/A
N/A
=> [MINOR] fix(web): fix click table path

web/app/ui/metalakes/MetalakeTree.js
Change the cursor hover area for the treeview click.
Fix: #1641 
N/A
N/A
=> [#1641] improve(web):  change treeview click area hover cursor

integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/TestMultipleJdbcLoad.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlVersion12IT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlVersion14IT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlVersion15IT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlVersion16IT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/TestPostgreSqlAbstractIT.java
Use separate classes representing various PG versions.
junit5 doesn't support class-level ParameterizedTest. so use a separate class.
Test compatibility with various versions of PG.
Fix: #1361 
no
existing IT
=> [#1361] test(postgres-jdbc) support multi pg version in IT

common/src/main/java/com/datastrato/gravitino/dto/requests/TableUpdateRequest.java, common/src/test/java/com/datastrato/gravitino/dto/requests/TestTableUpdatesRequest.java
allow blank property value when update table property
Fix: #1681 
no
UT added
=> [#1681] fix: allow blank property value when update table property

catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/operation/MysqlTableOperations.java
Compatible with lower versions of MySQL driver, unable to obtain table comments.
Fix: #1701
NO
UT/IT
=> [#1701] fix(mysql): Compatible with lower versions of MySQL driver, unable to obtain table comments.

gradle/libs.versions.toml, integration-test/build.gradle.kts, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/MetalakePageTest.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/AbstractWebIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/ChromeWebDriverProvider.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/WebDriverManager.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/WebDriverProvider.java, web/lib/layout/VersionView.js
1. Automatic download `Chrome` & `Chrome Driver` into `./intergration-test/build/chrome` directory. need to download about 150 MB zip file for the first time.
2. Support embedded and deploy test mode.
3. Support Linux and macOS operation systems
4. Successed load metalake webpage and check the browser title.
5. #1687 
Gravitino Web UI needs an E2E test to ensure Web UI usability.
Fix: #1503
N/A
CI Passed
=> [#1503] feat(IT): Gravitino web e2e test framework

web/app/ui/DetailsDrawer.js, web/app/ui/metalakes/DetailsView.js
Fix comment display if length is too long.
After:
Fix: #1709 
N/A
N/A
=> [#1709] fix(web): fix comment display

bin/gravitino.sh
I add error start options in previous pull request.
I will fix the start command of Java17 in this pull request.
Fix: #1722 
No.
```
export JAVA_HOME=<jdk17>
./gradlew compileDistribution
cd distribution/package/
sh bin/gravitino.sh restart
```
run the command successfully.
=> [#1722] fix: Fix the start command of Java17

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcCatalogOperations.java, catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlSchemaOperations.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/CatalogMysqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlIT.java
to get gravitino identifier id from schema, 
1. get comment from pg
2. add gravitino identifier to properties,
```
//  properties is not changed , we should use the returned properties.
StringIdentifier.newPropertiesWithId(id, properties);
JdbcSchema.Builder().withProperties(properties).build();
```
we couldn't get audit info from entity store without  gravitino identifier id
Fix: #1449 
no
add test to check audit info
=> [#1449] fix(jdbc-postgres): audit info is empty

common/src/main/java/com/datastrato/gravitino/dto/rel/partitions/IdentityPartitionDTO.java, common/src/main/java/com/datastrato/gravitino/dto/rel/partitions/ListPartitionDTO.java, common/src/main/java/com/datastrato/gravitino/dto/rel/partitions/PartitionDTO.java, common/src/main/java/com/datastrato/gravitino/dto/rel/partitions/RangePartitionDTO.java, common/src/main/java/com/datastrato/gravitino/json/JsonUtils.java, common/src/test/java/com/datastrato/gravitino/json/TestJsonUtils.java
Add JSON serde for partitions
Fix: #1678 
no
UTs added
=> [#1678] feat(partition): Add JSON serde for partitions

core/src/main/java/com/datastrato/gravitino/catalog/file/EntityCombinedFileset.java, core/src/test/java/com/datastrato/gravitino/TestCatalogOperations.java
This PR is a followup PR to fix the building issue after #1667 is merged.
Fix building issue.
No.
Existing UTs.
=> [MINOR] fix(hadoop-catalog): Fix building issue after #1667 is merged.

web/app/ui/metalakes/CreateCatalogDialog.js, web/app/ui/metalakes/DetailsDrawer.js, web/app/ui/metalakes/RightContent.js, web/app/ui/metalakes/TableView.js, web/app/ui/metalakes/TabsContent.js, web/lib/api/catalogs/index.js, web/lib/store/metalakes/index.js
Add API-based catalog management.
Fix: #1208 
N/A
N/A
=> [#1208] feat(web): add catalog management via api

web/app/ui/CreateMetalakeDialog.js, web/app/ui/MetalakeList.js, web/app/ui/metalakes/CreateCatalogDialog.js, web/app/ui/metalakes/MetalakePath.js, web/lib/utils/regex.js
1. Add naming rules to the name field of the metalake
2. Optimize the display of the name field
Fix: #1429
Fix: #1628 
Fix: #1629 
N/A
N/A
=> [#1429] improve(web): add form fields rules

integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoQueryIT.java, integration-test/src/test/resources/trino-ci-testset/testsets/tpcds/00014.txt
Remove warning messages from the query execution output in Trino.
Set the TPC-H test set as the default for CI.
Fix: #1781
NO
TrinoQueryIT
=> [#1781] fix:(trino-connector) Remove warning messages from the query execution output in Trino.

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcCatalogOperations.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcColumn.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcTableOperations.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/operation/MysqlTableOperations.java, catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlTableOperations.java, common/src/main/java/com/datastrato/gravitino/dto/rel/ColumnDTO.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/TestJdbcAbstractIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/CatalogMysqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/TestMysqlTableOperations.java
1.Delete unnecessary code sections about the properties of the jdbc column
2.MySQL supports load properties of auto_increment
Fix: #1279 
NO
UT
=> [#1279] feat(jdbc): MySQL supports auto_increment

common/src/main/java/com/datastrato/gravitino/dto/requests/AddPartitionsRequest.java, common/src/main/java/com/datastrato/gravitino/dto/responses/PartitionListResponse.java, common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/PartitionOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestPartitionOperations.java
Add REST API for adding partition
Fix: #1774 
no
UTs added
=> [#1774] feat(server): Add REST API for adding partition

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcCatalogOperations.java
The table properties values extracted from MySQL need to go through the Gravitino conversion logic.
Fix: #1789 
NO
Conducted end-to-end testing
=> [#1789] fix(mysql): The table properties values extracted from MySQL need to go through the Gravitino conversion logic.

catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/operation/MysqlDatabaseOperations.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/AuditCatalogMysqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/CatalogMysqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java
throw a exception when user. set comment on MySQL database
Fix: #1717 #1767 
yes, if user  set comment on MySQL database, will throw a exception.
add UT
=> [#1717] fix(jdbc-mysql): throw an exception if setting comment on MySQL database

catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveTableOperations.java, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveTableOperations.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalTable.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalTable.java, common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/hive/CatalogHiveIT.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/PartitionOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestPartitionOperations.java
Support `listPartitions` for Hive catalog
Fix: #1769 
no
tests added
=> [#1769] feat(partition): Support `listPartitions` for Hive catalog

web/app/ui/CreateMetalakeDialog.js, web/app/ui/metalakes/CreateCatalogDialog.js, web/lib/utils/regex.js
Fix duplicate key message and disable the Select component.
1. disabled the Select component
2. fix duplicate key message
Step1: input the key field
Step2: input the value field
Fix: #1783 
Fix: #1794 
Fix: #1808 
N/A
N/A
=> [#1783] fix(web): fix duplicate key message and disabled the Select component

docs/apache-hive-catalog.md, docs/jdbc-mysql-catalog.md, docs/jdbc-postgresql-catalog.md, docs/lakehouse-iceberg-catalog.md, docs/trino-connector/installation.md
Fix https://github.com/datastrato/gravitino/issues/1813
There are 5 files, and 13 links in total, the links are wrong.
The original link was not complete, so when we click the link, it jumped to an error page in Github.
N/A
N/A
=> [#1813] fix(doc): Update the internal links for md files

web/app/ui/metalakes/DetailsView.js, web/app/ui/metalakes/TableView.js
1. Fix special characters in DetailsView.
Related PR #1770 
2. Disabled Table component header menu, and optimize the column text displaying.
Fix: #1684 
N/A
N/A
=> [#1684] fix(web): fix special characters in DetailsView

.gitignore
Add `*.ipr` to `.gitignore` file.
We include [idea plugin](https://github.com/datastrato/gravitino/blob/dd2786a4ff7c84bcb067e1d8a67bdf052992a8d2/build.gradle.kts#L22) in Gradle, so users can run ./gradlew openIdea or ./gradlew idea to open IDEA editor. With the command, there is a new file gravitino.ipr. The file is not included in [.gitignore](https://github.com/datastrato/gravitino/blob/dd2786a4ff7c84bcb067e1d8a67bdf052992a8d2/.gitignore#L26-L34) or [exclusions](https://github.com/datastrato/gravitino/blob/dd2786a4ff7c84bcb067e1d8a67bdf052992a8d2/build.gradle.kts#L323-L343). If users run ./gradlew build -x test, they will get failed rat task.
Fix: https://github.com/datastrato/gravitino/issues/1823
No
Make sure the build doesn't get error when there is `gravitino.ipr` file.
``` …
```
=> [#1823] feat(ci): Add *.ipr file

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/bean/JdbcIndexBean.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcTableOperations.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/operation/MysqlTableOperations.java, catalogs/catalog-jdbc-postgresql/build.gradle.kts, catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlTableOperations.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/operation/TestPostgreSqlTableOperations.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/CatalogMysqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/PostgreSqlTableOperationsIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/AbstractIT.java
Support PostgreSQL index.
Fix: #1736
NO
UT/IT
=> [#1736] feat(postgresql): Support PostgreSQL index.

catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogOperations.java, catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveProxyPlugin.java, catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveTable.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalCatalog.java, core/src/main/java/com/datastrato/gravitino/catalog/OperationsProxy.java, core/src/main/java/com/datastrato/gravitino/catalog/rel/BaseTable.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/hive/ProxyCatalogHiveIT.java
Now, we only support catalog operations to impersonate. We should support it in the TableOperation.
Better user experience.
Fix: #1830 
No.
Add UT.
=> [#1830] improvement(core,hive):  TableOperations support impersonation

integration-test/build.gradle.kts
change poll image pause timeout from 30s to 60s
There are 2 parameters control pull image:
1. PULL_RETRY_TIME_LIMIT,  2 mins, which isn't configable.
2. pull.pause.timeout, defaults 30s.
if there are no progress for pulling image, it will check whether the total of  image pull time is beyond `PULL_RETRY_TIME_LIMIT`. In this pr we change pause timeout from 30s to 60s to adapt bad network.
Fix: #955 
no
existing UT
=> [#955] fix(test): change poll image pause timeout from 30s to 60s

common/src/main/java/com/datastrato/gravitino/auth/KerberosUtils.java
Fix Kerberos client retrieve the credential form TGT cache.
Fix: #1841
No.
By hand.
=> [#1841] fix(client):  Fix Kerberos client to retrieve the credential form TGT cache.

docs/jdbc-postgresql-catalog.md
PostgreSQL does not support the Byte type of Gravetino and needs to be removed from the document
Fix: #1843 
NO
NO
=> [#1843] fix(postgresql-doc): PostgreSQL does not support the Byte type of Gravetino and needs to be removed from the document

docs/jdbc-postgresql-catalog.md
PostgreSQL mapping type update for Gravitino.
Fix: #1845 
NO
NO
=> [#1845] Improvement(postgresql-doc): PostgreSQL mapping type update for Gravitino.

common/src/main/java/com/datastrato/gravitino/Config.java, common/src/main/java/com/datastrato/gravitino/auth/AuthConstants.java, common/src/main/java/com/datastrato/gravitino/auth/AuthenticatorType.java, common/src/main/java/com/datastrato/gravitino/config/ConfigBuilder.java, common/src/main/java/com/datastrato/gravitino/config/ConfigConstants.java, common/src/main/java/com/datastrato/gravitino/dto/AuditDTO.java, common/src/main/java/com/datastrato/gravitino/dto/CatalogDTO.java, common/src/main/java/com/datastrato/gravitino/dto/rel/ColumnDTO.java, common/src/main/java/com/datastrato/gravitino/dto/rel/DistributionDTO.java, common/src/main/java/com/datastrato/gravitino/dto/rel/partitioning/BucketPartitioningDTO.java, common/src/main/java/com/datastrato/gravitino/dto/rel/partitioning/DayPartitioningDTO.java, common/src/main/java/com/datastrato/gravitino/dto/rel/partitioning/Partitioning.java, common/src/main/java/com/datastrato/gravitino/dto/requests/AddPartitionsRequest.java, common/src/main/java/com/datastrato/gravitino/dto/requests/CatalogUpdateRequest.java
Add Java docs for module `client`, `api` and `common`.
It's necessary for the user API. 
Fix: #1817 
No, we are only adding Java docs.
Test locally using MacOS.
=> [#1817] improvement(all): Remove warning informations when building with JDK17 

docs/build.gradle.kts
treat warnings as errors in lint OpenAPI
Fix: #1893
no
about `recommended-strict`,  see [here](https://github.com/Redocly/redocly-cli/pull/1311)
before:
after:
=> [#1893] improvement(build): treat warnings as errors in lint OpenAPI

web/app/ui/MetalakeList.js, web/app/ui/metalakes/TableView.js, web/app/ui/metalakes/TabsContent.js, web/lib/theme/mui.js
1. Add the column headers `autoIncrement` and `comment` in the Table view.
2. Changed the style of Table column header and Tab label.
Fix: #1988
N/A
N/A
=> [#1988] improve(web): add the column headers `autoIncrement` and `comment` in the Table view

core/src/main/java/com/datastrato/gravitino/metrics/source/MetricsSource.java
1.The constructor access specifier was changed to protected 
fix: #1944 
no
Existing tests
=> [#1944] fix(core): Make constructor of MetricsSource.java protected 

catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveTable.java, catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveTableOperations.java, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveTableOperations.java
Use HMS's `listPartitions` RPC to replace the two RPC calls of `listPartitionNames` and `getPartitionsByNames`.
Fix: #1974
No
exist UT
=> [#1974] fix(hive): Hive table listPartitions reduces HMS RPC calls

docs/expression.md, docs/table-partitioning-bucketing-sort-order-indexes.md
Add user doc of expression
Fix: #1134 
no
no need
=> [#1134] docs: Add user doc of expression

web/lib/utils/axios/checkStatus.ts
Improve the format of the error message.
Remove meaningless `[` `]` from the return message format.
N/A
N/A
=> [MINOR] improve(web): improve format of the error message

web/app/ui/metalakes/TableView.js
Improve the table cell formatting.
https://github.com/datastrato/gravitino/issues/1997#issuecomment-1925012531
N/A
N/A
=> [MINOR] improve(web): improve table cell format

build.gradle.kts
Add check warning information in the JavaDoc task.
Module `api`, `common`, and `client-java` will be exposed and used by users, we need to make it more standard. 
Fix: #1987 
N/A.
Test locally.
=> [#1987] improvement(build): Take warning information as error when build java docs

integration-test/src/main/java/com/datastrato/gravitino/integration/test/util/ITUtils.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/ChromeWebDriverProvider.java
1. set connect and read timeout 30s when downloading chrome
2. add error retry 
Fix: #1979 
no
could run web IT
=> [#1979] fix(test): add timeout and retry when downloading chrome

integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/hive/HivePropertyMeta.java
Remove default values of `input_format`, `output_format` and `serde_lib` in Trino Hive connector.
When we create hive table, format value can't overwrite the value of `serde_lib`, `input_format` and `output_fomat`
Fix: #2027 
N/A.
Add some tests in `testHiveTableCreatedByGravitino`.
=> [#2027] fix(trino-connector): Fix the bug that `format` configuration can't overwrite default `InputFormat` value.

docs/how-to-use-the-playground.md, docs/iceberg-rest-service.md
Add an Iceberg REST service demo in the playground.
This pr is related to https://github.com/datastrato/gravitino-playground/pull/26
Fix: #1857 #1699 
No, just doc.
By hand.
=> [#1857] improvement: Add an Iceberg REST service demo

docs/security.md
Unify the style of configuration options
Fix: #2042 
No.
Just doc.
=> [#2042] improvement(doc): Unify the style of configuration options

docs/apache-hive-catalog.md, docs/expression.md, docs/jdbc-mysql-catalog.md, docs/jdbc-postgresql-catalog.md, docs/lakehouse-iceberg-catalog.md, docs/manage-metadata-using-gravitino.md, docs/open-api/tables.yaml
Add doc for column default value
Fix: #1590 
no
no need
=> [#1590] docs: Add doc for column default value

docs/iceberg-rest-service.md, docs/lakehouse-iceberg-catalog.md
1.  remove `gravitino.auxService.iceberg-rest.jdbc-driver` not required message
2. polish catalog to catalog backend to make it more clear.
3. remove `struct` from the Iceberg catalogs support types
polish iceberg rest catalog document
no
just document
=> [MINOR] docs(lakehouse-iceberg): polish iceberg document

docs/open-api/partitions.yaml
Adjust the position of the example to fit the Docusaurus OpenAPI plugin
There seems a bug with Docusaurus OpenAPI plugin:
no
locally tested
=> [MINOR] docs: Adjust the position of the example to fit the Docusaurus OpenAPI plugin

integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/AbstractWebIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/WebDriverManager.java
really wait 60s to load the web page
in the form implement, if load failed in 10s, will try load again using `driver.navigate().to(url);`, seems unnecessary, we could wait 60s to load page.
```
while (System.currentTimeMillis() - start < 60 * 1000) {
try {
(new WebDriverWait(driver, 10))
.until(
new ExpectedCondition<Boolean>() {
@Override
public Boolean apply(WebDriver d) {
String gravitinoVersion = d.findElement(By.id("gravitino_version")).getText();
String projectVersion = System.getenv("PROJECT_VERSION");
return projectVersion.equalsIgnoreCase(gravitinoVersion);
}
});
loaded = true;
break;
} catch (TimeoutException e) {
LOG.info("Exception in WebDriverManager while WebDriverWait ", e);
driver.navigate().to(url);
}
}
```
Fix: #2052 
no
=> [#2052] fix(IT): improve the timeout handle of web driver

docs/open-api/tables.yaml
Add complex data type example to `HiveTableCreate`
The example of complex data type schema does work with Docusaura open API plugin, So I add complex type example to `HiveTableCreate`
Fix: #1274 
no
local tested:
=> [#1274] docs: Add complex data type example to `HiveTableCreate`

docs/open-api/catalogs.yaml, docs/open-api/metalakes.yaml, docs/open-api/partitions.yaml, docs/open-api/schemas.yaml, docs/open-api/tables.yaml
Condense the summary to fit the Docusaurus open api plugin
Docusaurus open api plugin generate the sidebar tag value by the API summary, so we need to condense the summary to make the sidebar more cleaner
no
locally tested:
=> [MINOR] docs: Condense the summary to fit the Docusaurus open api plugin

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcTableOperations.java, catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/operation/SqliteTableOperations.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlIT.java
Add logic to check the table schema when listing tables.
Method `getTables` supports regex and if we use `pg_` as the database name, all tables in schemas that start with `pg` will
Retrieved. 
Fix: #2067 
N/A
Add IT `testPGListTable`
=> [#2067] Fix the bugs that list tables in schema `pg_` will get all tables in schema starts with `pg`

api/build.gradle.kts, catalogs/catalog-hadoop/build.gradle.kts, catalogs/catalog-hive/build.gradle.kts, catalogs/catalog-jdbc-common/build.gradle.kts, catalogs/catalog-jdbc-mysql/build.gradle.kts, catalogs/catalog-jdbc-postgresql/build.gradle.kts, catalogs/catalog-lakehouse-iceberg/build.gradle.kts, clients/client-java/build.gradle.kts, common/build.gradle.kts, core/build.gradle.kts, integration-test/build.gradle.kts, server-common/build.gradle.kts, server/build.gradle.kts
…destination #1969
Group dependencies by their destination.
Change to group dependencies by their destination.
no
=> [#1969] Improvement: In all gradle files group dependancies by their destination

catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/ConvertUtil.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/FromIcebergType.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/ToIcebergType.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/ToIcebergTypeVisitor.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/TestIcebergTable.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/TestConvertUtil.java, docs/lakehouse-iceberg-catalog.md, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/lakehouse/iceberg/CatalogIcebergIT.java
add  struct column support for iceberg 
Fix: #1313
Fix: #1471 
no
UT added
=> [#1313][#1471] feat(iceberg): Support struct column for iceberg

common/src/main/java/com/datastrato/gravitino/config/ConfigEntry.java, common/src/test/java/com/datastrato/gravitino/config/TestConfigEntry.java, common/src/test/java/com/datastrato/gravitino/config/TestConfigEntryList.java
Add `toSequence()` support while dealing with a list of values in one conf entry.
Fix #1357 
Just like Spark [does](https://github.com/apache/spark/blob/e8dfcd3081abe16b2115bb2944a2b1cb547eca8e/core/src/main/scala/org/apache/spark/internal/config/ConfigBuilder.scala#L126) and can be indeed useful for Gravitino.
No
Run `./gradlew test -PskipITs` should pass all.
=> [#1357] improvement(common): add `toSequence` support for configuration builder

common/src/main/java/com/datastrato/gravitino/auth/AuthConstants.java
Transform AuthConstants.java into a final class with all constant fields declared as public static final.
Fix: #1865
N/A
N/A
=> [#1865] fix: Transform AuthConstants.java into a final class with all constant fields declared as public static final

docs/how-to-install.md, docs/how-to-use-the-playground.md
replace `<>` with `[]()` on link
There is a rendering error for current md
no
local tested
=> [MINOR] docs: fix unparsed link

.github/ISSUE_TEMPLATE/bug-report.yml, .github/ISSUE_TEMPLATE/epic.yml, .github/ISSUE_TEMPLATE/feature-request.yml, .github/ISSUE_TEMPLATE/improvement.yml, .github/ISSUE_TEMPLATE/subtask.yml, .github/workflows/add-to-project.yml 
Revert `github/workflows/add-to-project.yml` Action.
Currently, only issues created by Datastrato organization members can automatically add project(`Gravitino`).
Fix: #2106
N/A
CI
=> [#1694] improve: optimized Github issue template file

docs/open-api/openapi.yaml
Update the version of the OpenAPI document to 0.4.0
As the [OAS](https://spec.openapis.org/oas/latest.html#info-object) description, the version field in Info object should be:
> The version of the OpenAPI document (which is distinct from the [OpenAPI Specification version](https://spec.openapis.org/oas/latest.html#oasVersion) or the API implementation version).
So I update the version to 0.4.0
no
no need
=> [MINOR] docs: Update the version of the OpenAPI document to 0.4.0

.gitattributes, CONTRIBUTING.md
Force line endings to be LF not CRLF
So users using windows don't get confused and submit PRs with CRLFs in them.
Fix: # N/A
N/A
I don't have a windows machine to test this on, but it's simple enough.
=> [Minor] Force line endings to be LF not CRLF

build.gradle.kts, gradle.properties, gradle/libs.versions.toml, integration-test/build.gradle.kts
support specify scala versions, by two methods:
1. `gradle build -PscalaVersion=xx`
2. set `defaultScalaVersion` in gradle.properties
method2 will be overwrite  by method1 if both existing,  and supports scala 2.12 for now.
spark hive connector just supports scala 2.12
existing UTs
=> [#1530]  feat(spark-connector): support specifying scala version to build and test Gravitino

catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlTableOperations.java
Use constant literals instead of multiple strings for PostgreSqlTableOperations
Fix: https://github.com/datastrato/gravitino/issues/1954
N/A
By hand
=> [#1954] Use constant literals for PostgreSqlTableOperations class

core/src/main/java/com/datastrato/gravitino/catalog/BaseCatalog.java
Refactor the `BaseCatalog.java` to replace "entity is not set" with a static string.
Replace the "entity is not set" with a static string variable.
Fix: #1866
N/A
No test is required as 6 separate strings are replaced with a static string variable.
=> [#1866] refactor(core): Replace repeated string with variable

core/src/main/java/com/datastrato/gravitino/catalog/PropertiesMetadata.java
Return the value after executing apply() in checkValueFormat()
Return the value after executing apply() in checkValueFormat()
Address the linter issue in #2158
Fix: #2158
No.
=> [#2158] Improvement: Return the value after executing apply() in checkValueFormat()

api/src/main/java/com/datastrato/gravitino/NameIdentifier.java, api/src/main/java/com/datastrato/gravitino/Namespace.java
Remove redundant `null` checks when using `instanceof`.
Simplify the code logic.
Fix: #2187
No.
=> [#2187] Improvement: Remove redundant null checks when using instanceof

catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveClientPool.java
Remove redundant null check when using `instanceof`.
Fix: https://github.com/datastrato/gravitino/issues/2187
No.
Tested with existing tests.
=> [#2187] Improvement: Remove redundant null check when using instanceof

server-common/src/main/java/com/datastrato/gravitino/server/auth/KerberosServerUtils.java
- Convert L80-94 into javadoc
- Follow conventions in other class, convert license comment into block comment
Fix https://github.com/datastrato/gravitino/issues/2161
No
Update comments only.
=> [#2161] Improvement: Fix JavaDoc in KerberosServerUtils.java

core/src/main/java/com/datastrato/gravitino/metrics/MetricsSystem.java
Replace LinkedList with ArrayList.
Address linter issues mentioned in #2163.
Fix #2163
No.
Covered by existing tests.
=> [#2163] Improvement: Replace LinkedList with ArrayList

api/src/test/java/com/datastrato/gravitino/TestNameIdentifier.java, api/src/test/java/com/datastrato/gravitino/rel/TestLiteral.java, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveTable.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/TestIcebergTable.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/TestConvertUtil.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/TestFromIcebergSortOrder.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/web/rest/TestIcebergConfig.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/web/rest/TestIcebergNamespaceOperations.java, common/src/test/java/com/datastrato/gravitino/dto/responses/TestResponses.java
Swap order of assertEquals parameters to be correct
If the test fails the error message will be misleading.
Fix: #2209
N/A
Built and run test locally all passed.
=> [#2209] Swap order of assertEquals parameters to be correct

catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogOperations.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/KerberosTokenProvider.java, server-common/src/main/java/com/datastrato/gravitino/server/auth/KerberosAuthenticator.java
Due to the linter warning "Null type safety: The expression of type
'String' needs unchecked conversion to conform to '@Nonnull
CharSequence'", @SuppressWarnings("null") is added to suppress the
warning
Replace String.split("@") with Splitter.on('@').splitToList()
Address linter issue mentioned in #2159
Fix: #2159
No.
=> [#2159] Improvement:  Replace String.split("@") with Splitter.on('@').splitToList()

docs/how-to-use-the-playground.md
fixed a small typo: there were "can will" in a sentence at the same time
=> [MINOR] fix: typo in document

integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoQueryITBase.java
TrinoQueryITBase removes unusual static call (`ContainerSuite.getInstance().getTrinoITContainers()`).
There are unusual static call (`ContainerSuite.getInstance().getTrinoITContainers()`) in `TrinoQueryITBase`, which could remove from `TrinoQueryITBase`.
Fix: #2135
No.
`TrinoQueryITBase`
=> [#2135] improvement(integration-test): TrinoQueryITBase removes unusual static call

core/src/main/java/com/datastrato/gravitino/storage/kv/RocksDBKvBackend.java
close #1955
Fix: #1955 
- no
- unit
=> [#1955] imporvement(core): Fix resource leak in RocksDBKvBackend.java

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcDatabaseOperations.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/ConvertUtil.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/FromIcebergPartitionSpec.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/ToIcebergPartitionSpec.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/ops/IcebergTableOpsHelper.java, common/src/main/java/com/datastrato/gravitino/json/JsonUtils.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoQueryIT.java
`@return` missing description in:
JdbcDatabaseOperations.java
ConvertUtil.java
FromIcebergPartitionSpec.java
ToIcebergPartitionSpec.java
IcebergTableOpsHelper.java
JsonUtils.java
TrinoQueryIT.java
For better document.
Fix: #2155
No.
Make sure there is no missing description for `@return`.
=> [#2155] fix: add missing @return

api/src/main/java/com/datastrato/gravitino/Catalog.java, api/src/main/java/com/datastrato/gravitino/NameIdentifier.java, api/src/main/java/com/datastrato/gravitino/Namespace.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/BaseSchemaCatalog.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/DTOConverters.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/ErrorHandlers.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/FilesetCatalog.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalCatalog.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalTable.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestBase.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestFilesetCatalog.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestGravitinoMetalake.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalCatalog.java
Add Java client support for fileset
Fix: #1838 
- Add Java client support for fileset
add ut. `com.datastrato.gravitino.client.TestFilesetCatalog`
=> [#1838] feat(client): Add Java client support for fileset

integration-test/src/main/java/com/datastrato/gravitino/integration/test/MiniGravitino.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/hive/ProxyCatalogHiveIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/AuditCatalogMysqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/client/AuditIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/AbstractIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/rest/OAuth2OperationsIT.java
Fix use of OAuthConfig.AUTHENTICATOR
Static members are associated with the class itself, not with any specific instance of the class or its children classes.
Change OAuthConfig.AUTHENTICATOR to Configs.AUTHENTICATOR.
Fix: #2192
No.
Check there is no OAuthConfig.AUTHENTICATOR.
=> [#2192] fix: change OAuthConfig.AUTHENTICATOR to Configs.AUTHENTICATOR

trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/hive/HiveConnectorAdapter.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/iceberg/IcebergConnectorAdapter.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/jdbc/mysql/MySQLConnectorAdapter.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/jdbc/postgresql/PostgreSQLConnectorAdapter.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/memory/MemoryConnectorAdapter.java
close #1953 #1946 #1941 #1920 #1910 
Fix: #1953 #1946 #1941 #1920 #1910 
- no
- ut
=> [#1953] [#1946] [#1941] [#1920] [#1910] improment(trino): make version atomic to keep thread safe

core/src/test/java/com/datastrato/gravitino/storage/kv/TestRocksDBKvBackend.java
TestRocksDBKvBackend test method `testScan` should not return values
Fix: https://github.com/datastrato/gravitino/issues/2258
N/A
By hand
=> [Improvement] TestRocksDBKvBackend tests should not return values

core/src/main/java/com/datastrato/gravitino/storage/kv/TransactionalKvBackendImpl.java
Possible memory leak issue with TransactionalKvBackendImpl class 
Fix: https://github.com/datastrato/gravitino/issues/2257
N/A
By hand
=> [#2257] improve(core): Fix possible memory leak on TransactionalKvBackendImpl.java

build.gradle.kts, catalogs/catalog-hadoop/build.gradle.kts, catalogs/catalog-hadoop/src/main/resources/META-INF/services/com.datastrato.gravitino.CatalogProvider, catalogs/catalog-hadoop/src/main/resources/core-site.xml.template, catalogs/catalog-hadoop/src/main/resources/hadoop.conf, catalogs/catalog-hadoop/src/main/resources/hdfs-site.xml.template, core/src/test/java/com/datastrato/gravitino/proto/TestEntityProtoSerDe.java, meta/src/main/proto/gravitino_meta.proto
This PR enables the Hadoop catalog in Gravitino's build, so users can use it in end-to-end test and local verification.
Change the build script to enable the Hadoop catalog module.
Fix: #2287
No.
Local verification.
=> [#2287] feat(hadoop-catalog): Enable Hadoop catalog module in Gravitino project

integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/CatalogMysqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlIT.java
Add tests to retrieve index keys for tables in wildcard scenarios.
Fix: #2288
NO
IT
=> [#2288] Improvement(test) : Add tests to retrieve index keys for tables in wildcard scenarios.

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcTableOperations.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/operation/MysqlTableOperations.java
- Moved AFTER and MODIFY COLUMN string as constants
- Fix: https://github.com/datastrato/gravitino/issues/1948
- No
- ./gradlew test -PskipITs
=> [#1948] Improvement(catalog-mysql): Moved AFTER and MODIFY COLUMN string  as constants

catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/HadoopCatalogOperations.java, catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java
This PR improves to formalize the storage location path into a standard URI format before storing into the entity store.
Users could set the storage location with different ways, like "/tmp/xxx", "xxx". We need to formalize the path to give user a consistent view of the path.
Fix: #2307 
No.
UTs.
=> [#2307] improve(catalog-hadoop): Formalize the storage location path before storing

web/app/ui/MetalakeList.js
Fix sorting and filtering of the metalakes table.
Fix: #1735 
Fix: #2072
N/A
N/A
=> [#1735] fix(web): fix sorting and filtering of the metalakes table

core/src/main/java/com/datastrato/gravitino/storage/kv/KvEntityStore.java, core/src/main/java/com/datastrato/gravitino/storage/kv/KvNameMappingService.java, core/src/test/java/com/datastrato/gravitino/storage/kv/TestKvEntityStorage.java
Remove the RW lock that guard concurrent issues in `KvEntityStore`.
#779 has introduced tree lock to guarantee thread-safe, so we can remove it. 
Fix: #780 
N/A.
Existing tests can cover it.
=> [#780] improvment(core): Remove RW lock in KvEntityStore as #779 has guaranteed thread safe.

api/src/main/java/com/datastrato/gravitino/rel/types/Type.java, api/src/main/java/com/datastrato/gravitino/rel/types/Types.java, api/src/test/java/com/datastrato/gravitino/rel/TestTypes.java, catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/converter/FromHiveType.java, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/converter/TestTypeConverter.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/converter/MysqlTypeConverter.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/converter/TestMysqlTypeConverter.java, catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/converter/PostgreSqlTypeConverter.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/converter/TestPostgreSqlTypeConverter.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/FromIcebergType.java, common/src/main/java/com/datastrato/gravitino/json/JsonUtils.java, common/src/test/java/com/datastrato/gravitino/json/TestJsonUtils.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/CatalogMysqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/MysqlTableOperationsIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlIT.java
`Type` adds `UNPARSED` column data type to handle an unresolvable type from the catalog.
If a column data type in the catalog does not have a mapping in Gravitino, an exception will be thrown. We should map all data types from a catalog to Gravitino. However, in practical situations, loading exceptions may occur due to the addition of new data types or insufficient mapping support. Introduce `UnparsedType` to represent the unparsed data type.
Fix: #2117 
`Type` adds `UNKNOWN` column data type that represents an unresolvable type.
- `TestJsonUtils#testTypeSerDe`
- `TestTypes#testUnparsedType`
- `TestTypeConverter#testTypeConverter`
- `TestMysqlTypeConverter#testToGravitinoType`
- `TestPostgreSqlTypeConverter#testToGravitinoType`
- `CatalogMysqlIT#testUnparsedTypeConverter`
- …
=> [#2117] improvement(api): Type adds UNPARSED column data type to handle an unresolvable type from the catalog

catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/HadoopCatalogOperations.java
- fix incorrect static field reference for HadoopCatalogOperations
Fix: #2188 
N/A
No
=> [#2188] improvement(catalogs): fix incorrect static field reference for HadoopCatalogOperations

api/src/main/java/com/datastrato/gravitino/rel/Column.java, api/src/main/java/com/datastrato/gravitino/rel/expressions/transforms/Transform.java, api/src/main/java/com/datastrato/gravitino/rel/partitions/Partitions.java, api/src/main/java/com/datastrato/gravitino/rel/types/Decimal.java, api/src/main/java/com/datastrato/gravitino/rel/types/Types.java, build.gradle.kts, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/bean/JdbcIndexBean.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/converter/JdbcTypeConverter.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestHTTPClient.java, common/src/main/java/com/datastrato/gravitino/dto/MetalakeDTO.java, common/src/main/java/com/datastrato/gravitino/dto/rel/DistributionDTO.java, common/src/main/java/com/datastrato/gravitino/dto/rel/indexes/IndexDTO.java, common/src/main/java/com/datastrato/gravitino/dto/rel/partitions/IdentityPartitionDTO.java, common/src/main/java/com/datastrato/gravitino/dto/rel/partitions/ListPartitionDTO.java, common/src/main/java/com/datastrato/gravitino/dto/rel/partitions/RangePartitionDTO.java, core/src/main/java/com/datastrato/gravitino/lock/TreeLockNode.java, core/src/main/java/com/datastrato/gravitino/meta/CatalogEntity.java, core/src/main/java/com/datastrato/gravitino/meta/SchemaEntity.java, core/src/main/java/com/datastrato/gravitino/meta/TableEntity.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/hive/SortingColumn.java
- close #2154 
- Fix: #2154 
- no
`./gradlew build` and UTs
=> [#2154] improvement: enable EqualsGetClass error-prone check

common/src/main/java/com/datastrato/gravitino/utils/MapUtils.java
A private constructor has been added to the MapUtils.java file, which is located at 'common\src\main\java\com\datastrato\gravitino\utils'.
In order to follow efficient programming, these changes have been introduced.
Fix: # ([1940](https://github.com/datastrato/gravitino/issues/1940))
No.
Now, for some reason, I am not able to run the `./gradlew :common:spotlessApply` command. I mean it opens a dialog box like this: 
I am not sure what changes are required this time.
When I try executing the command like `bash +x gradlew :common:spotlessApply`, I am getting the following errors:
Sincere apologies for all the trouble that's being caused till …
=> #1940 : [Improvement](common) MapUtils.java is missing a private constructor

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcColumn.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergColumn.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/ConvertUtil.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/TestIcebergTable.java
Add annotation `@EqualsAndHashCode` of `IcebergColumn` and `JdbcColumn`.
As `HiveColumn` has annotation `@EqualsAndHashCode` to support `equals` and `hashCode` method at present, `IcebergColumn` and `JdbcColumn` shoud be added the annotation `@EqualsAndHashCode`.
Fix: #1918
No.
No.
=> [#1918] improvement(catalog): Add annotation `@EqualsAndHashCode` of `IcebergColumn` and `JdbcColumn`

integration-test/src/test/java/com/datastrato/gravitino/integration/test/container/HiveContainer.java
increase retry interval of container status check from 5s to 10s
the retry interval is too short to wait HDFS initialization completed
Fix: #2365 
no
existing tests
=> [#2365]Improvement(IT): increase retry interval of container status check

docs/apache-hive-catalog.md, docs/jdbc-mysql-catalog.md, docs/jdbc-postgresql-catalog.md, docs/lakehouse-iceberg-catalog.md, docs/manage-metadata-using-gravitino.md, docs/open-api/datatype.yaml
Document `UnparsedType` data type which handles an unresolvable type from the catalog.
`UnparsedType` data type that handles an unresolvable type from the catalog is supported in #2140.
Fix: #2323
No.
No.
=> [#2323] docs: document `UnparsedType` data type which handles an unresolvable type from the catalog

dev/docker/build-docker.sh, dev/docker/doris/Dockerfile, dev/docker/doris/doris-dependency.sh
support `platform=all` for doris images
Fix: #2326
N/A
local
```
./build-docker.sh --type doris --image doris_ci --tag test
./build-docker.sh --platform linux/arm64 --type doris --image doris_ci --tag test
./build-docker.sh --platform linux/amd64 --type doris --image doris_ci --tag test
```
=> [#2326] feat(docker): support build with arg platform=all on Doris docker image

build.gradle.kts, core/src/test/java/com/datastrato/gravitino/utils/TestByteUtils.java
Enable `UseCorrectAssertInTests` error-prone check to avoid using `assert` in tests.
Error prone has `UseCorrectAssertInTests` bug pattern that Java assert is used in testing code. For testing purposes, prefer using Truth-based assertions in [UseCorrectAssertInTests](https://errorprone.info/bugpattern/UseCorrectAssertInTests). Therefore enable `UseCorrectAssertInTests` check to avoid using `assert` in tests.
Fix: #2362
No.
`./gradlew build`
=> [#2362] improvement: enable `UseCorrectAssertInTests` error-prone check

web/app/ui/metalakes/page.js
Fixing some compatibility issues with certain versions of Safari(macOS/13, Safari/16.4).
After testing, it was found that some native methods(`useSearchParams().size`) were missing in certain versions of Safari.
Fix: #2378
N/A
Test locally, please see.
=> [#2378] fix(web): fix compatibility with safari

web/app/ui/login/page.js, web/lib/api/auth/index.js, web/lib/layout/Logout.js, web/lib/provider/session.js, web/lib/store/auth/index.js, web/lib/utils/axios/checkStatus.ts, web/lib/utils/axios/index.ts
Remove refresh token and redirect to login page if token has expired.
Fix: #2099 
N/A
N/A
=> [#2099] fix(web): redirect to login page if token has expired

catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlSchemaOperations.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/TestMultipleJdbcLoad.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlIT.java
Remove the `public` schema from the `SYS_PG_DATABASE_NAMES` attribute
public schema is the default schema if not specifying schema names. we shouldn't filter it
Fix: #2314
N/A.
Existing tests can cover it.
=> [#2314] fix(postgresql): postgresql `public` schema should not be filtered in `listDatabases`

web/app/ui/MetalakeList.js, web/app/ui/metalakes/TableView.js, web/package.json, web/pnpm-lock.yaml
Fix table action button click event.
After testing, there is no problem with using the MUI built-in icons inside MuiButton, but using a custom icon will cause this issue.
Icon styles have been changed due to the use of MUI built-in icons.
Before: 
After: 
Fix: #1538 
N/A
N/A
=> [#1538] fix(web): fix table action button click event

common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java, common/src/test/java/com/datastrato/gravitino/dto/util/TestDTOConverters.java
- Arguments in incorrect order fixed with correct order!
- Fix: #2150 
- No
- ./gradlew test -PskipITs
=> [#2150] Improvement : Arguments in incorrect order fixed with correct order

build.gradle.kts, clients/client-java/src/main/java/com/datastrato/gravitino/client/KerberosTokenProvider.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestOAuth2TokenProvider.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/rest/OAuth2OperationsIT.java, server-common/src/test/java/com/datastrato/gravitino/server/auth/TestOAuth2TokenAuthenticator.java
- close #2156 
Fix: #2156 
- no
=> [#2156] improvement: enable JavaUtilDate error-prone check

integration-test/build.gradle.kts, trino-connector/build.gradle.kts, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/GravitinoConnector.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/GravitinoMetadata.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/hive/HiveConnectorAdapter.java
Remove the Trino runtime dependency to avoid version incompatibility.
Our Trino-connector uses Trino-426 for development. The AllowAllAccessControl dependency, trino-toolkit-426.jar, causes compatibility issues with Trino-426
Fix: #2376
NO
Manually testing in Trino-435
=> [#2376] fix(trino-connector) Gravitino-trino-connector is incompatible with Trino-435

integration-test/build.gradle.kts, trino-connector/build.gradle.kts, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/GravitinoConnector.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/GravitinoMetadata.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/hive/HiveConnectorAdapter.java
Remove the Trino runtime dependency to avoid version incompatibility.
Our Trino-connector uses Trino-426 for development. The AllowAllAccessControl dependency, trino-toolkit-426.jar, causes compatibility issues with Trino-426
Fix: #2376
NO
Manually testing in Trino-435
=> [#2376] fix(trino-connector) cherrypick  Gravitino-trino-connector is incompatible with Trino-435

catalogs/catalog-lakehouse-iceberg/build.gradle.kts
Fix include correct name to be `core-site.xml.template` instead of `hive-site.xml.template`.
=> [MINOR] fix(lakehouse-iceberg): Fix the include core-site conf file name for lakehouse-iceberg gradle script

integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/SparkIT.java
Make all Spark SQL keywords used in spark connector integration test uppercase
Fix: #2424 
No
`./gradlew build -PskipTests`
=> [#2424] improvement(spark-connector): make all Spark SQL keywords uppercase for consistency

catalogs/catalog-lakehouse-iceberg/build.gradle.kts
Fix include correct name to be `core-site.xml.template` instead of `hive-site.xml.template`.
=> [Backport] fix(lakehouse-iceberg): Fix the include core-site conf file name for lakehouse-iceberg gradle script

integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/SparkIT.java, spark-connector/src/main/java/com/datastrato/gravitino/spark/catalog/GravitinoCatalog.java
Support alter namespace operation implementation.
Support to set namespace properties in Spark sql like:
```
ALTER DATABASE inventory SET DBPROPERTIES ('Edited-by' = 'John', 'Edit-date' = '01/01/2001');
```
Fix: #2401
No.
- `SparkIT#testAlterSchema`
=> [#2401] improvement(spark-connector): support alter namespace operation

integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/SparkIT.java, spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/SparkTypeConverter.java, spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/table/SparkBaseTable.java, spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/TestSparkTypeConverter.java
using DataTypes to replace  `StringType$.MODULE$` make code more simple
```java
public class DataTypes {
/**
* Gets the StringType object.
*/
public static final DataType StringType = StringType$.MODULE$;
}
```
no
existing UT
=> [MINOR]: feat(spark-connector): use DataTypes to create spark datatype

integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/SparkIT.java, spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/catalog/GravitinoCatalog.java, spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/TestTransformTableChange.java, spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/catalog/TestTransformTableChange.java
support add table property and remove table property for spark-connector in AlterTableCommand.
Implement setProperty and RemoveProperty ops for Spark AlterTableCommand.
Fix: [#2448](https://github.com/datastrato/gravitino/issues/2448)
Yes, users can run the following commands to modify the table properties using spark sql.
```
-- Alter TABLE property Using SET PROPERTIES
ALTER TABLE gravitino_catalog.dbx.tab1 SET TBLPROPERTIES ('key1' = 'value1');
-- DROP TABLE PROPERTIES
ALTER TABLE gravitino_catalog.dbx.tab1 UNSET TBLPROPERTIES ('key1');
```
new uts.
=> [#2448] feat(spark-connector): support  alter table setProperty and removeProperty for spark-connector

docs/trino-connector/requirements.md
The requirements document for the Trino connector need to remove the limitation that disabled the 'allow_pushdown_into_connectors' configuration
Fix: #2462
NO
NO
=> [#2462] fix(doc) Remove 'allow_pushdown_into_connectors=false'  in trino-connector/requirements doc 

spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/SparkTypeConverter.java, spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/TestSparkTypeConverter.java
Support Float and Double type for spark-connector; add related test
Fix: #2451 
No
`./gradlew test -PskipITs`
=> [#2451] feat(spark-connector): support Float and Double type for spark-connector

clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalCatalog.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalTable.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/hive/CatalogHiveIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/TestMultipleJdbcLoad.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/AuditCatalogMysqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/mysql/CatalogMysqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/jdbc/postgresql/CatalogPostgreSqlIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/catalog/lakehouse/iceberg/CatalogIcebergIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java
- Use `ColumnImpl` instead of `ColumnDTO` when calling gravitino API in test cases.
- Rename variable columnDTOs to columns to avoid misunderstanding.
Fix: #1635
No
Existing integration tests.
=> [#1635] Improvement: Replace ColumnDTO with ColumnImpl in test cases 

build.gradle.kts, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/GravitinoErrorCode.java
ImmutableEnumChecker will check whether a Eunm is immutable.
Such cases will be recognized as an immutable object:
- All fields are final.
- The types of all fields of the enum are deeply immutable.
- The class annotated by `@com.google.errorprone.annotations.Immutable`.
See more details at https://errorprone.info/bugpattern/ImmutableEnumChecker.
In this MR, we suppress ImmutableEnumChecker on `io.trino.spi.ErrorCode`, because it is outside the project.
- Fix: #2162 
- no
=> [#2162] improvement: enable ImmutableEnumChecker error-prone

integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/SparkIT.java, spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/catalog/GravitinoCatalog.java, spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/catalog/TestTransformTableChange.java
support rename table column for spark-connector in RenameColumnCommand.
Fix: # 2450
`alter table  default_catalog.default_db.default_table rename age to new_age;`
write new unit tests.
=> #2450 add RenameColumn support for spark-connector

integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/MetalakePageTest.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/Pages/MetalakePage.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/AbstractWebIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/WebDriverManager.java, web/app/ui/CreateMetalakeDialog.js, web/app/ui/MetalakeList.js, web/app/ui/TableHeader.js, web/app/ui/metalakes/MetalakePath.js, web/app/ui/metalakes/RightContent.js, web/components/ConfirmDeleteDialog.js, web/components/DetailsDrawer.js
Add web e2e test to homepage.
Fix: #2394 
N/A
N/A
=> [#2394] feat(IT): Add metalake page to web e2e test

catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/CachedClientPool.java
Close the Caffeine Scheduler explicitly in method `close`.
The scheduler thread can't be exited after we close the CachedClientPool. This problem will be triggered by `atlerCatalog` opertion.
Fix: #2513
N/A.
N/A.
=> [#2513] fix: Fix thread pool leak in CachedClientPool

.gitignore
add integration-test/metastore_db to .gitignore
Avoid temporary files being tracked by Git after IT testing.
N/A
local
=> [MINOR] feat(ci): add integration-test/metastore_db to .gitignore

integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/SparkIT.java, spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/catalog/GravitinoCatalog.java, spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/catalog/TestTransformTableChange.java
support update column comment for spark-connector
Fix: #2449
`alter table  default_catalog.default_db.default_table change column col1 col1 int comment 'new_comment;'`
write new unit tests.
=> [#2449] feat(spark-connector): support update column comment for spark-connector

catalogs/catalog-messaging-kafka/build.gradle.kts, catalogs/catalog-messaging-kafka/src/main/java/com/datastrato/gravitino/catalog/kafka/KafkaCatalogOperations.java, catalogs/catalog-messaging-kafka/src/main/java/com/datastrato/gravitino/catalog/kafka/KafkaSchema.java, catalogs/catalog-messaging-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/TestKafkaCatalogOperations.java, core/src/main/java/com/datastrato/gravitino/meta/SchemaEntity.java
This PR tracks the work of adding schema support for the Kafka catalog. Unlike the other catalog, the Kafka catalog manages schema in the Gravitino's store, and will automatically create a “default” schema to contain all topics in the cluster.
Fix: #2467 
no
UTs added
=> [#2467] feat(kafka-catalog): Add schema operations support for Kafka catalog

core/src/test/java/com/datastrato/gravitino/storage/kv/TestRocksDBKvBackend.java
Added coverage for scan and deleteRange methods.
Fix: https://github.com/datastrato/gravitino/issues/2186
No
./gradlew clean build
=> [#2186] Improvement: Added more coverage for scan and deleteRange methods

build.gradle.kts, catalogs/catalog-jdbc-doris/build.gradle.kts, catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/DorisCatalog.java, catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/converter/DorisColumnDefaultValueConverter.java, catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/converter/DorisExceptionConverter.java, catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/converter/DorisTypeConverter.java, catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/operation/DorisDatabaseOperations.java, catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/operation/DorisTableOperations.java, catalogs/catalog-jdbc-doris/src/main/resources/META-INF/services/com.datastrato.gravitino.CatalogProvider, catalogs/catalog-jdbc-doris/src/main/resources/jdbc-doris.conf, settings.gradle.kts
Add a basic skeleton for Doris catalog
Fix: #2551 
N/A
just build
=> [#2551] feat(catalog-jdbc-doris): Add a basic skeleton for Doris catalog

web/package.json, web/pnpm-lock.yaml, web/src/app/layout.js, web/src/app/metalakes/CreateMetalakeDialog.js, web/src/app/metalakes/TableBody.js, web/src/app/metalakes/layout.js, web/src/app/metalakes/metalake/MetalakePageLeftBar.js, web/src/app/metalakes/metalake/MetalakeView.js, web/src/app/metalakes/page.js, web/src/app/rootLayout/AppBar.js, web/src/app/rootLayout/Layout.js, web/src/app/rootLayout/Loading.js, web/src/lib/provider/session.js
…odule and fix load table data issues
1. Displaying a fallback while content is loading for the main content
Displaying a fallback while content is loading for metalakes list table body module
Displaying a fallback while content is loading for catalog tree list modul
2. Define metadata icon src path based on the operating environment
3. Fix some issue of inconsistent behaviour
- Smooth display of loaded data
- Preserve search parameters when strongly refreshing a page
An instant loading state is fallback UI that is shown immediately upon navigation.
You can pre-render loading indicators such as skeletons and spinners.
This helps users understand the app is responding and provides a better user experience.
Fix issue because of the need for consistent behaviour after refactoring
Fix: #2570, …
=> [#2570][#2559] refactor(web): Displaying a fallback while content is loading for each small module, upgrade axios to v1.6.8

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcCatalogOperations.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcTableOperations.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/TableOperation.java, catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/operation/SqliteTableOperations.java, catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/operation/TestJdbcTableOperations.java, catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/operation/DorisTableOperations.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/converter/MysqlExceptionConverter.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/operation/MysqlTableOperations.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/MysqlTableOperationsIT.java, catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlTableOperations.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/PostgreSqlTableOperationsIT.java
Refact catalog-jdbc distribution parameter check, move to catalog-jdbc-mysql 、postgres、sqlite
Fix: #2553 
Doris support distribution
N/A
UT、IT
=> [#2553] refactor: refact catalog-jdbc distribution parameter check

trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/system/table/GravitinoSystemTableCatalog.java, trino-connector/src/test/java/com/datastrato/gravitino/trino/connector/TestGravitinoConnector.java
Trino-435 changed the SPI interfaces of the BlockBuilder and Page classes. We have switched to using the unmodified API..
Fix: #2577
NO
UT, Manunally testing in Trino-435
=> [#2577 ]fix (trino-connector): Compatible create Page interfaces with the version of Trino-435

docs/open-api/filesets.yaml
Remove the "description" field in Fileset related APIs.
Because the `description` field does not exist in the related APIs, it should be removed, otherwise, it will lead to an issue.
Fix: #2618 
No.
Manually verification.
=> [#2618] fix(doc): Remove description field in fileset openapi doc

.github/workflows/backend-integration-test.yml, .github/workflows/frontend-integration-test.yml, docs/how-to-test.md, integration-test/build.gradle.kts, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/MetalakePageTest.java
1. Add Gradle compile parameter `skipWebITs`
2. Splitting integration-test Github Action
Run WEB E2E integration test in alone Github Action.
Fix: #2608 
N/A
CI passed
=> [#2608] improvement(IT): Splitting WEB-E2E IT into an alone Github Action

catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/CachedClientPool.java, core/src/main/java/com/datastrato/gravitino/utils/ClientPoolImpl.java
Close `HiveClientPool` before closing the class loader as the removal listener is asynchronous and can't make this guarantee.
It's bugs that need to be fixed.
Fix: #2525 
N/A.
Test locally.
=> [#2525] fix(catalog-hive): Fix classNotFoundError in the Caffeine removal listener

gradle/libs.versions.toml, integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/SparkCommonIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/SparkEnvIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/hive/SparkHiveCatalogIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/spark/SparkTableInfo.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/spark/SparkTableInfoChecker.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/spark/SparkUtilIT.java, spark-connector/build.gradle.kts, spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/ConnectorConstants.java, spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/SparkTransformConverter.java, spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/catalog/GravitinoCatalog.java, spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/table/SparkBaseTable.java, spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/TestSparkTransformConverter.java
add partition, distribution, sort order support for spark connector
Fix: #1550 
no
add UT and IT, also verified in local env.
=> [#1550] feat(spark-connector) support partition,bucket, sortorder table

common/src/main/java/com/datastrato/gravitino/Config.java, common/src/main/java/com/datastrato/gravitino/config/ConfigEntry.java
1. make clear the semantics of configuration `alternatives` for storing the deprecated config keys.
2. log warning for all deprecated config keys when loading configurations
3. log warning when users try to call `config.set` of deprecated keys, just ignore the warning of `config.get`
Fix: #2653 
No
By hand.
=> [#2653] Improvement(common): Make clear the semantics of configuration alternatives

spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/SparkTypeConverter.java, spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/TestSparkTypeConverter.java
Support null type for spark-connector; add related test
Fix: #2595 
No
`./gradlew test -PskipITs`
=> [#2595] feat(spark-connector) support null type for spark connector 

build.gradle.kts
Skip signing when execute `./gradlew publishToMavenLocal` without gpg key.
If developer wants to generate signed file locally, it still can be generated by setting the env `GPG_ID`, `GPG_PRIVATE_KEY` and `GPG_PASSPHRASE`.
Publish to local Maven repository should succeed even without signing a signature.
Fix: #2657
N/A
`./gradlew publishToMavenLocal`
=> [#2657] improvement: Skip signing for publishToMavenLocal.

docs/open-api/filesets.yaml
- fix some incorrect descriptions for fileset on open-API doc.
Fix: #2624 
- no
=> [#2624] fix(open-api): add openapi description for fileset

integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/CatalogsPageTest.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/pages/CatalogsPage.java, web/src/app/metalakes/layout.js, web/src/app/metalakes/metalake/MetalakeTree.js, web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js, web/src/app/metalakes/metalake/rightContent/MetalakePath.js, web/src/app/metalakes/metalake/rightContent/tabsContent/TabsContent.js, web/src/app/metalakes/metalake/rightContent/tabsContent/tableView/TableView.js, web/src/components/DetailsDrawer.js
Add catalogs page to web e2e test.
- show parent details
- create a catalog
- view existed catalog details
- edit existed catalog
- delete existed catalog
- link to schemas
- link to tables
- back to homepage
Fix: #2436
N/A
N/A
=> [#2436] feat(IT): Add catalogs page to web e2e test

integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/SparkCommonIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/SparkEnvIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/hive/SparkHiveCatalogIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/spark/SparkUtilIT.java
add integrate test for `create table as select xx` and `insert table select xx`
Fix: #2402 
no
IT
=> [#2402] test(spark-connector): Add the integration tests for CTAS and ITAS

integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/util/AbstractIT.java, integration-test/build.gradle.kts, integration-test/src/test/java/com/datastrato/gravitino/integration/test/client/filesystem/hadoop3/GravitinoVirtualFileSystemIT.java
Add e2e tests for gvfs. Mainly covers `create`, `append`, `delete`, `getStatus`, `listStatus`, `mkdirs` and `rename` operations.
Fix: #2689
=> [#2689] improvement(gvfs): Add e2e tests for gvfs

dev/docker/doris/Dockerfile, dev/docker/doris/start.sh, docs/docker-image-details.md
- Optimize`startup.sh`, cat log to stdout
- Add disk space check before starting Doris
- Exit when FE or BE start failed
Fix: #2651 
N/A
UT
=> [#2651] feat(docker): optimize start.sh in Doris container

api/src/main/java/com/datastrato/gravitino/SupportsCatalogs.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/GravitinoClient.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/GravitinoMetalake.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestGravitinoMetalake.java, common/src/main/java/com/datastrato/gravitino/dto/responses/CatalogListResponse.java, common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java, core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java, core/src/main/java/com/datastrato/gravitino/connector/CatalogInfo.java, core/src/main/java/com/datastrato/gravitino/meta/CatalogEntity.java, core/src/test/java/com/datastrato/gravitino/catalog/TestCatalogManager.java, docs/manage-metadata-using-gravitino.md, docs/open-api/catalogs.yaml, integration-test/src/test/java/com/datastrato/gravitino/integration/test/client/CatalogIT.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/CatalogOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestCatalogOperations.java
support list all catalogs' info in the API module, REST server and client
Fix: #2396 
yes, user can use the `listCatalogsInfo` API to obtain all catalog details info
tests added
=> [#2396] feat(all): support list all catalogs info

.github/workflows/backend-integration-test.yml, .github/workflows/build.yml, .github/workflows/frontend-integration-test.yml, .github/workflows/python-ci.yml, clients/client-python/build.gradle.kts, settings.gradle.kts
- use Gradle to manage Python build.
- add Github CI
- `./gradlew clean clients:client-python:test`
Fix: #2518 
- no
- `./gradlew clean clients:client-python:test`
=> [#2518] feat(build): support Github CI for client-python

.github/workflows/backend-integration-test.yml, catalogs/catalog-jdbc-doris/build.gradle.kts, catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/TestDorisAbstractIT.java, catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/TestDorisDatabaseOperations.java, catalogs/catalog-jdbc-doris/src/test/resources/log4j2.properties, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/BaseContainer.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/DorisContainer.java, integration-test/build.gradle.kts
add Doris container implement for integration-test
Fix: #2552 
N/A
UT
=> [#2552] feat(catalog-jdbc-doris): add Doris container implement for integration-test

integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/CatalogsPageTest.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/pages/CatalogsPage.java, web/src/app/rootLayout/AppBar.js, web/src/app/rootLayout/VersionView.js, web/src/lib/store/metalakes/index.js
Add  the metalake selection/dropdown to the right-up corner, see the picture below. 
Now the entry page is clearer for the user, he can quickly start with the catalog. Only when he wants to edit, switch metalake, can he easily find that in the right-up corner.
Fix: #2480, #2698
N/A
run the e2e test local
=> [#2480][#2698]feat(web): add metalake select to the right-up corner

catalogs/catalog-messaging-kafka/build.gradle.kts, catalogs/catalog-messaging-kafka/src/main/java/com/datastrato/gravitino/catalog/kafka/KafkaCatalogOperations.java, catalogs/catalog-messaging-kafka/src/main/java/com/datastrato/gravitino/catalog/kafka/KafkaTopic.java, catalogs/catalog-messaging-kafka/src/main/java/com/datastrato/gravitino/catalog/kafka/KafkaTopicPropertiesMetadata.java, catalogs/catalog-messaging-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/TestKafkaCatalogOperations.java, catalogs/catalog-messaging-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/embeddedKafka/KafkaClusterEmbedded.java, catalogs/catalog-messaging-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/embeddedKafka/KafkaEmbedded.java, catalogs/catalog-messaging-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/embeddedKafka/ZooKeeperEmbedded.java, core/src/main/java/com/datastrato/gravitino/catalog/messaging/BaseTopic.java, core/src/main/java/com/datastrato/gravitino/connector/BaseTopic.java, core/src/main/java/com/datastrato/gravitino/connector/PropertyEntry.java, gradle/libs.versions.toml
This PR proposes to add the topic operations support for the Kafka catalog.
This is a part of the work to support messaging management in Gravitino
Fix: #2468 
no
Add UTs to cover the codes.
=> [#2468] feat(kafka-catalog): support topic operations for Kafka catalog

api/src/main/java/com/datastrato/gravitino/messaging/TopicCatalog.java, catalogs/catalog-messaging-kafka/src/main/java/com/datastrato/gravitino/catalog/kafka/KafkaCatalogOperations.java, catalogs/catalog-messaging-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/TestKafkaCatalogOperations.java, core/src/main/java/com/datastrato/gravitino/GravitinoEnv.java, core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java, core/src/main/java/com/datastrato/gravitino/catalog/EntityCombinedTopic.java, core/src/main/java/com/datastrato/gravitino/catalog/OperationDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/TopicOperationDispatcher.java, core/src/main/java/com/datastrato/gravitino/storage/kv/BinaryEntityKeyEncoder.java, core/src/main/java/com/datastrato/gravitino/storage/relational/JDBCBackend.java, core/src/test/java/com/datastrato/gravitino/TestCatalogOperations.java, core/src/test/java/com/datastrato/gravitino/TestTopic.java, core/src/test/java/com/datastrato/gravitino/catalog/TestTopicOperationDispatcher.java
This PR add the Kafka catalog adaption to the CatalogOperationsDispatcher
Part of Kafka catalog support work
Fix: #2610 
no
UTs
=> [#2610] feat(kafka-catalog, core): Adapt the Kafka catalog to CatalogOperationsDispatcher

integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/CatalogsPageTest.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/pages/CatalogsPage.java, web/src/app/metalakes/metalake/MetalakeTree.js, web/src/app/metalakes/metalake/MetalakeView.js, web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js, web/src/app/metalakes/metalake/rightContent/MetalakePath.js, web/src/app/metalakes/metalake/rightContent/tabsContent/TabsContent.js, web/src/app/metalakes/metalake/rightContent/tabsContent/tableView/TableView.js, web/src/lib/api/catalogs/index.js, web/src/lib/api/filesets/index.js, web/src/lib/store/metalakes/index.js, web/src/lib/utils/initial.js
Web ui support for fileset catalog
Some try catch which helpful for debugging among extraReducers functions 
Fix: #2292
N/A
run catalog e2e test successfully
=> [#2292]feat(fileset): add web ui support for fileset catalog

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/converter/JdbcColumnDefaultValueConverter.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/converter/MysqlColumnDefaultValueConverter.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
Fix a bug for a Date string as column default value in MySqlColumnDefaultValueConverter
Use date pattern for such a date type value.
Fix: #2737
No
UT covered, which is added by charliecheng630
=> [#2737] fix(catalog-jdbc-mysql): MySqlColumnDefaultValueConverter DATE conversion failed.

api/src/main/java/com/datastrato/gravitino/NameIdentifier.java, api/src/main/java/com/datastrato/gravitino/Namespace.java, common/src/main/java/com/datastrato/gravitino/dto/messaging/TopicDTO.java, common/src/main/java/com/datastrato/gravitino/dto/requests/TopicCreateRequest.java, common/src/main/java/com/datastrato/gravitino/dto/requests/TopicUpdateRequest.java, common/src/main/java/com/datastrato/gravitino/dto/requests/TopicUpdatesRequest.java, common/src/main/java/com/datastrato/gravitino/dto/responses/TopicResponse.java, common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java, server/src/main/java/com/datastrato/gravitino/server/GravitinoServer.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/ExceptionHandlers.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/TopicOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestTopicOperations.java
This PR adds RESTful API implementation of messaging catalog topic operations
Part of Kafka catalog support work
Fix: #2611 
yes, add several topic operations RESTful API
UTs
=> [#2611] feat(server): Add server-side REST API support for topic

api/src/main/java/com/datastrato/gravitino/Catalog.java, api/src/main/java/com/datastrato/gravitino/NameIdentifier.java, api/src/main/java/com/datastrato/gravitino/Namespace.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/DTOConverters.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/ErrorHandlers.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/FilesetCatalog.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/MessagingCatalog.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestGravitinoMetalake.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestMessagingCatalog.java
Add Java client support for the messaging catalog
Fix: #2612 
Add Java client support for the messaging catalog
UTs
=> [#2612] feat(client): Add Java client support for messaging catalog

integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java
Fix HDFS client IP address resolution when using Docker Desktop. Originally it may resolve to invalid domain name causing error.
Fix: #2598
No.
=> [#2598] Fix: Fix HDFS IP resolution for Docker Desktop

docs/apache-hive-catalog.md, docs/expression.md, docs/index.md, docs/jdbc-mysql-catalog.md, docs/jdbc-postgresql-catalog.md, docs/lakehouse-iceberg-catalog.md, docs/manage-metalake-using-gravitino.md, docs/manage-relational-metadata-using-gravitino.md, docs/trino-connector/development.md, docs/trino-connector/installation.md, docs/trino-connector/supported-catalog.md, docs/trino-connector/trino-connector.md, docs/webui.md
Split the "manage-metadata-using-gravitino.md" into several ones.
As we added more catalog types, it is not feasible to list all the APIs in one doc, so here propose to split the docs.
Fix: #2750 
No.
Just docs.
=> [#2750]improve(doc): Split the metadata managing doc into several ones

web/src/lib/store/metalakes/index.js
When listing metalakes they get sorted by their createdTime value
Its requested in the issue
Fix: #2754  (issue)
metalakes will be shown in ASC order
N/A
=> [#2754] improvement(web): list metalakes sort by created time as default

docs/manage-metalake-using-gravitino.md, docs/manage-relational-metadata-using-gravitino.md, docs/manage-table-partition-using-gravitino.md, docs/security.md
After separating the Gravitino java client to two clients, the documents should be updated as well.
The Gravitino java client was separated to two: GravitinoClient and GravitinoAdminClient. So the document need be corrected.
Fix: #2761
No; Just the mark down documents.
Manual review.
=> [#2761] fix(docs): update docs after separating the Gravitino java client to two clients

.github/workflows/backend-integration-test.yml, integration-test/trino-it/launch.sh, integration-test/trino-it/shutdown.sh
Change `docker-compose` to `docker compose`
Github CI image updates its base image to upgrade docker compose from v1 to v2, in which the command `docker-compose` is no longer supported, instead user should use `docker compose`.
Fix: #2788
N/A.
Test locally and CI.
=> [#2788] fix(ci):  Fix CI issue after Github CI image is upgraded

docs/hadoop-catalog.md, docs/index.md, docs/manage-fileset-metadata-using-gravitino.md
This PR proposes to add docs for fileset catalog.
Fix: #2695 
No.
No.
=> [#2695] feat(doc): Add docs for fileset catalog

integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java
make `startxxxContainer` Singleton
Fix: #2793 
no
existing tests
=> [#2793] improvement(CI): Starting a Container Using the Singleton Mode

api/src/main/java/com/datastrato/gravitino/rel/TableChange.java, spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/catalog/GravitinoCatalog.java, spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/catalog/TestTransformTableChange.java
support UpdateColumnDefaultValue in AlterTable for spark connector.
Fix: #2650 
No
New UTs.
=> [#2650] feat(spark-connector): support UpdateColumnDefaultValue in AlterTable for spark connector

catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/integration/test/TestJdbcAbstractIT.java, catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/converter/DorisExceptionConverter.java, catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/operation/DorisDatabaseOperations.java, catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/utils/DorisUtils.java, catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/converter/TestDorisExceptionConverter.java, catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/TestDorisDatabaseOperations.java, catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/utils/TestDorisUtils.java
Add database operations for Doris catalog
Fix: #2571 
N/A
UT & IT
=> [#2571] feat(catalog-jdbc-doris): Add database operations for Doris catalog

.github/workflows/backend-integration-test.yml, .github/workflows/frontend-integration-test.yml, .github/workflows/python-integration-test.yml, clients/client-python/README.md, clients/client-python/build.gradle.kts, clients/client-python/requirements-dev.txt, clients/client-python/tests/integration_test_env.py, clients/client-python/tests/test_integration_gravitino_client.py, docs/how-to-test.md
Add two Gradle command in the client-python module
1. `./gradlew :clients:client-python:test`
2. `./gradlew :clients:client-python: integrationTest`
Proved a real test environment for Gravitino server. 
Fix: #2756
N/A
CI Passed
=> [#2756] feat(PyClient): Integration test with Gravitino Python client

core/src/main/java/com/datastrato/gravitino/storage/kv/BinaryEntityEncoderUtil.java, core/src/main/java/com/datastrato/gravitino/storage/relational/JDBCBackend.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/TopicMetaMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/po/TopicPO.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/CatalogMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/MetalakeMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/SchemaMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/TopicMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/session/SqlSessionFactoryHelper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/utils/POConverters.java, core/src/test/java/com/datastrato/gravitino/storage/TestEntityStorage.java, core/src/test/java/com/datastrato/gravitino/storage/relational/utils/TestPOConverters.java, core/src/test/resources/h2/schema-h2.sql, scripts/mysql/schema-0.5.0-mysql.sql
Add JDBC backend operations for topic
Implement support for storing messaging catalog metadata in the JDBC backend.
Fix: #2775 
no
tests added
=> [2775] feat(core): Add JDBC backend operations for topic

catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/FromIcebergType.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/TestConvertUtil.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergIT.java, docs/gravitino-server-config.md
in com.datastrato.gravitino.catalog.lakehouse.iceberg.converter.ConvertUtil#formIcebergType
```
Types.TimestampType.withZone() -> com.datastrato.gravitino.rel.types.Types.TimestampType.withTimeZone()
Types.TimestampType.withoutZone() -> com.datastrato.gravitino.rel.types.Types.TimestampType.withoutTimeZone()
```
Fixed abnormal timestamp type conversion between iceberg and gravitino
Fix: https://github.com/datastrato/gravitino/issues/2824
No
Existing Unit tests and new IT.
=> [#2824] bugFix: Fixed abnormal timestamp type conversion between iceberg and gravitino

spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/catalog/GravitinoCatalogManager.java, spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/plugin/GravitinoDriverPlugin.java
filter non relational catalogs before register to spark catalog manager
Fix: #2388 
no
existing test
=> [#2388] feat(spark-connector): filter non relational catalogs before register to spark catalog manager

.github/workflows/frontend-integration-test.yml
Merging embedded and deploy test mode for frontend integration test, and just test with Java 8 version.
Fix: #2798
N/A
CI
=> [#2798] improve(CI): Modified CI configuration for frontend integration test

integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/SparkCommonIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/hive/SparkHiveCatalogIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/spark/SparkUtilIT.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/hive/HivePropertiesConstants.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/hive/HivePropertiesConverter.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/hive/TestHivePropertiesConverter.java
supports location properties, transform from Spark location to Gravitino location
`CREATE TABLE xx LOCATION xxx`
Fix: #2621 
No
IT
=> [#2621] feat(spark-connector) support hive table location properties

build.gradle.kts
Don't package the Doris module into released package, since it is not ready for shipping. We could enable this when it is functional-ready.
To avoid ship with incomplete feature.
No.
No.
=> [MINOR] Disable doris module since it is not ready for shipping

.github/workflows/backend-integration-test.yml, catalogs/catalog-hadoop/src/test/resources/log4j2.properties, catalogs/catalog-hive/src/test/resources/log4j2.properties, catalogs/catalog-jdbc-doris/src/test/resources/log4j2.properties, catalogs/catalog-jdbc-mysql/src/test/resources/log4j2.properties, catalogs/catalog-jdbc-postgresql/src/test/resources/log4j2.properties, catalogs/catalog-lakehouse-iceberg/src/test/resources/log4j2.properties, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/util/AbstractIT.java, integration-test/src/test/resources/log4j2.properties
Separate TestContainers logs into a different log file.
Fix: #2839 
no
by hand
=> [#2839] improvment(CI): add log of testcontainers

server/src/main/java/com/datastrato/gravitino/server/web/rest/CatalogOperations.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/FilesetOperations.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/MetalakeOperations.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/SchemaOperations.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/TableOperations.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/TopicOperations.java
Change lock method in metalake/catalog/schema/table/fileset opertaions.
Use solution 1 in #2260 
```
list -> parent read lock
create -> parent write lock
load -> itself read lock
alter -> parent write lock
drop -> parent write lock
```
Applicable to scenarios where list requests are more frequent than create/update requests
Fix: #2647
Nothing
test detail in https://docs.google.com/document/d/1GPynb8SbxcIU2s6h3W-mPqeRVqmv0ac9_rBJm63awqs/edit#heading=h.v6mlybfhntc
=> [#2647] improvement(server): use read lock in list api

catalogs/catalog-hadoop/build.gradle.kts, catalogs/catalog-hive/build.gradle.kts, catalogs/catalog-lakehouse-iceberg/build.gradle.kts, dev/docker/hive/start.sh, docs/docker-image-details.md, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java, integration-test/build.gradle.kts, integration-test/trino-it/docker-compose.yaml
- Remove SSH service from the startup script.
- Use `hadoop-daemon.sh` to start HDFS services.
Fix: #2874 
no
CI pass
=> [#2874] improvement(CI): remove SSH service from Hive container

web/src/app/metalakes/metalake/MetalakeTree.js, web/src/app/metalakes/metalake/MetalakeView.js, web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js, web/src/app/metalakes/metalake/rightContent/MetalakePath.js, web/src/app/metalakes/metalake/rightContent/tabsContent/TabsContent.js, web/src/app/metalakes/metalake/rightContent/tabsContent/detailsView/DetailsView.js, web/src/app/rootLayout/AppBar.js, web/src/lib/api/topics/index.js, web/src/lib/store/metalakes/index.js, web/src/lib/utils/initial.js
…age for no data tree
1. Add web UI support for Kafka catalog
2. Add default page for no data tree
N/A
Fix: #2614, #2530
N/A
Local Smoke Test and e2e test
=> [#2614][#2530]feat(web): Add web UI support for Kafka catalog and add default page for no data tree

catalogs/catalog-kafka/src/main/java/com/datastrato/gravitino/catalog/kafka/KafkaCatalogOperations.java, catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java, core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java
- move creating default schema to catalog initialization
- cascade droping the default schema when drop Kafka catalog
because we don't allow to drop the default schema in Kafka catalog
Fix: #2795 
yes, user now can drop Kafka catalog successfully
tests added
=> [#2795] fix(kafka-catalog): Fix Kafka catalog cannot be dropped

core/src/main/java/com/datastrato/gravitino/storage/kv/KvGarbageCollector.java
Add a check mechanism in `KvGarbageCollector` to avoid removing uncommitted data wrote into kv storage a few seconds or minutes ago. 
There is a potential that  `KvGarbageCollector` will take normal data as uncommitted data and remove it. For more please see #2888 
Fix: #2888 
N/A.
N/A.
=> [#2888] fix(core): Fix the possible concurrency for `KvGarbageCollector`

dev/docker/doris/start.sh, docs/docker-image-details.md
- remove log from container stdout
- improvement: add config to avoid storage_medium_check
Fix: #2886
N/A
CI
=> [#2886] improvement(ci): optimize  Docker container to suite CI framework

core/src/main/java/com/datastrato/gravitino/storage/relational/JDBCBackend.java, core/src/main/java/com/datastrato/gravitino/storage/relational/converters/H2ExceptionConverter.java, core/src/main/java/com/datastrato/gravitino/storage/relational/converters/MySQLExceptionConverter.java, core/src/main/java/com/datastrato/gravitino/storage/relational/converters/SQLExceptionConverter.java, core/src/main/java/com/datastrato/gravitino/storage/relational/converters/SQLExceptionConverterFactory.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/CatalogMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/FilesetMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/MetalakeMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/SchemaMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/TableMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/TopicMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/utils/ExceptionUtils.java, core/src/test/java/com/datastrato/gravitino/storage/relational/TestJDBCBackend.java
Determine exceptions more accurately based on SQL Exception error codes.
Fix: #2227
Add the unit tests.
=> [#2227] improvement(jdbc-backend): Improve the judgment of exception information in JDBC backend

catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergTable.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergTablePropertiesMetadata.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergIT.java
Support more file formats in using clause when create iceberg tables, such as `using parquet`, `using orc`, `using avro`, `using iceberg`.
using other provider will throw an exception.
Because Iceberg official supports using parquet/orc/avro/iceberg when create a new table.
Fix: https://github.com/datastrato/gravitino/issues/2927
Yes, users can using `parquet/orc/avro/iceberg` keywork in `using clause` when create a new table.
New IT.
=> [#2927] Improvement(catalog-lakehouse-iceberg): Support more file formats in using clause when create iceberg tables

clients/filesystem-hadoop3/src/main/java/com/datastrato/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java
Make `getWorkingDirectory` method synchronized to avoid some concurrent issues.
Fix: #2910
=> [#2910] improvement(filesystem-hadoop3): Make `getWorkingDirectory` method synchronized

catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalog.java, catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogCapability.java, catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogOperations.java, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveTable.java, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/integration/test/CatalogHiveIT.java, core/src/main/java/com/datastrato/gravitino/catalog/CapabilityHelpers.java, core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java, core/src/main/java/com/datastrato/gravitino/catalog/TableOperationDispatcher.java, core/src/main/java/com/datastrato/gravitino/connector/BaseCatalog.java, core/src/main/java/com/datastrato/gravitino/connector/capability/Capability.java, core/src/main/java/com/datastrato/gravitino/connector/capability/CapabilityResult.java, core/src/test/java/com/datastrato/gravitino/catalog/TestTableOperationDispatcher.java
1. Introduce catalog capability framework
2. Support `column not null` capability to show how the framework works
Improving code quality
Fix: #1662 
no
existing tests
=> [#1661] feat(core): introduce catalog capability framework

clients/filesystem-hadoop3/src/main/java/com/datastrato/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java, clients/filesystem-hadoop3/src/main/java/com/datastrato/gravitino/filesystem/hadoop/GravitinoVirtualFileSystemConfiguration.java, clients/filesystem-hadoop3/src/test/java/com/datastrato/gravitino/filesystem/hadoop/FileSystemTestUtils.java, clients/filesystem-hadoop3/src/test/java/com/datastrato/gravitino/filesystem/hadoop/TestGvfsBase.java
It will use the path without scheme in tensorflow. This MR will support the path without gvfs scheme.
https://github.com/tensorflow/io/blob/master/tensorflow_io/core/filesystems/hdfs/hadoop_filesystem.cc#L618
https://github.com/tensorflow/io/blob/master/tensorflow_io/core/filesystems/hdfs/hadoop_filesystem.cc#L116
-  support path without Scheme for Hadoop API
- #2860
- no
- UTs pass
=> improve(filesystem-hadoop): support path without scheme for gvfs api

trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/hive/HiveMetadataAdapter.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/iceberg/IcebergMetadataAdapter.java
Use Collections.emptyList() rather than Collections.EMPTY_LIST
Use of Collections.EMPTY_LIST can cause ClassCastException exactions at runtime, better to let the compiler catch these sort of issues.
Fix: #2916 
No
UT
=> [#2916] Improvement(trino): Improvement on Collections. EMPTY_LIST

catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogCapability.java, catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogOperations.java, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveTable.java, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/integration/test/CatalogHiveIT.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergCatalog.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergCatalogCapability.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergCatalogOperations.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/ops/IcebergTableOpsHelper.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/TestIcebergTable.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergIT.java, core/src/main/java/com/datastrato/gravitino/catalog/CapabilityHelpers.java, core/src/main/java/com/datastrato/gravitino/connector/BaseCatalog.java, core/src/main/java/com/datastrato/gravitino/connector/capability/Capability.java
- remove the column default value validation in Hive catalog and Iceberg catalog
- available column default capability in the framework
Fix: #2953 
no
tests added
=> refactor(core): use capability of column default value

catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/operation/MysqlDatabaseOperations.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/TestMysqlDatabaseOperations.java
Backquote the schema(database) name when dropping it. 
We must backquote the name if the name contains special character like `%`, '-', '/' and so on.
Fix: #2634
N/A.
Add new IT `testDropTableWithSpecificName`.
=> [#2634] fix(jdbc-mysql): Fix the backquote issues in drop schema

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/config/JdbcConfig.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/utils/DataSourceUtils.java, catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/utils/TestJdbcConfig.java, docs/jdbc-mysql-catalog.md, docs/jdbc-postgresql-catalog.md
Make the value `testOnBorrow` in JDBC catalogs can be tuned by users.
When we do performance test for the JDBC catalog, we'd better set `testOnBorrow` to false as testing connection is time-consuming 
Fix: #2786 
N/A.
Add unit test.
=> [#2786] improvement(jdbc-common): Make value `testOnBorrow` configurable in JDBC catalog

integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/iceberg/SparkIcebergCatalogIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/spark/SparkUtilIT.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/GravitinoIcebergCatalog.java
Implement `FunctionCatalog` in `GravitinoIcebergCatalog`
Implement `FunctionCatalog` in `GravitinoIcebergCatalog` to support `Iceberg` partition functions.
Fix: https://github.com/datastrato/gravitino/issues/2979
No.
New ITs.
=> [#2979] feat(spark-connector): Implement FunctionCatalog in GravitinoIcebergCatalog

catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/operation/DorisTableOperations.java, catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/DorisTableOperationsIT.java
Increase the maximum wait time from 5 seconds to 30 seconds, which is set in schema alteration test for the Doris table operation
Avoid the instability of the GitHub CI flow.
Github CI flow failed because table schema has not been done.
N/A
Github CI
=> [MINOR]test: Increase the maximum wait time in Doris table operation test

catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/HadoopCatalogOperations.java, catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java
When dropping the schema, if the schema is null or does not exist, then return false.
a clear drop behavior of return value and exception thrown.
Fix: #2913 
No
UT
=> [#2913] Improvement(catalog-hadoop) Return false if the schema is not dropped.

integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/CatalogsPageTest.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/pages/CatalogsPage.java, web/src/app/login/page.js, web/src/app/metalakes/metalake/MetalakeTree.js, web/src/app/metalakes/metalake/rightContent/tabsContent/TabsContent.js, web/src/app/metalakes/metalake/rightContent/tabsContent/detailsView/DetailsView.js, web/src/app/metalakes/metalake/rightContent/tabsContent/tableView/TableView.js, web/src/lib/store/metalakes/index.js
1. add table properties displaying
- partitioning
- sortOrders
- distribution
- indexes
3. modified fileset icon
4. fix tree list refresh table
5. add fileset `type` and `storageLocation` displaying
6. fix login page logo icon error 9cc806574b49d211dd6b734bab9a01ce2ce0e944
Fix: #2861
Fix: #2963
Fix: #2974
N/A
N/A
=> [#2861][#2963][#2974] improve(web): add table properties and fileset fields displaying

build.gradle.kts, core/src/main/java/com/datastrato/gravitino/EntitySerDe.java, core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java, core/src/main/java/com/datastrato/gravitino/meta/CatalogEntity.java, core/src/main/java/com/datastrato/gravitino/meta/FilesetEntity.java, core/src/main/java/com/datastrato/gravitino/meta/GroupEntity.java, core/src/main/java/com/datastrato/gravitino/meta/RoleEntity.java, core/src/main/java/com/datastrato/gravitino/meta/SchemaEntity.java, core/src/main/java/com/datastrato/gravitino/meta/TableEntity.java, core/src/main/java/com/datastrato/gravitino/meta/TopicEntity.java, core/src/main/java/com/datastrato/gravitino/meta/UserEntity.java, core/src/main/java/com/datastrato/gravitino/proto/AuditInfoSerDe.java, core/src/main/java/com/datastrato/gravitino/proto/BaseMetalakeSerDe.java, core/src/main/java/com/datastrato/gravitino/proto/CatalogEntitySerDe.java, core/src/main/java/com/datastrato/gravitino/proto/FilesetEntitySerDe.java, core/src/main/java/com/datastrato/gravitino/proto/GroupEntitySerDe.java, core/src/main/java/com/datastrato/gravitino/proto/ProtoEntitySerDe.java, core/src/main/java/com/datastrato/gravitino/proto/ProtoSerDe.java, core/src/main/java/com/datastrato/gravitino/proto/RoleEntitySerDe.java, core/src/main/java/com/datastrato/gravitino/proto/SchemaEntitySerDe.java, core/src/main/java/com/datastrato/gravitino/proto/TableEntitySerDe.java, core/src/main/java/com/datastrato/gravitino/proto/TopicEntitySerDe.java, core/src/main/java/com/datastrato/gravitino/proto/UserEntitySerDe.java, core/src/main/java/com/datastrato/gravitino/storage/kv/KvEntityStore.java, core/src/test/java/com/datastrato/gravitino/proto/TestEntityProtoSerDe.java
This PR fixes the namespace missing issue when entities are gotten from kv storage.
Fix: #2856 
No.
Modified UTs.
=> [#2856] fix(core): Fix the namespace missing issue when get entities from kv storage

web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js
Disabled update  the "location" property item for fileset catalog
The "location" property of fileset catalog is immutable or reserved
Fix: #2970
Edit a fileset catalog and open the dialog
local e2e test
=> [#2970]fix(UI): disabled update the location property of fileset catalog

clients/client-java/src/main/java/com/datastrato/gravitino/client/GravitinoAdminClient.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/GravitinoClient.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/GravitinoClientBase.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestGravitinoClientBuilder.java
- Support pass header when using the Java Gravitino Client.
- For now, we can't pass the useful header on the Java Gravitino Client. We want to pass on more information such as some audit messages. The base header may not be used for now, but it is useful for users to integrate with their platform. 
Fix: #2976 
- yes
- add `withHeaders` in GravitinoClientBuilder.
```
GravitinoClient.builder("uri")
.withMetalake("metalake")
.withHeaders(Map) // add header
.builder();
GravitinoAdminClient.builder("uri")
.withHeaders(Map) // add header
.builder();
```
2. Addition or removal of property keys.
- add withHeaders() method
- original Uts
=> [#2976] improve(api): support header for gravitino client

.github/workflows/backend-integration-test.yml, .github/workflows/python-integration-test.yml, clients/client-python/build.gradle.kts, clients/client-python/tests/integration/integration_test_env.py, clients/client-python/tests/integration/test_fileset_catalog.py
1. Add `skipPyClientITs` param in Gradle build script. Let's Python client integration test not running in the backend ITs
2. Combined Gradle build command of Python client test and integration test
3. improvement FilesetCatalog integration test codes.
4. Test mode
+ Test Principle: Every Python ITs class base on the `IntegrationTestEnv`, `IntegrationTestEnv` will automatic start and stop Gravitino server to support ITs, But when you run multiple ITs class at same time, The first test class that finishes running will shut down the Gravitino server, which will cause other test classes to fail if they can't connect to the Gravitino server.
+ Run test in the IDE: Through `IntegrationTestEnv` class automatic start and stop Gravitino server to support ITs.
+ Run test in the Github Action: …
=> [#2292] improvement(PyClient): Fix unstable Python client integration test

web/src/app/metalakes/metalake/rightContent/tabsContent/TabsContent.js, web/src/app/metalakes/metalake/rightContent/tabsContent/tableView/TableView.js, web/src/lib/store/metalakes/index.js
fix table properties displaying format
- partitioning:
- <img width="329" alt="image" src="https://github.com/datastrato/gravitino/assets/17310559/009bd5a6-d886-488c-bc2b-4d8da7650622">
- <img width="272" alt="image" src="https://github.com/datastrato/gravitino/assets/17310559/65f68435-699e-4769-b700-4f197c0ea522">
- indexes:
- <img width="230" alt="image" src="https://github.com/datastrato/gravitino/assets/17310559/eb5bcfbc-6146-447e-b732-6e664796e622">
- <img width="257" alt="image" src="https://github.com/datastrato/gravitino/assets/17310559/d61eefaa-8d0d-496c-89c6-ac59f4f288b8">
- distribution:
- <img width="160" alt="image" src="https://github.com/datastrato/gravitino/assets/17310559/a0d457f5-b7b5-4588-9fca-475d1a94c4d1">
- <img width="265" alt="image" …
=> [#3005] fix(web): fix table properties displaying format

web/src/app/metalakes/metalake/MetalakeTree.js, web/src/app/metalakes/metalake/MetalakeView.js, web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js, web/src/app/metalakes/metalake/rightContent/tabsContent/detailsView/DetailsView.js, web/src/lib/store/metalakes/index.js
Load catalogs first when refresh schema or table level page
Fix kafka topic property issue
Fix: #2996, Fix: #3011
When schema, table or fileset page network error, refresh the page
=> [#2996][#3011] fix(web): fix refresh issue and kafka topic property issue

integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/CatalogsPageTest.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/MetalakePageTest.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/hive/TestHivePropertiesConverter.java
assertion arguments should be in the in correct order: expected value, actual value
Fix: #3030 
N/A
exist ut
=> [#3030] fix(test): adjust the order of assertion parameters

docs/how-to-use-gvfs.md
Fix the format of authentication content in gvfs docs.
Fix: #3042
=> [#3042] [MINOR] fix(docs): Fix the authentication content format in gvfs docs

catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/operation/DorisTableOperations.java
Use a string builder rather than concatenation for comment += resultSet.getString("TABLE_COMMENT")
Fix: #3038 
N/A
existing unit tests
=> [#3038] fix(catalog-doris): use a string builder rather than concatenation

integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java, integration-test/build.gradle.kts, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/CatalogsPageKafkaTest.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/CatalogsPageTest.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/pages/CatalogsPage.java, integration-test/src/test/resources/run, web/src/app/metalakes/metalake/rightContent/tabsContent/detailsView/DetailsView.js
…a topic level
Improvement of fileset and kafka test case
Fix: #2896
N/A
=> [#2896] improve(IT): Add e2e test case for verifying fileset schema level and kafka topic level

catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/HadoopCatalog.java, catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/HadoopCatalogCapability.java, catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/HadoopCatalogOperations.java, catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveCatalogOperations.java, catalogs/catalog-kafka/src/main/java/com/datastrato/gravitino/catalog/kafka/KafkaCatalog.java, catalogs/catalog-kafka/src/main/java/com/datastrato/gravitino/catalog/kafka/KafkaCatalogCapability.java, catalogs/catalog-kafka/src/main/java/com/datastrato/gravitino/catalog/kafka/KafkaCatalogOperations.java, catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/TestKafkaCatalogOperations.java, core/src/main/java/com/datastrato/gravitino/catalog/OperationDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/SchemaOperationDispatcher.java, core/src/main/java/com/datastrato/gravitino/connector/BasePropertiesMetadata.java, core/src/test/java/com/datastrato/gravitino/catalog/TestFilesetOperationDispatcher.java, core/src/test/java/com/datastrato/gravitino/catalog/TestOperationDispatcher.java
- remove property `GRAVITINO_MANAGED_ENTITY`
- add managedStorage capability for Hadoop and Kafka catalog
Fix: #2955 
no
existing tests
=> [#2955] refactor(catalogs): use managedStorage capability

catalogs/catalog-kafka/src/main/java/com/datastrato/gravitino/catalog/kafka/KafkaCatalogOperations.java, catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java, core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java
- postpone default schema creation after admin client
- reduced exception nesting
Fix: #3015 
yes, when the Kafka catalog creation fails, use the correct error message
IT added
=> [#3051] fix(kafka-catalog): Make the catalog creation failure exception more accurate

spark-connector/spark-connector-runtime/build.gradle.kts
shade apache hc only
if shading `org.apache`, spark package will be shaded to `com/datastrato/gravitino/shaded/org/apache/spark`, but spark package is not build in spark-connector, leading ClassNotFound exception
Fix: #3059 
no
build spark connector jar and run with spark
=> [#3059] fix(spark-connector):  Failed to run spark sql with spark-connector-runtime.jar

core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java, core/src/main/java/com/datastrato/gravitino/meta/CatalogEntity.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/client/CatalogIT.java
Filter out hidden properties before returning the result in `listCatalogInfo`.
Fix: #2696 
yes, hidden properties will not show in result of `listCatalogInfo`
tests added
=> [#2696] fix(core): list catalog info handle hidden properties

catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/utils/DorisUtils.java, catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/utils/TestDorisUtils.java
Use * instead of {0,} in regular expressions
Fix: #2917
N/A
UT
=> [#2917] fix: Use * instead of {0,} in regular expressions

web/src/app/metalakes/CreateMetalakeDialog.js, web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js, web/src/lib/utils/regex.js
Support for the use of dashes in naming metalake and catalog by web UI.
The dashes is a relatively common usage in naming.
Fix: #3083
N/A
Manually Test
=> [#3083] improve(web): update regular expression of metalake and catalog name

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/MySQLProtocolCompatibleCatalogOperations.java, catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/DorisCatalog.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/MysqlCatalog.java
Introduce a common class `MySQLProtocolCompatibleCatalogOperations` so that any JDBC catalog that is compatible with MySQL protocol can use it. 
It's a bug that need to fix
Fix: #3089 
N/A.
Test locally.
=> [#3089] fix:(jdbc-doris): Make class loaders of Doris Catalog can be GCed normally.

integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/SparkEnvIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/iceberg/SparkIcebergCatalogIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/spark/SparkUtilIT.java
configurate spark time zone to UTC
if not specifying timezone, Iceberg partition path varies for different time zone in local machine.
Fix: #3072 
no
test in local machine
=> [#3072] fix(spark-connector):  fix local run SparkIcebergCatalogIT failed for non-utc timezone

web/src/app/metalakes/metalake/rightContent/tabsContent/TabsContent.js, web/src/app/metalakes/metalake/rightContent/tabsContent/tableView/TableView.js, web/src/lib/store/metalakes/index.js
Fix value displaying and enhance the styles.
Fix: #3058
`[['id', 'b'], ['name'], ['d', 'e'], ['f'], ['g']]`
header:
column:
others:
local
=> [#3058] fix(web): fix value displaying and enhance the styles

docs/spark-connector/spark-catalog-hive.md, docs/spark-connector/spark-catalog-iceberg.md, docs/spark-connector/spark-connector.md
add spark connector document
Fix: #3001
no
document
=> [#3001] docs(spark-connector): add spark connector document

catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergSchema.java
Simplified some nested ternary operator code in catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergSchema.java
Fix: #2915 
Followed testing instructions in how-to-test.md
=> [#2915] improvement(catalog-lakehouse-iceberg): simplify ternary operators

web/src/app/metalakes/metalake/MetalakeTree.js, web/src/app/metalakes/metalake/rightContent/MetalakePath.js, web/src/app/metalakes/metalake/rightContent/RightContent.js, web/src/app/rootLayout/AppBar.js, web/src/components/DetailsDrawer.js
Fix breadcrumbs text display styles.
Fix: #3057 
local
=> [#3057] fix(web): fix breadcrumbs text display styles and appbar layout

web/src/lib/api/catalogs/index.js, web/src/lib/api/filesets/index.js, web/src/lib/api/schemas/index.js, web/src/lib/api/tables/index.js, web/src/lib/api/topics/index.js, web/src/lib/provider/session.js, web/src/lib/store/metalakes/index.js, web/src/lib/utils/axios/index.ts
1. Support special character like '//' for database name or table name and so on.
3. Improvment interceptors of axois for avoide repeat request
4. Fix some runtime errors
N/A
Fix: #3062
N/A
Manual
=> [#3062] fix(web): Support special character like "//" and improve the interceptors of axios

core/src/main/java/com/datastrato/gravitino/connector/capability/Capability.java, core/src/test/java/com/datastrato/gravitino/connector/capability/TestCapability.java
Use \\w instead of [a-zA-Z0-9_] in regexp in Capability.java
Fix: #3078 
N/A
ut
=> [#3078] feat(core): Use \\w instead of [a-zA-Z0-9_] in regexp

api/src/main/java/com/datastrato/gravitino/exceptions/GravitinoRuntimeException.java, catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java, catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/BaseSchemaCatalog.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/FilesetCatalog.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalCatalog.java, core/src/main/java/com/datastrato/gravitino/catalog/CapabilityHelpers.java, core/src/main/java/com/datastrato/gravitino/catalog/FilesetNormalizeDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/SchemaNormalizeDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/TableNormalizeDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/TopicNormalizeDispatcher.java
only validate the name when creating
The constraints of the name spec may be more strict than the underlying catalog
Fix: #3101 
no
tests added
=> [#3101] fix(all): Only validate the name when creating

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcTableOperations.java, catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/operation/PostgreSqlTableOperations.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java
Add check logic about schema name when loading table meta from driver. 
Some drivers , such as PG drivers, contain schema name information, we need to filter it. Some drivers like MySQL don't like it, we do not need to check it. 
check it. 
Fix: #2115 
N/A.
Add ITs: `testCreateSameTableInDifferentSchema`
=> [#2115] fix(jdbc-catalog):  Can't create a table in database with the same name prefix.

core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/client/CatalogIT.java
Check if properties is null before use it.
Without this Gravitino will throw NPE.
Fix: #3139 
No.
IT added.
=> [#3139] fix(core): Fix NPE issue during creating catalog when properties are not specified

docs/manage-table-partition-using-gravitino.md, docs/open-api/partitions.yaml, docs/open-api/tables.yaml
add docs and OAS for drop partition operation
Fix: #3140
no
no
=> [#3140] docs(partition): add docs and OAS for drop partition operation

docs/iceberg-rest-service.md
using `http://127.0.0.1:9001/iceberg/v1/config` to. verify the avaibility of Iceberg service.
The original verify URL is not accessible in some environment.
Fix: #3158 
no
just document
=> [#3158] fix(doc): correct iceberg rest catalog service verify url

core/src/main/java/com/datastrato/gravitino/connector/BaseCatalog.java
Modify the description of `CATALOG_OPERATION_IMPL`, avoid the use of "hack"
Fix: #3081 
No
No need to test
=> [#3081] improvement(core): Remove hack in BaseCatalog.java

integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/SparkEnvIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/hive/SparkHiveCatalogIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/iceberg/SparkIcebergCatalogHiveBackendIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/iceberg/SparkIcebergCatalogIT.java
Refactor Spark-connector IT.
to support more iceberg catalog backends, such as testing hive, jdbc, rest catalog backends.
Fix: https://github.com/datastrato/gravitino/issues/3163
No.
Existing ITs.
=> [#3163] Refactor(spark-connector): Refactor Spark-connector IT to support more iceberg catalog backends

catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/PostgreSQLCatalogOperations.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java
Change the dummy port to a real valid port.
PostgreSQL is different from MySQL and is more strict about obtaining JDBC drivers. We need to provide a real port or we can't the driver. 
Fix: #3161 
N/A.
IT.
=> [#3161] fix(jdbc-pg): Fix getting PostgreSQL jdbc driver error

integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/iceberg/SparkIcebergCatalogIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/spark/SparkMetadataColumnInfo.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/spark/SparkTableInfo.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/spark/SparkTableInfoChecker.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/spark/SparkUtilIT.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/SparkIcebergTable.java
Support retrieve iceberg metadataColumns, such as `_spec_id`,
`_partition`, `_file`, `_pos`, `_deleted`.
Support retrieve iceberg metadataColumns, row-level operations depend on
this.
Fix: https://github.com/datastrato/gravitino/issues/2587
No.
New integration test.
=> [#2587] feat(spark-connector): Support iceberg metadataColumns

catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogOperations.java, catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveClientPool.java
Catch Exception instead of Throwable in HiveCatalogOperations.java and HiveClientPool.java
Fix: #3035 
N/A
exist ut
=> [#3035] fix(catalog-hive): catch Exception instead of Throwable

clients/client-java/src/main/java/com/datastrato/gravitino/client/GravitinoVersion.java
Use ? rather than {0,1} in regex in GravitinoVersion.java
Fix: #3077 
N/A
exist ut
=> [#3077] feat(client): Use ? rather than {0,1} in regex

.github/workflows/backend-integration-test.yml, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/MiniGravitino.java
Trigger integration test when there is a change in module `integration-test-common`. 
We should start the integration test if there are changes in module `integration-test-common`.  however, CI https://github.com/datastrato/gravitino/actions/runs/8872110159/job/24356012525?pr=3197 of PR https://github.com/datastrato/gravitino/pull/3197 can't start the CI pipeline.
Fixed: #3207 
N/A.
CI passed.
=> [#3207] fix(test): Trigger integration test with changes in module `integration-test-common`

integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/DorisContainer.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/HiveContainer.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/KafkaContainer.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/util/AbstractIT.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/util/CloseContainerExtension.java
close containers and upload container log after all tests are finished
Fix: #3024 
N/A
existing ITs
=> [#3024] improvement(IT): close containers and upload container log after all tests are finished

core/src/main/java/com/datastrato/gravitino/storage/relational/JDBCBackend.java, core/src/main/java/com/datastrato/gravitino/storage/relational/RelationalGarbageCollector.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/FilesetVersionMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/po/FilesetMaxVersionPO.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/FilesetMetaService.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/util/AbstractIT.java, integration-test/build.gradle.kts, integration-test/src/test/java/com/datastrato/gravitino/integration/test/store/relational/service/FilesetMetaServiceIT.java
When obtaining the maximum version result of fileset, pass the result into the object to solve the `ClassCastException` problem.
Fix: #3190 
Add some ITs.
=> [#3190] fix(jdbc-backend): Fix the cast issue when Relational Garbage Collector cleaning fileset version info

common/src/main/java/com/datastrato/gravitino/config/ConfigEntry.java, common/src/test/java/com/datastrato/gravitino/config/TestConfigEntryList.java, core/src/main/java/com/datastrato/gravitino/Configs.java, core/src/test/java/com/datastrato/gravitino/authorization/TestAccessControlManagerForPermissions.java
Fix the issue of method `checkValue` in the ConfigOption. If we use `checkValue` in the wrong position, it won't work.
Fix: #3216
No.
UT.
=> [#3216] fix(core): Fix the issue of method `checkValue` in the ConfigOption

catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/HTTPClient.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/client/CatalogIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/client/MetalakeIT.java
Currently in the java client, the json result is not encoded with `UTF-8` when requesting the server, which will cause some Chinese characters to be garbled.It will use `ISO_8859_1` as default. This PR fixed this.
Fix: #3165 
Add some ITs.
=> [#3165] fix(client-java): Fix the http client `toJson` encode without UTF-8

integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/TrinoContainer.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java
use simple catalog name in `com.datastrato.gravitino.integration.test.container.TrinoContainer#checkSyncCatalogFromGravitino`, and verify it where it is called.
Fix: #3237 
N/A
ITs
=> [#3237] fix(IT): use simple catalog name in `TrinoContainer`

trino-connector/src/test/java/com/datastrato/gravitino/trino/connector/TestGravitinoConnector.java, trino-connector/src/test/java/com/datastrato/gravitino/trino/connector/TestGravitinoConnectorWithMetalakeCatalogName.java
Fixed assertion
Fix:  #3251
No
Ran test locally multiple times
=> [3251] Improvement: fix assertion

integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/CatalogsPageTest.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/hive/TestHivePropertiesConverter.java
Equality assertions did not have correct expected and actual order. 
Provides code clarity. 
Fix: #3252 
No
Test only changes and ran associated tests.
=> [#3252] Improvement(IT): Test arguments should be in the right order

catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/web/metrics/TestIcebergMetricsManager.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/DorisContainer.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/HiveContainer.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/MySQLContainer.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/TrinoContainer.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoConnectorIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoQueryIT.java
use `Awaitility#await` instead of `Thread#sleep`
Fix: #3214 
N/A 
ITs
=> [#3214] improvement(IT): use `Awaitility#await` instead of `Thread#sleep`

clients/client-python/.gitignore, clients/client-python/build.gradle.kts, clients/client-python/gravitino/api/supports_schemas.py, clients/client-python/gravitino/client/gravitino_admin_client.py, clients/client-python/gravitino/client/gravitino_client_base.py, clients/client-python/gravitino/client/gravitino_metalake.py, clients/client-python/gravitino/dto/dto_converters.py, clients/client-python/gravitino/dto/requests/fileset_updates_request.py, clients/client-python/gravitino/dto/responses/entity_list_response.py, clients/client-python/gravitino/dto/responses/schema_response.py, clients/client-python/gravitino/exceptions/gravitino_runtime_exception.py, clients/client-python/gravitino/exceptions/illegal_name_identifier_exception.py, clients/client-python/gravitino/exceptions/illegal_namespace_exception.py, clients/client-python/gravitino/exceptions/no_such_metalake_exception.py, clients/client-python/gravitino/exceptions/not_found_exception.py, clients/client-python/gravitino/name_identifier.py, clients/client-python/gravitino/utils/http_client.py, clients/client-python/pylintrc, clients/client-python/requirements-dev.txt, clients/client-python/tests/integration/integration_test_env.py, clients/client-python/tests/integration/test_metalake.py
* Add pylint rule for logging, logging should use old format (%), not fstring
* Unify all the logging format
* Set many disable rules for future modification (I add TODO tags after them, will work on them after this PR)
Fix: #3203 
No
```bash
./gradlew :clients:client-python:test
```
=> [#3203] improvement(PyClient): Add pylint Rules for Python client

catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/operation/DorisDatabaseOperations.java, catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/TestDorisDatabaseOperations.java
Filter system database `information_schema` when `list` or `get` table for Doris catalogs. 
The system database/table should not be accessible to users directly, and both MySQL and PG have filtered it. 
Fix: #3275 
N/A
Added test `testListSystemDatabase`.
=> [#3275] improvement(jdbc-doris): Filter system database like `information_schema` for Doris catalog.

clients/filesystem-hadoop3/src/main/java/com/datastrato/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java, clients/filesystem-hadoop3/src/test/java/com/datastrato/gravitino/filesystem/hadoop/TestGvfsBase.java
replace the non-capturing group `?:` with independent, non-capturing group (atomic group) `?>` to eliminate backtracking.
To prevent stack overflow
Fix: #3037 
Fix: #3086 
N/A
Add UT
=> [#3037][#3086] improve(catalog-hadoop): Improve regexp in GravitinoVirtualFileSystem.java

catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/integration/test/TestJdbcAbstractIT.java, catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/DorisTableOperationsIT.java
- Update distribution num to 2, which may make IT more staleable
- update `assertColumn` in TestJdbcAbstractIT, message is clearer when type is not as expected 
make Doris IT more staleable
N/A
Mannual
=> [MINOR] refactor: update distribution parameters for Doris Test

core/src/main/java/com/datastrato/gravitino/storage/relational/RelationalEntityStore.java, core/src/test/java/com/datastrato/gravitino/storage/TestEntityStorage.java
When Relational Entity Store deleteing an entity and throwing a NoSuchEntityException, return false finally. It's consistent with KV Store.
Fix: #3092 
Add some duplicate deleted uts.
=> [#3092] fix(relational-entity-store): Return false when deleting throw a `NoSuchEntityException`

core/src/main/java/com/datastrato/gravitino/GravitinoEnv.java, core/src/main/java/com/datastrato/gravitino/catalog/CapabilityHelpers.java, core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java, core/src/main/java/com/datastrato/gravitino/catalog/OperationDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/PartitionDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/PartitionNormalizeDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/PartitionOperationDispatcher.java, core/src/test/java/com/datastrato/gravitino/TestTable.java, core/src/test/java/com/datastrato/gravitino/TestTableOperations.java, core/src/test/java/com/datastrato/gravitino/catalog/TestPartitionNormalizeDispatcher.java, core/src/test/java/com/datastrato/gravitino/catalog/TestPartitionOperationDispatcher.java, core/src/test/java/com/datastrato/gravitino/catalog/TestTopicNormalizeDispatcher.java, server/src/main/java/com/datastrato/gravitino/server/GravitinoServer.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/PartitionOperations.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestPartitionOperations.java
- reuse the class loader of the catalog for partition operation
- add partition operation dispatcher
Fix: #2997 #2999 
no
tests added
=> [#2999][#2997] improvement(partition): add partition operation dispatcher

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcTableOperations.java, catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/CatalogDorisDriverIT.java, catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/CatalogDorisIT.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlDriverIT.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
replace `DatabaseMetaData#getSchema` by `DatabaseMetaData#getCatalog` and provide a more general way to get tables through jdbc driver
jdbc driver `DatabaseMetaData#getSchema` method return null causes list tables failure on some jdbc mysql 8.x driver (mysql-connector-java-8.0.11). 
Fix: #3269
not
=> [#3269] fix(jdbc-mysql): Solve DatabaseMetaData#getSchema return null cause list tables error on some jdbc 8.x driver

clients/client-java-runtime/build.gradle.kts, spark-connector/spark-connector-runtime/build.gradle.kts
shadow slf4j for client-java-runtime and spark-connector-runtime 
some systems like spark 3.3 need low version log4j, will encounter the conflict bug:
```
java.lang.NoSuchMethodError: org.apache.logging.slf4j.Log4jLoggerFactory: method 'void <init>()' not found
```
fix: #3320 
no
existing tests
=> [#3320] fix(client): shadow slf4j for client-java-runtime 

clients/filesystem-hadoop3/build.gradle.kts, clients/filesystem-hadoop3/src/main/java/com/datastrato/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java, clients/filesystem-hadoop3/src/main/java/com/datastrato/gravitino/filesystem/hadoop/GravitinoVirtualFileSystemConfiguration.java, clients/filesystem-hadoop3/src/test/java/com/datastrato/gravitino/filesystem/hadoop/GravitinoMockServerBase.java, clients/filesystem-hadoop3/src/test/java/com/datastrato/gravitino/filesystem/hadoop/KdcServerBase.java, clients/filesystem-hadoop3/src/test/java/com/datastrato/gravitino/filesystem/hadoop/TestKerberosClient.java, docs/how-to-use-gvfs.md
Support using Kerberos authentication type to initialize Gravitino client in gvfs.
Fix: #2711 
Add some uts for: 
1. use principal and keytab to auth.
2. kerberos configs for gvfs.
3. some invalid kerberos case.
Test locally and use `kerberos ticket cache` to initialize gvfs. The steps are as follows: 
1. Deploy the KDC server locally, refer to the doc: https://blog.csdn.net/lo085213/article/details/105057186.
2. Register the service account `HTTP/localhost@HADOOP.COM` and client account `client@HADOOP.COM` in the KDC server.
3. Execute the `kinit -kt client.keytab client@HADOOP.COM` command locally.
4. Use the `klist` command to check the environment for tickets containing `client@HADOOP.COM`.
5. Write a unit test to load metalake through gvfs with the kerberos ticket cache.
=> [#2711] feat(filesystem): Support Kerberos client authentication in gvfs

catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/operation/DorisTableOperations.java
Output the alter status of table into the log
Fix: #3326
N/A
Manual, check log
=> [#3326] feat(jdbc-doris): output the alter status of table into the log

.github/workflows/python-integration-test.yml, clients/client-python/build.gradle.kts, clients/client-python/tests/integration/test_metalake.py, clients/client-python/tests/unittests/test_metalake.py
1. Add `skipITs` build params in the Python Client Gradle script.
2. Use different directory storage integration test and unit tests.
When running this command ./gradlew test -PskipITs directly. the Gradle python test task will be failed because of lacking compileDistribution step. we should fix it to make all the commands work.
Fix: #3319
N/A
CI Passed
=> [#3319] fix(PyClient): ./gradlew test -PskipITs failed in python-client

docs/apache-hive-catalog.md, docs/lakehouse-iceberg-catalog.md, docs/spark-connector/spark-catalog-hive.md, docs/spark-connector/spark-catalog-iceberg.md, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/PropertiesConverter.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/hive/GravitinoHiveCatalog.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/hive/HivePropertiesConverter.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/GravitinoIcebergCatalog.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConstants.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConverter.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/hive/TestHivePropertiesConverter.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/iceberg/TestIcebergPropertiesConverter.java
1. passing Gravitino catalog properties with `spark.bypass.` prefix to spark connector
2. refactor the catalog properties transform logic.
Fix: #3292
yes, add document
1. add UT
3. test in local envriment
=> [#3292] fix(spark-connector): passing Gravitino catalog properties to spark connector

api/src/main/java/com/datastrato/gravitino/rel/expressions/transforms/Transform.java, api/src/main/java/com/datastrato/gravitino/rel/expressions/transforms/Transforms.java, api/src/main/java/com/datastrato/gravitino/rel/partitions/Partitions.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalCatalog.java, common/src/main/java/com/datastrato/gravitino/dto/rel/partitioning/ListPartitioningDTO.java, common/src/main/java/com/datastrato/gravitino/dto/rel/partitioning/RangePartitioningDTO.java, common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java, common/src/main/java/com/datastrato/gravitino/json/JsonUtils.java, common/src/test/java/com/datastrato/gravitino/json/TestDTOJsonSerDe.java, docs/open-api/partitioning.yaml, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestTableOperations.java
enable pre-assign partition when creating range and list partitioning table
Fix: #2266 
yes, enable pre-assign partition when creating range and list partitioning table
tests modified
=> [#2266] fix(partition): enable preassign partition when creating range and list partitioning table

clients/client-python/gravitino/client/gravitino_admin_client.py, clients/client-python/gravitino/client/gravitino_metalake.py, clients/client-python/gravitino/dto/version_dto.py, clients/client-python/gravitino/name_identifier.py, clients/client-python/gravitino/namespace.py, clients/client-python/gravitino/typing.py, clients/client-python/gravitino/utils/http_client.py, clients/client-python/pylintrc, clients/client-python/tests/integration/integration_test_env.py
- Define naming style of each class, module, function and variable
- See `pylintrc` for detail settings
Fix: #3205 
No
No
=> [#3205] improvement(client-python): Apply naming convention to client-python

docs/spark-connector/spark-catalog-iceberg.md, integration-test/build.gradle.kts, integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/SparkCommonIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/hive/SparkHiveCatalogIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/iceberg/SparkIcebergCatalogIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/spark/SparkTableInfo.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/util/spark/SparkUtilIT.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/ConnectorConstants.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/SparkTransformConverter.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/catalog/BaseCatalog.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/hive/GravitinoHiveCatalog.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/hive/SparkHiveTable.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/GravitinoIcebergCatalog.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/SparkIcebergTable.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/plugin/GravitinoDriverPlugin.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/utils/ConnectorUtil.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/utils/GravitinoTableInfoHelper.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/utils/TestConnectorUtil.java
- refactor table implementation, make `SparkIcebergTable` extend Iceberg `SparkTable`, and `SparkHiveTable` extend Kyuubi `HiveTable`.
- support row-level operations to iceberg Table
```
1. update tableName set c1=v1, c2=v2, ...
2. merge into targetTable t
using sourceTable s
on s.key=t.key
when matched then ...
when not matched then ...
3. delete from table where xxx
```
1. For spark-connector in Iceberg, it explicitly uses `SparkTable` to identify whether it is an Iceberg table, so the `SparkIcebergTable` must extend `SparkTable`.
2. support row-level operations to iceberg Table.
Fix: https://github.com/datastrato/gravitino/issues/2543
Yes, support update ... , merge into ..., delete from ...
New ITs.
=> [#2543] feat(spark-connector): support row-level operations to iceberg Table

catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergCatalogBackend.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/utils/IcebergCatalogUtil.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergBaseIT.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergHiveIT.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergRestIT.java, docs/lakehouse-iceberg-catalog.md
Add Iceberg `RestCatalog` backend in Gravitino
As discussed in https://github.com/datastrato/gravitino/issues/2716, we should support Iceberg `RESTCatalog` in Gravitino, and after supporting this, we can use `RESTCatalog` in spark-connector.
Fix: https://github.com/datastrato/gravitino/issues/3149
No
New UTs and ITs.
And tested locally.
=> [#3149] feat(catalog-lakehouse-iceberg): Support Iceberg RestCatalog in Gravitino

web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js, web/src/app/rootLayout/VersionView.js, web/src/lib/utils/initial.js
Add a default optional properties for fileset catalog
Remove fix width of version component
Although the location property is optional, it is better to be there for ease of use
The width of version component is should be flexible
Fix: #3257
N/A
manual
=> [#3257] fix(web): add a default optional properties for fileset catalog

web/src/app/rootLayout/AppBar.js
disable the metalake select with only one
With only one metalake UI presents user with a choice
Fix: #3285
N/A
manual
=> [#3285] fix(web): disable the metalake select with only one

web/LICENSE, web/src/app/login/page.js, web/src/app/rootLayout/AppBar.js, web/src/lib/styles/globals.css
Fix font family of the Gravitino title.
Before:
After:
Fix: #3386
Change to the true font family.
N/A
=> [#3386] fix(web): fix font family of the gravitino title

integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/CatalogsPageTest.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/pages/CatalogsPage.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/AbstractWebIT.java, web/src/app/metalakes/metalake/rightContent/tabsContent/TabsContent.js, web/src/app/metalakes/metalake/rightContent/tabsContent/tableView/TableView.js
add checking table properties to the web e2e test
Fix: #3210
N/A
IT
=> [#3210] improve(web): add checking table properties to the web e2e test

web/src/lib/utils/initial.js
Rename the ASF providers to their correct names.
Fix: #3288
IT
=> [#3288] improve(web): rename the ASF providers to their correct names

clients/client-java/src/main/java/com/datastrato/gravitino/client/GravitinoClientBase.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/HTTPClient.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/OAuth2ClientUtil.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/ObjectMapperProvider.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestBase.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestHTTPClient.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestOAuth2TokenProvider.java, common/src/main/java/com/datastrato/gravitino/json/JsonUtils.java, server/src/main/java/com/datastrato/gravitino/server/web/ConfigServlet.java, server/src/main/java/com/datastrato/gravitino/server/web/ObjectMapperProvider.java
1. provide separate method to get object mapper in  client and service side
2. rename `JsonUtils.objectMapper` to `JsonUtils.objectMapperForTest`
Fix: #3313 
no
existing tests
=> [#3313] feat(common): refactor JsonUtils object mapper to client and service side

integration-test/build.gradle.kts, integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/SparkEnvIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/iceberg/SparkIcebergCatalogRestBackendIT.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConstants.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConverter.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/iceberg/TestIcebergPropertiesConverter.java
Support Iceberg `RestCatalog` in spark-connector.
Add IT for Iceberg `RestCatalog` with HiveCatalog backend.
without this, spark-connector does not support Iceberg `RestCatalog`
Fix: https://github.com/datastrato/gravitino/issues/3193
No.
New ITs.
=> [#3193] feat(spark-connector): Support Iceberg RestCatalog in spark-connector

api/src/test/resources/log4j2.properties, catalogs/catalog-hadoop/src/test/resources/log4j2.properties, catalogs/catalog-hive/src/test/resources/log4j2.properties, catalogs/catalog-jdbc-doris/src/test/resources/log4j2.properties, catalogs/catalog-jdbc-mysql/src/test/resources/log4j2.properties, catalogs/catalog-jdbc-postgresql/src/test/resources/log4j2.properties, catalogs/catalog-kafka/src/main/java/com/datastrato/gravitino/catalog/kafka/KafkaCatalogOperations.java, catalogs/catalog-kafka/src/main/resources/kafka.conf, catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java, catalogs/catalog-kafka/src/test/resources/log4j2.properties, catalogs/catalog-lakehouse-iceberg/src/test/resources/log4j2.properties, clients/client-java/src/test/java/resources/log4j2.properties, clients/client-java/src/test/resources/log4j2.properties, common/src/test/java/resources/log4j2.properties, core/src/test/resources/log4j2.properties, dev/docker/trino/conf/log4j2.properties, integration-test/src/test/resources/log4j2.properties, server/src/test/resources/log4j2.properties, spark-connector/spark-connector/src/test/resources/log4j2.properties
-  Transmit the real reason for the error to the user
- shorten timeout from 60s to 15s
- add thread info to the log
- add default timeout config to the conf file
Fix: #3249 
no
test added
=> [#3249] improvement(kafka-catalog): clarify error message and shorten timeout

catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java
fix use wrong `createCatalog` method
client API changed
no
no
=> [MINOR] fix use wrong createCatalog method

web/src/app/metalakes/TableBody.js
Fix metalake list actions focus when using keyboard key:tab.
Fix: #3248 
When using keyboard key:tab to row actions:
local
=> [#3248] fix(web): fix metalake list actions focus when using keyboard key:tab

.gitignore, common/build.gradle.kts, common/src/main/java/com/datastrato/gravitino/Version.java
The naming of `project.properties` may conflict with other dependencies. When the class loading order is uncertain, it will cause the version comparison of the client and server to fail because of using the file of other dependencies. The naming rules here refer to Gluten(https://github.com/apache/incubator-gluten/blob/main/dev/gluten-build-info.sh).
Fix: #3434
=> [#3434] Improvement(build): Avoid name conflicts with `project.properties`

web/src/app/rootLayout/AppBar.js
fix next/image component src issue
Fix: #3413
Before
After
smoke test
=> [#3413] fix(web): fix logo error

integration-test/src/test/java/com/datastrato/gravitino/integration/test/spark/iceberg/SparkIcebergCatalogIT.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/catalog/BaseCatalog.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/hive/GravitinoHiveCatalog.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/GravitinoIcebergCatalog.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/SparkIcebergTable.java
Support Iceberg time travel in SQL queries
supports time travel in SQL queries using `TIMESTAMP AS OF`, `FOR SYSTEM_TIME AS OF` or `VERSION AS OF`, `FOR SYSTEM_VERSION AS OF` clauses.
Fix: https://github.com/datastrato/gravitino/issues/3264
No.
New ITs.
=> [#3264] feat(spark-connector): Support Iceberg time travel in SQL queries

clients/client-python/MANIFEST.in, clients/client-python/build.gradle.kts, clients/client-python/setup.py, docs/how-to-use-python-client.md, docs/how-to-use-the-playground.md
1. Update markdown file
2. Optimized Gradle script in the Python client module.
1. add missing Python tab switch params in the `how-to-use-python-client.md`
3. Optimized Gravitino Python client Gradle build script
Fix: #3422
N/A
CI Passed
=> [#3422]improve(doc, build): Set code tab switching params in the Python Client doc

catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveTable.java, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/integration/test/CatalogHiveIT.java
Fix order of sort column for ascending sort direction should be 1.
The order of ascending sort direction should be 1 that refers to [L34](https://github.com/apache/hive/blob/master/ql/src/java/org/apache/hadoop/hive/ql/util/DirectionUtils.java#L34). Meanwhile, `HiveClientImpl` return empty sort columns for descending sort direction in spark connector which refers to [L461](https://github.com/apache/spark/blob/master/sql/hive/src/main/scala/org/apache/spark/sql/hive/client/HiveClientImpl.scala#L461).
Fix: #3128 
No.
- `CatalogHiveIT`
=> [#3128] bugfix(hive): fix order of sort column for ascending sort direction should be 1

.github/workflows/docker-image.yml, build.gradle.kts, dev/docker/build-docker.sh, dev/docker/kerberos-hive/Dockerfile, dev/docker/kerberos-hive/check-status.sh, dev/docker/kerberos-hive/core-site.xml, dev/docker/kerberos-hive/hadoop-env.sh, dev/docker/kerberos-hive/hdfs-site.xml, dev/docker/kerberos-hive/hive-dependency.sh, dev/docker/kerberos-hive/hive-site.xml, dev/docker/kerberos-hive/kadm5.acl, dev/docker/kerberos-hive/kdc.conf, dev/docker/kerberos-hive/krb5.conf, dev/docker/kerberos-hive/mapred-site.xml, dev/docker/kerberos-hive/start.sh, dev/docker/kerberos-hive/yarn-env.sh, dev/docker/kerberos-hive/yarn-site.xml, docs/docker-image-details.md
Add all the Docker image files required by Hive with Kerberos enabled.
We need to confirm that everything goes smoothly in a Kerberos-enabled Hive cluster.
Fix: #2226 
N/A
Test locally.
=> [#2226] dev(docker): Add a Hive with Kerberos mode Docker image

catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/converter/MysqlTypeConverter.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/converter/TestMysqlTypeConverter.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/MysqlTableOperationsIT.java
- map `datetime` of MySQL to `timestamp` of Gravitino
- map `timestamp` of MySQL to `timestamp_tz` type of Gravitino.
unify the type semantics
Fix: #1761 
no
tests added
=> [#1761] fix(mysql)clarify `timestamp` and `datetime` type convert

catalogs/catalog-hadoop/build.gradle.kts, catalogs/catalog-hive/build.gradle.kts, catalogs/catalog-lakehouse-iceberg/build.gradle.kts, dev/docker/build-docker.sh, dev/docker/hive/Dockerfile, dev/docker/hive/start.sh, docs/docker-image-details.md, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java, integration-test/build.gradle.kts
Use multi-stage build to reduce hive image size from 2.27GB to 1.83GB.
I use first stage to download archive file and unzip them, then in the final stage, copied them to destination directory.
Fix: #3262 
No.
Unit tests.
=> refactor(dev/docker/hive): shrink hive Docker image size by 420MB

core/src/main/java/com/datastrato/gravitino/storage/relational/JDBCBackend.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/GroupMetaMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/GroupRoleRelMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/RoleMetaMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/UserMetaMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/mapper/UserRoleRelMapper.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/GroupMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/RoleMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/UserMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/utils/SessionUtils.java, core/src/test/java/com/datastrato/gravitino/storage/relational/TestJDBCBackend.java, core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestGroupMetaService.java, core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestRoleMetaService.java, core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestUserMetaService.java
support clean user, group and role entity in RelationalGarbageCollector
Fix: #3188 
N/A
ut
=> [#3188] feat(core): Clean user,group and role entity in RelationalGarbageCollector

catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/FromIcebergSortOrder.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/ToIcebergSortOrder.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/TestIcebergTable.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/TestBaseConvert.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/TestFromIcebergSortOrder.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/TestToIcebergSortOrder.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergBaseIT.java
Add width param to bucket and truncate functions in Gravitino SortOrder.
for example:
change `bucket([id]) `to `bucket(10, id)`
change `truncate([name]) `to `truncate(2, name)`
SortOrder in Iceberg supports `FunctionExpression`, such as `year,
month, bucket, truncate, etc`.
`truncate` and `bucket` functions both have two parameters, such as
`bucket(10, col1), truncate(2, col2)`.
However, in gravitino, when converting an iceberg sortorder with
`bucket` or `truncate` to gravitino sortOrder, there is only one
parameter in `bucket` and `truncate` functions.
This picture shows the details of the parameters of the `bucket` and
`truncate` functions in gravitino sortorder, we can test it in
`com.datastrato.gravitino.catalog.lakehouse.iceberg.converter.TestFromIcebergSortOrder#testFromSortOrder` …
=> [#2921] fix(catalog-lakehouse-iceberg): Add width param to bucket and truncate functions in Gravitino SortOrder

gradle/libs.versions.toml, integration-test/build.gradle.kts, spark-connector/spark-connector-runtime/build.gradle.kts, spark-connector/spark-connector/build.gradle.kts, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/SparkTransformConverter.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/hive/HivePropertiesConverter.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/TestSparkTransformConverter.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/hive/TestHivePropertiesConverter.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/SparkCommonIT.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/SparkEnvIT.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/hive/SparkHiveCatalogIT.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/iceberg/SparkIcebergCatalogHiveBackendIT.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/iceberg/SparkIcebergCatalogIT.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/iceberg/SparkIcebergCatalogRestBackendIT.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/util/SparkMetadataColumnInfo.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/util/SparkTableInfo.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/util/SparkTableInfoChecker.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/util/SparkUtilIT.java
move spark connector integration test from integration-test module to spark-connector
Fix: #3305 
no
moving test location
=> [#3305] test(spark-connector): move spark connector integration test from integration-test module to spark-connector

clients/client-python/gravitino/name_identifier.py, clients/client-python/tests/unittests/test_name_identifier.py
Fix `hash()` function in `name_identifier`.
Fix: #3521 
Add a ut.
=> [#3521] fix(client-python): Fix `hash()` function with multiple variables issue in `name_identitifer`

catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java, clients/client-python/tests/integration/test_fileset_catalog.py, clients/client-python/tests/integration/test_metalake.py, clients/client-python/tests/integration/test_schema.py, core/src/main/java/com/datastrato/gravitino/GravitinoEnv.java, core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java, core/src/main/java/com/datastrato/gravitino/catalog/CatalogNormalizeDispatcher.java, core/src/main/java/com/datastrato/gravitino/connector/capability/Capability.java, core/src/main/java/com/datastrato/gravitino/metalake/MetalakeManager.java, core/src/main/java/com/datastrato/gravitino/metalake/MetalakeNormalizeDispatcher.java, core/src/test/java/com/datastrato/gravitino/catalog/TestCatalogNormalizeDispatcher.java, core/src/test/java/com/datastrato/gravitino/metalake/TestMetalakeNormalizeDispatcher.java
- Check name spec when creating and renaming catalogs or metalakes
Fix: #3202 
yes, catalogs and metadata lakes have a much stricter name specification.
tests added
=> [#3202] improvement(core): add name spec for catalog and metalake

clients/client-python/gravitino/catalog/fileset_catalog.py
* Change the suggest type of `type` from `Catalog.Type` to `Fileset.Type`
Fix: #3508 
No
`./gradlew :clients:client-python:test`
=> [#3058] improvement(client-python): Correct type specification of create_fileset function

api/src/main/java/com/datastrato/gravitino/MetadataObject.java, api/src/main/java/com/datastrato/gravitino/authorization/SecurableObject.java, api/src/main/java/com/datastrato/gravitino/authorization/SecurableObjects.java, api/src/main/java/com/datastrato/gravitino/exceptions/NoSuchTagException.java, api/src/main/java/com/datastrato/gravitino/exceptions/TagAlreadyExistsException.java, api/src/main/java/com/datastrato/gravitino/tag/SupportsTags.java, api/src/main/java/com/datastrato/gravitino/tag/Tag.java, api/src/main/java/com/datastrato/gravitino/tag/TagChange.java, api/src/main/java/com/datastrato/gravitino/tag/TagOperations.java, api/src/test/java/com/datastrato/gravitino/authorization/TestSecurableObjects.java
This PR adds the API support for Tag system in Gravitino.
This is the first step to add a tag system.
Fix: #3460 
Yes.
No. Test will be added later when implementing the logic.
=> [#3460] feat(api): Add API design for Tag system

build.gradle.kts, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/util/CloseContainerExtension.java
- clarify OrbStack status
- check the docker env before IT start
The previous detection logic was located in the constructor, and when the test failed, it would throw an exception `ExceptionInInitializerError`, causing the original error to be covered.
Fix: #3336 
no
Locally, by hand
=> [#3336] improvement(test): make docker detection failure error messages more clear

clients/client-python/.gitignore, clients/client-python/build.gradle.kts, clients/client-python/requirements-dev.txt
* Merge test coverage into Gradle tasks
* Generate html report for both unit and integration tests (`htmlcov/index.html` under their folders)
The generated html report is as follows:
Unit Test Covergae:
Integration Test Coverage:
Fix: #3517
No
=> [#3517] improvement(client-python): Add Coverage as python test coverage tool

LICENSE, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergTable.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergTablePropertiesMetadata.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/DescribeIcebergSortOrderVisitor.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/utils/IcebergTablePropertiesUtil.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConstants.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/iceberg/SparkIcebergCatalogIT.java
Add reserved properties to Table properties when load an Iceberg table, such as:
```
provider,
format,
current-snapshot-id,
location,
format-version,
sort-order,
identifier-fields
```
for example, when execute `desc extended IcebergTableName`，it will get some information from the result properties of this Iceberg table, so it should contain the above properties.
Fix: https://github.com/datastrato/gravitino/issues/2962
No.
New UTs and ITs.
=> [#2962] feat(catalog-lakehouse-iceberg): Add reserved properties to Iceberg Table Properties in Gravitino

dev/docker/kerberos-hive/core-site.xml, dev/docker/kerberos-hive/start.sh, docs/docker-image-details.md
- Add a principal for Gravitino web server named 'HTTP/localhost@HADOOPKRB'.
- Fix bugs about the configuration of proxy users. 
To serve user authentication e2e test. 
Fix: #3548 
N/A.
Test locally.
=> [#3548] fix(dev): Create a new image to add a principal for Gravitino web server and fix several bugs about proxy users

docs/spark-connector/spark-catalog-iceberg.md, docs/spark-connector/spark-connector.md, spark-connector/spark-connector-runtime/build.gradle.kts, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/GravitinoSparkConfig.java, spark-connector/spark-connector/src/main/java/com/datastrato/gravitino/spark/connector/plugin/GravitinoDriverPlugin.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/SparkEnvIT.java, spark-connector/spark-connector/src/test/java/com/datastrato/gravitino/spark/connector/plugin/TestGravitinoDriverPlugin.java
remove iceberg runtime from spark-connector jar
Fix: #3396 
yes add document
set `enableIcebergSupport` == true,  could use Iceberg catalog with extra iceberg-runtime jars. had tested iceberg 1.4,1.3,1.5 jars
not set `enableIcebergSupport`, could only use hive catalog.
=> [#3396] feat(spark-connector): remove iceberg runtime from spark-connector jar

web/src/lib/provider/session.js, web/src/lib/store/auth/index.js, web/src/lib/utils/axios/checkStatus.ts, web/src/lib/utils/axios/index.ts
Improve the user experience of refreshing the oauth token.
Fix: #3009
When the user doesn't interact with the interface for 30 minutes, they will be brought back to the login page.
Local
=> [#3009] improve(web): improve the user experience of refreshing the oauth token

clients/client-python/gravitino/api/catalog_change.py, clients/client-python/gravitino/api/fileset_change.py, clients/client-python/gravitino/api/metalake_change.py, clients/client-python/gravitino/api/schema_change.py, clients/client-python/gravitino/catalog/base_schema_catalog.py, clients/client-python/gravitino/catalog/fileset_catalog.py, clients/client-python/gravitino/client/gravitino_client.py, clients/client-python/gravitino/client/gravitino_metalake.py, clients/client-python/gravitino/dto/catalog_dto.py, clients/client-python/gravitino/dto/dto_converters.py, clients/client-python/gravitino/dto/requests/catalog_create_request.py, clients/client-python/gravitino/dto/requests/catalog_update_request.py, clients/client-python/gravitino/dto/requests/fileset_create_request.py, clients/client-python/gravitino/dto/requests/fileset_update_request.py, clients/client-python/gravitino/dto/requests/metalake_update_request.py, clients/client-python/gravitino/dto/requests/schema_update_request.py, clients/client-python/pylintrc, clients/client-python/tests/integration/test_fileset_catalog.py, clients/client-python/tests/integration/test_schema.py
* Replace varaible names `type` and `property`, which is Python functions and keywords, with more readable and custom variable names
Fix: #3561 
No
=> [#3561] improvement(client-python): Fix redefined-builtin Pylint rule for client-python

clients/client-java-runtime/build.gradle.kts, core/src/main/java/com/datastrato/gravitino/connector/PropertyEntry.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/metadata/GravitinoCatalog.java
relocate `org.apache.logging.log4j` in `clients-java-runtime`
Fix: #3564 
no
1. existing UTs
2. start spark connector in spark 3.3 envriment
=> [#3564] fix(client): spark connector failed to start in real spark3.3 envriment 

.github/workflows/cron-integration-test.yml
Skip running cron-integration-test job in fork repo by default.
Fix: #3571 
N/A
Test on fork repo:
=> [#3571] fix(CI): Skip cron job in fork repo by default.

api/src/main/java/com/datastrato/gravitino/rel/types/Types.java, common/src/main/java/com/datastrato/gravitino/json/JsonUtils.java, common/src/test/java/com/datastrato/gravitino/json/TestJsonUtils.java
use `UnparedType` to represent unknow types
ensure the compatibility between higher version servers and lower version clients
Fix: #3598 
no
UT added
=> [#3598] fix(common): fix compatibility of type serde

clients/client-python/requirements-dev.txt
As title, specify pylint version in order to avoid unexpected bugs in the future development.
Fix: #3558
No.
`./gradlew build -x test` or `./gradlew :clients:client-python:pylint` for for the convenience.
=> [#3558] fix(client-python): specified tests packages version

web/LICENSE, web/src/app/login/page.js, web/src/app/rootLayout/AppBar.js
replace the Alata font family with Roboto
before: 
after:
Fix: #3593
N/A
N/A
=> [#3593] fix(web): replace the Alata font family with Roboto whose license is under the Apache Software License 2.0

api/src/main/java/com/datastrato/gravitino/rel/types/Type.java, api/src/main/java/com/datastrato/gravitino/rel/types/Types.java, api/src/test/java/com/datastrato/gravitino/rel/TestTypes.java, catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/converter/FromHiveType.java, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/converter/TestTypeConverter.java, catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/converter/SqliteTypeConverter.java, catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/converter/DorisTypeConverter.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/converter/MysqlTypeConverter.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/converter/TestMysqlTypeConverter.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java, catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/converter/PostgreSqlTypeConverter.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/converter/TestPostgreSqlTypeConverter.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/converter/FromIcebergType.java, common/src/main/java/com/datastrato/gravitino/json/JsonUtils.java, common/src/test/java/com/datastrato/gravitino/json/TestJsonUtils.java, docs/apache-hive-catalog.md, docs/jdbc-mysql-catalog.md, docs/jdbc-postgresql-catalog.md, docs/lakehouse-iceberg-catalog.md, docs/manage-relational-metadata-using-gravitino.md, docs/open-api/datatype.yaml
- introduce externalType so that users can use external types when creating JDBC tables
- deprecated `unparsedType`
- add docs for externalType
Fix: #3500 
yes, `unparsedType` is deprecated, please use `externalType` instead
tests added
=> [#3500] feat(relational): add `ExternalType` data type

catalogs/catalog-hadoop/build.gradle.kts, catalogs/catalog-hive/build.gradle.kts, dev/docker/kerberos-hive/start.sh, docs/docker-image-details.md
Modify kerberized Hive docker file and do the following changes:
- Add `ssh-keyscan ${HOSTNAME} >> /root/.ssh/known_hosts`
- Add some checks to monitor the status of DataNode
To improve the stability of the CI pipeline.
Fix: #3583 
N/A.
Test locally.
=> [#3583] fix(docker-image): Fix the problem that kerberized HDFS datanode start fail occasionally

core/src/main/java/com/datastrato/gravitino/catalog/CatalogManager.java, core/src/main/java/com/datastrato/gravitino/connector/BaseCatalog.java
avoid to initialize catalog ops when closing catalog
Fix: #3673 
no
no
=> [#3673] fix(core): avoid to initialize catalog ops when closing catalog

core/src/main/java/com/datastrato/gravitino/authorization/UserGroupManager.java
Remove the confusing comment.
Just a minor.
No need.
No need.
=> [MINOR] improvement: Remove the confusing comment

core/src/main/java/com/datastrato/gravitino/storage/relational/service/GroupMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/UserMetaService.java, core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestGroupMetaService.java, core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestUserMetaService.java
The user, group insert overwrite semantics are not update the relationship with role.
we should overwrite the relationship
Fix: #3546 
/
ut
=> [#3546] fix(core): overwrite the relationship when insert overwrite user and group

catalogs/catalog-kafka/build.gradle.kts, integration-test/build.gradle.kts
add Kafka catalog dependency to pageIT
`./gradlew clean build` failed because:
```
Caused by: java.lang.ClassNotFoundException: Class no found org.apache.kafka.common.KafkaException
at com.datastrato.gravitino.utils.IsolatedClassLoader$CustomURLClassLoader.loadClass(IsolatedClassLoader.java:161)
at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
... 86 more
```
no
local tested
=> [MINOR] fix(pageIT): add Kafka catalog dependency to pageIT

api/src/main/java/com/datastrato/gravitino/SupportsSchemas.java, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/integration/test/CatalogHiveIT.java, catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/CatalogDorisIT.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/TestMultipleJDBCLoad.java, catalogs/catalog-kafka/src/test/java/com/datastrato/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergBaseIT.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/TestMultipleJDBCLoad.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/BaseSchemaCatalog.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalCatalog.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoQueryITBase.java, spark-connector/spark-common/src/main/java/com/datastrato/gravitino/spark/connector/catalog/BaseCatalog.java, trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/catalog/CatalogConnectorMetadata.java, trino-connector/src/test/java/com/datastrato/gravitino/trino/connector/GravitinoMockServer.java
Currently, the SupportsSchemas.listSchemas() method returns an array of NameIdentifier to represents the schemas. Actually a String[] will be more clear and easier to use.
To make the API more clear to use.
Fix: #3701
Almost not; Just return type changed, will be more simple.
Yes, many test cases cover this API.
=> [#3701]refactor(API): Refactoring SupportsSchemas.listSchemas() method to return String[]

.github/workflows/docker-image.yml, dev/docker/build-docker.sh, dev/docker/ranger/Dockerfile, dev/docker/ranger/init-mysql.sql.template, dev/docker/ranger/start-ranger-services.sh, docs/docker-image-details.md, gradle/libs.versions.toml, integration-test-common/build.gradle.kts, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/ContainerSuite.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/container/RangerContainer.java, integration-test/build.gradle.kts, integration-test/src/test/java/com/datastrato/gravitino/integration/test/authorization/ranger/RangerIT.java
This future includes：
1. A Gravitino Ranger CI Docker image
2. Add Ranger integration test
3. `docker run -it -p 6080:6080 datastrato/gravitino-ci-ranger`
Created an Apache Ranger Docker image myself, because Apache Ranger's official Docker image has 5 child docker images, It's very complex.
Fix: #2411 
N/A
1. Created [datastrato/gravitino-ci-ranger:0.1.0](https://hub.docker.com/r/datastrato/gravitino-ci-ranger/tags) Docker image and pushed hub.docker.com successed.
2. CI Passed
=> [#2411] Add Apache Ranger Docker CI image and integration test

docs/trino-connector/installation.md
Fix configuration name error in documentation for the Trino connector installation
Fix: #3754 
Update docs
No
=> [#3754] fix(doc): Fix configuration name error in documentation for the Trino connector installation

spark-connector/v3.3/spark-runtime/build.gradle.kts, spark-connector/v3.3/spark/build.gradle.kts, spark-connector/v3.4/spark-runtime/build.gradle.kts, spark-connector/v3.4/spark/build.gradle.kts, spark-connector/v3.5/spark-runtime/build.gradle.kts, spark-connector/v3.5/spark/build.gradle.kts
Add scala version to the name of maven artifact. 
Currently, we support multiple versions of scala version, if we don't include the scale version information, users would be unable to use jars with different scala version.
Fix: #3746
N/A.
=> [#3746] improvement(spark-connector): Add scala version to maven artifact name for spark-connector

README.md, bin/gravitino.sh, docs/how-to-install.md
`bin/gravitino.sh` support running on frontend.
For dev cases, it's easy to start/stop and watch logs.
For production environments where services are managed by `supervisord` or `systemd`, we usually run the service in frontend and print logs to stdout/stderr.
Yes, users can run `bin/gravitino.sh run` to run Gravitino in frontend, and press `Ctrl + C` to terminate the process.
Manuel test.
```
$ ./gradlew clean compileDistribution -x test
$ cd distribution/package
$ echo > conf/log4j2.properties <<EOF
rootLogger.level = info
rootLogger.appenderRef.rolling.ref = console
appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n%ex
EOF …
```
=> [#3750] feat: Support running in frontend

spark-connector/spark-common/src/test/java/com/datastrato/gravitino/spark/connector/integration/test/SparkCommonIT.java
table name is upper for using `%S`
Fix: #3772 
no
existing tests
=> [#3772] fix(spark-connector): Iceberg will use upper table to access gravitino server sometimes #3772

trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/GravitinoSplitSource.java
Fix query performance is lower than 0.5 version
Fix: #3738 
NO
Manually test
=> [#3738] fix(docker): Fix query performance is lower than 0.5 version

trino-connector/src/main/java/com/datastrato/gravitino/trino/connector/GravitinoSplitSource.java
Fix query performance is lower than 0.5 version
Fix: #3738 
NO
Manually test
=> [#3738] fix(trino-connector): Fix query performance is lower than 0.5 version

.github/workflows/cron-integration-test.yml
Extend timeout time for crob integration test 
crob-integration-test timeout minutes is 60, but currently crob-integration-test job costs about 71 minutes per execution. 
N/A
N/A
=> [Minor] Extend timeout time for crob integration test

scripts/mysql/schema-0.6.0-mysql.sql, scripts/mysql/upgrade-0.5.0-to-0.6.0-mysql.sql
If we support to remove securable object, we will use the entity id and type to find the securable object. It will be faster if we have the index.
Fix: #3833
No.
I run the SQL in my local mysql.
=>  [#3833] improvement(relational-backend): Add index for table `role_meta_securable_object`

clients/client-python/.gitignore, clients/client-python/build.gradle.kts, clients/client-python/gravitino/constants/doc.py, clients/client-python/gravitino/constants/root.py, clients/client-python/gravitino/constants/version.py, clients/client-python/scripts/generate_doc.py
* Use `pydoc` to generate docs
* Add Gradle task `doc` to generate docs (it will create a `docs` folder and generate all doc html files in it)
Screenshots of generated htmls:
* gravitino.html
* gravitino.api.fileset.html
Fix: #3824 
No
=> [#3824] improvement(client-python): Support generating pydoc from client-python code

flink-connector/build.gradle.kts
Add the scale version to the flink-connector artifact name.
The Flink connector has introduced scala-related dependencies, we'd better add the scale version name to the artifact to make it more user-friendly.
Fix: #3847 
N/A
Test locally.
=> [#3847] improvement(flink-connector): Add the scale version to the flink-connector artifact name.

core/src/main/java/com/datastrato/gravitino/config/ConfigEntry.java
=> [MINOR] improvement: Fix the typo in ConfigEntry.java

integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoQueryIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoQueryITBase.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/trino/TrinoQueryTestTool.java
1、Support `ignore_failed` on run TrinoQueryTestTool.
2、Summarize all the test cases results when test finished
Fix: #3637
NO
Exist IT
=> [#3637]improvement(IT):  Add ignore_failed flag and test report for TrinoQueryTestTool

docs/expression.md, docs/jdbc-doris-catalog.md, docs/jdbc-mysql-catalog.md, docs/jdbc-postgresql-catalog.md, docs/lakehouse-iceberg-catalog.md, docs/manage-messaging-metadata-using-gravitino.md, docs/manage-relational-metadata-using-gravitino.md, docs/manage-table-partition-using-gravitino.md, docs/table-partitioning-bucketing-sort-order-indexes.md
This pull request updates all `<Tabs>` components in the documentation to support multi-language switching by adding `groupId='language'` and `queryString` attributes. It also ensures that all related links in the documentation include the appropriate `queryString` parameter for language selection.
Changes include:
- Updating all `<Tabs>` components to the following format:
```markdown
<Tabs groupId='language' queryString>
<TabItem value="Json" label="Json">
```json
{
"direction": "asc",
"nullOrder": "NULLS_LAST",
"sortTerm":  {
"type": "field",
"fieldName": ["score"]
}
}
```
</TabItem>
<TabItem value="java" label="Java">
```java
SortOrders.of(NamedReference.field("score"), SortDirection.ASCENDING, NullOrdering.NULLS_LAST);
```
</TabItem>
</Tabs>
****
Fix: #3409
These changes are needed …
```
=> [#3409] improve(docs): Replace multi language tags with <Tabs groupId='language' queryString>

clients/client-python/version.ini, docs/how-to-build.md
This pull request adds detailed instructions for building Gravitino on Windows using the Windows Subsystem for Linux (WSL). The new section provides a comprehensive step-by-step guide to setting up the necessary environment and dependencies on Windows to successfully build and run Gravitino. It also includes specific instructions for integrating with IntelliJ IDEA and Visual Studio Code (VS Code).
These changes are needed to provide Windows users with clear and concise instructions on how to build Gravitino using WSL. This documentation expands the accessibility of the project to a wider audience who may be using Windows as their primary development environment. The detailed steps ensure that developers can set up a consistent development environment across different operating systems. …
=> [#3812] improve(docs): Add Windows build instructions to how-to-build.md

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcCatalog.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcCatalogCapability.java, catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/DorisCatalog.java, catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/DorisCatalogCapability.java, catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/CatalogDorisIT.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/MysqlCatalog.java, catalogs/catalog-jdbc-mysql/src/main/java/com/datastrato/gravitino/catalog/mysql/MysqlCatalogCapability.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java, catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/PostgreSqlCatalog.java, catalogs/catalog-jdbc-postgresql/src/main/java/com/datastrato/gravitino/catalog/postgresql/PostgreSqlCatalogCapability.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java, core/src/main/java/com/datastrato/gravitino/catalog/SchemaNormalizeDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/TableNormalizeDispatcher.java
Improve security when creating and dropping schemas and tables.
This PR adds the following checks for identifier names using the capability framework
- Regex check
- As a best practice, it's generally advised to avoid including spaces in database names. In this PR, database names that include space will be considered illegal.
- String length check, since SQL injection usually requires using longer string
- Mysql: at most 64 characters
- Postgresql: at most 63 characters
We refer to specifications of the earliest version of DB that gravitino currently supports:
- Postgresql identifier rules: https://www.postgresql.org/docs/12/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS
- Mysql identifier naming: https://dev.mysql.com/doc/refman/5.7/en/identifiers.html
- Mysql identifier length limit: …
=> [#2179] Improvement: Improve security when creating and dropping schemas and tables

common/src/main/java/com/datastrato/gravitino/dto/util/DTOConverters.java, common/src/test/java/com/datastrato/gravitino/dto/util/TestDTOConverters.java
Convert literal values of partition in `DTOConverters`.
Fix: #3903 
No.
UT.
=> [#3903] fix(common): convert literal values of partition in `DTOConverters`

api/src/main/java/com/datastrato/gravitino/MetadataObject.java, api/src/main/java/com/datastrato/gravitino/MetadataObjects.java, api/src/main/java/com/datastrato/gravitino/authorization/SecurableObjects.java, catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveTableOperations.java, core/src/main/java/com/datastrato/gravitino/Entity.java, core/src/main/java/com/datastrato/gravitino/GravitinoEnv.java, core/src/main/java/com/datastrato/gravitino/catalog/CatalogNormalizeDispatcher.java, core/src/main/java/com/datastrato/gravitino/connector/capability/Capability.java, core/src/main/java/com/datastrato/gravitino/meta/TableEntity.java, core/src/main/java/com/datastrato/gravitino/meta/TagEntity.java, core/src/main/java/com/datastrato/gravitino/storage/relational/JDBCBackend.java, core/src/main/java/com/datastrato/gravitino/storage/relational/service/RoleMetaService.java, core/src/main/java/com/datastrato/gravitino/storage/relational/utils/MetadataObjectUtils.java, core/src/main/java/com/datastrato/gravitino/tag/TagManager.java, core/src/test/java/com/datastrato/gravitino/catalog/TestCatalogNormalizeDispatcher.java, core/src/test/java/com/datastrato/gravitino/catalog/TestFilesetNormalizeDispatcher.java, core/src/test/java/com/datastrato/gravitino/catalog/TestSchemaNormalizeDispatcher.java, core/src/test/java/com/datastrato/gravitino/catalog/TestTableNormalizeDispatcher.java, core/src/test/java/com/datastrato/gravitino/catalog/TestTopicNormalizeDispatcher.java, core/src/test/java/com/datastrato/gravitino/connector/capability/TestCapability.java, core/src/test/java/com/datastrato/gravitino/meta/TestEntity.java, server/src/main/java/com/datastrato/gravitino/server/web/rest/RoleOperations.java
This PR proposes to add a basic `TagManager` framework. The current framework is not ready to work since it misses the core logic. 
This subtask adds a basic tag framework without actual logic. The reason of adding this is to control the PR size to avoid a big PR, since there're many changes in RDBMS support. If we want to make it complete, the PR will be very big.
Fix: #3895 
No.
The current PR is not ready to work, so tests will be added later on.
=> [#3895] feat(core): Add a basic tag manager framework for tag system

web/src/app/metalakes/TableBody.js, web/src/app/metalakes/metalake/rightContent/tabsContent/tableView/TableView.js, web/src/components/DetailsDrawer.js
In this PR, I've changed the tool tip to show the metalake comment and catalog comment when hovering over the metalake and catalog in each row respectively.
Before the PR when hovering over the metalake row, it would display the metalake name which is redundant. Additionally, when hovering over the catalog name it did not show any tooltip at all.
Fix: #3286 
N/A
I tested this using this the web UI to see if it displays correctly when the mouse is hovered over.
=> [3286] Improvement(ui): row tooltip displays comment

clients/client-python/tests/unittests/test_gvfs_with_local.py
* Add `PermissionError` to assert in function `test_rm_file()`
Fix: #3935 
No
`./gradlew clients:client-python:unittest` on MacOS
=> [#3935] test: fix test_rm_file() in test_gvfs_with_local.py on MacOS

clients/client-python/requirements-dev.txt, clients/client-python/requirements.txt
Add lose Python depends on library into `requirements-dev.txt`
```
cachetools==5.3.3
readerwriterlock==1.0.9
```
Fix: #3944
N/A
CI Passed.
=> [#3944] fix(pyClient): Python client loss depends library in the requirements-dev

integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/AbstractWebIT.java
update sleep millis of web ci
api data inconsistencies with test cast by the instability response
Fix: #3936
N/A
manual test
=> [#3936] ci(web): update sleep millis of web ci

catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergCatalogOperations.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergCatalogPropertiesMetadata.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergConfig.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/utils/IcebergCatalogUtil.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/TestIcebergCatalog.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergBaseIT.java, core/src/main/java/com/datastrato/gravitino/config/ConfigConstants.java, docs/iceberg-rest-service.md, docs/lakehouse-iceberg-catalog.md, spark-connector/spark-common/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/GravitinoIcebergCatalog.java, spark-connector/spark-common/src/main/java/com/datastrato/gravitino/spark/connector/iceberg/IcebergPropertiesConstants.java
add custom catalog name to Iceberg catalog backend
Fix: #3864 #3865 
yes, add configuration document
1.  create a jdbc catalog with custom iceberg-catalog-name
2.  check it takes effects in MySQL 
3.  spark connector could successfully operate under the jdbc catalog.
=> [#3864] feat(lakehouse-iceberg): add custom catalog name to Iceberg catalog backend

catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HadoopUserImpersonationIT.java, catalogs/catalog-lakehouse-iceberg/src/test/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/integration/test/IcebergRESTServiceIT.java, flink-connector/src/test/java/com/datastrato/gravitino/flink/connector/integration/test/hive/FlinkHiveCatalogIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/client/AuditIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/client/MetalakeIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/rest/KerberosOperationsIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/rest/OAuth2OperationsIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/rest/VersionOperationsIT.java, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/MetalakePageTest.java
Add missing docker it tag to the tests, so that test can run without Docker environment.
Add missing docker-it tag to the tests, with this tag Gravitino can build without Docker environment.
No
=> [MINOR] test: Add missing docker it tag

common/src/main/java/com/datastrato/gravitino/dto/messaging/TopicDTO.java
Override `toString` method of `topicDTO`
In order to locate the inconsistent properties when an assert fails.
no
tests passed
=> [MINOR] fix(common): Override `toString` method of `topicDTO`

clients/client-python/.gitignore, clients/client-python/MANIFEST.in, clients/client-python/build.gradle.kts, clients/client-python/gravitino/constants/root.py, clients/client-python/gravitino/constants/version.py, clients/client-python/scripts/generate_doc.py
Fix the issue of version.ini not found issue when installing python gravitino package using pip and run.
Previously, the `version.ini` file is under the project path, which will not be included after installing the package using pip, so now module to `graviitino` folder.
Fix: #3952
No.
Exisiting tests.
=> [#3952] fix(client-python): fix version.ini not found issue when installing the package

clients/client-python/build.gradle.kts
change build.gradle.kts test phase in python client
provide an option to skip python client unit tests
Fix: # #3959
no
./gradlew :client:client-python:test -PskipTests can skip unitTest
./gradlew :client:client-python:test -PskipTests -PskipITs can skip all python client tests
./gradlew :client:client-python:test -PskipTests -PskipPyClientITs can also skip all python client tests
=> [Improvement] test(python-client): Use skipTests parameter to skip unit tests of python client

integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/utils/ChromeWebDriverProvider.java
Frontend integration test failed in certain headless environment, like the ec2 in aws.
Frontend integration test failed due to the following error:
```
MetalakePageTest > initializationError FAILED
org.openqa.selenium.WebDriverException: unknown error: Chrome failed to start: exited abnormally.
(chrome not reachable)
(The process started from chrome location /actions-runner/_work/gravitino-test/gravitino-test/gravitino/integration-test/build/chrome/chrome-linux/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'ip-172-31-5-251', ip: '172.31.5.251', os.name: 'Linux', os.arch: 'amd64', os.version: '6.5.0-1020-aws', java.version: '1.8.0_412'
Driver info: …
```
=> [Minor] Frontend integration test failed in headless environment

clients/client-python/gravitino/client/gravitino_admin_client.py, clients/client-python/gravitino/client/gravitino_client.py, clients/client-python/gravitino/client/gravitino_client_base.py, clients/client-python/gravitino/client/gravitino_metalake.py, clients/client-python/tests/integration/test_catalog.py, clients/client-python/tests/integration/test_fileset_catalog.py, clients/client-python/tests/integration/test_metalake.py, clients/client-python/tests/integration/test_schema.py, clients/client-python/tests/integration/test_simple_auth_client.py
After the refactoring work in Java client is done (https://github.com/datastrato/gravitino/issues/3626), the Python client should also get updated to align with the Java API.
This PR mainly work on the following python classes:
1. gravitino_metalake.py
2. gravitino_client.py
3. gravitino_admin_client.py
To make the API simple and easy to use.
Fix: #3732
Change the Python client API.
The integration tests are updated and passed.
=> [#3732] refactor: update Python client to align with the Java client API: gravitino_metalake, gravitino_client

.github/workflows/backend-integration-test.yml, .github/workflows/build.yml, .github/workflows/cron-integration-test.yml, .github/workflows/flink-integration-test.yml, .github/workflows/frontend-integration-test.yml, .github/workflows/spark-integration-test.yml, docs/how-to-test.md, integration-test/src/test/java/com/datastrato/gravitino/integration/test/web/ui/MetalakePageTest.java
Remove `csexton/debugger-action@master` action in the github CI, if someone wants this functionality, they can add it in his fork repo and do the debug work the personal account. 
This action is not allowed in the Apache project.
Fixed: #4032 
N/A.
Test in the CI
=> [#4032] Fix(CI): Remove some CI actions to make CI back to normal

.asf.yaml
Add the asf yaml for Gravitino
Fix: #4031 
No.
This pull request needs to be verified after mering.
=> [#4031] build: Add the asf yaml for Gravitino

.asf.yaml
Apache infra doesn't support `branch-*`.
This is a follow-up pull request of #4033 
Fix: #4031 
No.
Verified after merging.
=> [#4031][followup] build: Revert the partial protected branches

clients/client-python/requirements-dev.txt
Currently twine 5.0.0 will cause Python client deploy task failed, upgrade twine version to fix this problem.
Fix: #4037
=> [MINOR] [#4037] Upgrade twine version to fix python client deploy task

clients/client-python/gravitino/api/supports_schemas.py, clients/client-python/gravitino/catalog/base_schema_catalog.py, clients/client-python/gravitino/catalog/fileset_catalog.py, clients/client-python/gravitino/client/gravitino_metalake.py, clients/client-python/gravitino/dto/dto_converters.py, clients/client-python/gravitino/filesystem/gvfs.py, clients/client-python/gravitino/name_identifier.py, clients/client-python/gravitino/namespace.py, clients/client-python/gravitino/rest/rest_utils.py, clients/client-python/tests/integration/test_catalog.py, clients/client-python/tests/integration/test_fileset_catalog.py, clients/client-python/tests/integration/test_schema.py, clients/client-python/tests/integration/test_simple_auth_client.py, clients/client-python/tests/unittests/mock_base.py, clients/client-python/tests/unittests/test_gvfs_with_local.py, clients/client-python/tests/unittests/test_name_identifier.py
After the refactoring work in Java client is done (https://github.com/apache/gravitino/issues/3626), the Python client should also get updated to align with the Java API.
* Update all the catalog, schema and their implementation to align wiith `client-java`
* Remove redundant methods in `Namespace` and `NameIdentifier`
* Add some missing tests and modify existing tests to conform with new API
Fix: #3732 
No
UT added and test with `./gradlew clients:client-python:test`
=> [#3732] refactor(client-python): Update Python client to align with the Java client API

server/src/main/java/com/datastrato/gravitino/server/GravitinoServer.java, server/src/main/java/com/datastrato/gravitino/server/web/mapper/JsonMappingExceptionMapper.java, server/src/main/java/com/datastrato/gravitino/server/web/mapper/JsonParseExceptionMapper.java, server/src/main/java/com/datastrato/gravitino/server/web/mapper/JsonProcessingExceptionMapper.java, server/src/test/java/com/datastrato/gravitino/server/web/mapper/TestJsonMappingExceptionMapper.java, server/src/test/java/com/datastrato/gravitino/server/web/mapper/TestJsonParseExceptionMapper.java, server/src/test/java/com/datastrato/gravitino/server/web/mapper/TestJsonProcessingExceptionMapper.java, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestMetalakeOperations.java
Add three ExceptionMapper to deal with exceptions that came from json deserialization.
Fix: #1061
NO, but when a user sends a malformed json request, the response will be in json format and with the call stack shown, which can make the debug process easier.
Via corresponding unit tests,  
or manually build and start the server, then send a malformed request, for example, 
```
curl -X POST -H "Accept: application/vnd.gravitino.v1+json" \
-H "Content-Type: application/json" -d '{"names":"metalake","comment":"comment","properties":{}}' \ 
http://localhost:8090/api/metalakes
```
=> [#1061] Improvement(server): Bad request may not response JSON content

dev/ci/util_free_space.sh
Fix issue:
```
sudo apt purge -y \
firefox \
google-chrome-stable \
microsoft-edge-stable
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package google-chrome-stable
E: Unable to locate package microsoft-edge-stable
```
Fix: #4078 
N/A
CI
=> [#4078] fix(CI): apt purge pop error "E: Unable to locate package" in some ubuntu vm

catalogs/catalog-jdbc-doris/build.gradle.kts, dev/docker/doris/Dockerfile, docs/docker-image-details.md, integration-test/build.gradle.kts
Decrease the size of the Docker image in ARM arch.
chmod makes Docker image increase to 8.89GB, but it's not necessary for user root.
N/A
Mannual/CI
=> [MINOR] fix: remove chmod in Dockerfile to decrease image size

clients/client-java/src/main/java/com/datastrato/gravitino/client/FilesetCatalog.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/MessagingCatalog.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalCatalog.java, clients/client-python/gravitino/catalog/fileset_catalog.py, docs/manage-fileset-metadata-using-gravitino.md, docs/manage-messaging-metadata-using-gravitino.md, docs/manage-metalake-using-gravitino.md, docs/manage-relational-metadata-using-gravitino.md, docs/manage-table-partition-using-gravitino.md, docs/table-partitioning-bucketing-sort-order-indexes.md
Update the documentations for the latest Java API change
To make the document sync with API change.
Fix: #3731
No
Document, local previewd.
=> [#3731] docs(API): Update the tutorial and document for the Java client API change

catalogs/catalog-lakehouse-paimon/src/main/java/com/datastrato/gravitino/catalog/lakehouse/paimon/ops/PaimonCatalogOps.java
Fix irregular variable names: tablename -> tableName
Variable name `tablename` is irregular
No
Modify variable name naming convention, no testing required.
=> [hotfix] Fix irregular variable names

build.gradle.kts, catalogs/catalog-hadoop/src/test/resources/log4j2.properties, catalogs/catalog-hive/src/test/resources/log4j2.properties, catalogs/catalog-jdbc-doris/src/test/resources/log4j2.properties, catalogs/catalog-jdbc-mysql/src/test/resources/log4j2.properties, catalogs/catalog-jdbc-postgresql/src/test/resources/log4j2.properties, catalogs/catalog-kafka/src/test/resources/log4j2.properties, catalogs/catalog-lakehouse-iceberg/src/test/resources/log4j2.properties, catalogs/catalog-lakehouse-paimon/src/test/resources/log4j2.properties, integration-test/src/test/resources/log4j2.properties, server/src/test/java/com/datastrato/gravitino/server/TestGravitinoServer.java
- Fix the path of the integration test is not as expected. 
- Remove directory data that lies in root project.
The path is not right. 
Fixed: #4065 
N/A
Test locally. 
**Before**
**After**
=> [#4065] improvement(test): Fix the path of integration log is wrong.

api/src/main/java/com/datastrato/gravitino/rel/SupportsPartitions.java, api/src/main/java/com/datastrato/gravitino/rel/TableCatalog.java, catalogs/catalog-hive/src/main/java/com/datastrato/gravitino/catalog/hive/HiveCatalogOperations.java, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/TestHiveTable.java, catalogs/catalog-hive/src/test/java/com/datastrato/gravitino/catalog/hive/integration/test/CatalogHiveIT.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcCatalogOperations.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcTableOperations.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/TableOperation.java, catalogs/catalog-lakehouse-iceberg/src/main/java/com/datastrato/gravitino/catalog/lakehouse/iceberg/IcebergCatalogOperations.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/RelationalCatalog.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestRelationalCatalog.java, core/src/main/java/com/datastrato/gravitino/catalog/PartitionDispatcher.java, core/src/main/java/com/datastrato/gravitino/catalog/TableOperationDispatcher.java
When purging tables, return `True` if the target was purged, and `False` if the target does not exist.
Fix: #3685
No
ITs and UTs.
=> [#3685] Improvement: revisit all the purgeXXX implementations to have a consistent behavior

core/src/main/java/com/datastrato/gravitino/lock/LockManager.java, core/src/main/java/com/datastrato/gravitino/lock/TreeLock.java, core/src/main/java/com/datastrato/gravitino/lock/TreeLockNode.java, core/src/test/java/com/datastrato/gravitino/lock/TestTreeLockUtils.java
Add the value of the name identifier in the holdingThreadTimestamp to support holding multiple tree lock at the same time.
To support more user sceanrio
Fix: #4129 
N/A.
Add new test class `TestTreeLockUtils`
=> [#4129] improvement(core): Support hold multiple tree lock within a thread at the same time

api/src/main/java/com/datastrato/gravitino/file/FilesetChange.java, catalogs/catalog-hadoop/src/main/java/com/datastrato/gravitino/catalog/hadoop/HadoopCatalogOperations.java, catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java, catalogs/catalog-hadoop/src/test/java/com/datastrato/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java, clients/client-java/src/main/java/com/datastrato/gravitino/client/DTOConverters.java, clients/client-java/src/test/java/com/datastrato/gravitino/client/TestFilesetCatalog.java, clients/client-python/gravitino/api/fileset_change.py, clients/client-python/gravitino/catalog/fileset_catalog.py, clients/client-python/gravitino/dto/requests/fileset_update_request.py, clients/client-python/tests/integration/test_fileset_catalog.py, common/src/main/java/com/datastrato/gravitino/dto/requests/FilesetUpdateRequest.java, core/src/test/java/com/datastrato/gravitino/catalog/TestFilesetOperationDispatcher.java, core/src/test/java/com/datastrato/gravitino/connector/TestCatalogOperations.java, docs/manage-fileset-metadata-using-gravitino.md, docs/open-api/filesets.yaml, server/src/test/java/com/datastrato/gravitino/server/web/rest/TestFilesetOperations.java
Add fileset commet removal operations: FilesetChange.RemoveComment
Fix: #4112
Fileset can be created without comment now, when user added a comment to fileset, they should be allowed to retract the comment.
Like other FilesetChange, FilesetChange.RemoveComment can be used for **alterFileset()** method
User can add new changes for fileset:
``` 
Fileset fileset = catalog.asFilesetCatalog().alterFileset(
NameIdentifier.of(metaLakeName, catalogName, schemaName, filesetName),
FilesetChange.removeComment());
```
or use update fileset http request: 
```
updates": [
{
"@type": "removeComment"
}
]
```
Create a fileset with comment, then use java/python client, or http requeset to remove comment and check the result
=> [#4112] feat(API, client): Add fileset comment removal operations

core/src/main/java/com/datastrato/gravitino/authorization/AccessControlManager.java, core/src/main/java/com/datastrato/gravitino/authorization/PermissionManager.java, core/src/main/java/com/datastrato/gravitino/authorization/RoleManager.java, core/src/main/java/com/datastrato/gravitino/authorization/UserGroupManager.java, core/src/test/java/com/datastrato/gravitino/authorization/TestAccessControlManagerForPermissions.java, core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestGroupMetaService.java, core/src/test/java/com/datastrato/gravitino/storage/relational/service/TestUserMetaService.java
Remove the logic of getValidRoles.
Fix: #4105 
No.
Modify some test cases.
=> [#4105] improvement(core): Remove the logic of getValidRoles

docs/how-to-build.md
[#4157] fix(doc): Fix the doc format in `how-to-build`
https://github.com/apache/gravitino/blob/main/docs/how-to-build.md#quick-start
The code block should only show the `git clone git@github.com:apache/gravitino.git`
Fix: #4157 
No
The doc format is fine in my dev branch.
https://github.com/1996fanrui/gravitino/blob/4157/fix-doc-format/docs/how-to-build.md#quick-start
=> [#4157] fix(doc): Fix the doc format in `how-to-build`

clients/client-python/build.gradle.kts
remove duplicated  `skipPyClientITs` parameter in Gradle
Fix: #4002
N/A
set `skipITs=false` to run integration test
=>  [#4002] Improvement(gradle): remove skipPyClientITs parameter in Gradle

catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/JdbcCatalogOperations.java, catalogs/catalog-jdbc-common/src/main/java/com/datastrato/gravitino/catalog/jdbc/operation/JdbcTableOperations.java, catalogs/catalog-jdbc-common/src/test/java/com/datastrato/gravitino/catalog/jdbc/TestJdbc.java, catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/operation/DorisTableOperations.java, catalogs/catalog-jdbc-doris/src/main/java/com/datastrato/gravitino/catalog/doris/utils/DorisUtils.java, catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/integration/test/CatalogDorisIT.java, catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/operation/TestDorisTableOperations.java, catalogs/catalog-jdbc-doris/src/test/java/com/datastrato/gravitino/catalog/doris/utils/TestDorisUtils.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java, catalogs/catalog-jdbc-mysql/src/test/java/com/datastrato/gravitino/catalog/mysql/operation/TestMysqlTableOperations.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java, catalogs/catalog-jdbc-postgresql/src/test/java/com/datastrato/gravitino/catalog/postgresql/operation/TestPostgreSqlTableOperations.java, integration-test-common/src/test/java/com/datastrato/gravitino/integration/test/util/ITUtils.java
Set partitioning when loading JDBC tables.
Fix: #4120 
No.
UT & IT.
=> [#4120] fix(catalog-jdbc): Set partitioning when loading JDBC tables

catalogs/bundled-catalog/build.gradle.kts, catalogs/bundled-catalog/src/main/java/org/apache/gravitino/catalog/common/ClassProvider.java, catalogs/bundled-catalog/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergConstants.java, catalogs/bundled-catalog/src/main/java/org/apache/gravitino/catalog/property/PropertyConverter.java, catalogs/catalog-lakehouse-iceberg/build.gradle.kts, catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergCatalogPropertiesMetadata.java, catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergSchemaPropertiesMetadata.java, catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergTablePropertiesMetadata.java, spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/iceberg/IcebergPropertiesConstants.java, spark-connector/v3.3/spark/build.gradle.kts, spark-connector/v3.4/spark/build.gradle.kts, spark-connector/v3.5/spark/build.gradle.kts, trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/hive/HiveCatalogPropertyConverter.java, trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/hive/HiveSchemaPropertyConverter.java, trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/hive/HiveTablePropertyConverter.java, trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/iceberg/IcebergCatalogPropertyConverter.java, trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/iceberg/IcebergSchemaPropertyConverter.java, trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/iceberg/IcebergTablePropertyConverter.java, trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/JDBCCatalogPropertyConverter.java, trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/mysql/MySQLTablePropertyConverter.java, trino-connector/src/test/java/org/apache/gravitino/trino/connector/catalog/iceberg/TestIcebergCatalogPropertyConverter.java
remove IcebergPropertiesMeta from bundled catalog,  `Iceberg catalog`, `trino-connector`, `spark-connector` use IcebergConstants defined in bundled-catalog.
Fix: #4084 
no
existing tests
=> [#4084] feat(bundled-catalog): remove IcebergPropertiesMeta from bundled catalog

api/src/main/java/org/apache/gravitino/exceptions/TagAlreadyAssociatedException.java, core/src/main/java/org/apache/gravitino/EntityStore.java, core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java, core/src/main/java/org/apache/gravitino/storage/relational/RelationalBackend.java, core/src/main/java/org/apache/gravitino/storage/relational/RelationalEntityStore.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/TagMetaMapper.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/TagMetadataObjectRelMapper.java, core/src/main/java/org/apache/gravitino/storage/relational/po/TagMetadataObjectRelPO.java, core/src/main/java/org/apache/gravitino/storage/relational/po/TagPO.java, core/src/main/java/org/apache/gravitino/storage/relational/po/TopicPO.java, core/src/main/java/org/apache/gravitino/storage/relational/service/MetadataObjectService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/TagMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/utils/POConverters.java, core/src/main/java/org/apache/gravitino/tag/SupportsTagOperations.java, core/src/main/java/org/apache/gravitino/tag/TagManager.java, core/src/main/java/org/apache/gravitino/utils/MetadataObjectUtil.java, core/src/main/java/org/apache/gravitino/utils/NameIdentifierUtil.java, core/src/test/java/org/apache/gravitino/storage/relational/service/TestTagMetaService.java, core/src/test/java/org/apache/gravitino/storage/relational/utils/TestPOConverters.java, core/src/test/java/org/apache/gravitino/tag/TestTagManager.java, core/src/test/java/org/apache/gravitino/utils/TestMetadataObjectUtil.java, core/src/test/java/org/apache/gravitino/utils/TestNameIdentifierUtil.java, scripts/h2/schema-h2.sql, scripts/mysql/schema-0.6.0-mysql.sql, scripts/mysql/upgrade-0.5.0-to-0.6.0-mysql.sql
This PR add the second part tag core logic to support associate tags with metadata object, and query the associations between tags and metadata objects.
This is a part of work to support tag system.
Fix: #4020 
NO.
Add UTs to cover the logic.
=> [#4020] feat(core): Add Tag Manage core logic to support tag operations (part-2)

catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogOperations.java, catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java
Check if the catalogLocation is empty when initializing
Fix: #3985 
No
Existing pipeline.
Before
After
=> [#3985] fix(hadooop-catalog): Create fileset catalog with empty location property success, but can't list schema of the catalog

core/src/main/java/org/apache/gravitino/GravitinoEnv.java, core/src/main/java/org/apache/gravitino/catalog/CapabilityHelpers.java, core/src/main/java/org/apache/gravitino/catalog/FilesetNormalizeDispatcher.java, core/src/main/java/org/apache/gravitino/catalog/FilesetOperationDispatcher.java, core/src/main/java/org/apache/gravitino/catalog/OperationDispatcher.java, core/src/main/java/org/apache/gravitino/catalog/PartitionNormalizeDispatcher.java, core/src/main/java/org/apache/gravitino/catalog/SchemaNormalizeDispatcher.java, core/src/main/java/org/apache/gravitino/catalog/SchemaOperationDispatcher.java, core/src/main/java/org/apache/gravitino/catalog/TableNormalizeDispatcher.java, core/src/main/java/org/apache/gravitino/catalog/TableOperationDispatcher.java, core/src/main/java/org/apache/gravitino/catalog/TopicNormalizeDispatcher.java, core/src/main/java/org/apache/gravitino/catalog/TopicOperationDispatcher.java, core/src/main/java/org/apache/gravitino/utils/NameIdentifierUtil.java, core/src/test/java/org/apache/gravitino/catalog/TestFilesetNormalizeDispatcher.java, core/src/test/java/org/apache/gravitino/catalog/TestOperationDispatcher.java, core/src/test/java/org/apache/gravitino/catalog/TestPartitionNormalizeDispatcher.java, core/src/test/java/org/apache/gravitino/catalog/TestSchemaNormalizeDispatcher.java, core/src/test/java/org/apache/gravitino/catalog/TestTableNormalizeDispatcher.java, core/src/test/java/org/apache/gravitino/catalog/TestTopicNormalizeDispatcher.java
- Decouple `OperationDispatcher` from `NormalizeDispatcher`
- move `getCatalogCapability` method from `OperationDispatcher` to `CapabilityHelpers`
Fix: #4195 
no
existing tests
=> [#4195] improvement(core): Decouple `OperationDispatcher` from `NormalizeDispatcher`

core/src/main/java/org/apache/gravitino/lock/TreeLockNode.java
Removed the redundant null check in TreeLockNode, since 'instanceof' returns false for null values.
Fix: #4210 
No need.
=> [#4210] Improvement: Removing redundant null check in TreeLockNode.java

trino-connector/src/main/java/org/apache/gravitino/trino/connector/GravitinoConfig.java
Added `try` block for handling file input operations to ensure the file is properly closed even if an error occurs.
Fix: #4182
No
existing tests
=> [#4182] improvement: close the input file stream

catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/authentication/AuthenticationConfig.java, catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/authentication/kerberos/KerberosConfig.java
Enhancements to the utilization and placement of KerberosConfig.DEFAULT_IMPERSONATION_ENABLE
Referencing a member of a subclass during initialisation, may give unexpected results because the child class might not have been initialised yet.
Fix: #4184
No
Let me know if you have any suggestions.
=>  [#4184] Improvement: Moved DEFAULT_IMPERSONATION_ENABLE from KerberosConfig to AuthenticationConfig

trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/CatalogConnectorManager.java
Catching exceptions of OutOfMemoryError and InternalError for method loadMetalake of CatalogConnectorManager.
Fix: #4191 
No
=> [#4191]Improvement: In CatalogConnectorManager.java to catch execption in loadMetalake function.

build.gradle.kts, docs/how-to-build.md
Read the environment variable (if exists) when -PskipDockerTests is not specified.
Fix: #4181 
No
```
export SKIP_DOCKER_TESTS=false
./gradlew build
```
=> [#4181]Improvement: Support setting gradle property skipDockerTests by environment variant

integration-test/src/test/java/org/apache/gravitino/integration/test/trino/TrinoQueryIT.java, integration-test/src/test/java/org/apache/gravitino/integration/test/trino/TrinoQueryTestTool.java
Add addition parameters in TrinoQueryTestTool
You need to passing the arguments like : --params=key1,value1;key2,value2... on run the TrinoQueryTestTool 
Fix: #4202 
Update the command output and error information of TrinoQueryTestTool
Manually Test
=> [#4202] feat(trino-connector): Add addition parameters in TrinoQueryTestTool

catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/integration/test/CatalogPaimonKerberosFilesystemIT.java
correct tag from `gravitino-docker-it` to `gravitino-docker-test` on the class `CatalogPaimonKerberosFilesystemIT`
should be `gravitino-docker-test`
no
test locally, default build should not run `CatalogPaimonKerberosFilesystemIT`
=> [MINOR] fix: wrong tag on `CatalogPaimonKerberosFilesystemIT`

build.gradle.kts
exclude `integration-test-common` when compileDistribution
Fix: #4253 
no
run `./gradlew compileDistribution` by hand
=> [#4253] fix(gradle): fix compileDistribution failed

flink-connector/src/main/java/org/apache/gravitino/flink/connector/catalog/BaseCatalog.java, flink-connector/src/main/java/org/apache/gravitino/flink/connector/utils/TableUtils.java, flink-connector/src/main/java/org/apache/gravitino/flink/connector/utils/TypeUtils.java, flink-connector/src/test/java/org/apache/gravitino/flink/connector/catalog/TestBaseCatalog.java, flink-connector/src/test/java/org/apache/gravitino/flink/connector/integration/test/FlinkCommonIT.java, flink-connector/src/test/java/org/apache/gravitino/flink/connector/utils/TestTypeUtils.java
- Support alter table operation for hive table.
- Fix: #3981 
- no
- add UTs
=> [#3981]feat(flink-connector):Support alter table operation for hive

core/src/main/java/org/apache/gravitino/GravitinoEnv.java, core/src/main/java/org/apache/gravitino/listener/PartitionEventDispatcher.java, core/src/main/java/org/apache/gravitino/listener/api/event/AddPartitionEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/AddPartitionFailureEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/DropPartitionEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/DropPartitionFailureEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/GetPartitionEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/GetPartitionFailureEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/ListPartitionEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/ListPartitionFailureEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/ListPartitionNamesEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/ListPartitionNamesFailureEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/PartitionEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/PartitionExistsEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/PartitionExistsFailureEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/PartitionFailureEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/PurgePartitionEvent.java, core/src/main/java/org/apache/gravitino/listener/api/event/PurgePartitionFailureEvent.java, core/src/main/java/org/apache/gravitino/listener/api/info/partitions/IdentityPartitionInfo.java, core/src/main/java/org/apache/gravitino/listener/api/info/partitions/ListPartitionInfo.java, core/src/main/java/org/apache/gravitino/listener/api/info/partitions/PartitionInfo.java, core/src/main/java/org/apache/gravitino/listener/api/info/partitions/RangePartitionInfo.java, core/src/test/java/org/apache/gravitino/listener/api/event/TestPartitionEvent.java
* create a PartitionEventDispatcher in GravitinoEnv, which hacks partition operation and generate event to event listener. the system will auto inject PartitionEventDispatcher to PartitionOperations
* create corresponding event like addPartitionEvent getPartitionEvent
* add test , please refer to TestCatalogEvent
Fix: [[Subtask] support partition event for event listener #3737](https://github.com/apache/gravitino/issues/3737)
1. no
1. Add UTs
=> [#3737] feat(core): support partition event for event listener

catalogs/catalog-hive/src/main/java/org/apache/gravitino/catalog/hive/HiveCatalogOperations.java, catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/ops/IcebergTableOpsHelper.java, catalogs/catalog-lakehouse-iceberg/src/test/java/org/apache/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergBaseIT.java, gradle.properties, spark-connector/spark-common/src/test/java/org/apache/gravitino/spark/connector/integration/test/SparkCommonIT.java, spark-connector/spark-common/src/test/java/org/apache/gravitino/spark/connector/integration/test/hive/SparkHiveCatalogIT.java, spark-connector/spark-common/src/test/java/org/apache/gravitino/spark/connector/integration/test/iceberg/SparkIcebergCatalogIT.java, spark-connector/spark-common/src/test/java/org/apache/gravitino/spark/connector/integration/test/util/SparkUtilIT.java
To support replace column:
* support delete and add **`same column name`** in valid column change logic in hive catalog
* remove get column position logic if not specifying column position in Iceberg catalog
Fix: #3136 
no
add IT
=> [#3136] fix(spark-connector): support replace column with same column name for spark connector

flink-connector/build.gradle.kts, flink-connector/src/main/java/org/apache/gravitino/flink/connector/utils/TypeUtils.java, flink-connector/src/test/java/org/apache/gravitino/flink/connector/integration/test/hive/FlinkHiveCatalogIT.java, flink-connector/src/test/java/org/apache/gravitino/flink/connector/utils/TestTypeUtils.java
- Support more columns for hive table
Fix: #3982 
- no
- add UTs and ITs: flink-connector/src/test/java/org/apache/gravitino/flink/connector/integration/test/hive/FlinkHiveCatalogIT.java
- flink-connector/src/test/java/org/apache/gravitino/flink/connector/utils/TestTypeUtils.java
=> [#3982]feat(flink-connector):Support more column data type for hive table

flink-connector/build.gradle.kts, settings.gradle.kts
Flink only supports Scala 2.12. All scala API will removed in the future version.
https://issues.apache.org/jira/browse/FLINK-23986
https://issues.apache.org/jira/browse/FLINK-20845
https://issues.apache.org/jira/browse/FLINK-13414
Fix: #4298
- no
- `./gradlew flink-connector:publishToMavenLocal -PdefaultScalaVersion=2.13 `
=> [#4298]fix(flink-connector): fix scala version in flink connector

web/src/lib/utils/initial.js
Improved the readability of the hint message for the Apache Kafka catalog. The updated hint message is now:
"The Apache Kafka brokers to connect to, allowing for multiple brokers separated by commas"
The previous hint message was unclear and less readable. The new message provides a clearer instruction to the users, enhancing the user experience.
Fix: #4148
_No_
_No need_
=> [#4148] fix(Kafka-catalog): improve readability of hint message

api/src/main/java/org/apache/gravitino/rel/expressions/UnparsedExpression.java, catalogs/catalog-jdbc-mysql/src/main/java/org/apache/gravitino/catalog/mysql/converter/MysqlColumnDefaultValueConverter.java, catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java, catalogs/catalog-jdbc-postgresql/src/main/java/org/apache/gravitino/catalog/postgresql/converter/PostgreSqlColumnDefaultValueConverter.java
use UnparsedExpression to represent unpared column default value
Fix: #4300 
yes, when loading a PG or MySQL table with an unparsed column default value, will use an UnparsedExpression instead of throw a exception
modified tests
=> [#4300] improvement(Mysql&PG catalog): use UnparsedExpression to represent unparsed column default value

docs/lakehouse-iceberg-catalog.md
This pull request fixes a typo in the "Gravitino Type" column of the "Table column types" section. The word "Sturct" is corrected to "Struct".
This change is needed to correct the spelling of the type name "Struct", ensuring consistency and clarity.
Fix: #4134
No, this PR does not introduce any user-facing changes.
No additional tests are required.
=> [#4134] docs: fix typo in table column types documentation

.github/workflows/python-integration-test.yml, clients/client-python/build.gradle.kts, clients/client-python/tests/unittests/test_name_identifier.py
Add `PYTHONPATH` environment and point Gravitino Python client path in the CI workflow.
Make Python search for module in the correct path.
Fix: #4322
N/A
CI Passed
=> [#4322] fix: python-client module import error

common/build.gradle.kts
fix get commit id failed as a submodule
when the project is a submodule, the `.git` is a file, not a directory,  we should handle the case
Fix: #4329 
no
test locally by hand
=> [#4329] improvement(build): fix get commit id failed as a submodule

trino-connector/src/main/java/org/apache/gravitino/trino/connector/GravitinoConnectorFactory.java, trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/CatalogConnectorContext.java, trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/DefaultCatalogConnectorFactory.java
Make the CatalogConnectorContext.Builder's functions to public. Users can extend the CatalogConnectorFactory outside the package.
Fix: #4332 
NO
NO
=> [#4332]Improve(trino-connector): Make the CatalogConnectorContext.Builder's functions to public

dev/docker/build-docker.sh, dev/docker/gravitino/Dockerfile, dev/docker/iceberg-rest-server/Dockerfile, dev/docker/iceberg-rest-server/iceberg-rest-server-dependency.sh, docs/docker-image-details.md
add gravitino iceberg rest service docker image
1. setup Gravition Iceberg REST service easily for test
2. user could add customer changes and setup a new docker image for product.
Fix: #4059 
no
in local machine, setup docker image and check it works
=> [#4059] feat(iceberg-rest-server): support Iceberg REST server docker image

clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClientBase.java
I added @Deprecated annotations to relevant methods in the GravitinoClientBase class to improve code clarity and guide developers towards using updated methods.   - Deprecated `getVersion()` method in favor of `serverVersion()`. - Provided explanations within the annotations to clarify why the deprecation was applied and what should be used instead.  This change ensures that outdated methods are clearly marked and helps maintain codebase consistency.  Closes #3084
As part of an effort to keep the Gravitino Java client codebase clean and up-to-date, deprecated annotations were added to certain methods in the GravitinoClientBase class. The `getVersion()` method was marked as deprecated since it duplicates the functionality provided by the `serverVersion()` method. An inline comment was …
=> [#3084] feat(client-java): Add @Deprecated annotations and explanations across GravitinoClientBase  

clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClientBase.java
fix splot check error
ci failed for spotless check, introduced by #4338 
```
Execution failed for task ':clients:client-java:spotlessJavaCheck'.
> The following files had format violations:
src/main/java/org/apache/gravitino/client/GravitinoClientBase.java
@@ -153,7 +153,7 @@
···*·Retrieves·the·version·of·the·Gravitino·API.
···*
···*·@deprecated·This·method·is·deprecated·because·it·is·a·duplicate·of·{@link·#serverVersion()}.
-···*·············Use·{@link·#serverVersion()}·instead·for·clarity·and·consistency.
+···*·····Use·{@link·#serverVersion()}·instead·for·clarity·and·consistency.
···*/
··@Deprecated
··@InlineMe(replacement·=·"this.serverVersion()")
Run './gradlew :clients:client-java:spotlessApply' to fix these violations.
```
no
existing tests
=> [HOTFIX]  fix spotless check error

docs/spark-connector/spark-catalog-hive.md
Add documents to note to users the limits of OpenCSVSerde in spark-catalog-hive.md
Fix: #3799
=> [#3799]feat(doc): Add documents to note to users the limits of OpenCSVSerde

.github/workflows/auto-cherry-pick.yml
This PR proposes to add auto cherry-pick support for branch-0.6, also removing the self token to use github token to make it work.
To support auto cherry-pick for branch-0.6.
No.
Test on Github CI.
=> [MINOR] CI: Add auto cherry-pick to branch-0.6 and remove self token

catalogs/catalog-jdbc-postgresql/src/main/java/org/apache/gravitino/catalog/postgresql/operation/PostgreSqlSchemaOperations.java, catalogs/catalog-jdbc-postgresql/src/main/java/org/apache/gravitino/catalog/postgresql/operation/PostgreSqlTableOperations.java, catalogs/catalog-jdbc-postgresql/src/test/java/org/apache/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java
Double quote table name or schema name to support upper case name.
It's a bug needs to be fixed.
Fix: #3817 
N/A.
Add IT.
=> [#3817] fix(catalog-postgresql): Fix bugs when creating a schema or table using upper-case name.

web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js
switch catalog properties value input disable to enable
hive catalog before: 
hive catalog after:
Iceberg catalog before: 
iceberg catalog after:
pg catalog before:
pg catalog after:
kafka catalog before: 
kafka catalog after:
fileset catalog before:
fileset catalog after:
make the change by the [PR](https://github.com/apache/gravitino/pull/4262) merged
Fix: #4351
N/A
manual
=> [#4351] [improvement] UI: Switch catalog properties from immutable to mutable

bin/common.sh, bin/gravitino-iceberg-rest-server.sh
add conf directory to classpath if starting standalone Iceberg REST catalog server in Gravitino package
Fix: #4389 
no
start Iceberg REST server and check classpath
=> [#4389]  fix(iceberg-rest-server): add conf directory to classpath if starting standalone Iceberg REST catalog server in Gravitino package

web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js
Show the required key msg when submit validate
N/A
Fix: #4180
N/A
manually operated
=> [#4180] fix(ui): show the required key msg when submit validate

web/src/lib/store/metalakes/index.js
Root cause: It will reset when get a table details data, and need to reset table props too
Reset table props when reset tables data
N/A
Fix: #4153
N/A
manually operated
=> [#4153] fix(ui): Reset table props when reset tables data

catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/authentication/UserContext.java
Title: [#4331] fix: add null check for parentContext in UserContext
This pull request adds a null check for the parentContext variable in the getUserContext method of UserContext.java. This ensures that a NullPointerException is avoided when deepCopy() is called on parentContext.
The change is needed to prevent a potential NullPointerException if parentContext is null. Adding this check makes the code more reliable.
Fix: #4331 
No, this change does not introduce any user-facing changes.
The change was reviewed to ensure that the null check effectively prevents the issue. No new tests were needed, as this is a preventive fix.
=> Fix potential NullPointerException in UserContext by adding null check for parentContext.

integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-postgresql/00004_query_pushdown.txt
Fix the jdbc-postgresql/00004_query_pushdown.sql under catalog pg failed. Because the explain result of the join query has random left and right table. 
Fix: #3929
NO
Exist testers
=> [#3929] fix(trino-connector): Fix the jdbc-postgresql/00004_query_pushdown.sql under catalog pg failed

clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoVersion.java, clients/client-java/src/test/java/org/apache/gravitino/client/TestGravitinoVersion.java, clients/client-python/gravitino/exceptions/base.py, clients/client-python/setup.py, gradle.properties
Change the version to 0.6.0-incubating-SNAPSHOT for branch-0.6.
To prepare for the Apache release.
No.
Existing CIs.
=> [MINOR] build: Change the version to 0.6.0-incubating-SNAPSHOT

build.gradle.kts
Add `**/*.out` to the list of exclusions will skip the licence check on the *.out file.
Fix: #4439
No
No
=> [#4439] fix: add **/*.out in list of exclusions

build.gradle.kts
Due to the Python Gravitino package name change, the RAT check will be failed in local, so fixing the RAT check to make the build work.
The RAT check is failed.
No.
Exisiting tests.
=> [HOTFIX] fix(build): Fix RAT issue in local build

.github/workflows/backend-integration-test.yml, .github/workflows/cron-integration-test.yml, integration-test/trino-it/docker-compose.yaml, integration-test/trino-it/init/hive/init.sh, integration-test/trino-it/launch.sh, integration-test/trino-it/shutdown.sh
Upgrade the Hive image version to 0.1.13 for the Trino tester.
Fix: #4424 
NO
NO
=> [#4424] Improvement (trino-connector): Upgrade the Hive image version for the Trino tester.

catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/JdbcCatalogOperations.java, catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/MySQLProtocolCompatibleCatalogOperations.java, catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/operation/TestMysql.java, catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/operation/TestMysqlCatalogOperations.java
Add the version checking for the MYSQL JDBC driver, if failed throw an exception
Fix: #3844 
NO
UT and manually test
=> [3844]fix(catalog-mysql) Add the version checking for the MYSQL JDBC driver

docs/how-to-use-relational-backend-storage.md, docs/manage-relational-metadata-using-gravitino.md, docs/manage-tags-in-gravitino.md
Refine docs as we are going to release version 0.6.0-incubating.
Better user experience.
N/A
N/A
=> [Minor] improvement(docs): Polish docs 

catalogs/catalog-jdbc-postgresql/src/main/java/org/apache/gravitino/catalog/postgresql/operation/PostgreSqlSchemaOperations.java, catalogs/catalog-jdbc-postgresql/src/test/java/org/apache/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java
Double quote the schema name in the drop sentence to support removing upper-case schema 
It's a bug. 
Fix: #4542 
N/A.
Add IT.
=> [#4542] fix(catalog-postgresql): Fix the problem that Gravitino is unable to drop upper-case PG schema.

core/src/main/java/org/apache/gravitino/storage/relational/mapper/TagMetaMapper.java, integration-test/src/test/java/org/apache/gravitino/integration/test/TagIT.java
Add NULL check for tag comment 
Fix: #4540 
No.
Add IT.
=> [#4540] fix(core): Support alter tag with null comment

web/src/app/metalakes/metalake/rightContent/tabsContent/detailsView/DetailsView.js, web/src/components/DetailsDrawer.js
Hide jdbc-password value in details page.
Fix: #4506 
Jdbc-password value is not palintext now.
=> [#4506] fix(UI): Hide jdbc-password value in details page

docs/open-api/catalogs.yaml, docs/open-api/openapi.yaml, docs/open-api/tags.yaml
This PR proposes to add a missing tag openapi to list all the metadata objects for a tag.
This is missing to add.
No.
Manual verification
=> [MINOR] fix(doc): Add missing tag api in openAPI

core/src/main/java/org/apache/gravitino/GravitinoEnv.java, core/src/main/java/org/apache/gravitino/SupportsRelationOperations.java, core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java, core/src/main/java/org/apache/gravitino/authorization/FutureGrantManager.java, core/src/main/java/org/apache/gravitino/authorization/PermissionManager.java, core/src/main/java/org/apache/gravitino/authorization/RoleManager.java, core/src/main/java/org/apache/gravitino/hook/CatalogHookDispatcher.java, core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/MetalakeMetaMapper.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/RoleMetaMapper.java, core/src/main/java/org/apache/gravitino/storage/relational/service/GroupMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/OwnerMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java, core/src/main/java/org/apache/gravitino/storage/relational/service/UserMetaService.java, core/src/main/java/org/apache/gravitino/utils/NameIdentifierUtil.java, core/src/test/java/org/apache/gravitino/authorization/TestAccessControlManager.java, core/src/test/java/org/apache/gravitino/authorization/TestAccessControlManagerForPermissions.java, core/src/test/java/org/apache/gravitino/authorization/TestFutureGrantManager.java, core/src/test/java/org/apache/gravitino/storage/relational/service/TestRoleMetaService.java, docs/docker-image-details.md, server/src/main/java/org/apache/gravitino/server/web/rest/RoleOperations.java
If we want to push the privileges down the underlying system, we need to call methods of the underlying system authorization plugin.
Fix: #4460
No.
Add some test cases.
=> [#4460] feat(core): Add the method call of the authorizationPlugin

docs/open-api/catalogs.yaml, docs/open-api/openapi.yaml, docs/open-api/tags.yaml
This PR proposes to add a missing tag openapi to list all the metadata objects for a tag.
This is missing to add.
No.
=> [MINOR] fix(doc): Add missing tag api in openAPI (#4579)

integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/CatalogsPageTest.java, integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/pages/CatalogsPage.java, web/src/components/DetailsDrawer.js
When the key and values are too long, they are not truncated and ellipses are added at the end of that string. The full key or value can be shown by hovering over with the tool tip.
When the key and values are too long, it will not be fully displayed unless the user uses the horizontal scroll bar.
Fix: #3280
N/A
Run the CI test case locally
=> [#3280] Improvement(ui): Truncate key and values detail properties

.github/workflows/backend-integration-test.yml
- run h2 backend tests only if test-mode is embedded
- run mysql backend tests only if test-mode is deploy
- if it's a PR triggered, run jdk17 only
- run multiple JDKs only if PR merged to main or branch-*
Fix: #4583 
no
CI passed
=> [#4583] improvement(CI): reduce Backend Integration Test jobs

.asf.yaml
This PR proposes to add several significant contributors to the collaborators so that the can have more permission to triage the issues.
Adding some contributors to the collaborator list.
No.
Unrelated.
=> [MINOR] Add collaborators for this project

core/src/main/java/org/apache/gravitino/GravitinoEnv.java, core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java, core/src/main/java/org/apache/gravitino/authorization/FutureGrantManager.java, core/src/main/java/org/apache/gravitino/authorization/OwnerManager.java, core/src/main/java/org/apache/gravitino/authorization/PermissionManager.java, core/src/main/java/org/apache/gravitino/authorization/RoleManager.java, core/src/main/java/org/apache/gravitino/connector/BaseCatalog.java, core/src/test/java/org/apache/gravitino/authorization/TestFutureGrantManager.java, core/src/test/java/org/apache/gravitino/authorization/TestOwnerManager.java, server/src/main/java/org/apache/gravitino/server/web/rest/OwnerOperations.java
This is the follow-up pull request of #3963.
#3963 add authorization plugin to set owner. This pull request is to call them.
Fix: #3963
No.
Add new ut.
=> [#3963][followup] feat(core): Call the method ownerset of authorization plugin

core/src/main/java/org/apache/gravitino/storage/relational/mapper/RoleMetaMapper.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/SecurableObjectMapper.java, core/src/main/java/org/apache/gravitino/storage/relational/po/SecurableObjectPO.java, core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java, scripts/h2/schema-0.6.0-h2.sql, scripts/mysql/schema-0.6.0-mysql.sql, scripts/mysql/upgrade-0.5.0-to-0.6.0-mysql.sql
Rename the table securable_object_meta field entity_id to metadata_object_id
Fix: #4637
No.
Existing UTs.
=> [#4637] improvement: Rename the table `securable_object_meta` field `entity_id` to `metadata_object_id`

clients/client-python/gravitino/catalog/base_schema_catalog.py, clients/client-python/gravitino/catalog/fileset_catalog.py, clients/client-python/gravitino/client/gravitino_admin_client.py, clients/client-python/gravitino/client/gravitino_client_base.py, clients/client-python/gravitino/client/gravitino_metalake.py, clients/client-python/gravitino/exceptions/base.py, clients/client-python/gravitino/exceptions/handlers/schema_error_handler.py, clients/client-python/pylintrc, clients/client-python/tests/integration/hdfs_container.py, clients/client-python/tests/integration/test_catalog.py, clients/client-python/tests/integration/test_fileset_catalog.py, clients/client-python/tests/integration/test_gvfs_with_hdfs.py, clients/client-python/tests/integration/test_metalake.py, clients/client-python/tests/integration/test_schema.py, clients/client-python/tests/integration/test_simple_auth_client.py, clients/client-python/tests/unittests/test_error_handler.py
* Remove all explicit `Exception`
* Modify some logic of tests to handle this modification
Fix: #3766 
* drop schema
* drop catalog
* drop fileset
* drop metalake
Now these APIs will raise exceptions directly, instead of handling exceptions internally.
`./gradlew client:client-python:test`
=> [#3766] improvement(client-python): Fix broad-exception-caught Pylint rule for client-python

clients/client-python/gravitino/filesystem/gvfs.py, clients/client-python/tests/unittests/test_gvfs_with_local.py, clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java, clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/TestGvfsBase.java
When the storage location of fileset has a trailing slash, the problem of not finding files may occur when traversing the directory using like the hadoop command: `hadoop dfs -ls -R gvfs://fileset/catalog/tmp/test/`. This PR detects the trailing slash when converting to a virtual path and aligns the prefix to be replaced.
Fix: #4586 
Add some UTs and test shell command locally.
=> [#4586] fix(filesystem): Fix convert the actual path which storage location end with slash

core/src/main/java/org/apache/gravitino/storage/relational/mapper/RoleMetaMapper.java, core/src/main/java/org/apache/gravitino/storage/relational/mapper/SecurableObjectMapper.java, core/src/main/java/org/apache/gravitino/storage/relational/po/SecurableObjectPO.java, core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java, scripts/h2/schema-0.6.0-h2.sql, scripts/mysql/schema-0.6.0-mysql.sql, scripts/mysql/upgrade-0.5.0-to-0.6.0-mysql.sql
Rename the table securable_object_meta field entity_id to metadata_object_id
Fix: #4637
No.
Existing UTs.
=> [#4637] improvement(core): Rename the table `securable_object_meta` field `entity_id` to `metadata_object_id`

iceberg/build.gradle.kts
Add gradle.kts to iceberg parent module so that it will not generate any empty jars.
Fix publishing issue.
No.
local build test
=> [MINOR] fix(build): Add gradle.kts to iceberg parent module

dev/docker/gravitino/Dockerfile
Use the linux distribution include basic tools like wget ,apt-get as basic image
The Debian linux distribution include basic tools like wget ,apt-get. While oracle linux use the YUM package manager, use yum command to install packages.
Gravitino docker used to build based on Debian, change to oracle linux is not consistent.
openjdk:17 ,it build from oraclelinux:8-slim  
https://hub.docker.com/layers/library/openjdk/17/images/sha256-98f0304b3a3b7c12ce641177a99d1f3be56f532473a528fda38d53d519cafb13?context=explore
openjdk:17-jdk-buster, it build from debian:10, 10.12, buster, buster-20220418
https://hub.docker.com/layers/library/openjdk/17-jdk-buster/images/sha256-e462f39f589395ce928db22f3c8ea2ca83ade3f78a0227133b5ffebfa0289ab0?context=explore
N/A
Run script on local:
``` …
```
=> [MINOR] Use Debian as gravitino basic image ,otherwise lack of basic tools like 'wget','apt-get'

conf/gravitino.conf.template, docs/security/access-control.md, server-common/src/main/java/org/apache/gravitino/server/authorization/NameBindings.java, server/src/main/java/org/apache/gravitino/server/web/rest/PermissionOperations.java, server/src/main/java/org/apache/gravitino/server/web/rest/RoleOperations.java
Add the missing annotations for access control interfaces.
Fix the document by the way.
Fix: #4664
No.
By hand.
=> [#4664] fix(server): Add the missing annotations fo access control interfaces

.github/workflows/backend-integration-test.yml
Increase the timeout time for backend integration tests from 60 minutes to 90 minutes
Accordingly tests from https://github.com/apache/gravitino/actions/runs/10552034338/job/29230290884?pr=4260, the backend integration could take up to 60 minutes, which is more than the maximum time allowed.  
**The root cause could be that MySQL's backend is relatively slow in some cases, so more tests are needed for information needs.**
N/A
N/A.
=> [Minor] improvement(CI): Fix backend tests fail occasionally as a result of CI pipeline timeout.
