- .github/workflows/access-control-integration-test.yml
- .github/workflows/backend-integration-test.yml
- LICENSE.bin
- NOTICE.bin
- authorizations/authorization-ranger/build.gradle.kts
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveE2EIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerITEnv.java
- build.gradle.kts
- catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/JdbcCatalogPropertiesMetadata.java
- catalogs/catalog-kafka/src/main/java/org/apache/gravitino/catalog/kafka/KafkaCatalogPropertiesMetadata.java
- core/src/main/java/org/apache/gravitino/catalog/CatalogManager.java
- core/src/main/java/org/apache/gravitino/connector/BaseCatalog.java
- core/src/test/java/org/apache/gravitino/connector/authorization/TestAuthorization.java
- gradle/libs.versions.toml
- integration-test-common/src/test/java/org/apache/gravitino/integration/test/container/MySQLContainer.java
1. Use an isolated class loader to create an authorization Ranger plugin.
2. Add authorization for Hive E2E tests using Ranger via Gravitino RESTful access control.
3. Copy the authorization ranger jar to the `distribution/package/authorizations/ranger/libs`.
4. Add `Apache Ranger` to license.bin
#4662 
N/A
CI
> [#4662] improve(IT): Add ranger authorization Hive E2E test

- docs/getting-started.md
- docs/how-to-build.md
- docs/how-to-install.md
- docs/how-to-upgrade.md
- docs/how-to-use-the-playground.md
- docs/index.md
make sure to set inline styles in my React application for img and show the content of docs
N/A
Fix: #4685
N/A
N/A
> [#4685] fix docs img inline style issue

- dev/docker/trino/Dockerfile
Fix the Trino playground Docker image cannot start up
Fix: #4688 
NO
Manually test
> [#4688] fix (docker): Fix the Trino playground Docker image cannot start up

- catalogs/catalog-kafka/build.gradle.kts
remove some unnecessary dependencies
Fix: #4530 
no
CI passed
> [#4530] improvement(kafka-catalog): reduce kafka catalog libs size from 91MB to 17MB

- clients/client-python/gravitino/constants/root.py
- clients/client-python/scripts/generate_version.py
Fix  gradlew :clients:client-python:build failed if the package does not contain .git directory
Fix: #4695 
NO
Manually test
> [#4695] Fix (python-client): Fix gradlew :clients:client-python:build failed if the package does not contain .git directory

- clients/client-java/src/main/java/org/apache/gravitino/client/ErrorHandlers.java
- integration-test/src/test/java/org/apache/gravitino/integration/test/authorization/AccessControlNotAllowIT.java
- server/src/main/java/org/apache/gravitino/server/web/filter/AccessControlNotAllowedFilter.java
The error response of addUser should meet the REST specification
Fix: #4699
No, access control isn't released.
By hand. If we don't enable authorization, it will return
```
{"code":1006,"type":"UnsupportedOperationException","message":"You should set 'gravitino.authorization.enable' to true in the server side `gravitino.conf` to enable the authorization of the system, otherwise these interfaces can't work."}
```
> [#4699] fix(server): The error response of addUser should meet the REST specification

- docs/security/access-control.md
Optimize the document of access control
Fix: #4754
No.
Just docs.
> [#4754] fix(docs): Optimize the document of access control

- LICENSE.bin
- authorizations/authorization-ranger/build.gradle.kts
- catalogs/catalog-hive/build.gradle.kts
- catalogs/catalog-hive/src/main/java/org/apache/gravitino/catalog/hive/HiveTable.java
- catalogs/catalog-hive/src/main/java/org/apache/gravitino/catalog/hive/HiveTableOperations.java
- gradle/libs.versions.toml
remove some unnecessary dependencies
Fix: #4528 
no
CI passed
> [#4528] improvement(hive-catalog): reduce hive catalog libs size from 146MB to 43MB

- .github/workflows/backend-integration-test.yml
exclude flinkIT from backendIT
backendIT does not need flinkIT
no
visit CI log
> [MINOR] fix(CI): exclude flinkIT from backendIT

- clients/client-python/build.gradle.kts
* Modify `clean` task to delete `apache_gravitino.egg_info`
Fix: #4803 
No
./gradlew client:client-python:clean
> [#4803] improvement(client-python): Delete egg-info directory due to Python package renamed improvement

- build.gradle.kts
Fix the OutOfMemoryError in the gradle running  testers
Fix: #4603
NO
NO
> [4603] fix (test): Fix the OutOfMemoryError in the gradle running  testers

- LICENSE.bin
- catalogs/catalog-common/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergConstants.java
- catalogs/catalog-common/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergPropertiesUtils.java
- catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergCatalogPropertiesMetadata.java
- docs/iceberg-rest-service.md
- docs/lakehouse-iceberg-catalog.md
- docs/spark-connector/spark-catalog-iceberg.md
- gradle/libs.versions.toml
- iceberg/iceberg-common/build.gradle.kts
- iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/IcebergConfig.java
- iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/ops/IcebergTableOps.java
add OSS support for Gravitino Iceberg REST server
Fix: #4367
yes, will add a separate PR to add document
1. setup a Iceberg REST server will following configurations
```
gravitino.iceberg-rest.catalog-backend = jdbc
gravitino.iceberg-rest.jdbc-driver = org.postgresql.Driver
gravitino.iceberg-rest.uri = jdbc:postgresql://127.0.0.1:5432/postgres
gravitino.iceberg-rest.jdbc-user = postgres
gravitino.iceberg-rest.jdbc-password = xxx
gravitino.iceberg-rest.jdbc-initialize = true
gravitino.iceberg-rest.warehouse = oss://xxx/key/prefix
gravitino.iceberg-rest.io-impl= org.apache.iceberg.aliyun.oss.OSSFileIO
gravitino.iceberg-rest.oss-access-key-id = xx
gravitino.iceberg-rest.oss-access-key-secret = xx
gravitino.iceberg-rest.oss-endpoint = https://oss-cn-beijing.aliyuncs.com
```
2. test with Spark …
> [#4367] feat(iceberg): add OSS support for Gravitino Iceberg REST server

- core/src/main/java/org/apache/gravitino/storage/relational/converters/H2ExceptionConverter.java
- core/src/test/java/org/apache/gravitino/storage/relational/converters/TestH2ExceptionConverter.java
- core/src/test/java/org/apache/gravitino/storage/relational/converters/TestMySQLExceptionConverter.java
Optimize the exception message of `SQLException` thrown in UI when duplicate entities occurs.
Fix: #4735 
Add some UTs.
> [#4735] improvement(core): Optimize the thrown duplicated entry error message

- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/service/metrics/TestIcebergMetricsFormatter.java
1. [#2184 ] test: Added test coverage for IcebergMetricsFormatter
Adding test cases to improve coverage of IcebergMetricsFormatter
Currently very low coverage for this class. 
Fix: #2184
No
Running IntelliJ with coverage. Code coverage Number before and after are attached.
**After the Fix**
** Before the Fix**
> [#2184] improve(iceberg-rest): Improved test coverage for IcebergMetricsFormatter

- catalogs/catalog-hive/src/test/java/org/apache/gravitino/catalog/hive/TestHiveTable.java
- catalogs/catalog-hive/src/test/java/org/apache/gravitino/catalog/hive/TestHiveTableOperations.java
`TestHiveTableOperations` can be tested before `TestHiveTable` initialized.
Make `TestHiveTableOperations::steup()` run alone.
When we try to just run `gradle :catalogs:catalog-hive:test --tests 'org.apache.gravitino.catalog.hive.TestHiveTableOperations'`, `TestHiveTableOperations` needs static variables which must be initialized ahead, and it can't be run alone.
Fix: #4851 
No.
Refactor of unit test setup, local unit tests have passed.
> [#4851] fix: make `TestHiveTableOperations` setup independently

- catalogs/catalog-jdbc-mysql/src/main/java/org/apache/gravitino/catalog/mysql/operation/MysqlTableOperations.java
backquote column name when altering table. 
To avoid cases where the column name is a keyword. 
N/A.
Existing test.
> [MINOR] improvement(mysql-catalog): Reduce possible keyword conflict in table creation for MySQL catalog.

- docs/lakehouse-iceberg-catalog.md
correct Iceberg document  location is immutable not reserved
Fix: #4758 
no
document
> [#4758]  correct Iceberg document  location is immutable not reserved

- core/src/main/java/org/apache/gravitino/storage/relational/mapper/GroupMetaBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/GroupMetaMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/GroupMetaSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/GroupRoleRelBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/GroupRoleRelMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/GroupRoleRelSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/OwnerMetaBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/OwnerMetaMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/OwnerMetaSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/RoleMetaBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/RoleMetaMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/RoleMetaSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/SecurableObjectBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/SecurableObjectMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/SecurableObjectSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/TagMetaBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/TagMetaMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/TagMetaSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/TagMetadataObjectRelBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/TagMetadataObjectRelMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/TagMetadataObjectRelSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/UserMetaBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/UserMetaMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/UserMetaSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/UserRoleRelBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/UserRoleRelMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/UserRoleRelSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/SchemaMetaService.java
Change tag, user, and role-related code to support the new framework introduced by #4832 
To support multiple JDBC backend.
Fix: #4868 
N/A.
Existing UTs and ITs.
> [#4868] improvement(core): Modify tag and user related mapper class to use the new framework to support multiple JDBC backend.

- .github/workflows/build.yml
- docs/build.gradle.kts
- update redocly/cli version from 1.5.0 to 1.23.1
- fixed the node version to 21.6.1
- fixed the npm version to 10.2.4
redocly/cli failed at version 1.5.0
no
build CI passed
> [HOTFIX] fix(openapi): fix the env of openAPI lint plugin

- LICENSE.bin
- docs/iceberg-rest-service.md
- docs/lakehouse-iceberg-catalog.md
- docs/spark-connector/spark-catalog-iceberg.md
- gradle/libs.versions.toml
- iceberg/iceberg-common/build.gradle.kts
Support GCS storage for Iceberg REST server
Fix: #4364
No
1. start Iceberg REST server with following config:
```
gravitino.iceberg-rest.warehouse = gs://xxx/test
gravitino.iceberg-rest.io-impl= org.apache.iceberg.gcp.gcs.GCSFileIO
```
2. run spark sqls to create Iceberg table
> [#4364] feat(iceberg): Support GCS storage for Iceberg REST server

- core/build.gradle.kts
- core/src/test/java/org/apache/gravitino/storage/TestEntityStorage.java
- integration-test-common/src/test/java/org/apache/gravitino/integration/test/container/ContainerSuite.java
- integration-test-common/src/test/java/org/apache/gravitino/integration/test/util/AbstractIT.java
Add some UTs to test MySQL and PostgreSQL storage backend.
To improve code robustness.
Fix: #4882 
N/A.
N/A
> [#4882] improvement(core): Add some ut for MySQL and PostgreSQL storage backend.

- docs/iceberg-rest-service.md
- docs/lakehouse-iceberg-catalog.md
- docs/spark-connector/spark-catalog-iceberg.md
For other storage not build in with Gravitino, we should add a document about how to run it
Fix: #4895 
no
existing tests
> [#4895]  docs(iceberg): add document for support not managed storages for Iceberg

- catalogs/catalog-common/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergConstants.java
- catalogs/catalog-common/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergPropertiesUtils.java
- catalogs/catalog-common/src/main/java/org/apache/gravitino/storage/OSSProperties.java
- catalogs/catalog-common/src/main/java/org/apache/gravitino/storage/S3Properties.java
- catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergCatalogPropertiesMetadata.java
- iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/IcebergConfig.java
unify the storage configurations
Fix: #4580 
no
existing tests
> [#4580] feat(catalog): unify cloud storage configurations

- trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/lakehouse-iceberg/00006_datatype.sql
- trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/lakehouse-iceberg/00006_datatype.txt
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/iceberg/IcebergDataTypeTransformer.java
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/util/GeneralDataTypeTransformer.java
- trino-connector/trino-connector/src/test/java/org/apache/gravitino/trino/connector/catalog/iceberg/TestIcebergDataTypeTransformer.java
- trino-connector/trino-connector/src/test/java/org/apache/gravitino/trino/connector/util/TestDataTypeTransformer.java
Fix the default precision of time and timestamp in the Iceberg catalog. 
It causes Trino to be unable to read Iceberg tables with data of time and timestamp
Fix: #4743
NO
New UT, IT
> [#4743]fix(trino-connector): Fix the default precision of time and timestamp in the Iceberg catalog.

- core/src/main/java/org/apache/gravitino/meta/ColumnEntity.java
- core/src/main/java/org/apache/gravitino/meta/TableEntity.java
- core/src/test/java/org/apache/gravitino/meta/TestColumnEntity.java
This PR adds a basic implementation of ColumnEntity in Gravitino.
This is the first PR to let Gravitino to manage columns in its store.
Fix: #4795
No.
Add UTs to test.
> [#4795] feat(core): Add column entity in Gravitino

- LICENSE.bin
- catalogs/catalog-lakehouse-iceberg/build.gradle.kts
- catalogs/catalog-lakehouse-iceberg/src/test/java/org/apache/gravitino/catalog/lakehouse/iceberg/converter/TestBaseConvert.java
- core/src/main/java/org/apache/gravitino/OverwriteDefaultConfig.java
- core/src/main/java/org/apache/gravitino/config/ConfigConstants.java
- gradle/libs.versions.toml
- iceberg/iceberg-common/build.gradle.kts
- iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/IcebergConfig.java
- iceberg/iceberg-common/src/test/java/org/apache/gravitino/iceberg/common/TestIcebergConfig.java
- iceberg/iceberg-rest-server/build.gradle.kts
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/provider/TestConfigBasedIcebergTableOpsProvider.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/provider/TestGravitinoBasedIcebergTableOpsProvider.java
- server-common/src/main/java/org/apache/gravitino/server/web/JettyServerConfig.java
remove some unnecessary dependencies for Iceberg REST server and Iceberg catalog
Fix: #4514 #4696 
No
CI passed
> [#4514] improvement(iceberg): shrink catalog-lakehouse-iceberg libs size from 184MB to 56MB,  IcebergRESTServer size from 162M to 70M

- catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergCatalogOperations.java
- catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/ops/IcebergCatalogWrapperHelper.java
- catalogs/catalog-lakehouse-iceberg/src/test/java/org/apache/gravitino/catalog/lakehouse/iceberg/TestIcebergCatalog.java
- catalogs/catalog-lakehouse-iceberg/src/test/java/org/apache/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergBaseIT.java
- catalogs/catalog-lakehouse-iceberg/src/test/java/org/apache/gravitino/catalog/lakehouse/iceberg/ops/TestIcebergTableUpdate.java
- iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/IcebergConfig.java
- iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/ops/IcebergCatalogWrapper.java
- iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/ops/IcebergCatalogWrapperProvider.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/RESTService.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/provider/ConfigBasedIcebergCatalogWrapperProvider.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/provider/GravitinoBasedIcebergCatalogWrapperProvider.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/IcebergCatalogWrapperManager.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/metrics/IcebergMetricsManager.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergNamespaceOperations.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergTableOperations.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergTableRenameOperations.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/provider/TestConfigBasedIcebergCatalogWrapperProvider.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/provider/TestGravitinoBasedIcebergCatalogWrapperProvider.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/service/TestIcebergCatalogWrapperManager.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/service/rest/ConfigBasedIcebergCatalogWrapperProviderForTest.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/service/rest/IcebergCatalogWrapperForTest.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/service/rest/IcebergRestTestUtil.java
The name of `IcebergTableOps` is not accurate, rename to `IcebergCatalogWrapper`
Fix: #4476 
no
existing tests
> [#4476] feat(iceberg):  rename IcebergTableOps to IcebergCatalogWrapper

- clients/client-java/build.gradle.kts
- add dependsOn hadoop catalog jar
Fix: #4955 
no
CI passed
> [#4955]fix(IT): fix client IT

- clients/client-java/src/main/java/org/apache/gravitino/client/FilesetCatalog.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestFilesetCatalog.java
- server/src/main/java/org/apache/gravitino/server/web/rest/FilesetOperations.java
- server/src/test/java/org/apache/gravitino/server/web/rest/TestFilesetOperations.java
Currently, after the client completes the `getFileLocation` request and the server completes the `getFileLocation` response, the Thread Local `CallerContext` is not cleaned up. This may cause the next request to incorrectly report the same information repeatedly when the thread is reused. We should eventually clean up the `CallerContext`.
Fix: #4973 
Add UTs.
> [#4973] improvement(client-java/server): Clear `CallerContext` in Java Client and Server when call `getFileLocation` finally

- server/src/main/java/org/apache/gravitino/server/web/rest/RoleOperations.java
put the check code into the code block Utils.doAs.
Fix: #4960 
Passing identity authentication information when checking hive resource
yes,finish functional test By hand, based on the hive meatasotre with kerberos authentication enabled
> [#4960] fix(server): hive metastore authentication failed when checking whether securable object exists in createRole() method

- dev/docker/hive/hive-site.xml
- dev/docker/hive/start.sh
- docs/docker-image-details.md
Add S3-related configuration in the `hive-site.xml`
To support create table with S3 location.
Fix: #4979 
N/A
Test locally.
> [#4979] improvement(docker-hive): Add S3 related configuration to support Hive S3 schema/table.

- clients/client-python/gravitino/audit/__init__.py
- clients/client-python/gravitino/audit/caller_context.py
- clients/client-python/gravitino/audit/fileset_audit_constants.py
- clients/client-python/gravitino/audit/fileset_data_operation.py
- clients/client-python/gravitino/audit/internal_client_type.py
- clients/client-python/gravitino/catalog/fileset_catalog.py
- clients/client-python/gravitino/dto/responses/file_location_response.py
- clients/client-python/tests/unittests/audit/__init__.py
- clients/client-python/tests/unittests/audit/test_caller_context.py
- clients/client-python/tests/unittests/test_responses.py
- common/src/main/java/org/apache/gravitino/audit/CallerContext.java
- common/src/main/java/org/apache/gravitino/audit/FilesetDataOperation.java
Added an interface code skeleton in Python Client for obtaining the file location so that the client can report some necessary information for the server to audit and simplify some check logics in Python GVFS later. Depend on #4320.
Fix: #4279 
Add UTs and ITs.
> [#4279] feat(client-python): Add the `getFileLocation` interface code skeleton in Python Client

- core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/CatalogMetaBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/CatalogMetaMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/CatalogMetaSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/FilesetMetaBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/FilesetMetaMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/FilesetMetaSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/FilesetVersionBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/FilesetVersionMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/FilesetVersionSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/MetalakeMetaBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/MetalakeMetaMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/MetalakeMetaSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/SchemaMetaBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/SchemaMetaMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/SchemaMetaSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/TableMetaBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/TableMetaMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/TableMetaSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/TopicMetaBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/TopicMetaMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/TopicMetaSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/session/SqlSessionFactoryHelper.java
1. Add a framework to support multiple JDBC backend 
2. Modify all the mapper classes related to metalake, catalog, schema, filesetset, table, topic and use new framework, others will use another PR to avoid a large PR.
To support more JDBC storage backend.
Fix: #4832 
N/A
> [#4832] feat(core): Add basic framework to support multiple JDBC backend

- docs/gravitino-server-config.md
correct `gravitino.eventListener.{name}.className` to `gravitino.eventListener.{name}.class`
the configuration is not correct
no
1. add the configuration to test a custom event listener.
> [MINOR] docs(core): fix iceberg event listener configuration

- clients/client-python/gravitino/audit/caller_context.py
- clients/client-python/gravitino/catalog/fileset_catalog.py
- clients/client-python/gravitino/utils/http_client.py
- clients/client-python/tests/integration/test_fileset_catalog.py
- clients/client-python/tests/unittests/audit/test_caller_context.py
- clients/client-python/tests/unittests/test_fileset_catalog_api.py
Add the implementations for `getFileLocation` interface in Python Client.
Fix: #4709 
Add some UTs and ITs.
> [#4709] improvement(client-python): Add the implementation for `getFileLocation` interface in python client

- catalogs/catalog-hive/src/test/java/org/apache/gravitino/catalog/hive/TestHiveCatalogOperations.java
- clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/CatalogIT.java
- core/src/main/java/org/apache/gravitino/connector/BaseCatalogPropertiesMetadata.java
Make catalog property `cloud.name` and `cloud.region-code` mutable.
As #4999 mentioned, the `cloud.name` and `cloud.region-code` may change after first creation.
Fix: #4999 
No.
Related integration tests have been added in this PR.
> [#4999] feat(catalog): make `cloud.name` and `cloud.region-code` mutable.

- authorizations/authorization-ranger/build.gradle.kts
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerHelper.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveE2EIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerITEnv.java
- authorizations/authorization-ranger/src/test/resources/log4j2.properties
- authorizations/authorization-ranger/src/test/resources/ranger-spark-security.xml.template
- integration-test-common/build.gradle.kts
- integration-test-common/src/test/java/org/apache/gravitino/integration/test/container/RangerContainer.java
- integration-test-common/src/test/java/org/apache/gravitino/integration/test/util/AbstractIT.java
1. Shadow integration-test-common module.
2. Add Ranger authorization Hive IT, use Spark to verify Ranger authorization Hive.
Fix: #4759
N/A
CI Passed.
> [#4759] feat(auth-ranger): Use Spark verify Ranger authorization Hive

- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/reference/VXGroup.java
When calling the ranger CREATE_GROUP api, the desc field cannot be null
When calling the ranger CREATE_GROUP api,  ranger response is error.
yes, by hand.
> fix(authorization-ranger):the descr field of ranger table x_group is not null

- docs/apache-hive-catalog.md
- docs/hive-catalog-with-s3.md
Add a document about how to create Hive S3 tables through Gravitino
To enhance the user experience. 
Fix: #5005
N/A
N/A
> [#5005] improvement(docs): Add a document about how to create Hive S3 tables through Gravitino.

- .github/workflows/python-integration-test.yml
Change the Python CI time to 45 minutes to reduce the chances of CI failure.
Current Python CI running time will hit the timeout and fail the CI, so increasing CI timeout to mitigate the failures.
No.
CI.
> [MINOR] improve(CI): Increase the Python timeout minutes to 45 minutes

- docs/iceberg-rest-service.md
- iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/IcebergConfig.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/RESTService.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/integration/test/TestIcebergExtendAPI.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/service/extension/HelloOperations.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/service/extension/HelloResponse.java
- integration-test-common/src/test/java/org/apache/gravitino/integration/test/util/ITUtils.java
support Iceberg REST extend API
Fix: #4959 
no
1.  add new operation classes with new URI PATH to `org.apache.gravitino.iceberg.service.rest2`
2. config `gravitino.iceberg-rest.extension-packages` to  `org.apache.gravitino.iceberg.service.rest2`
3. start Gravitino IcebergRESTServer
4. check new URI is accessable.
> [#4959] feat(Iceberg): support Iceberg REST extend API

- web/web/src/app/metalakes/metalake/MetalakeTree.js
- web/web/src/lib/store/metalakes/index.js
- web/web/src/lib/utils/index.js
show the expend arrow when reload tree node
show the correct info after reload tree node
Fix: #5042
N/A
manually
> [#5042] fix(ui): show the expend arrow when reload tree node

- catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/operation/JdbcDatabaseOperations.java
- catalogs/catalog-jdbc-common/src/test/java/org/apache/gravitino/catalog/jdbc/operation/SqliteDatabaseOperations.java
- catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/operation/DorisDatabaseOperations.java
- catalogs/catalog-jdbc-mysql/src/main/java/org/apache/gravitino/catalog/mysql/operation/MysqlDatabaseOperations.java
- catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
- catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/operation/TestMysqlDatabaseOperations.java
- catalogs/catalog-jdbc-oceanbase/build.gradle.kts
- catalogs/catalog-jdbc-oceanbase/src/main/java/org/apache/gravitino/catalog/oceanbase/operation/OceanBaseDatabaseOperations.java
- catalogs/catalog-jdbc-oceanbase/src/test/java/org/apache/gravitino/catalog/oceanbase/operation/TestOceanBase.java
- catalogs/catalog-jdbc-oceanbase/src/test/java/org/apache/gravitino/catalog/oceanbase/operation/TestOceanBaseDatabaseOperations.java
- catalogs/catalog-jdbc-postgresql/src/main/java/org/apache/gravitino/catalog/postgresql/operation/PostgreSqlSchemaOperations.java
- catalogs/catalog-jdbc-postgresql/src/test/java/org/apache/gravitino/catalog/postgresql/operation/TestPostgreSqlSchemaOperations.java
- integration-test-common/src/test/java/org/apache/gravitino/integration/test/container/ContainerSuite.java
- integration-test-common/src/test/java/org/apache/gravitino/integration/test/container/OceanBaseContainer.java
- Support schema operations for OceanBase JDBC catalog.
- Add OceanBaseContainer to test schema operations.
Fix: #4990 
no
Add unit test: TestOceanBaseDatabaseOperations.
> feat(oceanbase-catalog): Support schema operations for OceanBase JDBC catalog.

- build.gradle.kts
- clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/CatalogIT.java
- core/src/main/java/org/apache/gravitino/catalog/CatalogManager.java
- core/src/test/java/org/apache/gravitino/catalog/TestCatalogManager.java
- not clean catalog if catalog already exists
we will clean the catalog when the creation fails, but if the catalog already exists it will also be dropped which is unexpected.
Fix: #5082 
no
tests added
> [#5082] fix(catalog): fix clean bug after create catalog failed

- docs/docker-image-details.md
- docs/security/access-control.md
Fix the document error about access control
Fix: #5101
No.
Just docs.
> [#5101] improvement(docs): Fix the document error about access control

- catalogs/catalog-lakehouse-hudi/build.gradle.kts
- catalogs/catalog-lakehouse-hudi/src/main/java/org/apache/gravitino/catalog/lakehouse/hudi/HudiCatalogOperations.java
- catalogs/catalog-lakehouse-hudi/src/main/java/org/apache/gravitino/catalog/lakehouse/hudi/HudiCatalogPropertiesMetadata.java
- catalogs/catalog-lakehouse-hudi/src/main/java/org/apache/gravitino/catalog/lakehouse/hudi/HudiColumn.java
- catalogs/catalog-lakehouse-hudi/src/main/java/org/apache/gravitino/catalog/lakehouse/hudi/HudiSchema.java
- catalogs/catalog-lakehouse-hudi/src/main/java/org/apache/gravitino/catalog/lakehouse/hudi/HudiSchemaPropertiesMetadata.java
- catalogs/catalog-lakehouse-hudi/src/main/java/org/apache/gravitino/catalog/lakehouse/hudi/HudiTable.java
- catalogs/catalog-lakehouse-hudi/src/main/java/org/apache/gravitino/catalog/lakehouse/hudi/HudiTablePropertiesMetadata.java
- catalogs/catalog-lakehouse-hudi/src/main/java/org/apache/gravitino/catalog/lakehouse/hudi/backend/HudiCatalogBackend.java
- catalogs/catalog-lakehouse-hudi/src/main/java/org/apache/gravitino/catalog/lakehouse/hudi/backend/hms/HudiHMSBackendOps.java
- catalogs/catalog-lakehouse-hudi/src/main/java/org/apache/gravitino/catalog/lakehouse/hudi/backend/hms/HudiHMSSchema.java
- catalogs/catalog-lakehouse-hudi/src/main/java/org/apache/gravitino/catalog/lakehouse/hudi/backend/hms/HudiHMSTable.java
- catalogs/catalog-lakehouse-hudi/src/main/java/org/apache/gravitino/catalog/lakehouse/hudi/utils/CatalogUtils.java
- catalogs/catalog-lakehouse-hudi/src/test/java/org/apache/gravitino/catalog/lakehouse/hudi/TestHudiCatalog.java
- catalogs/catalog-lakehouse-hudi/src/test/java/org/apache/gravitino/catalog/lakehouse/hudi/TestHudiCatalogOperations.java
- catalogs/catalog-lakehouse-hudi/src/test/java/org/apache/gravitino/catalog/lakehouse/hudi/TestHudiSchema.java
- catalogs/catalog-lakehouse-hudi/src/test/java/org/apache/gravitino/catalog/lakehouse/hudi/TestHudiTable.java
- catalogs/catalog-lakehouse-hudi/src/test/java/org/apache/gravitino/catalog/lakehouse/hudi/backend/hms/TestHudiHMSBackend.java
- catalogs/catalog-lakehouse-hudi/src/test/java/org/apache/gravitino/catalog/lakehouse/hudi/backend/hms/TestHudiHMSBackendOps.java
- catalogs/catalog-lakehouse-hudi/src/test/java/org/apache/gravitino/catalog/lakehouse/hudi/ops/InMemoryBackendOps.java
- catalogs/catalog-lakehouse-hudi/src/test/java/org/apache/gravitino/catalog/lakehouse/hudi/utils/TestCatalogUtils.java
- catalogs/hive-metastore-common/src/main/java/org/apache/gravitino/hive/converter/HiveTableConverter.java
support read operations for Hudi catalog HMS backend
Fix: #4952 
no
UTs added
> [#4952] feat(hudi-catalog): add implementation of HMSBackend for Hudi catalog

- docs/trino-connector/catalog-hive.md
- docs/trino-connector/catalog-iceberg.md
Add documentation for the Gravitino-Trino connector running on AWS S3. 
The Hive catalog and Iceberg catalog support S3
Fix: #4657
Update docs
NO
> [#4657] Improvement (docs): Add documentation for the Gravitino-Trino connector running on AWS S3.

- catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/PaimonTablePropertiesMetadata.java
- catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/TestGravitinoPaimonTable.java
- docs/lakehouse-paimon-catalog.md
make some table properties from reserved to immutable.
```
merge-engine
sequence.field
rowkind.field
```
these table properties are immutable in Paimon.
Fix: https://github.com/apache/gravitino/issues/5094
updated related doc.
modified UT.
> [#5094] Fix(catalog-lakehouse-paimon): make some table properties from reserved to immutable

- build.gradle.kts
- catalogs/catalog-hive/build.gradle.kts
- catalogs/catalog-kafka/build.gradle.kts
- catalogs/catalog-lakehouse-hudi/build.gradle.kts
- catalogs/catalog-lakehouse-hudi/src/main/java/org/apache/gravitino/catalog/lakehouse/hudi/HudiCatalogOperations.java
- catalogs/catalog-lakehouse-hudi/src/main/resources/hive-site.xml.template
- catalogs/catalog-lakehouse-hudi/src/main/resources/lakehouse-hudi.conf
- catalogs/catalog-lakehouse-hudi/src/test/java/org/apache/gravitino/catalog/lakehouse/hudi/TestHudiCatalogOperations.java
- catalogs/catalog-lakehouse-hudi/src/test/java/org/apache/gravitino/catalog/lakehouse/hudi/integration/test/HudiCatalogHMSIT.java
- catalogs/catalog-lakehouse-hudi/src/test/resources/log4j2.properties
- catalogs/hive-metastore-common/build.gradle.kts
- common/src/main/java/org/apache/gravitino/dto/util/DTOConverters.java
- flink-connector/flink/build.gradle.kts
- gradle/libs.versions.toml
- integration-test-common/src/test/resources/log4j2.properties
- server/src/main/java/org/apache/gravitino/server/GravitinoServer.java
- spark-connector/spark-common/build.gradle.kts
- spark-connector/v3.3/spark/build.gradle.kts
- spark-connector/v3.4/spark/build.gradle.kts
- spark-connector/v3.5/spark/build.gradle.kts
add Hudi catalog IT and enable module
Fix: #4953 
yes. The Hudi catalog is available now
ITs added
> [#4953] feat(hudi-catalog): add Hudi catalog IT and enable module

- docs/lakehouse-hudi-catalog.md
- docs/manage-relational-metadata-using-gravitino.md
Add docs for Hudi catalog
Fix: #4954
no
no need
> [#4954] docs(hudi-catalog): Add docs for Hudi catalog

- api/src/main/java/org/apache/gravitino/exceptions/ForbiddenException.java
- clients/client-java/src/main/java/org/apache/gravitino/client/ErrorHandlers.java
- clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/authorization/CheckCurrentUserIT.java
- common/src/main/java/org/apache/gravitino/dto/responses/ErrorConstants.java
- common/src/main/java/org/apache/gravitino/dto/responses/ErrorResponse.java
- core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java
- core/src/main/java/org/apache/gravitino/hook/AccessControlHookDispatcher.java
- core/src/main/java/org/apache/gravitino/hook/CatalogHookDispatcher.java
- core/src/main/java/org/apache/gravitino/hook/FilesetHookDispatcher.java
- core/src/main/java/org/apache/gravitino/hook/SchemaHookDispatcher.java
- core/src/main/java/org/apache/gravitino/hook/TableHookDispatcher.java
- core/src/main/java/org/apache/gravitino/hook/TopicHookDispatcher.java
- server/src/main/java/org/apache/gravitino/server/web/Utils.java
- server/src/main/java/org/apache/gravitino/server/web/rest/ExceptionHandlers.java
Add the check of user before creating metadata object.
Fix: #5077 
No.
Added UT.
> [#5077] feat(core): Add the check of user before creating metadata object

- docs/security/access-control.md
Add the document of metadata object ownership
Fix: #5120
No.
Just document.
> [#5120] improvement(docs): Add the document of metadata object ownership

- catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/operation/DorisTableOperations.java
In `DorisTableOperations`, handled a possible Null Pointer Exception scenario 
Fix: (#4605)
No.
Local Test Run - Passed
> [#4605] Handle NPE in Doris table operation prop append

- core/src/main/java/org/apache/gravitino/listener/AsyncQueueListener.java
- core/src/main/java/org/apache/gravitino/listener/EventBus.java
- core/src/main/java/org/apache/gravitino/listener/EventListenerPluginWrapper.java
- core/src/main/java/org/apache/gravitino/listener/api/EventListenerPlugin.java
- core/src/main/java/org/apache/gravitino/listener/api/event/BaseEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/Event.java
- core/src/main/java/org/apache/gravitino/listener/api/event/PreEvent.java
- core/src/test/java/org/apache/gravitino/listener/DummyEventListener.java
- core/src/test/java/org/apache/gravitino/listener/TestEventListenerManager.java
- core/src/test/java/org/apache/gravitino/listener/api/event/TestCatalogEvent.java
- core/src/test/java/org/apache/gravitino/listener/api/event/TestFilesetEvent.java
- core/src/test/java/org/apache/gravitino/listener/api/event/TestMetalakeEvent.java
- core/src/test/java/org/apache/gravitino/listener/api/event/TestPartitionEvent.java
- core/src/test/java/org/apache/gravitino/listener/api/event/TestSchemaEvent.java
- core/src/test/java/org/apache/gravitino/listener/api/event/TestTableEvent.java
- core/src/test/java/org/apache/gravitino/listener/api/event/TestTopicEvent.java
support pre event for event listener systems
1. add  new `PreEvent` to represent Pre event and only `SYNC` event listeners could process `PreEvent`
2. keep `Event` as post event to keep compatibility.
3. `EventBus` dispatch event to corresponding event listeners.
Fix: #5112 
no
add UT
> [#5112] feat(core): support pre event for event listener systems

- flink-connector/flink-runtime/build.gradle.kts
- flink-connector/flink/build.gradle.kts
- shrink the flink-connector-runtime jar.
- Change client-java scope from implementation to CompileOnly  in flink module.
- use the client-java-runtime in flink-connector-runtime.
Fix: #5145 
- The flink-connector-runtime jar is much big as mentioned in https://github.com/apache/gravitino/pull/4791#discussion_r1738193021.
- no
- local test
> [#5145] improvement(flink-connector): Shrink the flink-connector-runtime lib size from 84MB to 16MB

- LICENSE.bin
- build.gradle.kts
- bundles/aliyun-bundle/build.gradle.kts
- bundles/aliyun-bundle/src/main/java/org/apache/gravitino/oss/fs/OSSFileSystemProvider.java
- bundles/aliyun-bundle/src/main/resources/META-INF/services/org.apache.gravitino.catalog.hadoop.fs.FileSystemProvider
- bundles/gcp-bundle/build.gradle.kts
- catalogs/catalog-hadoop/build.gradle.kts
- catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopGCSCatalogIT.java
- catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopOSSCatalogIT.java
- clients/filesystem-hadoop3/build.gradle.kts
- clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/integration/test/GravitinoVirtualFileSystemGCSIT.java
- clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/integration/test/GravitinoVirtualFileSystemOSSIT.java
- gradle/libs.versions.toml
- integration-test-common/src/test/java/org/apache/gravitino/integration/test/util/BaseIT.java
- settings.gradle.kts
Add OSS fileset support. 
OSS is widely used in China and Asia. 
Fix: #5173 
N/A.
Test Locally.
> [#5173] feat(hadoop-catlog): Support OSS fileset for Gravitino.

- .github/workflows/access-control-integration-test.yml
- api/src/main/java/org/apache/gravitino/MetadataObjects.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationHivePlugin.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerClientExtension.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerHelper.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerPrivileges.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerPrivilegesMappingProvider.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerSecurableObject.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerSecurableObjects.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/TestRangerAuthorizationPlugin.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveE2EIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerITEnv.java
- build.gradle.kts
The owner of catalog/metalake should have all the privileges of schemas/tables.
Fix: 
- #5116
- #5106
- #4616
- #5135
N/A
Add ITs.
> [#5116][#5106][#4616][#5135] improve(auth-ranger): The owner of catalog/metalake should have all the privileges of schemas/tables

- README.md
Some users suggest us to add the playgound link to Gravitino homepage as well as code repository, so that a new user can quickly know there is such a quick way to evaluate Gravitino.
To improve the user experience, especially for new user.
Fix: #5175
No
Reviewed the doc in local.
> [#5175] docs: add playgound information in README

- integration-test-common/src/test/java/org/apache/gravitino/integration/test/container/BaseContainer.java
The max user processes in the OB catalog unit tests should be larger than 120000
Fix: #5152
No
./gradlew :catalogs:catalog-jdbc-oceanbase:test -PskipDockerTests=false
> [#5152] fix(oceanbase-catalog): OB catalog UTs failed on Mac

- docs/trino-connector/index.md
- docs/trino-connector/trino-cascading-query.md
Add docs for Trino cascading query
Fix: #5072 
Update docs
NO
> [#5072]Improvement(docs): Add docs for Trino cascading query

- api/src/main/java/org/apache/gravitino/MetadataObjects.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationHivePlugin.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerHelper.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerMetadataObject.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerMetadataObjectRule.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerMetadataObjects.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerSecurableObject.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerSecurableObjects.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerAuthorizationPluginIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveIT.java
- build.gradle.kts
1. Add `RangerMetadataObject` class.
Currently, RangerSecurableObject extends MetadataObject, but Ranger managers meta types different with Gravitino, for example, Ranger doesn't have `METALAKE`, `ROLE`, So we need to Refactor RangerSecurableObject class.
Fix: #5196
N/A
CI Passed.
> [#5196] improve(auth-ranger): Refactor RangerSecurableObject class

- api/src/main/java/org/apache/gravitino/MetadataObjects.java
- api/src/main/java/org/apache/gravitino/rel/Column.java
- api/src/test/java/org/apache/gravitino/TestMetadataObjects.java
- catalogs/catalog-lakehouse-hudi/src/test/java/org/apache/gravitino/catalog/lakehouse/hudi/integration/test/HudiCatalogHMSIT.java
- catalogs/catalog-lakehouse-iceberg/src/test/java/org/apache/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergBaseIT.java
- catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/integration/test/CatalogPaimonBaseIT.java
- catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/utils/TestCatalogUtils.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GenericColumn.java
- clients/client-java/src/main/java/org/apache/gravitino/client/RelationalTable.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestGenericTag.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestRelationalCatalog.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestSupportTags.java
- clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/TagIT.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/TableColumnMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/TableColumnSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/TableColumnBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/MetadataObjectService.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/TableColumnMetaService.java
- core/src/main/java/org/apache/gravitino/tag/TagManager.java
- core/src/main/java/org/apache/gravitino/utils/MetadataObjectUtil.java
- core/src/main/java/org/apache/gravitino/utils/NameIdentifierUtil.java
- core/src/main/java/org/apache/gravitino/utils/NamespaceUtil.java
- core/src/test/java/org/apache/gravitino/storage/relational/service/TestTableColumnMetaService.java
- core/src/test/java/org/apache/gravitino/tag/TestTagManager.java
- core/src/test/java/org/apache/gravitino/utils/TestMetadataObjectUtil.java
- core/src/test/java/org/apache/gravitino/utils/TestNameIdentifierUtil.java
- docs/manage-tags-in-gravitino.md
- docs/open-api/openapi.yaml
- docs/open-api/tags.yaml
This PR proposes to add tag support for columns.
With this PR, user could add and remove tags in the column level.
Fix: #4599 
Fix: #4809 
No.
Add new UT and IT to test.
> [#4599][#4809] feat(core): Add tag support for column

- clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/CatalogIT.java
- core/src/main/java/org/apache/gravitino/catalog/CatalogManager.java
fix disable catalog miss invalidate cache
Fix: #5252 
no
tests added
> [#5252] fix(catalog): fix disable catalog miss invalidate cache

- catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/operation/JdbcTableOperations.java
- catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/operation/DorisTableOperations.java
- catalogs/catalog-jdbc-mysql/src/main/java/org/apache/gravitino/catalog/mysql/operation/MysqlTableOperations.java
- catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
- catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/operation/TestMysqlTableOperations.java
- catalogs/catalog-jdbc-oceanbase/src/main/java/org/apache/gravitino/catalog/oceanbase/operation/OceanBaseTableOperations.java
- catalogs/catalog-jdbc-oceanbase/src/test/java/org/apache/gravitino/catalog/oceanbase/operation/TestOceanBaseTableOperations.java
- catalogs/catalog-jdbc-postgresql/src/main/java/org/apache/gravitino/catalog/postgresql/operation/PostgreSqlTableOperations.java
Support table operations for OceanBase JDBC catalog.
Fix: #5227 
no
Added unit test: `TestOceanBaseTableOperations`
> [#5227] feat(oceanbase-catalog): Support table operations for OceanBase JDBC catalog

- api/src/main/java/org/apache/gravitino/file/FilesetChange.java
- catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java
- catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java
- catalogs/catalog-kafka/src/test/java/org/apache/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestFilesetCatalog.java
- clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/CatalogIT.java
- clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/MetalakeIT.java
- clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/TagIT.java
- clients/client-python/gravitino/api/fileset_change.py
- clients/client-python/gravitino/catalog/fileset_catalog.py
- clients/client-python/gravitino/dto/requests/catalog_update_request.py
- clients/client-python/gravitino/dto/requests/fileset_update_request.py
- clients/client-python/gravitino/dto/requests/metalake_update_request.py
- clients/client-python/tests/integration/test_catalog.py
- clients/client-python/tests/integration/test_fileset_catalog.py
- clients/client-python/tests/integration/test_metalake.py
- common/src/main/java/org/apache/gravitino/dto/requests/CatalogUpdateRequest.java
- common/src/main/java/org/apache/gravitino/dto/requests/FilesetUpdateRequest.java
- common/src/main/java/org/apache/gravitino/dto/requests/MetalakeUpdateRequest.java
- common/src/main/java/org/apache/gravitino/dto/requests/TableUpdateRequest.java
- common/src/main/java/org/apache/gravitino/dto/requests/TagUpdateRequest.java
- common/src/main/java/org/apache/gravitino/dto/requests/TopicUpdateRequest.java
- core/src/test/java/org/apache/gravitino/catalog/TestFilesetOperationDispatcher.java
- docs/manage-fileset-metadata-using-gravitino.md
- server/src/test/java/org/apache/gravitino/server/web/rest/TestFilesetOperations.java
- deprecated the removeComment change
- the new comment of updateComment supports null and empty string
Fix: #4968 
N/A
Pass existing tests
> [#4968] improvement(api): Unify the modification behavior of the comment field

- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/CatalogConnectorManager.java
Reduce redundant logging in the Trino connector.
Fix: #5302 
No
No
> [5302]Improvement (trino-connector): Set the log level to debug for the logging of load catalog

- authorizations/authorization-ranger/build.gradle.kts
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationHivePlugin.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerAuthorizationPluginIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveE2EIT.java
- build.gradle.kts
- core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java
1) Add more integration tests about access control.
2) Fix the can't create a role in authorization plugin with `CREATE_ROLE`, `MANAGE_USERS`.
3) Fix creating a role contains metalake, it won't take effect.
Fix: #5180 
No.
Just tests.
> [#5180][part-1] improvement(test): Add more integration tests about access control

- catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogOperations.java
- catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java
Add the trailing slash to avoid issues when user set illegal location to catalog and schema. For example, if user set "hdfs://ip:port" as a catalog or schema location, we need to add a trailing "/" to avoid issues in creating a `Path`.
Users can set Catalog and schema "location" with improper path, like "hdfs://ip:port", to support this case, we need to add an additional slash to the end of the location.
Fix: #4582 
No.
Add a new IT to test.
> [#4582] fix(hadoop-catalog): Fix some location without slash issue

- catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/PaimonCatalogPropertiesMetadata.java
- catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/PaimonConfig.java
- catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/utils/CatalogUtils.java
- catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/integration/test/CatalogPaimonBaseIT.java
- catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/integration/test/CatalogPaimonJdbcIT.java
- catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/integration/test/CatalogPaimonMultipleJDBCLoadIT.java
- catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/utils/TestCatalogUtils.java
- docs/lakehouse-paimon-catalog.md
- integration-test-common/src/test/java/org/apache/gravitino/integration/test/util/TestDatabaseName.java
add jdbc-driver to Paimon JDBC catalog backend configuration
Fix: https://github.com/apache/gravitino/issues/5214
updated the related doc
New IT and modified UT.
> [#5214] Improvement(catalog-lakehouse-paimon): add jdbc-driver to Paimon JDBC catalog backend configuration

- build.gradle.kts
Add LICENSE and NOTICE files to the built jars.
To meet the requirement.
Fix: #4661
No.
Local verification.
> [#4661] improve(build): Add LICENSE and NOTICE file to jar

- api/src/main/java/org/apache/gravitino/credential/GCSTokenCredential.java
- api/src/main/java/org/apache/gravitino/credential/S3SecretKeyCredential.java
- api/src/main/java/org/apache/gravitino/credential/S3TokenCredential.java
- bundles/aws-bundle/build.gradle.kts
- bundles/aws-bundle/src/main/java/org/apache/gravitino/s3/credential/S3SecretKeyProvider.java
- bundles/aws-bundle/src/main/java/org/apache/gravitino/s3/credential/S3TokenProvider.java
- bundles/aws-bundle/src/main/resources/META-INF/services/org.apache.gravitino.credential.CredentialProvider
- bundles/gcp-bundle/build.gradle.kts
- catalogs/catalog-common/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergConstants.java
- catalogs/catalog-common/src/main/java/org/apache/gravitino/credential/CredentialConstants.java
- catalogs/catalog-common/src/main/java/org/apache/gravitino/storage/S3Properties.java
- common/src/main/java/org/apache/gravitino/credential/CredentialPropertyUtils.java
- common/src/test/java/org/apache/gravitino/credential/TestCredentialPropertiesUtils.java
- core/build.gradle.kts
- core/src/main/java/org/apache/gravitino/credential/config/S3CredentialConfig.java
- gradle/libs.versions.toml
- iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/ops/IcebergCatalogWrapper.java
- iceberg/iceberg-rest-server/build.gradle.kts
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergTableOperations.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/integration/test/IcebergRESTS3IT.java
support S3 credential vending, include s3 token and s3 static key
Fix: #4994 
Fix: #4369 
no
add IT to do Iceberg operation by using S3 token
> [#4994][#4369] feat(core): support S3 credential vending

- docs/iceberg-rest-service.md
correct Iceberg multi catalog document,  was refactored to `static-config-provider`, `dynamic-config-provider`
The name was refactored and polish document
no
just document
> [MINOR] correct Iceberg multi catalog document

- .github/workflows/access-control-integration-test.yml
- api/src/main/java/org/apache/gravitino/authorization/MetadataObjectChange.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationHivePlugin.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerHelper.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerMetadataObjects.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerPrivilegesMappingProvider.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerAuthorizationPluginIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveE2EIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerITEnv.java
- core/src/main/java/org/apache/gravitino/connector/authorization/MetadataAuthorizationPlugin.java
- core/src/test/java/org/apache/gravitino/connector/authorization/mysql/TestMySQLAuthorizationPlugin.java
- core/src/test/java/org/apache/gravitino/connector/authorization/ranger/TestRangerAuthorizationPlugin.java
Add rename a securable object in the RoleChange.
Fix: #5124 #5146
N/A
Add ITs.
> [#5124][#5146] feat(auth-ranger): Ranger plugin should support rename operation

- bundles/gcp-bundle/build.gradle.kts
- dev/docker/iceberg-rest-server/iceberg-rest-server-dependency.sh
- dev/docker/iceberg-rest-server/rewrite_config.py
- dev/docker/iceberg-rest-server/start-iceberg-rest-server.sh
- docs/docker-image-details.md
- docs/iceberg-rest-service.md
1.  add AWS and GCP bundle jar to IcebergRESTServer docker image
2.  use environment variable to change the config 
Fix: #4551 
no
run SQL with access S3 and GCS data
> [#4551]  feat(iceberg): add S3 and GCS support for IcebergRESTService docker image

- api/src/main/java/org/apache/gravitino/exceptions/AuthorizationPluginException.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerHelper.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerITEnv.java
- core/src/main/java/org/apache/gravitino/connector/authorization/RoleAuthorizationPlugin.java
- core/src/main/java/org/apache/gravitino/connector/authorization/UserGroupAuthorizationPlugin.java
Currently, the Authorization plugin throws RuntimePluginException, We needs change it to AuthorizationPluginExceptionto
Fix: #5364
N/A
Added ITs.
> [#5364] feat(auth-ranger): Throw AuthorizationPluginException in authorization plugin

- catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
- catalogs/catalog-jdbc-oceanbase/src/main/java/org/apache/gravitino/catalog/oceanbase/converter/OceanBaseColumnDefaultValueConverter.java
- catalogs/catalog-jdbc-oceanbase/src/test/java/org/apache/gravitino/catalog/oceanbase/integration/test/CatalogOceanBaseIT.java
fix ob catalog default value parse error
For OceanBase catalog, the `IS_GENERATEDCOLUMN` value of the column ResultSet is set to `NO`, which is causing `isExpression` to be false and leading to a parse error.
Fix: #5359 
no
tests added
> [#5359] fix(ob-catalog): fix ob catalog default value parse error

- catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/PaimonCatalogPropertiesMetadata.java
export paimon jdbc user and password to properites
Fix: #5355 
no
existing IT
> [#5355] export Paimon jdbc user and password to properites

- dev/docker/gravitino/gravitino-dependency.sh
- docs/docker-image-details.md
Copy cloud storage bundles jars to folder `$GRAVITINO_HOME/catalogs/hadoop/libs` when building Gravitino docker image to free from manually doing it. 
We aim to make Gravitino user-friendly for managing cloud storage. 
Fix: #5349 
N/A.
Manually verify locally.
> [#5349] improvement(docker): Update Gravitino dockerfile to put cloud bundles into the docker image.

- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveE2EIT.java
- core/src/main/java/org/apache/gravitino/authorization/AccessControlDispatcher.java
- core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java
- core/src/main/java/org/apache/gravitino/hook/CatalogHookDispatcher.java
- core/src/main/java/org/apache/gravitino/hook/FilesetHookDispatcher.java
- core/src/main/java/org/apache/gravitino/hook/MetalakeHookDispatcher.java
- core/src/main/java/org/apache/gravitino/hook/SchemaHookDispatcher.java
- core/src/main/java/org/apache/gravitino/hook/TableHookDispatcher.java
- core/src/main/java/org/apache/gravitino/hook/TopicHookDispatcher.java
- core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java
- core/src/test/java/org/apache/gravitino/catalog/TestFilesetOperationDispatcher.java
- core/src/test/java/org/apache/gravitino/catalog/TestTableOperationDispatcher.java
- core/src/test/java/org/apache/gravitino/catalog/TestTopicOperationDispatcher.java
- core/src/test/java/org/apache/gravitino/hook/TestFilesetHookDispatcher.java
- core/src/test/java/org/apache/gravitino/hook/TestTableHookDispatcher.java
- core/src/test/java/org/apache/gravitino/hook/TestTopicHookDispatcher.java
- core/src/test/java/org/apache/gravitino/storage/relational/service/TestRoleMetaService.java
Support to rename and delete metadata object in the authorization plugin
Fix: #5146 
No.
add new IT and UT
> [#5146] fix(core): Support to rename and delete metadata object in the authorization plugin

- trino-connector/integration-test/src/test/java/org/apache/gravitino/trino/connector/integration/test/TrinoQueryITBase.java
- trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/hive/00006_datatype.sql
- trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-mysql/00006_datatype.sql
- trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-mysql/00006_datatype.txt
- trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-postgresql/00006_datatype.sql
- trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-postgresql/00006_datatype.txt
- trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/lakehouse-iceberg/00006_datatype.sql
- trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/lakehouse-iceberg/00006_datatype.txt
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/hive/HiveDataTypeTransformer.java
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/mysql/MySQLDataTypeTransformer.java
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/postgresql/PostgreSQLDataTypeTransformer.java
Adjust the default precision of the time and timestamp types for different catalogs. keep the same precision as the original connector
Fix: #5341
No
Update IT
> [#5341] fix (trino-connector): Adjust the default precision of the time and timestamp types for different catalogs

- LICENSE.bin
- gradle/libs.versions.toml
Add org.apache.logging.log4j:log4j-layout-template-json to support server log in json format.
There are use cases required server logs to be viewed from logsearch tools such as Kibana. These use cases recommends log format to be json.
Based on https://logging.apache.org/log4j/2.x/manual/json-template-layout.html, `log4j-layout-template-json` is needed to enable json layout for log4j.
Fix: https://github.com/apache/gravitino/issues/5389
No.
Tested locally with modified lo4j property file.
```
appender.rolling.layout.type = JsonTemplateLayout
appender.rolling.layout.eventTemplate = {"instant":{"$resolver":"timestamp","pattern":{"format":"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'","timeZone":"UTC"}},"level":{"$resolver":"level","field":"name"},"thread":{"$resolver":"thread","field":"name"},"message":{"$re …
```
> [#5389] feat(logging): add org.apache.logging.log4j:log4j-layout-template-json to support server log in json format

- catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/JdbcCatalogPropertiesMetadata.java
[#5306][Improvement] Some JDBC catalog properties should be defined as required
Fix: #5306 
change some JDBC catalog properties
No
> [#5306]Improvement(jdbc-catalog): make properties required

- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/IcebergRequestContext.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/dispatcher/IcebergTableEventDispatcher.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/dispatcher/IcebergTableOperationDispatcher.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/dispatcher/IcebergTableOperationExecutor.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergTableOperations.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergTableRenameOperations.java
add `IcebergRequestContext` in `IcebergTableOperationDispatcher`
Fix: #5370 
No
existing tests
> [#5370] feat(iceberg):  make IcebergTableOperationDispatcher interface more extendable

- docs/trino-connector/catalog-hive.md
Some properties are automatically added and managed as reserved properties.
Update the doc to describe them
Fix: #5399 
Update docs
No
> [#5399] fix (docs): Add a description of reserved properties to the `trino-connector/catalog-hive.md` documentation.

- docs/trino-connector/catalog-hive.md
ix the unsupported format types in the documentation for the Gravitino Trino connector
Fix: #5401 
Update docs
No
> [#5401] fix (docs): Fix the unsupported format types in the documentation for the Gravitino Trino connector

- docs/apache-hive-catalog.md
- docs/gravitino-server-config.md
- docs/index.md
- docs/jdbc-doris-catalog.md
- docs/jdbc-mysql-catalog.md
- docs/jdbc-oceanbase-catalog.md
- docs/jdbc-postgresql-catalog.md
- docs/manage-relational-metadata-using-gravitino.md
Correct document
Correct document
no
no need
> [MINOR] fix(docs): Correct document

- catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/PaimonCatalogOperations.java
remove duplicate schema names after list schemas from Paimon
Fix: #5424 
no
test in local env, create schema s1, create table t1, will get only one schema not two schemas
> [#5424] fix(paimon): remove duplicate schema names for Paimon catalog JDBC backend

- catalogs/catalog-hive/src/main/java/org/apache/gravitino/catalog/hive/HiveCatalogOperations.java
- catalogs/catalog-hive/src/test/java/org/apache/gravitino/catalog/hive/TestHiveTable.java
- catalogs/catalog-hive/src/test/java/org/apache/gravitino/catalog/hive/integration/test/CatalogHiveIT.java
- docs/apache-hive-catalog.md
the problem of slow acquisition of hive table list.
Using listTableNamesByFilter replace the getTableObjectsByName method.
I found that list-table will takes 300s when a schema has 5000 tables .
Fix: #4089 
no
Manual testing
> [#4089] fix(hive catalog): the problem of slow acquisition of hive table list

- bundles/gcp-bundle/build.gradle.kts
- bundles/gcp-bundle/src/main/resources/META-INF/services/org.apache.hadoop.fs.FileSystem
- docs/manage-fileset-metadata-using-gravitino.md
shade `gcp` package to `org.apache.gravitino.gcp.shaded` to avoid conflict with the shaded package in Gravitino.
The faster XML package in GCP bundle jar is conflict with the package in Gravitino java client runtime.
Fix: #5444 
no
run a app to use GCP bundle to do fileset operations.
> [#5444] fix(gcp): relocate GCP bundle jar to avoid conflict with Gravitino

- docs/how-to-use-gvfs.md
- docs/manage-fileset-metadata-using-gravitino.md
Fix s3 fileset example that uses "oss:/" prefix mistakenly. 
It's a mistake. 
N/A.
N/A
> [Minor] fix(docs): Fix mistakes in docs about the example of S3 fileset.

- web/web/src/lib/utils/axios/checkStatus.js
Refine error message in WebUI
N/A
Fix: #5461
N/A
manually
> [#5461] Improvement(web): Refine error message in WebUI

- docs/iceberg-rest-service.md
correct default catalog from `gravitino.iceberg-rest.catalog.<param name>=<value>`  to `gravitino.iceberg-rest.<param name>=<value>`
The example for Iceberg multi catalog is not correct 
no
testing with multi catalog for IcebergREST server
> [MINOR] docs: polish Iceberg REST server document

- bundles/gcp-bundle/build.gradle.kts
- core/src/main/java/org/apache/gravitino/Configs.java
- core/src/main/java/org/apache/gravitino/audit/FileAuditWriter.java
- docs/gravitino-server-config.md
1.  keep `gravitino.audit.enabled` configuration consistent with document
2. add FlushIntervalSecs to flush log writer
Fix: #5460 
No
enable audit log and check audit is written after about 10s
> [#5460] feat(core): Add FlushIntervalSecs to audit log file writer

- iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/utils/IcebergHiveCachedClientPool.java
- iceberg/iceberg-common/src/test/java/org/apache/gravitino/iceberg/common/utils/TestIcebergHiveCachedClientPool.java
Overwrite the equals and hashCode methods to avoid frequently creating HiveClientPool instances
Fix: https://github.com/apache/gravitino/issues/5442
No.
New UT.
> [#5442] Improvement(iceberg-common): Overwrite the equals and hashCode methods to avoid frequently creating HiveClientPool instances

- .github/workflows/build.yml
- bundles/aws-bundle/src/main/java/org/apache/gravitino/s3/fs/S3FileSystemProvider.java
Add the bundles and their sub-modules to the changes listening list. 
Bundles are newly added modules and should be added to the changes listening list.
Fix: #5473 
N/A
CI.
> [#5473] improvement(CI): Change CI build file to add bundles files into the build task.

- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoOptions.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/MetalakeAuditInfo.java
Add the `--audit` option to display audit information on Metalakes.
This change allows users to retrieve additional audit information on Metalakes, providing more insights.
Fix: #5276 
Yes, it adds the `--audit` option to `CommandEntities.METALAKE`.
1. Follow the instructions in the [cli README](https://github.com/apache/gravitino/tree/main/clients/cli) to build the CLI sub-project.
2. Start the Gravitino server.
To test, use a command like the following:
```
gcli metalake details --metalake <your meatalake name> --audit
```
Check that the output matches the expected audit information.
> [#5276] improment(cli): display audit information on Metalakes in the Gravitino CLI

- docs/open-api/catalogs.yaml
add provider enum value to openAPI
more catalog supports
no
CI passed
> [MINOR] fix(openAPI): add provider enum value to openAPI

- authorizations/authorization-ranger/build.gradle.kts
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/SecurableObjectMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/SecurableObjectSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/TagMetadataObjectRelMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/TagMetadataObjectRelSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/OwnerMetaBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/SecurableObjectBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/TagMetadataObjectRelBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/OwnerMetaPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/SecurableObjectPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/TagMetadataObjectRelPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/CatalogMetaService.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/FilesetMetaService.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/MetalakeMetaService.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/SchemaMetaService.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/TableMetaService.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/TopicMetaService.java
- core/src/test/java/org/apache/gravitino/storage/relational/TestJDBCBackend.java
- core/src/test/java/org/apache/gravitino/storage/relational/service/TestOwnerMetaService.java
- core/src/test/java/org/apache/gravitino/storage/relational/service/TestSecurableObjects.java
- core/src/test/java/org/apache/gravitino/storage/relational/service/TestTagMetaService.java
Delete the related relations about the metadata object when it is deleted.
Fix: #5029 
No.
Add UTs.
> [#5029] improvement(storage): Delete the related relations about the metadata object when it is deleted.

- api/src/main/java/org/apache/gravitino/authorization/Privilege.java
- api/src/main/java/org/apache/gravitino/authorization/Privileges.java
- authorizations/authorization-ranger/build.gradle.kts
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorization.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationHadoopSQLPlugin.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerBaseE2EIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveE2EIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerITEnv.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerIcebergE2EIT.java
- docs/security/access-control.md
- docs/security/authorization-pushdown.md
Lakehouse Iceberg catalog supports Ranger authorization plugin
Fix: #5118 
Add the document.
Add E2E tests.
> [#5118] feat(auth):  Lakehouse Iceberg catalog supports Ranger authorization plugin

- docs/how-to-use-the-playground.md
Add instructions for launching the playground with Git and a single curl command.
Provide instructions for users to launch the playground.
Fix: #5496
1. Change in how-to-use-the-playground.md
Use Markdown Live Preview.
https://markdownlivepreview.com/
> [#5496] docs: launch playground

- build.gradle.kts
- dev/release/release-build.sh
This PR improves the gradle and release script to skip some modules.
This is to avoid some unnecessary empty jars to be published to maven repo.
Fix: #5489 
No.
> [#5489] fix(build): Improve the gradle to skip some modules to avoid publishing empty jars

- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/AuditCommand.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/CatalogAudit.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/MetalakeAudit.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/SchemaAudit.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/TableAudit.java
- docs/cli.md
Add the `--audit` option to display audit information on Catalog, Schema, Table
This change allows users to retrieve additional audit information on Catalog/Schema/Table, providing more insights.
Close: #5477 
Yes, it adds the `--audit` option to `CommandEntities.CATALOG/SCHEMA/TABLE`.
1. Follow the instructions in the [cli README](https://github.com/apache/gravitino/tree/main/clients/cli) to build the CLI sub-project.
2. Start the Gravitino Playground.
To test, use a command like the following:
```
gcli metalake details --metalake metalake_demo --audit
gcli catalog details --metalake metalake_demo --name catalog_postgres --audit
gcli schema details --metalake metalake_demo --name catalog_postgres.hr --audit
gcli table details --metalake metalake_demo --name …
```
> [#5477] improvement(cli): display audit information on Catalog, Schema, Table

- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerBaseE2EIT.java
- core/src/main/java/org/apache/gravitino/config/ConfigConstants.java
- core/src/main/java/org/apache/gravitino/storage/relational/database/H2Database.java
- core/src/test/java/org/apache/gravitino/storage/relational/TestJDBCBackend.java
- core/src/test/java/org/apache/gravitino/storage/relational/service/TestFilesetMetaService.java
- integration-test-common/src/test/java/org/apache/gravitino/integration/test/util/BaseIT.java
- scripts/h2/schema-0.8.0-h2.sql
- scripts/h2/upgrade-0.7.0-to-0.8.0-h2.sql
- scripts/mysql/schema-0.8.0-mysql.sql
- scripts/mysql/upgrade-0.7.0-to-0.8.0-mysql.sql
- scripts/postgresql/schema-0.8.0-postgresql.sql
- scripts/postgresql/upgrade-0.7.0-to-0.8.0-postgresql.sql
Modify the length limit of privileges column
According to the privilege interface, our privilege max value is 64 * 64. Every privilege name is about 14 character. So I use 64* 64 * 20 as new length limit.
Fix: #5498 
No.
Manual test.
> [#5498] improvement(storage): Modify the length limit of privileges column

- clients/client-python/pylintrc
- clients/client-python/tests/integration/auth/test_oauth2_client.py
- clients/client-python/tests/integration/config.py
- clients/client-python/tests/integration/integration_test_env.py
This PR fixes missing-timeout Pylint rule for client-python 
- modified:
* clients/client-python/tests/integration/integration_test_env.py    (added a reasonable timeout for requests.get)
* clients/client-python/tests/integration/auth/test_oauth2_client.py   (added a reasonable timeout for requests.get)
* clients/client-python/pylintrc   (removed missing-timeout from disable section in pylintrc)
- new file:
* clients/client-python/tests/integration/config.py (added a file to store constant values)
Define a reasonable timeout for requests.get to prevent program from hanging indefinitely
Fix: #3765
No.
```bash
./gradlew clients:client-python:pylint
```
> [#3765] improvement(client-python): Fixed missing-timeout Pylint rule for client-python

- catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogOperations.java
- catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java
- catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopUserAuthenticationIT.java
- docs/manage-fileset-metadata-using-gravitino.md
This PR changes the schema drop mechanism to delete the fileset path one by one, instead of delete the schema path. This improvement will:
1. Delete the fileset path that is not under the schema's location.
2. Avoid deleting the external fileset path that happens to under schema location.
To make the drop mechanism correct.
Fix: #4842 
No.
Add UT to cover the changes.
> [#4842] fix(hadoop-catalog): Improve the schema drop logic for fileset catalog

- authorizations/authorization-ranger/build.gradle.kts
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorization.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationHadoopSQLPlugin.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerPrivileges.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerBaseE2EIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveE2EIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerITEnv.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerIcebergE2EIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerPaimonE2EIT.java
- docs/security/authorization-pushdown.md
- gradle/libs.versions.toml
Paimon catalog supports Ranger plugin. Kyuubi authz plugin doesn't support to update or delete the table.
Fix: #5517 
No.
Add IT.
> [#5517] feat(auth): Paimon catalog supports Ranger plugin

- core/src/main/java/org/apache/gravitino/listener/SchemaEventDispatcher.java
- core/src/main/java/org/apache/gravitino/listener/api/event/AlterSchemaPreEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/AlterTablePreEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/CreateSchemaPreEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/DropSchemaPreEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/ListSchemaPreEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/LoadSchemaPreEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/SchemaPreEvent.java
- core/src/test/java/org/apache/gravitino/listener/api/event/TestSchemaEvent.java
- core/src/test/java/org/apache/gravitino/listener/api/event/TestTableEvent.java
- docs/gravitino-server-config.md
add schema pre event to event listener
Close: #5547
no
add Unit Test
> [#5547] feat(core): support schema pre event for Gravitino server

- docs/how-to-test.md
Added instructions to docs/how-to-test.md for configuring Docker-dependent tests by setting skipDockerTests=false in gradle.properties, using -PskipDockerTests=false in the command, or exporting SKIP_DOCKER_TESTS=false in the shell.
To prevent confusion for users expecting a complete test run, as tests requiring Docker will be skipped by default without these configurations.
Fix: #5563
Yes, it provides clearer documentation on how to enable Docker-related tests to ensure a comprehensive test run.s.)
N/A
> [#5563] Improvement(docs): Improve Docker test instructions to enhance user clarity and guidance

- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoOptions.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/TableDistribution.java
- docs/cli.md
Add --distribution option to display distribution information on Tables.
This change allows users to retrieve additional distribution information on Tables
Closes: #5280 
Yes, it adds the --distribution option to CLI
Compiled and tested locally.
> [#5280] improvement(cli): Display distribution / bucketing information for Tables in the Gravitino CLI 

- build.gradle.kts
- remove cli dependencies from server lib
cli module introduces the slf4j-simple, which is unnecessary
Fix: #5598 
no
1. package: `compileDistribution -x test`
2. list the server libs and does not see the jar of slf4j-simple
> [#5598] fix(dependency): fix multiple SLF4J providers issue

- web/web/src/app/metalakes/metalake/rightContent/CreateTableDialog.js
- web/web/src/lib/utils/index.js
- web/web/src/lib/utils/initial.js
Create and update column types `['char', 'varchar', 'fixed', `decimal`]` with parameters  
Close: #5453 
four more table type column type on selection 
Create part 1
Create part 2
Update
> [#5453] subtask(web): support for table column types with parameters

- catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/SecureHadoopCatalogOperations.java
the `testConnection` throw Exception is redundant in this method, so we should remove it.
update the code quality
n/a
n/a
> [MINOR] Remove unused throw exception in SecureHadoopCatalogOperations#testConnection

- core/src/main/java/org/apache/gravitino/listener/TopicEventDispatcher.java
- core/src/main/java/org/apache/gravitino/listener/api/event/AlterTopicPreEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/CreateTopicPreEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/DropTopicPreEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/ListTopicPreEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/LoadTopicPreEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/TopicPreEvent.java
- core/src/test/java/org/apache/gravitino/listener/api/event/TestTopicEvent.java
Add pre-events for topic events, including `AlterTopicPreEvent`, `CreateTopicPreEvent`, `DropTopicPreEvent`, `ListTopicPreEvent` and `LoadTopicPreEvent`.
Fix: #5551 
No.
Related Unit Tests have been added.
> [#5551] feat(core): add topic pre-event to Gravitino event.

- catalogs/catalog-hive/src/test/java/org/apache/gravitino/catalog/hive/TestFetchFileUtils.java
Increase the timeout to avoid flaky issue.
Previously we increased the retry times, but not timeout, we should increase the timeout to make the test more robust.
Fix: #5213 
No.
Existing UTs.
> [#5213] fix(test): Increase the timeout to avoid flaky test

- web/web/src/app/metalakes/metalake/rightContent/CreateTableDialog.js
- web/web/src/lib/utils/initial.js
When creating or updating a table, the column types will vary depending on the provider.
Fixes: #5454
No.
Tested by creating and updating tables with different providers to verify that the column types differ as expected and match the [documentation](https://gravitino.apache.org/docs/0.6.1-incubating/lakehouse-iceberg-catalog/#table-column-types).
Additionally, verified the success of the create/update operations.
> [#5454] feat(web): different data table column types are supported depending on the provider

- web/web/src/app/metalakes/metalake/rightContent/CreateCatalogDialog.js
- web/web/src/lib/utils/initial.js
Modified:
- app/metalakes/metalake/rightContent/CreateCatalogDialog.js
- lib/utils/initial.js
Iceberg catalog supports hive, jdbc catalog backend in WEB, we need to support rest catalog backend too, it only supports uri properties.
1. Add select item 'rest' in the dropbox menu.
2. When select rest menu item, only show 'uri' properties edit needs to input.
Yes, this PR introduces web UI changes : 
1.  Add a selectable item called 'rest' to the dropdown menu when creating a new catalog.
2.  Remove all other properties except 'uri.'
Visit the Gravitino web UI through the browser and click 'Create Catalog' .
Then, check the menu items and the API call in debug mode. 
You can see the HTTP payload sent as follows:
POST  http://localhost:3000/api/metalakes/test/catalogs
```json
{
"name": "1", …
```
> [#5452] Improvement(web): add REST catalog backend for Iceberg catalog

- api/src/main/java/org/apache/gravitino/Catalog.java
- api/src/main/java/org/apache/gravitino/MetadataObject.java
- api/src/main/java/org/apache/gravitino/MetadataObjects.java
- api/src/main/java/org/apache/gravitino/exceptions/ModelAlreadyExistsException.java
- api/src/main/java/org/apache/gravitino/exceptions/ModelVersionAliasesAlreadyExistException.java
- api/src/main/java/org/apache/gravitino/exceptions/ModelVersionAliasesAlreadyExistsException.java
- api/src/main/java/org/apache/gravitino/exceptions/NoSuchModelException.java
- api/src/main/java/org/apache/gravitino/exceptions/NoSuchModelVersionException.java
- api/src/main/java/org/apache/gravitino/model/Model.java
- api/src/main/java/org/apache/gravitino/model/ModelCatalog.java
- api/src/main/java/org/apache/gravitino/model/ModelVersion.java
This PR adds the API definition for ML model and model catalog.
This is the first step to support ML model management in Gravitino.
Fix: #5600 
Yes.
Manual verification.
> [#5600] feat(API): Add Java API definition for ML model in Gravitino

- web/web/src/app/metalakes/metalake/rightContent/CreateTableDialog.js
- web/web/src/lib/utils/initial.js
Disable the creation or update of reserved fields in table properties.
Fix #5455.
Users will no longer be able to create or update reserved fields in table properties.
Tested by attempting to create or update reserved fields in table properties to ensure it is not allowed.
> [#5455] feat(web): disable to update the reserved fields of table properties

- core/src/main/java/org/apache/gravitino/listener/FilesetEventDispatcher.java
- core/src/main/java/org/apache/gravitino/listener/api/event/AlterFilesetPreEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/CreateFilesetPreEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/DropFilesetPreEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/FilesetPreEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/GetFileLocationPreEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/ListFilesetPreEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/LoadFilesetPreEvent.java
- core/src/test/java/org/apache/gravitino/listener/api/event/TestFilesetEvent.java
- docs/gravitino-server-config.md
add fileset pre event to Gravitino event 
Fix: #5548 
no
added unit test
> [#5548] feat(core): add fileset pre event to Gravitino event 

- core/src/main/java/org/apache/gravitino/Entity.java
- core/src/main/java/org/apache/gravitino/GravitinoEnv.java
- core/src/main/java/org/apache/gravitino/catalog/CapabilityHelpers.java
- core/src/main/java/org/apache/gravitino/catalog/ModelDispatcher.java
- core/src/main/java/org/apache/gravitino/catalog/ModelNormalizeDispatcher.java
- core/src/main/java/org/apache/gravitino/catalog/ModelOperationDispatcher.java
- core/src/main/java/org/apache/gravitino/connector/capability/Capability.java
- core/src/main/java/org/apache/gravitino/meta/ModelEntity.java
- core/src/main/java/org/apache/gravitino/meta/ModelVersionEntity.java
- core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java
- core/src/main/java/org/apache/gravitino/utils/MetadataObjectUtil.java
- core/src/main/java/org/apache/gravitino/utils/NameIdentifierUtil.java
- core/src/main/java/org/apache/gravitino/utils/NamespaceUtil.java
- core/src/test/java/org/apache/gravitino/meta/TestModelEntity.java
- core/src/test/java/org/apache/gravitino/meta/TestModelVersionEntity.java
- core/src/test/java/org/apache/gravitino/utils/TestMetadataObjectUtil.java
- core/src/test/java/org/apache/gravitino/utils/TestNameIdentifierUtil.java
- core/src/test/java/org/apache/gravitino/utils/TestNamespaceUtil.java
1. Define and add the model namespace, name identifier, entity definition in Gravitino.
2. Add the basic dispatcher framework in Gravitino.
This is the second PR to support model management in Gravitino.
Fix: #5601 
No.
Add UTs to verify part of the code.
> [#5601] feat(core): Add model entity and model dispatcher in Gravitino

- build.gradle.kts
As title
Fix: #5647
Makes users easy to know it is from Gravitino
Execute Gradle command `./gradlew publishToMavenLocal -x test` then check in Maven local path.
> [#5647] improvement(build): update the jar name to add gravitino prefix 

- core/src/main/java/org/apache/gravitino/credential/CredentialUtils.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergTableOperations.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/integration/test/IcebergRESTS3IT.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/integration/test/IcebergRESTServiceIT.java
This PR updates the credential generation process to also consider `write.data.path` and `write.metadata.path`.
To provide greater flexibility for users.  
Fixes: #5648
No.
- Used Spark to create a table via Gravitino Iceberg REST server to AWS S3 and verified that `write.data.path` and `write.metadata.path` are working as expected.  
- Added unit tests to check if table properties include `write.data.path` and `write.metadata.path`.
> [#5648] improvement(iceberg): generate credential according to the data path and metadata path

- catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/converter/DorisTypeConverter.java
- catalogs/catalog-jdbc-doris/src/test/java/org/apache/gravitino/catalog/doris/integration/test/CatalogDorisIT.java
- catalogs/catalog-jdbc-doris/src/test/java/org/apache/gravitino/catalog/doris/operation/TestDorisTableOperations.java
When loading table with datetime column from Doris table, we should convert it to Gravitno timestamp without timezone NOT timestamp_tz(timestamp with timezone)
According to docs 
1. https://gravitino.apache.org/docs/0.7.0-incubating/jdbc-doris-catalog#table-column-types
2. https://doris.apache.org/docs/1.2/sql-manual/sql-reference/Data-Definition-Statements/Create/CREATE-TABLE
it's a bug when converting Gravitino timestamp type to Doris datetime type. 
Fix: #5691
N/A
UT & IT
> [#5691] fix(doris-catalog): Fix errors in type mapping about timestamp in Doris catalog.

- clients/cli/build.gradle.kts
- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoOptions.java
- clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/CatalogDetails.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/Command.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListMetalakes.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/MetalakeDetails.java
- clients/cli/src/main/java/org/apache/gravitino/cli/outputs/OutputFormat.java
- clients/cli/src/main/java/org/apache/gravitino/cli/outputs/PlainFormat.java
- clients/cli/src/main/java/org/apache/gravitino/cli/outputs/TableFormat.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestCatalogCommands.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestMetalakeCommands.java
- clients/cli/src/test/java/org/apache/gravitino/cli/integration/test/TableFormatOutputIT.java
Enhance the Gravitino CLI with formatted output.
Issue: #5506
Cause the original PR (https://github.com/apache/gravitino/pull/5606) cannot be reopened, I create a new PR.
The purpose is to make Gravitino CLI output look more readable; currently, it supports only table and plain output formats.
No.
```shell
gcli metalake list
gcli metalake list --output plain
gcli metalake list --output table
```
> [#5506] feat(CLI): Table formatted output

- build.gradle.kts
- clients/cli/src/main/resources/catalog_help.txt
Added extended help for catalog commands.
To provide user with extra help.
Fix: #5700
No.
N/A
> [#5700] feat(CLI):Add extended help for catalogs in Gravitino CLI

- dev/docker/iceberg-rest-server/rewrite_config.py
Fix potential parsing error in the `rewrite_config.parse_config_file` function.
If a configuration line contains multiple '=' characters, the `rewrite_config.parse_config_file` function will throw a `ValueError: too many values to unpack`. 
This change ensures the function correctly handles lines with multiple '=' characters.
No.
Rebuilt the project and tested with configurations containing multiple '=' characters in a single line.
> [minor] fix(dev): fix ValueError when parsing config file with multiple '=' in one line

- catalogs/catalog-lakehouse-paimon/src/main/java/org/apache/gravitino/catalog/lakehouse/paimon/utils/TableOpsUtils.java
- catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/ops/TestPaimonCatalogOps.java
- catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/utils/TestTableOpsUtils.java
fix camelCase method names from `getfieldName` to `getFieldName`
`getfieldName` is not standardized in naming
none
TestTableOpsUtils
> [hotfix] fix camelCase method names from getfieldName to getFieldName

- docs/lakehouse-paimon-catalog.md
Fix the binary data type mapping error of the gravitino and paimon tables in the paimon catalog document.
> [MINOR] fix(doc): Fix the binary data type mapping error of the gravitino and paimon tables in the paimon catalog document.

- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoOptions.java
- clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/TableSortOrder.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestTableCommands.java
- docs/cli.md
Add --sortorder option to display sort order information on Tables.
Closes: #5279
Yes, it adds the --sortorder option to CLI
Compiled and tested locally.
> [#5279] improvement(cli): Display sort order information for Tables in the Gravitino CLI

- web/web/src/app/metalakes/metalake/rightContent/CreateTableDialog.js
Handle unsupported column types.
Fix: #5707
No.
Tested by opening a table containing unsupported column types (e.g., list, map, struct).
> [#5707] fix(web): edit some table would encounter the error: TypeError: e.type.match is not a function 

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/Command.java
Missing param `<T>` is added to the `output` method of `Command.java`.
Fix: https://github.com/apache/gravitino/issues/5772
No.
To verify, please run the following command:
```
./gradlew clean build -x test
```
After running this command, the warning `no @param for <T>` will no longer appear.
> [#5772] fix: missing param <T>

- dev/docker/iceberg-rest-server/rewrite_config.py
modified:
- __dev/docker/iceberg-rest-server/rewrite_config.py__
Correct the shebang line to specify the correct shell `bash`
```bash
#!/usr/bin/env bash
```
<br>
The `env` command should be assigned an interpreter like `bash` or `python`. 
<br>
No.
<br>
Although we usually execute this script with the Python interpreter (for example: `python rewrite_config.py`) rather than executing it without an interpreter, with the fix applied, executing this script without an interpreter will no longer result in a hang.
> [#5754] improve(build): Fix rewrite_config.py with the correct shebang line

- clients/cli/src/main/java/org/apache/gravitino/cli/outputs/TableFormat.java
- clients/cli/src/test/java/org/apache/gravitino/cli/integration/test/TableFormatOutputIT.java
Enhanced the Gravitino CLI to support properly formatted output. Fixed alignment issues in formatted output when it includes Chinese characters.
The bounding box length calculation is now based on the number of characters rather than the character display width . The correct output should look like this(Here are the results of my local tests):
Only change the implementation of the TableFormatImpl class, the same effect is achieved when the `catalog list --output table` command is supported
Fix: #5768
NO.
```shell
gcli catalog details --name <catalog>  --metalake <metalake> --output table
gcli metalake details --name <metalake>  --output table
gcli metalake list --output table
```
> [#5768] improvement(CLI): improve formatted output

- catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/converter/JdbcTypeConverter.java
- catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/operation/JdbcTableOperations.java
- catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/converter/DorisColumnDefaultValueConverter.java
- catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/converter/DorisTypeConverter.java
- catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/operation/DorisTablePartitionOperations.java
- catalogs/catalog-jdbc-mysql/src/main/java/org/apache/gravitino/catalog/mysql/converter/MysqlColumnDefaultValueConverter.java
- catalogs/catalog-jdbc-mysql/src/main/java/org/apache/gravitino/catalog/mysql/converter/MysqlTypeConverter.java
- catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/converter/TestMysqlTypeConverter.java
- catalogs/catalog-jdbc-oceanbase/src/main/java/org/apache/gravitino/catalog/oceanbase/converter/OceanBaseColumnDefaultValueConverter.java
- catalogs/catalog-jdbc-oceanbase/src/main/java/org/apache/gravitino/catalog/oceanbase/converter/OceanBaseTypeConverter.java
- catalogs/catalog-jdbc-oceanbase/src/test/java/org/apache/gravitino/catalog/oceanbase/converter/TestOceanBaseTypeConverter.java
- catalogs/catalog-jdbc-postgresql/src/main/java/org/apache/gravitino/catalog/postgresql/converter/PostgreSqlColumnDefaultValueConverter.java
- catalogs/catalog-jdbc-postgresql/src/main/java/org/apache/gravitino/catalog/postgresql/converter/PostgreSqlTypeConverter.java
- catalogs/catalog-jdbc-postgresql/src/test/java/org/apache/gravitino/catalog/postgresql/converter/TestPostgreSqlTypeConverter.java
Modify the ColumnSize/Scale of JdbcTypeBean to be of type integer. 
Fix: [# (5784)](https://github.com/apache/gravitino/issues/5784)
> [#5784] improvement(catalog) Modify the ColumnSize/Scale of JdbcTypeBean to be of type integer. 

- clients/cli/src/main/resources/schema_help.txt
Add extended help for schema in Gravitino CLI
To provide user with extra help.
Fix: https://github.com/apache/gravitino/issues/5782
No.
N/A
> [#5782][Improvement] Add extended help for schema in Gravitino CLI

- api/src/main/java/org/apache/gravitino/Catalog.java
- api/src/main/java/org/apache/gravitino/CatalogProvider.java
- api/src/main/java/org/apache/gravitino/SupportsCatalogs.java
- build.gradle.kts
- catalogs/catalog-hadoop/build.gradle.kts
- catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java
- catalogs/catalog-hive/src/test/java/org/apache/gravitino/catalog/hive/TestHiveCatalog.java
- catalogs/catalog-kafka/src/test/java/org/apache/gravitino/catalog/kafka/TestKafkaCatalogOperations.java
- catalogs/catalog-lakehouse-hudi/src/test/java/org/apache/gravitino/catalog/lakehouse/hudi/TestHudiCatalogOperations.java
- catalogs/catalog-lakehouse-iceberg/src/test/java/org/apache/gravitino/catalog/lakehouse/iceberg/TestIcebergCatalog.java
- catalogs/catalog-lakehouse-paimon/src/test/java/org/apache/gravitino/catalog/lakehouse/paimon/TestPaimonCatalog.java
- catalogs/catalog-model/build.gradle.kts
- catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalog.java
- catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogCapability.java
- catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogPropertiesMetadata.java
- catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelPropertiesMetadata.java
- catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelSchemaPropertiesMetadata.java
- catalogs/catalog-model/src/main/resources/META-INF/services/org.apache.gravitino.CatalogProvider
- catalogs/catalog-model/src/main/resources/model.conf
- clients/client-python/gravitino/api/catalog.py
- clients/client-python/gravitino/dto/catalog_dto.py
- clients/client-python/gravitino/dto/requests/catalog_create_request.py
- common/src/main/java/org/apache/gravitino/dto/requests/CatalogCreateRequest.java
- common/src/test/java/org/apache/gravitino/dto/requests/TestCatalogCreateRequest.java
- core/src/main/java/org/apache/gravitino/connector/BaseCatalog.java
- core/src/main/java/org/apache/gravitino/connector/HasPropertyMetadata.java
- settings.gradle.kts
This PR adds the basic catalog-model framework in Gravitino. In the meantime, it also makes `provider` optional for built-in catalog.
Fix: #5744 
No.
Tests will be added later on.
> [#5744]feat(catalog-model): Add a basic catalog-model framework in Gravitino

- core/src/main/java/org/apache/gravitino/auxiliary/AuxiliaryServiceManager.java
Fix the issue #5697 
Adding a filter operator to filter out unexpected key.
Currently it will lead to unexpected warning which is confusing.
Fix: #5697 
No
Test locally
> [#5697] feat(core): Fix unexpected warning in AuxiliaryServiceManager

- catalogs/catalog-jdbc-mysql/src/main/java/org/apache/gravitino/catalog/mysql/converter/MysqlTypeConverter.java
- catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
- catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/operation/TestMysqlTableOperations.java
- docs/jdbc-mysql-catalog.md
- trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-mysql/00006_datatype.sql
- trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-mysql/00006_datatype.txt
Fix: https://github.com/apache/gravitino/issues/5659
> [#5659] improvement(catalog-mysql) : support load MySQL BOOLEAN data in Trino

- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/GravitinoConfig.java
The exception message should be `catalog.management = dynamic` when the trino configuration is incorrect.
No
Not required
> [MINOR] docs: fix typo in catalog.management exception message

- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoOptions.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestGroupCommands.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestUserCommands.java
Add ability to grant or revoke multiple roles or groups at once in the Gravitino CLI,
Fix:[#5569](https://github.com/apache/gravitino/issues/5569)
No.
**Grant\revoke role to user**
1. Grant single role to a user
2. Grant multiple role to a user
3. Revoke multiple role to from user
**Grant\revoke role to group**
1.  Grant single role to a group
2. Grant multiple role to a group
3. Revoke multiple role to from group
Please check the [commit](https://github.com/apache/gravitino/commit/788396aab379638707ca5733e89069fab0e0002f)
> [#5569] improvement(CLI): Add ability to grant or revoke multiple roles or groups at once in the Gravitino CLI

- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
Currently, when a metalake is created without specifying the metalake argument, the message "Cannot parse a null or empty identifier" is displayed. This message is unclear and lacks helpful guidance for the user. Update the message to: "! metalake is not defined" to make it more user-friendly and informative.
Fix: #5825 
NO
> [#5825] improvement(CLI): Update the error message for creating a metalake when the required parameter is missing.

- .github/workflows/gvfs-fuse-build-test.yml
- clients/filesystem-fuse/.cargo/config.toml
- clients/filesystem-fuse/rust-toolchain.toml
- clients/filesystem-fuse/src/filesystem.rs
- clients/filesystem-fuse/src/fuse_api_handle.rs
- clients/filesystem-fuse/src/lib.rs
1. Implement basic FUSE interfaces.
2. Implement filesystem trait and relation structures.
Fix: #5734
No
No
> [#5734] feat (gvfs-fuse):  Gvfs-fuse basic FUSE-level implementation and code structure layout

- catalogs/catalog-jdbc-postgresql/src/test/java/org/apache/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java
- core/src/main/java/org/apache/gravitino/catalog/SchemaOperationDispatcher.java
- core/src/main/java/org/apache/gravitino/catalog/TableOperationDispatcher.java
- docs/manage-relational-metadata-using-gravitino.md
- remind users not to register multiple catalogs using the same data source in the user doc
- clarify exception when importing entity multiple times.
Fix: #5329 
import one source multiple times will update the existing record and result in unexpected behaviors
yes, clarify the exception
tests added
> [#5329] improvement(core): Clarify exception when importing entity multiple times

- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ColumnAudit.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestColumnCommands.java
- docs/cli.md
Add column audit command.
Column audi info was added after the CLI work was done.
Fix: # N/A
Adds one command
> [Minor] Add column audit command to CLI

- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/GroupAudit.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RoleAudit.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/UserAudit.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestGroupCommands.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestRoleCommands.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestUserCommands.java
- docs/cli.md
Added audit command to roles, users and groups in the Gravitino CLI.
So all entities support the audit command.
Fix: #5527
No, but add more commands.
> [#5527] Add audit command to roles, users and groups in the Gravitino CLI

- clients/client-python/gravitino/api/credential/oss_secret_key_credential.py
- clients/client-python/gravitino/utils/credential_factory.py
- clients/client-python/tests/unittests/test_credential_factory.py
It adds support for OSSSecretKeyCredential for the Python client by implementing it, updating CredentialFactory to create instances of it, and adding corresponding unit tests in TestCredentialFactory.
These changes are necessary to support authentication using OSS credentials and to allow the CredentialFactory to generate OSS credentials correctly. It ensures proper functionality and integration.
Fix: #5880 
No
Unit tests were created to test the new OSSSecretKeyCredential class, verifying its functionality and integration with the CredentialFactory.
> [Improvement] support OSSSecretKeyCredential for python client

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListColumns.java
When using the column list command, the CLI should provide a hint rather than throwing an exception if the table does not exist.
When using the column list command, the CLI should provide a hint rather than throwing an exception if the table does not exist.
Fix: #5824 
No
> [#5824] fix(CLI): Fix CLi throws an inappropriate exception when table name is unknown in Gravitino CLI command

- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/PartitionConverter.java
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/catalog/BaseCatalog.java
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/catalog/BaseCatalogFactory.java
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/hive/GravitinoHiveCatalog.java
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/hive/GravitinoHiveCatalogFactory.java
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/store/GravitinoCatalogStore.java
1. Remove useless code
2. Optimize the logic of the store, and when adding connector support, there is no need to modify the logic of the store.
Fix : [#5867](https://github.com/apache/gravitino/issues/5867)
No.
FlinkHiveCatalogIT
> [#5867] feat(flink-connector) Improve flink connector

- docs/security/access-control.md
Fix the wrong shell command. We should use `roles` instead of `tags`
Fix: #5913
No.
Just documents.
> [#5913] fix(docs): Fix the wrong shell command

- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorization.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationHDFSPlugin.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationHadoopSQLPlugin.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerAuthorizationHDFSPluginIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerAuthorizationPluginIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerBaseE2EIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerFilesetIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveE2EIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerITEnv.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerIcebergE2EIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerPaimonE2EIT.java
- core/src/main/java/org/apache/gravitino/connector/BaseCatalog.java
- core/src/main/java/org/apache/gravitino/connector/authorization/BaseAuthorization.java
- core/src/test/java/org/apache/gravitino/connector/authorization/mysql/TestMySQLAuthorization.java
- core/src/test/java/org/apache/gravitino/connector/authorization/ranger/TestRangerAuthorization.java
1. Remove AuthorizationPlugin single instance implement in the `BaseAuthorizaiton.java`
2. Updatge ITs codes.
Fix: #5916
N/A
CI Passed.
> [#5916] improve(auth): Remove AuthorizationPlugin single instance implement

- clients/cli/src/main/java/org/apache/gravitino/cli/ErrorMessages.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
Slightly missing leading error message when group is not specified, it should give some hints to user.
Fix: #5829 
NO
```bash
bin/gcli.sh group create --metalake demo_metalake
bin/gcli.sh group details --metalake demo_metalake
bin/gcli.sh group delete --metalake demo_metalake
```
> [#5829] improvement(CLI): Slightly misleading error message when group is not specified

- core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java
- core/src/main/java/org/apache/gravitino/authorization/PermissionManager.java
- core/src/main/java/org/apache/gravitino/authorization/RoleManager.java
- core/src/test/java/org/apache/gravitino/authorization/TestAuthorizationUtils.java
Avoid other catalogs' privileges are pushed down.
For example, if a role has two catalogs. One catalog has select table, the other catalog has create table.
The plugin will make the role can create and select table at the same time.
Fix: #5934
No.
Add a UT
> [#5934] fix(auth): Avoid other catalogs' privileges are pushed down

- catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergCatalogPropertiesMetadata.java
- catalogs/catalog-lakehouse-iceberg/src/test/java/org/apache/gravitino/catalog/lakehouse/iceberg/TestIcebergCatalog.java
- gradle.properties
- iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/IcebergConfig.java
- iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/ops/IcebergCatalogWrapper.java
Removed the systematic validations in Iceberg Config and modified the instantiation of the warehouse attribute and uri attribute in the IcebergCatalogWrapper to conform with the new possibility (REST).
The bug was blocking the creation of a rest catalog.
Fix: [#5756](https://github.com/apache/gravitino/issues/5756)
No
./gradlew build && compileDistribution && assembleDistribution + creation of the docker image there : https://hub.docker.com/r/fsalhi2/gravitino
Started gravitino with such configs : 
```
gravitino.auxService.names = iceberg-rest
gravitino.iceberg-rest.classpath = iceberg-rest-server/libs, iceberg-rest-server/conf
gravitino.iceberg-rest.host = 0.0.0.0
gravitino.iceberg-rest.httpPort = 9001
gravitino.iceberg-rest.io-impl = org.apache.iceberg.aws.s3.S3FileIO …
```
> [#5756] Bug Fix : Warehouse parameter systematically required 

- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestSchemaCommands.java
Fix schema arguments validation just like table commands. running  command like  `gcli schema details --metalake metalake_demo --name catalog_postgres -I` give Missleading error message as below.
```bash
Malformed entity name.
Invalid string to encode: null
```
It should display a friendly error message.
Fix: #5926 
NO
```bash
bin/gcli.sh schema details --m demo_metalake -i
bin/gcli.sh schema details --m demo_metalake --name Hive_catalog -i
bin/gcli.sh schema details --m demo_metalake --name Hive_catalog.default -i
bin/gcli.sh schema list --m demo_metalake -i
bin/gcli.sh schema list --m demo_metalake -i --name Hive_catalog
```
> [#5926] fix(CLI): Fix Missleading error message in Gravitino CLI when missing schema

- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerBaseE2EIT.java
- core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java
Fix the issue of renaming catalogs or metalakes.
Fix: #5947
No.
Add UT.
> [#5947] fix(auth): It will throw error if we enable authorization and rename catalog

- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestColumnCommands.java
Fix columns details command produces no output, when command without --audit option, cli should tell user that command is not support.
Fix: #5928 
NO
local test.
> [#5928] fix(CLI): Fix columns details command produces no output

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/GroupDetails.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/UserDetails.java
If a user has no roles then no output is produced from `user\group details` command, it should give some help information.
Fix: #5929 
NO
```bash
bin/gcli.sh user details -m demo_metalake --user test_user
bin/gcli.sh group details -m demo_metalake --group group_no_role
```
> [#5929] improvement(CLI): fix cli details command produce no output

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListAllTags.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListCatalogs.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListFilesets.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListGroups.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListMetalakes.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListRoles.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListSchema.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListTables.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListTopics.java
When using the list command, it’s helpful to provide a friendly information if no data is retrieve.
Fix: #5924 
NO
```bash
bin/gcli.sh catalog list -m demo_metalake2
bin/gcli.sh table list -m demo_metalake --name Hive_catalog.empty
```
> [#5924] improvement(CLI): fix cli list command produce no outputs

- clients/cli/src/main/java/org/apache/gravitino/cli/FullName.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestFulllName.java
If an entity name is malformed, the CLI should output 'Malformed entity name.' only once, instead of multiple times.
Fix: #5927 
NO
```bash
bin/gcli.sh column list  -m demo_metalake --name Hive_catalog -i
```
> [#5927] improvement(CLI): fix cli get multiple "Malformed entity name."

- clients/client-python/gravitino/api/credential/adls_token_credential.py
- clients/client-python/gravitino/api/credential/azure_account_key_credential.py
- clients/client-python/gravitino/api/credential/gcs_token_credential.py
- clients/client-python/gravitino/api/credential/oss_secret_key_credential.py
- clients/client-python/gravitino/api/credential/oss_token_credential.py
- clients/client-python/gravitino/api/credential/s3_secret_key_credential.py
- clients/client-python/gravitino/api/credential/s3_token_credential.py
- clients/client-python/gravitino/utils/credential_factory.py
- clients/client-python/tests/unittests/test_credential_factory.py
Support ADLS credential for python client
These changes are necessary to support authentication using ADLS credentials and to allow the CredentialFactory to generate ADLS credentials correctly. It ensures proper functionality and integration.
Fix: #5895
No
Unit tests.
> [#5895] support ADLSToken/AzureAccountKey credential for python client

- clients/filesystem-fuse/.cargo/config.toml
- clients/filesystem-fuse/Cargo.toml
- clients/filesystem-fuse/Makefile
- clients/filesystem-fuse/build.gradle.kts
- clients/filesystem-fuse/src/default_raw_filesystem.rs
- clients/filesystem-fuse/src/filesystem.rs
- clients/filesystem-fuse/src/fuse_api_handle.rs
- clients/filesystem-fuse/src/lib.rs
- clients/filesystem-fuse/src/main.rs
- clients/filesystem-fuse/src/opened_file.rs
- clients/filesystem-fuse/src/opened_file_manager.rs
- clients/filesystem-fuse/src/utils.rs
Implement a common filesystem layer to handle manage file ids, file name mappings, and file relationships. and delegate filesystem APIs to PathFilesystem.
Fix: #5877
No
Uts
> [#5877] feat (gvfs-fuse): Implement a common filesystem layer 

- integration-test-common/src/test/java/org/apache/gravitino/integration/test/container/ContainerSuite.java
Uses thread safe to create Docker network
Fix: #5969
N/A
CI Passed.
> [#5969] fix(Docker): Failed to create Docker network by concurrent execution ITs

- clients/cli/src/main/java/org/apache/gravitino/cli/ErrorMessages.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestCatalogCommands.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestColumnCommands.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestFilesetCommands.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestGroupCommands.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestMain.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestTableCommands.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestTagCommands.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestTopicCommands.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestUserCommands.java
refactor the validation logic of all entities and add test case, just like validation of table command #5906 . A hint is provided when the user's output is missing the required arguments. for example:
```bash
gcli column list -m demo_metalake, --name Hive_catalog
gcli column details -m demo_metalake, --name Hive_catalog --audit
gcli user delete -m demo_metalake
Missing --user option.
```
Currently, the Role command needs to be refactored and opened as a separate issue
Fix: #5861 
NO
local test
> [#5861] improvement(CLI): Refactor the validation logic in the handle methods

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/TagEntity.java
Improve output when CLI add an unknown tags.
Fix: #5930 
NO
local test
> [#5930] improvement(CLI): improve unknown tag output.

- api/src/main/java/org/apache/gravitino/model/ModelCatalog.java
- catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogImpl.java
- catalogs/catalog-model/src/main/resources/META-INF/services/org.apache.gravitino.CatalogProvider
- common/src/main/java/org/apache/gravitino/dto/model/ModelDTO.java
- common/src/main/java/org/apache/gravitino/dto/model/ModelVersionDTO.java
- common/src/main/java/org/apache/gravitino/dto/requests/CatalogCreateRequest.java
- common/src/main/java/org/apache/gravitino/dto/requests/ModelRegisterRequest.java
- common/src/main/java/org/apache/gravitino/dto/requests/ModelVersionLinkRequest.java
- common/src/main/java/org/apache/gravitino/dto/responses/ModelResponse.java
- common/src/main/java/org/apache/gravitino/dto/responses/ModelVersionListResponse.java
- common/src/main/java/org/apache/gravitino/dto/responses/ModelVersionResponse.java
- common/src/main/java/org/apache/gravitino/dto/util/DTOConverters.java
- common/src/test/java/org/apache/gravitino/dto/model/TestModelDTO.java
- common/src/test/java/org/apache/gravitino/dto/model/TestModelVersionDTO.java
- common/src/test/java/org/apache/gravitino/dto/requests/TestCatalogCreateRequest.java
- common/src/test/java/org/apache/gravitino/dto/requests/TestModelRegisterRequest.java
- common/src/test/java/org/apache/gravitino/dto/requests/TestModelVersionLinkRequest.java
- common/src/test/java/org/apache/gravitino/dto/responses/TestResponses.java
- docs/open-api/models.yaml
- docs/open-api/openapi.yaml
- server/src/main/java/org/apache/gravitino/server/GravitinoServer.java
- server/src/main/java/org/apache/gravitino/server/web/rest/ExceptionHandlers.java
- server/src/main/java/org/apache/gravitino/server/web/rest/ModelOperations.java
- server/src/main/java/org/apache/gravitino/server/web/rest/OperationType.java
- server/src/test/java/org/apache/gravitino/server/web/rest/TestModelOperations.java
This PR adds the server-side REST endpoint for model management.
This is a part of model management for Gravitino.
Fix: #5817 
No.
Add UTs for this PR.
> [#5817] core(feat): Add server-side REST APIs for model management

- authorizations/authorization-common/src/main/java/org/apache/gravitino/authorization/jdbc/JdbcAuthorizationPlugin.java
- authorizations/authorization-common/src/main/java/org/apache/gravitino/authorization/jdbc/JdbcSecurableObject.java
- authorizations/authorization-common/src/test/java/org/apache/gravitino/authorization/jdbc/TestJdbcAuthorizationPlugin.java
Make some methods public, let some classes to reuse some methods.
This is a follow-up PR.
No.
No need. Just refactor.
> [#5993][FOLLOWUP] Make some methods public

- server/src/main/java/org/apache/gravitino/server/web/ConfigServlet.java
- server/src/test/java/org/apache/gravitino/server/web/TestConfigServlet.java
- web/web/src/lib/store/auth/index.js
Add more configurations for the config API
Fix #5987 
Front end can use this config option to optimize the user experience.
No.
> [#5987] improvement: Add more configurations for the config API

- catalogs/catalog-common/src/main/java/org/apache/gravitino/credential/CredentialConstants.java
- core/src/main/java/org/apache/gravitino/config/ConfigBuilder.java
- core/src/main/java/org/apache/gravitino/connector/PropertyEntry.java
- core/src/main/java/org/apache/gravitino/credential/CatalogCredentialManager.java
- core/src/main/java/org/apache/gravitino/credential/CredentialCache.java
- core/src/main/java/org/apache/gravitino/credential/CredentialCacheKey.java
- core/src/main/java/org/apache/gravitino/credential/PathBasedCredentialContext.java
- core/src/main/java/org/apache/gravitino/credential/config/CredentialConfig.java
- core/src/test/java/org/apache/gravitino/credential/TestCredentialCacheKey.java
add credential cache for Gravitino server,  not support for Iceberg rest server yet.
Fix: #4398 
no
testing in local env,  get credential from Gravitino server and see whether it's fetched from remote or local cache
> [#4398] feat(core): support credential cache for Gravitino server

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListCatalogs.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListMetalakes.java
- clients/cli/src/main/java/org/apache/gravitino/cli/outputs/PlainFormat.java
- clients/cli/src/main/java/org/apache/gravitino/cli/outputs/TableFormat.java
In the `ListMetalakes` and `ListCatalogs` methods, retain the use of  `output(metalakes)`  and `output(catalogs)`. If metalakes or catalogs are empty arrays, they will be handled by the `output` method in `PlainFormat` and `TableFormat`.
Issue: https://github.com/apache/gravitino/issues/6014
No.
No.
> [#6014] refactor: CLI output methods for no data hints

- catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogCapability.java
- catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java
- catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
- clients/client-java/src/main/java/org/apache/gravitino/client/BaseSchemaCatalog.java
- clients/client-java/src/main/java/org/apache/gravitino/client/FilesetCatalog.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoMetalake.java
- clients/client-java/src/main/java/org/apache/gravitino/client/MessagingCatalog.java
- clients/client-java/src/main/java/org/apache/gravitino/client/RelationalCatalog.java
- clients/client-java/src/main/java/org/apache/gravitino/client/RelationalTable.java
- clients/client-python/gravitino/client/base_schema_catalog.py
- clients/client-python/gravitino/client/fileset_catalog.py
- clients/client-python/gravitino/client/gravitino_admin_client.py
- clients/client-python/gravitino/client/gravitino_client_base.py
- clients/client-python/gravitino/client/gravitino_metalake.py
- clients/client-python/gravitino/rest/rest_utils.py
- limit '/' in schema name and fileset name for hadoop catalog
- fix name encode issue when create schema, table, fileset and topic
Fix: #6007 
yes, add new limitation for fileset name
ITs added
> [#6007] fix: fix hadoop catalog entity name limitation

- clients/client-java/src/main/java/org/apache/gravitino/client/DTOConverters.java
- clients/client-java/src/main/java/org/apache/gravitino/client/ErrorHandlers.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GenericModel.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GenericModelCatalog.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GenericModelVersion.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestGenericModelCatalog.java
- clients/client-python/gravitino/client/generic_model_catalog.py
This PR adds the Java client API for model management.
This is a part of work of model management.
Fix: #5872 
No.
UT added.
> [#5872] feat(client): Add model management Java client API

- clients/cli/src/main/java/org/apache/gravitino/cli/ErrorMessages.java
- clients/cli/src/main/java/org/apache/gravitino/cli/FullName.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestFulllName.java
Fix Gravitino CLI get wrong catalogName when set metalake name by --name option. A hint is given if the -metalake option is not set.
Fix: #6027 
No
local test
```bash
gcli table list --name Hive_catalog.default
Missing --metalake option.
```
> [#6027] improvement(CLI): fix Gravitino CLI get wrong catalogName

- clients/client-python/gravitino/api/types/types.py
Update the type variables in the types.py
Fix: #5536
No
Unit Test
> [#5536] Improvement(client-python): reportUndefinedVariable warning in types.py 

- bundles/aws/src/main/java/org/apache/gravitino/s3/credential/S3TokenProvider.java
add get file meta permission for fileset operation
Fix: #6031 
no
pass fileset tests
> [#6031]  extend S3 credential provider to support S3 fileset operations

- bundles/aliyun/src/main/java/org/apache/gravitino/oss/credential/OSSTokenProvider.java
1. correct `ListBucket` to `ListObjects`
2. add `oss:GetBucketInfo` action
Fix: #6055 
no
1. run pass fileset oss test
> [#6055] feat(core):  extend OSS credential provider to support OSS fileset operations

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/TagEntity.java
Fix the error information when Setting the same tags multiple times in the Gravitino CLi. now a hint information is given when the tag is set repeatedly
Fix: #6030 
NO
```bash
gcli tag set --metalake demo_metalake --name Hive_catalog --tag tagB tagC
gcli tag set --metalake demo_metalake --name Hive_catalog --tag tagB tagC
```
> [#6030] fix(CLI): Fix Setting the same tags multiple times in the Gravitino CLi gives unexpected output

- docs/how-to-use-gvfs.md
Fix a vague description about customized file system usage in file how-to-use-gvfs.md.
To make documents more accurate. 
Fix: #5979 
N/A
N/A
> [#5979] fix(docs): Fix incorrect description in document how-to-use-gvfs.md

- docs/open-api/roles.yaml
List role names for metadata object, "COLUMN" and "ROLE" value for "metadataObjectType" are meaningless currently. Remove it.
Fix: #6080
No.
Just documents.
> [#6080] fix(docs): Fix the wrong possible values.

- .github/workflows/backend-integration-test.yml
- bundles/aws-bundle/build.gradle.kts
- bundles/azure-bundle/build.gradle.kts
- bundles/gcp-bundle/build.gradle.kts
Add `mergeServiceFiles()` when build the bundle jars
After add HDFS client to gravitino bundle jar, we should add make sure both Gravitino and HDFS `Filesystem` are merged into resource file
Fix: #6049
N/A
Existing test.
> [#6049] fix(bundles): Fix scheme gs not found problem

- core/src/main/java/org/apache/gravitino/utils/MetadataObjectUtil.java
- server/src/main/java/org/apache/gravitino/server/web/rest/RoleOperations.java
- server/src/test/java/org/apache/gravitino/server/web/rest/TestRoleOperations.java
We should return 400, if the role contains an error metalake metadata object.
We should return 400, if the catalog doesn't exist.
Fix: #6082
No.
Added UT.
> [#6082] fix: Fix error code of creating role operation

- clients/cli/src/main/java/org/apache/gravitino/cli/ErrorMessages.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoOptions.java
- clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/LinkModel.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RegisterModel.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestModelCommands.java
Add register and link commands to CLI for model
- register a model：`model create`
- link a model：`model update <—uri uri> [--alias aliaA aliaB]` 
meantime, add two options
- `—uri` ：The URI of the model version artifact.
- `—alias` ：The aliases of the model version.
The documentation will be updated after #6047  merge and I will create a new issue.
Fix: #5960 
NO
```bash
gcli model create -m demo_metalake --name Hive_catalog.default.model
gcli model create -m demo_metalake --name Hive_catalog.default.model --comment comment
gcli model create -m demo_metalake --name Hive_catalog.default.model --properties key1=val1 key2=val2
gcli model create -m demo_metalake --name Hive_catalog.default.model --properties key1=val1 klinkey2=val2 --comment comment
```
```bash
gcli model update -m …
```
> [#5960] fix(CLI): Add register and link commands to CLI for model

- clients/cli/src/main/java/org/apache/gravitino/cli/ParseType.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestParseType.java
- Supporting list and map types in Gravitino CLI operations.
Fix: # (issue) https://github.com/apache/gravitino/issues/5755
No
Unit test to verify ParseType class can handle list and map input.
> [#5755] Add List and Map types to table/columns in Gravitino CLI

- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/CreateModel.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/DeleteModel.java
- clients/cli/src/main/resources/model_help.txt
- clients/cli/src/test/java/org/apache/gravitino/cli/TestModelCommands.java
The delete command is one of the commands suggested by @justinmclean as part of adding Model entity support for the CLI.
To add delete functionality for a Model using the CLI
Improvement: https://github.com/apache/gravitino/issues/5963 (NOTE: Create command is redundant with addition of Register command)
Yes.
The delete command for a model was added.
Unit tests were added for Model CLI support and ran successfully for the delete command, along with CI tests in forked repository
>  [#5963] feat(client): added delete cli command model 

- .github/workflows/auto-cherry-pick.yml
add auto cherry pick to branch-0.8
prepare release 0.8
no
no
> [MINOR] add auto cherry pick to branch-0.8

- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestTagCommands.java
Fix Exception thrown when trying to set multiple tags properties in Gravitino CLI. It should give some user-friendly information.
Fix: #6102 
No
ut + local test
```bash
gcli tag set --metalake demo_metalake --tag tagA tagB tagC --property test --value value
gcli tag details --metalake demo_metalake --tag tagA tagB tagC 
gcli tag remove --metalake demo_metalake   --tag tagA tagB tagC  --property test
gcli tag update --metalake demo_metalake --tag tagA tagB tagC --comment "new comment"
gcli tag update --metalake demo_metalake --tag tagA tagB tagC --rename "new name"
```
> [#6102] fix(CLI): Fix Exception thrown when trying to set multiple tags properties in Gravitino CLI

- clients/cli/src/main/java/org/apache/gravitino/cli/ErrorMessages.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/Command.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/CreateTable.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RemoveCatalogProperty.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RemoveMetalakeProperty.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RemoveSchemaProperty.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RemoveTableProperty.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/SetCatalogProperty.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/SetMetalakeProperty.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/SetSchemaProperty.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/SetTableProperty.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestSchemaCommands.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestTableCommands.java
1. Refactor the validation logic of schema and table.
2. Add test case.
Fix: #6105 
No
UT + local test
Schema test
```bash
gcli schema set -m demo_metalake --name Hive_catalog.default
gcli schema set -m demo_metalake --name Hive_catalog.default --property propertyA
gcli schema set -m demo_metalake --name Hive_catalog.default
--value valA
gcli schema remove -m demo_metalake --name Hive_catalog.default
```
Table test
```bash
gcli table set -m demo_metalake --name Hive_catalog.default.test_dates
gcli table set -m demo_metalake --name Hive_catalog.default.test_dates
--property propertyA
gcli table set -m demo_metalake --name Hive_catalog.default.test_dates
--value valA
gcli table remove -m demo_metalake --name …
```
> [#6105] fix(CLI): Refactor the validation logic of schema and table

- build.gradle.kts
Added configuration to ensure that subprojects using the 'com.diffplug.spotless' plugin are included in the 'spotlessCheck' task dependencies.
Fix: https://github.com/apache/gravitino/issues/5937
no
Break style by adding spaces to any java file in iceberg-common module, and test it by running ./gradlew compileIcebergRESTServer -x test
check dependence trees by running ./gradlew compileIcebergRESTServer taskTree
> [#5937]feat(build): enhance spotless integration in Gradle build script

- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RemoveFilesetProperty.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RemoveTopicProperty.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/SetFilesetProperty.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/SetTopicProperty.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestFilesetCommands.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestTopicCommands.java
Refactor the validation logic of fileset and topic, meanwhile fix the test case.
Fix: #6121 
No
ut + local test
Topic test
```bash
gcli topic set -m demo_metalake --name catalog.schema.topic 
gcli topic set -m demo_metalake --name catalog.schema.topic --property property
gcli topic set -m demo_metalake --name catalog.schema.topic --value value
gcli topic remove -m demo_metalake --name catalog.schema.topic 
```
Fileset test
```bash
gcli fileset set -m demo_metalake --name catalog.schema.fileset
gcli fileset set -m demo_metalake --name catalog.schema.fileset --property property
gcli fileset set -m demo_metalake --name catalog.schema.fileset --value value
gcli fileset remove -m demo_metalake --name catalog.schema.fileset 
```
> [#6121] fix(CLI): Refactor the validation logic of topic and fileset

- api/src/main/java/org/apache/gravitino/MetadataObjects.java
- api/src/test/java/org/apache/gravitino/TestMetadataObjects.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/MetadataObjectService.java
- core/src/main/java/org/apache/gravitino/utils/NameIdentifierUtil.java
- core/src/test/java/org/apache/gravitino/storage/relational/TestJDBCBackend.java
use fullName instead of names.get(0) when get role Why are the changes needed?
Fix: #6004
NO
existing ut
> [#6004] fix: use fullName instead of names.get(0) when get role

- dev/docker/iceberg-rest-server/iceberg-rest-server-dependency.sh
- dev/docker/iceberg-rest-server/rewrite_config.py
- docs/docker-image-details.md
- docs/iceberg-rest-service.md
add OSS support for IcebergRESTService docker image
Fix: #5779 
no
run SQL with access Aliyun OSS data
> [#5779] feat(iceberg): add OSS support for IcebergRESTService docker image

- api/src/main/java/org/apache/gravitino/credential/SupportsCredentials.java
- clients/client-java/src/main/java/org/apache/gravitino/client/ErrorHandlers.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestSupportCredentials.java
- docs/open-api/catalogs.yaml
- docs/open-api/credentials.yaml
- docs/open-api/openapi.yaml
- docs/open-api/tags.yaml
- server/src/test/java/org/apache/gravitino/server/web/rest/TestMetadataObjectCredentialOperations.java
add credential openapi document 
Fix: #6092 
no
just document
> [#6092] docs(core): add credential openapi document

- docs/hadoop-catalog.md
- docs/iceberg-rest-service.md
- docs/security/credential-vending.md
move credential vending related document from iceberg-rest-server part to a separate file, then fileset could refer to it.
Fix: #6070 #5649 
no
just document
> [#6070][#5649] docs(core): add credential vending document

- clients/cli/src/main/java/org/apache/gravitino/cli/ErrorMessages.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/CreateTag.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/DeleteTag.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/GrantPrivilegesToRole.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RemoveAllTags.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RevokePrivilegesFromRole.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/SetTagProperty.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/TagEntity.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/UntagEntity.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestRoleCommands.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestTagCommands.java
Refactor the validation logic of the Tag and Role, meantime  fix the test case.
Fix: #6123 
No
ut + local test
**Role test**
```bash
gcli role grant -m demo_metalake --role admin
gcli role revoke -m demo_metalake --role admin
```
**Tag test**
```bash
gcli tag set -m demo_metalake 
gcli tag set -m demo_metalake  --name catalog.schema.table --property property --tag tagA
gcli tag set -m demo_metalake  --name catalog.schema.table --value value --tag tagA
gcli tag remove -m demo_metalake --tag tagA
gcli tag remove -m demo_metalake
gcli tag delete -m demo_metalake
gcli tag create -m demo_metalake
```
> [#6123] fix(CLI): Refactor the validation logic of tag and role

- clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/integration/test/GravitinoVirtualFileSystemABSIT.java
- clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/integration/test/GravitinoVirtualFileSystemGCSIT.java
- clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/integration/test/GravitinoVirtualFileSystemIT.java
- clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/integration/test/GravitinoVirtualFileSystemOSSIT.java
- clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/integration/test/GravitinoVirtualFileSystemS3IT.java
Fix typo of the block
Not `bock`, is `block`
no
CI pass
> [MINOR] fix: typo of block

- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerBaseE2EIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerFilesetIT.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/GrantPrivilegesToRole.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RevokePrivilegesFromRole.java
- clients/client-java/src/main/java/org/apache/gravitino/client/DTOConverters.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClient.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoMetalake.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestPermission.java
- clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/authorization/AccessControlIT.java
- core/src/main/java/org/apache/gravitino/authorization/AccessControlDispatcher.java
- core/src/main/java/org/apache/gravitino/authorization/AccessControlManager.java
- core/src/main/java/org/apache/gravitino/authorization/PermissionManager.java
- core/src/main/java/org/apache/gravitino/hook/AccessControlHookDispatcher.java
- core/src/test/java/org/apache/gravitino/authorization/TestAccessControlManagerForPermissions.java
- server/src/main/java/org/apache/gravitino/server/web/rest/PermissionOperations.java
Fix the check of duplicated privileges
Fix: #6116 
No.
Added new UT.
> [#6116] fix(authz): Fix the check of duplicated privileges

- .github/PULL_REQUEST_TEMPLATE
Remove unnecessary blank space in the PR template
This is not a major issue, but the unnecessary blank space is somewhat annoying and requires adjustment every time I create a PR.
No
Not needed
> [MINOR] Remove unnecessary blank space in the PR template

- clients/client-python/gravitino/api/expressions/partitions/identity_partition.py
- clients/client-python/gravitino/api/expressions/partitions/list_partition.py
- clients/client-python/gravitino/api/expressions/partitions/partition.py
- clients/client-python/gravitino/api/expressions/partitions/partitions.py
- clients/client-python/gravitino/api/expressions/partitions/range_partition.py
- clients/client-python/tests/unittests/rel/test_partitions.py
Porting `interface Partitions`, `interface IdentityPartition`, `interface ListPartition`, `interface RangePartition`,  and `class Partitions` from java to python.
Fix: #5203 
Yes.
Unit tests.
> [#5203] feat(client-python): porting partitions from java client

- web/web/src/app/metalakes/metalake/MetalakeView.js
Reload tree data after refreshing the version details page
N/A
Fix: #6166
N/A
manually
> [#6166] web(ui): load tree load data after refreshing the version details page

- clients/cli/src/main/java/org/apache/gravitino/cli/CommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/ModelCommandHandler.java
Refactor model commands and Base class in Gavitino CLI.
Fix: #6148 
No
local test
> [#6148] improve(CLI): Refactor model commands in Gavitino CLI

- LICENSE.trino
- NOTICE.trino
- build.gradle.kts
- dev/release/release-build.sh
Added LICENSE and NOTICE file for the Trino connector.
to comply with ASF policy
Fix: #6173
No.
> [#6173] fix Trino license and notice files

- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GroupCommandHandler.java
Refactor group commands in Gavitino CLI.
Fix: #6151 
No
local test.
> [#6151] improve(CLI): Refactor group commands in Gavitino CLI

- dev/docker/iceberg-rest-server/iceberg-rest-server-dependency.sh
- docs/iceberg-rest-service.md
- docs/security/credential-vending.md
- iceberg/iceberg-rest-server/build.gradle.kts
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/integration/test/IcebergRESTADLSTokenIT.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/integration/test/IcebergRESTAzureAccountKeyIT.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/integration/test/IcebergRESTGCSIT.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/integration/test/IcebergRESTOSSIT.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/integration/test/IcebergRESTOSSSecretIT.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/integration/test/IcebergRESTS3TokenIT.java
1. use Gravitino cloud jar without hadoop packages for Iceberg REST server credential vending  in test and document 
2. For OSS, use Gravitino Aliyun bundle jar in test and docker image because Iceberg doesn't provide Iceberg Aliyun bundle jar
Fix: #6165 
no
test S3 OSS GCS ADLS Iceberg REST test in local
> [#6165]  feat(core): Use Gravitino cloud jar without hadoop packages for Iceberg REST server

- bundles/gcp/src/main/java/org/apache/gravitino/gcs/credential/GCSTokenProvider.java
- bundles/gcp/src/test/java/org/apache/gravitino/gcs/credential/TestGCSTokenProvider.java
1. for resource path like `a/b`, add "a", "a/", "a/b" read permission for GCS connector
2. replace `storage.legacyBucketReader` with `storage.insightsCollectorService`, because `storage.legacyBucketReader` provides extra list permission for the bucket.
Fix: #6054 
no
Iceberg GCS IT and fileset GCS credential IT
> [#6054]  feat(core):  add more GCS permission to support fileset operations

- clients/cli/src/main/java/org/apache/gravitino/cli/CommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/SchemaCommandHandler.java
Refactor schema commands in Gravitino CLI.
Fix: #6144
No
Local test
> [#6144] improve(CLI): Refactor schema commands in Gravitino CLI

- NOTICE.bin
- NOTICE.rest
- clients/client-java/build.gradle.kts
- common/build.gradle.kts
- core/build.gradle.kts
- gradle/libs.versions.toml
Remove the unused protobuf dependency.
Since we already removed the KV storage support, so protobuf dependency is not required any more.
Fix: #6184 
No.
> [#6184]improve(core): Remove the protobuf dependency

- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/RoleCommandHandler.java
Break up role commands in Gravitino command line class
For readability and maintainability.
None.
> [#6153]refactor: Break up role commands in Gravitino CLI

- trino-connector/integration-test/src/test/java/org/apache/gravitino/trino/connector/integration/test/TrinoQueryIT.java
- trino-connector/integration-test/src/test/java/org/apache/gravitino/trino/connector/integration/test/TrinoQueryRunner.java
- trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-mysql/00002_alter_table.sql
- trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-mysql/00002_alter_table.txt
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/GravitinoErrorCode.java
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/CatalogConnectorMetadata.java
Fix the exception of ArrayIndexOutOfBoundsException when handle error message of IllegalArgumentException
Fix: #5533 
No
IT
> [#5533] fix (trino-connector): Fix the exception of ArrayIndexOutOfBoundsException when execute COMMENT COLUMN command

- docs/cli.md
Update command usage and add usage tracker
So everything is up to date and we can see many many people look up the CLI docs.
Fix: # N/A
No.
> [Minor] Update command usage and add usage tracker in Gravitino CLI

- docs/glossary.md
This PR fixes the glossary docs.
The glossary is reordered for quick reference.
No.
N/A
> [doc] Revise the glossary documentation

- catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/operation/DorisTableOperations.java
- catalogs/catalog-jdbc-doris/src/test/java/org/apache/gravitino/catalog/doris/integration/test/CatalogDorisIT.java
Modify table properties SQL in alter table sentence to support setting table properties.
It's a bug.
Fix: #5545
N/A.
IT.
> [#5545] fix(doris-catalog): Fix the problem that we can't set Doris table properties.

- catalogs/catalog-jdbc-mysql/src/main/java/org/apache/gravitino/catalog/mysql/operation/MysqlTableOperations.java
- catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
- catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/operation/TestMysqlTableOperations.java
add column not null limitation in unique index
mysql will automatically change the null column in unique index to not null, so we add the limitation at creation
Fix: #5721
yes, limitation for mysql unique index is more strict
tests added
> [#5721] improvement(mysql-catalog): add column not null limitation in unique index

- docs/jdbc-mysql-catalog.md
Add more details about the usage of engine type for MySQL catalog. 
The value of engine type may be influenced by many factors like MySQL version, configurations and so on, we need to clarify it. 
Fix: #5100 
N/A
N/A
> [#5100] improvement(docs): Add extra documents to clarify the engine type of MySQL catalog

- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/TagCommandHandler.java
Reduce complexity in `GravitinoCommandLine`
For readability and maintainability.
Fix: #6152 
None.
> [#6152] refactor: Refactor tag commands in Gravitino CLI

- docs/hadoop-catalog-with-adls.md
- docs/hadoop-catalog-with-gcs.md
- docs/hadoop-catalog-with-oss.md
- docs/hadoop-catalog-with-s3.md
add credential vending document for fileset
Fix: #6229 
no
just document
> [#6229] docs: add  fileset credential vending example

- clients/cli/src/main/java/org/apache/gravitino/cli/ColumnCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/FilesetCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/SimpleCommandHandler.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestSimpleCommands.java
Clean up GravitinoCommandLine class now it been refactored
Fix: #6220 
No
local ut test.
> [#6220] improve(CLI):  Clean up GravitinoCommandLine class now it been refactored

- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/catalog/BaseCatalog.java
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/paimon/GravitinoPaimonCatalog.java
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/FlinkEnvIT.java
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/hive/FlinkHiveCatalogIT.java
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/paimon/FlinkPaimonCatalogIT.java
Support basic table DDL Operation for paimon-catalog
Fix: #5194
None.
org.apache.gravitino.flink.connector.integration.test.paimon.FlinkPaimonCatalogIT
> [#5194] feat(flink): Support basic table DDL Operation for paimon-catalog

- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerClientExtension.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/reference/VXGroup.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/reference/VXUser.java
- catalogs/catalog-jdbc-oceanbase/src/main/java/org/apache/gravitino/catalog/oceanbase/operation/OceanBaseTableOperations.java
- core/src/main/java/org/apache/gravitino/hook/MetalakeHookDispatcher.java
- core/src/main/java/org/apache/gravitino/listener/api/event/CreateTablePreEvent.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/CatalogMetaPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/MetalakeMetaPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/SecurableObjectPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/TagMetaPostgreSQLProvider.java
Add missing `@override` annotations
Fix:  https://github.com/apache/gravitino/issues/6237
N/A
N/A
> [#6237]fix: add missing @override annotations

- core/src/main/java/org/apache/gravitino/connector/BaseCatalog.java
Authorization should use classloader to create the plugin
Fix: #6245
No.
I tested it manually.
> [#6245] fix(authz): Authorization should use classloader to create the plugin

- docs/flink-connector/flink-connector.md
Replace `=` with `:` to correct the yaml example.
The yaml example uses wrong seperator.
Fix: #6243
None
None.
> [#6243] fix(docs): Fix wrong seperator of yaml example in flink-connector.md

- docs/hadoop-catalog-with-gcs.md
- docs/hadoop-catalog-with-oss.md
- docs/hive-catalog-with-cloud-storage.md
Fix several errors in the document about hadoop-catalog and hive-catalog
Improving the user experience. 
N/A.
N/A.
> [MINOR] fix(docs): Fix several document errors

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/AllMetalakeDetails.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/GroupDetails.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListAllTags.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListColumns.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListEntityTags.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListFilesets.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListGroups.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListProperties.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListRoles.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListSchema.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListTables.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListUsers.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/UntagEntity.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/UserDetails.java
Remove unnecessary toSrting() from CLI
Fix: [#(6239)](https://github.com/apache/gravitino/issues/6239)
N/A
N/A
> [#6239] fix: No need for toString() on string (CLI)

- docs/flink-connector/flink-catalog-iceberg.md
- flink-connector/flink/build.gradle.kts
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/catalog/GravitinoCatalogManager.java
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/iceberg/GravitinoIcebergCatalog.java
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/iceberg/GravitinoIcebergCatalogFactory.java
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/iceberg/GravitinoIcebergCatalogFactoryOptions.java
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/iceberg/IcebergPropertiesConstants.java
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/iceberg/IcebergPropertiesConverter.java
- flink-connector/flink/src/main/resources/META-INF/services/org.apache.flink.table.factories.Factory
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/iceberg/TestIcebergPropertiesConverter.java
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/FlinkCommonIT.java
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/FlinkEnvIT.java
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/hive/FlinkHiveCatalogIT.java
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/iceberg/FlinkIcebergCatalogIT.java
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/iceberg/FlinkIcebergHiveCatalogIT.java
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/paimon/FlinkPaimonCatalogIT.java
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/utils/TestUtils.java
Support flink iceberg catalog
Fix: [#3515](https://github.com/apache/gravitino/issues/3515)
no
FlinkIcebergCatalogIT
FlinkIcebergHiveCatalogIT
> [#3515] feat(flink-connector): Support flink iceberg catalog

- docs/flink-connector/flink-catalog-paimon.md
> [#6218] docs: Adding Documentation for GravitinoPaimonCatalog in Flink Connectors

- catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergCatalogOperations.java
- catalogs/catalog-lakehouse-iceberg/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergTable.java
- catalogs/catalog-lakehouse-iceberg/src/test/java/org/apache/gravitino/catalog/lakehouse/iceberg/integration/test/CatalogIcebergBaseIT.java
- docs/lakehouse-iceberg-catalog.md
Adjust the distribution mode for creating Iceberg table with none distribution.  the following is the Spark adjust logic, the flink is similar.
```java
private DistributionMode defaultWriteDistributionMode() {
if (table.sortOrder().isSorted()) {
return RANGE;
} else if (table.spec().isPartitioned()) {
return HASH;
} else {
return NONE;
}
}
```
Fix: #6196 
Yes, add document
add UT and IT
> [#6196] feat(iceberg): adjust table distribution if creating table without specifying disribution mode

- .github/workflows/access-control-integration-test.yml
- .github/workflows/backend-integration-test-action.yml
- .github/workflows/build.yml
- .github/workflows/cron-integration-test.yml
- .github/workflows/flink-integration-test-action.yml
- .github/workflows/frontend-integration-test.yml
- .github/workflows/gvfs-fuse-build-test.yml
- .github/workflows/python-integration-test.yml
- .github/workflows/spark-integration-test-action.yml
- .github/workflows/trino-integration-test.yml
upgrade actions/upload-artifact to v4 
Fix: [#(6304)](https://github.com/apache/gravitino/issues/6304)
N/A
N/A
> [#6304] fix: upgrade actions/upload-artifact to v4 

- clients/cli/src/main/java/org/apache/gravitino/cli/RoleCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RevokeAllPrivileges.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RevokePrivilegesFromRole.java
- clients/cli/src/main/resources/role_help.txt
- clients/cli/src/test/java/org/apache/gravitino/cli/TestRoleCommands.java
- docs/cli.md
Revoke all privileges from a role via the Gravitino CLI. syntax: `gcli role revoke --name <name> --role <role> --all`
The step as follows:
1. Retrieve the `SecurableObject` instance using `role` and `fullname`;
2. Obtain the privileges associated with the `SecurableObject`;
3. Revoke all identified privileges;
Fix: #6278 
No
local tests + ut
```bash
gcli role grant -m demo_metalake --name Hive.default --role roleA --privilege create_table modify_table -i
gcli role revoke -m demo_metalake --name Hive.default --all --role roleA -i
```
> [#6278] improve(CLI): Revoke all privileges from a role via the Gravitino CLI.

- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/paimon/GravitinoPaimonCatalog.java
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/paimon/GravitinoPaimonCatalogFactory.java
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/paimon/GravitinoPaimonCatalogFactoryOptions.java
remove paimon package from `GravitinoPaimonCatalogFactory`,  because Paimon package may not in the Flink classpath when loading catalog factories.
Fix: #6309 
no
tested in local flink cluster
> [#6309] fix(flink):  remove paimon package from GravitinoPaimonCatalogFactory

- authorizations/authorization-common/src/main/java/org/apache/gravitino/authorization/jdbc/JdbcAuthorizationPlugin.java
- authorizations/authorization-common/src/test/java/org/apache/gravitino/authorization/jdbc/TestJdbcAuthorizationPlugin.java
Fix the OOM of JdbcAuthorizationPlugin. In old implement, we will call roleUpdate in the roleCreate. We will repeated call, they will cause oom.
Fix: #6306 
No.
Added a new UT.
> [#6306] fix(authz): Fix the OOM of JdbcAuthorizationPlugin

- flink-connector/flink-runtime/build.gradle.kts
- flink-connector/flink/build.gradle.kts
remove log4j from Gravitino Flink connector
Fix: #6307 
no
setup an local flink cluster, run flink SQL
> [#6307] feat(flink): remove log4j from Gravitino Flink connector

- docs/flink-connector/flink-catalog-hive.md
- docs/flink-connector/flink-catalog-iceberg.md
- docs/flink-connector/flink-catalog-paimon.md
- docs/flink-connector/flink-connector.md
polish Flink document
Polish the document
no
just document
> [MINOR] docs: Polish Gravitino Flink connector document

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/OwnerDetails.java
Optionals should not be set to null
see above
Fix: # N/A
No
Tested locally
> [Minor] Optionals should not be set to null

- clients/client-python/build.gradle.kts
Correct the Gravitino document link from `https://datastrato.ai/docs/latest` to `https://gravitino.apache.org/docs/$gravitinoVersion`, suppose the publish version is `0.8.0-incubating`, the link will start with `https://gravitino.apache.org/docs/0.8.0-incubating`
Fix: #6335 
no
run `./gradlew :clients:client-python:distribution -x test` and check `README`
> [#6335] fix(python-client): Fix pypi document link error 

- catalogs/catalog-hive/build.gradle.kts
- catalogs/hive-metastore-common/build.gradle.kts
- core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java
- core/src/test/java/org/apache/gravitino/authorization/TestAuthorizationUtils.java
- Fix some working not null judge logic in AuthorizationUtils
- Remove `protobuf-java` jar from hive distribution package
It's bug that need to fix
Fix: #6349
N/A
N/A
> [#6349] fix(core,hive-catalog): Fix bugs in AuthorizationUtils and remove protobuf-java from catalog hive

- api/src/main/java/org/apache/gravitino/MetadataObjects.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GenericModel.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GenericModelCatalog.java
- clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/TagIT.java
- docs/manage-tags-in-gravitino.md
- docs/open-api/tags.yaml
This PR adds the tag support for model metadata.
This is to complement the tag support for model metadata.
Fix: #6222 
No.
Add ITs in test.
> [#6222]feat(tag): Add tag support for model

- spark-connector/spark-common/build.gradle.kts
- spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/catalog/GravitinoCatalogManager.java
- spark-connector/v3.3/spark-runtime/build.gradle.kts
- spark-connector/v3.4/spark-runtime/build.gradle.kts
- spark-connector/v3.5/spark-runtime/build.gradle.kts
Unified cache framework
Fix: https://github.com/apache/gravitino/issues/6270
N/A
N/A
> [#6270] (Improvement) unified cache framework

- server-common/src/main/java/org/apache/gravitino/server/authentication/KerberosServerUtils.java
Use standard definition lib value to replace the hardcoded value: UTF-8.
Fix: #4209
no
no
> [#4209] chore replace hardcoded  value with std definition

- catalogs/catalog-common/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergPropertiesUtils.java
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/PropertiesConverter.java
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/hive/HivePropertiesConverter.java
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/iceberg/IcebergPropertiesConverter.java
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/paimon/PaimonPropertiesConverter.java
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/iceberg/TestIcebergPropertiesConverter.java
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/iceberg/FlinkIcebergCatalogIT.java
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/paimon/FlinkPaimonCatalogIT.java
- Unified params format, add flink.bypass. prefix, especially Iceberg.
- Extract the flink.bypass. logic to the PropertiesConverter, and the extension logic does not care about this operation
Fix: [#(6302)](https://github.com/apache/gravitino/issues/6302)
N/A
N/A
> [#6302] refactor:Optimize Flink connector properties converter 

- bundles/gcp-bundle/build.gradle.kts
Shade some GCP, gcp and probobuf classes to avoid conflicts with GCP IAM classes. 
To avoid possible class conflicts.
Fix: #6363
N/A.
existing UTs and ITs.
> [#6363] improvment(bundle-gcp): Shade some GCP IAM classes in `gcp-bundles` to avoid possible conflict

- authorizations/authorization-chain/src/main/java/org/apache/gravitino/authorization/chain/ChainedAuthorizationPlugin.java
- authorizations/authorization-common/build.gradle.kts
- authorizations/authorization-common/src/main/java/org/apache/gravitino/authorization/common/AuthorizationProperties.java
- authorizations/authorization-common/src/main/java/org/apache/gravitino/authorization/jdbc/JdbcAuthorizationPlugin.java
- authorizations/authorization-common/src/test/java/org/apache/gravitino/authorization/jdbc/TestJdbcAuthorizationPlugin.java
1. Load the JDBC driver of when the plugin is initializing
2. Fix the failure of chained plugin to load jdbc  plugin
Fix: #6353 
No.
Test by hand.
> [#6353]  fix(authz): Fix the failure of chained plugin to load JDBC authz  plugin

- docs/webui.md
- web/web/src/app/metalakes/metalake/rightContent/LinkVersionDialog.js
The singular of aliases is alias not aliase.
See above.
Fix: #N/A
Yes, as it's a UI change.
locally.
> [Minor] Change aliase to alias

- .github/workflows/access-control-integration-test.yml
- .github/workflows/backend-integration-test-action.yml
- .github/workflows/build.yml
- .github/workflows/cron-integration-test.yml
- .github/workflows/flink-integration-test-action.yml
- .github/workflows/frontend-integration-test.yml
- .github/workflows/gvfs-fuse-build-test.yml
- .github/workflows/python-integration-test.yml
- .github/workflows/spark-integration-test-action.yml
- .github/workflows/trino-integration-test.yml
upgrade actions/upload-artifact to v4 
Fix: [#(6304)](https://github.com/apache/gravitino/issues/6304)
N/A
N/A
> [#6304] fix: upgrade actions/upload-artifact to v4  (#6305)

- bin/common.sh.template
Update Gravitino JVM memory default.
Fix: https://github.com/apache/gravitino/issues/6384
No
No test
> [#6384] fix: Gravitino default JVM config mismatches with comments from gravitino-env.sh

- core/src/main/java/org/apache/gravitino/storage/relational/RelationalGarbageCollector.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/CatalogMetaPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/FilesetMetaPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/FilesetVersionPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/GroupMetaPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/GroupRoleRelPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/MetalakeMetaPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/ModelMetaPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/ModelVersionAliasRelPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/ModelVersionMetaPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/OwnerMetaPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/RoleMetaPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/SchemaMetaPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/SecurableObjectPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/TableColumnPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/TableMetaPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/TagMetaPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/TagMetadataObjectRelPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/TopicMetaPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/UserMetaPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/UserRoleRelPostgreSQLProvider.java
- core/src/test/java/org/apache/gravitino/storage/TestEntityStorage.java
PostgreSQL does not support SQL sentences like `DELETE FROM xxxx_table where xxxx limit 10` , Cluase `limit xxx` is not allowed in the `Delete syntax`
it's a bug.
Fix: #6380 
N/A
UT
> [#6380] fix(postgres-sql): Fix errors for PG backend about `delete...limit..` clause.

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RemoveAllTags.java
Add tag support for model in CLI.
1. `UntagEntity`
2. `TagEntity`
3. `ListEntityTags`
The logic for handling models in these three methods has been added.  need to add the processing logic to the `RemoveAllTags` method.
Fix: #6356 
No
local test.
> [#6356] improve(CLI): Add tag support for model in CLI

- clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java
Improve the gvfs to expose the nested exception for better understanding.
The exception message may not be enough to understand the problem why the fs initialization is failed. So we should expose the whole stack for better understanding.
No.
> [MINOR] fix(gvfs): expose the nested exception for better understanding

- catalogs/catalog-hadoop/build.gradle.kts
Remove jar `protobuf-java.jar` from the distribution package to avoid conflicts
To make authorization works for GCS fileset.
Fix: #6375 
N/A.
N/A
> [#6375] improvment(catalog-hadoop): Remove `protobuf-java` to avoid conflict with authorization module

- clients/client-python/gravitino/client/fileset_catalog.py
This PR changes the return value to `GenericFileset` for fileset operation.
Previously, it returns the plain fileset dto, so that it cannot support some operations like get credentials.
Fix: #6409 
No.
> [#6409] fix(client-python): Change to use `GenericFileset`  for the return value of fileset catalog

- clients/cli/src/main/java/org/apache/gravitino/cli/ErrorMessages.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/DeleteUser.java
Fix the CLI  delete the anonymous user
Fix: #5932 
local test
```bash
gcli user delete -m demo_metalake --user anonymous
```
> [#5932] improve(CLI): Fix the CLI  delete the anonymous user

- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/SchemaCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/CreateSchema.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/DeleteSchema.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListSchema.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListSchemaProperties.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RemoveSchemaProperty.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/SchemaAudit.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/SchemaDetails.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/SetSchemaProperty.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestSchemaCommands.java
Add schema command context CLI
Fix: #6416 
No
local test.
> [#6416] improve(CLI): Add schema command context CLI

- clients/cli/src/main/java/org/apache/gravitino/cli/CatalogCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/CatalogAudit.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/CatalogDetails.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/CatalogDisable.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/CatalogEnable.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/CreateCatalog.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/DeleteCatalog.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListCatalogProperties.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListCatalogs.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RemoveCatalogProperty.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/SetCatalogProperty.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateCatalogComment.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateCatalogName.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestCatalogCommands.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestCommandContext.java
Add catalog command context CLI
Fix: #6414 
No
local test.
> [#6414] improve(CLI): Add catalog command context CLI

- docs/overview.md
This PR fixes the description of the `Multi-engine support` section in `overview.md`, as Gravitino now supports connectors for Apache Spark and Apache Flink.
Gravitino now supports connectors for Apache Spark and Apache Flink.
No
manual review
> [MINOR] docs: Fix the description of `Multi-engine support` in `overview.md`

- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/OwnerCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/RoleCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/CreateRole.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/DeleteRole.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/GrantPrivilegesToRole.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListRoles.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/OwnerDetails.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RevokeAllPrivileges.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RevokePrivilegesFromRole.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RoleAudit.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RoleDetails.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/SetOwner.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestOwnerCommands.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestRoleCommands.java
Add roles and owner command context CLI
Fix: #6422 
No.
local test.
> [#6422] improve(CLI): Add roles and owner command context CLI

- core/src/main/java/org/apache/gravitino/authorization/AuthorizationUtils.java
The PR updates incorrect log format codes from `%s` to `{}` in the following lines:
- Line 420
- Line 483
- Line 504
- Line 525
The original code in these lines used the `%s` placeholder, which is invalid for the logging framework used. It has been corrected to use `{}` to match the proper syntax for log messages.
This change is necessary to fix the incorrect log format codes in the codebase. The `%s` placeholder is not valid and can lead to incorrect log formatting or errors when the logs are generated. The correct placeholder syntax for this logging framework is `{}`.
Fix: #6429
No user-facing changes are introduced. This is an internal fix for the logging format.
The changes were verified manually by reviewing the code and ensuring that all instances of `%s` were replaced with `{}` in …
> [#6429] Fixed Wrong log format codes

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/AuditCommand.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/Command.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListProperties.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/MetadataCommand.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/TableCommand.java
Remove redundant code in CLI, and make context argument final in Command class. 
The constructor should take only one argument, CommandContext.
No.
local test.
> [MINOR] improve(CLI): Remove redundant code in CLI

- clients/cli/src/main/java/org/apache/gravitino/cli/CommandContext.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoOptions.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/Command.java
Add --quiet option to the Gravitino CLI
Fix: #6097 
user can use --quiet option suppress the output.
local test
```bash
gcli tag create -m cli_demo --tag tagA tagB -i
gcli tag create -m cli_demo --tag tagC tagD -i --quiet
```
> [#6097] improve(CLI): Add --quiet option to the Gravitino CLI

- clients/cli/src/main/java/org/apache/gravitino/cli/CatalogCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/ColumnCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/CommandContext.java
- clients/cli/src/main/java/org/apache/gravitino/cli/CommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/FilesetCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GroupCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/MetalakeCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/ModelCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/OwnerCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/RoleCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/SchemaCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/TableCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/TagCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/TopicCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/UserCommandHandler.java
Refactor getAuth method in CLI.
Fix: #6449
No
local test.
> [#6449] improve(CLI): Refactor getAuth method in CLI

- core/src/main/java/org/apache/gravitino/storage/relational/mapper/CatalogMetaMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/CatalogMetaSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/FilesetMetaMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/FilesetMetaSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/SchemaMetaMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/SchemaMetaSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/CatalogMetaBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/FilesetMetaBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/SchemaMetaBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java
- core/src/test/java/org/apache/gravitino/storage/relational/service/TestRoleMetaService.java
- core/src/test/java/org/apache/gravitino/storage/relational/service/TestSecurableObjects.java
fix issue https://github.com/apache/gravitino/issues/6238
improve performance when a single role is bound to many metadata.
Use batch queries when getting role securable object full names instead of loop queries to get each securable object full name.
Fix: #6238
No
Unit tests and integration tests have all passed, this feature has been running internally at Xiaomi for two weeks.
> [#6238] improvement(storage): Improve get role performance when roles is bound to many metadata.

- clients/filesystem-fuse/conf/gvfs_fuse.toml
- clients/filesystem-fuse/src/main.rs
Fix the bug of using a relative path to configure gvfs-fuse.
Fix: #6464
NO
Manually test
> [#6464] fix (gvfs-fuse): Fix the bug of using a relative path to configure gvfs-fuse.

- docs/webui.md
This pr removes outdated tips from `web-ui.md` because, as indicated in the subsequent text, operations such as creating or modifying schemas, tables, or filesets can now be performed through the web UI.
Remove outdated tips from `web-ui.md`
No
manual review
> [MINOR] docs: Remove outdated tips from `web-ui.md`

- dev/docker/iceberg-rest-server/rewrite_config.py
- docs/iceberg-rest-service.md
Add the environment variables `GRAVITINO_JDBC_USER`, `GRAVITINO_JDBC_PASSWORD`, and `GRAVITINO_S3_ENDPOINT` to the `rewrite_config.py`, so database user and password can be set by the user in a container environment as well as a custom S3 endpoint.
Currently, JDBC user and PW are hardcoded to `iceberg` and cannot be changed when using the container images. One workaround is including the values in the JDBC connection string, but this neither elegant nor in line with how containers commonly handle this issue.
Additionally, it wasn't possible to set the value of `gravitino.iceberg-rest.s3-endpoint` in a container environment, which can be useful in a variety of situations when using a provider other than AWS.
Added the three aforementioned two environment variables that can be used by the …
> [Improvement] Enable setting of additional configuration parameters through environment variables

- clients/filesystem-fuse/README.md
Add Readme document of gvfs-fuse
Fix: #6404
No
No
> [#6404] feat (gvfs-fuse): Add Readme document of gvfs-fuse

- build.gradle.kts
Disable the ryuk
Fix: #6475
No.
CI passed.
> [#6475] improvement: Disable the ryuk

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/Command.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListSchema.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListTables.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/SchemaDetails.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/TableDetails.java
- clients/cli/src/main/java/org/apache/gravitino/cli/outputs/TableFormat.java
- clients/cli/src/test/java/org/apache/gravitino/cli/integration/test/TableFormatOutputIT.java
- clients/cli/src/test/java/org/apache/gravitino/cli/output/TestTableFormat.java
Support table format output for Schema and Table command.
Fix: #6493 
No.
local test.
```bash
gcli schema list -m demo_metalake --name Hive_catalog --output table -i
+---------------------------+
|          Schema           |
+---------------------------+
| convert_example           |
| default                   |
| hive_best_performance     |
| test_hive_convert_example |
| test_multiple_data_source |
+---------------------------+
gcli schema details -m demo_metalake --name Hive_catalog.default --output table -i
+---------+-----------------------+
| Schema  |        Comment        |
+---------+-----------------------+
| default | Default Hive database |
+---------+-----------------------+
gcli table list -m demo_metalake --name Hive_catalog.default -i --output table …
```
> [#6493] feat(CLI): Support table format output for Schema and Table command

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/AuditCommand.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/CatalogAudit.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/SchemaAudit.java
- clients/cli/src/main/java/org/apache/gravitino/cli/outputs/TableFormat.java
- clients/cli/src/test/java/org/apache/gravitino/cli/output/TestTableFormat.java
Support table format output for Audit command.
Fix: #5746 
No
local test.
```bash
gcli metalake  details   --output table  -m demo_metalake --audit  -i
+-----------+--------------------------+-----------+--------------------------+
|  Creator  |       Creation at        | Modifier  |       Modified at        |
+-----------+--------------------------+-----------+--------------------------+
| anonymous | 2024-12-04T07:41:18.512Z | anonymous | 2025-01-14T07:56:25.496Z |
+-----------+--------------------------+-----------+--------------------------+
gcli catalog  details --name Hive_catalog  -i --output table  -m demo_metalake --audit
+-----------+--------------------------+-----------+-----------------------------+
|  Creator  |       Creation at        | Modifier  |         Modified at …
```
> [#5746] feat(CLI): Support table format output for Audit command

- clients/filesystem-fuse/Makefile
Fix rust build failed on `rust check, make the version of `cargo-machete` is 0.7.0.
Fix: #6511
No
Manually
> [#6511] fix (gvfs-fuse): Fix rust build failed on `rust check`

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/UntagEntity.java
As tags is an array of strings, `tags[0].toString()` doesn't require `toString()`.
to string method not needed.
Fix: #6517 
no
no needed
> [#6517] fix: unneeded call to toString()

- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/rest/IcebergTableRenameOperations.java
Fixed an incorrect logging class reference in IcebergTableRenameOperations.
The logger was incorrectly referencing IcebergTableOperations instead of IcebergTableRenameOperations, which could cause confusion in logs.
Fix: #6518 
No
No testing is required.
> fix(logging): Correct logger class in IcebergTableRenameOperations

- clients/cli/src/main/java/org/apache/gravitino/cli/outputs/OutputFormat.java
- clients/cli/src/main/java/org/apache/gravitino/cli/outputs/PlainFormat.java
- clients/cli/src/test/java/org/apache/gravitino/cli/output/TestPlainFormat.java
Support plain format output for Schema and Table command
Fix: #6496
No
local test
```bash
gcli schema list -m demo_metalake --name Hive_catalog  -i
default,Default Hive database
gcli table list -m demo_metalake --name Hive_catalog.default -i 
employee_partitions
source_table
test_dt_partition
test_key_en
sales
order_tb1
tmp
float_test
test_tbl
gcli table details -m demo_metalake --name Hive_catalog.default.test1  -i 
test1,N/A
gcli schema details -m demo_metalake --name Hive_catalog.default -i 
default,Default Hive database
```
> [#6496] feat(CLI): Support plain format output for Schema and Table command

- web/integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/MetalakePageTest.java
- web/integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/pages/CatalogsPage.java
- web/integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/pages/MetalakePage.java
- web/integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/utils/BaseWebIT.java
This improvement follows our [E2E testing guide](https://gravitino.apache.org/docs/0.8.0-incubating/webui#e2e-test) by utilizing the wait methods and removing `Thread.sleep(sleepTimeMillis)`.
Fix: #6459
no
CI
> [#6459]improve(test): Use explicit wait for time-based condition

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListColumns.java
- clients/cli/src/main/java/org/apache/gravitino/cli/outputs/LineUtil.java
- clients/cli/src/main/java/org/apache/gravitino/cli/outputs/PlainFormat.java
- clients/cli/src/main/java/org/apache/gravitino/cli/outputs/TableFormat.java
- clients/cli/src/test/java/org/apache/gravitino/cli/output/TestLineUtil.java
- clients/cli/src/test/java/org/apache/gravitino/cli/output/TestPlainFormat.java
- clients/cli/src/test/java/org/apache/gravitino/cli/output/TestTableFormat.java
improvement(CLI): Add default values to column list output in CLI
Fix: #6533
No
local test
Hive Catalog
```bash
gcli column list -m demo_metalake --name Hive_catalog.default.test_dates -i
name,datatype,default_value,comment,nullable,auto_increment
id,integer,,N/A,true,false
event_date,date,,N/A,true,
event_timestamp,timestamp,,N/A,true,
gcli column list -m demo_metalake --name Hive_catalog.default.test_dates -i --output table
+-----------------+-----------+---------+---------------+----------+---------+
|      Name       |   Type    | Default | AutoIncrement | Nullable | Comment |
+-----------------+-----------+---------+---------------+----------+---------+
| id              | integer   |         | false         | true     | N/A     |
| event_date      | date      |         | …
```
> [#6533] improvement(CLI): Add default values to column list output in CLI

- .github/workflows/auto-cherry-pick.yml
This reverts commit 54a5371f572b7b3eca063cae8606951903c12867.
Seems like the new version cannot be used by Apache Gravitino https://github.com/apache/gravitino/actions/runs/13558713734
No.
Existing test.
> Revert "build(deps): bump carloscastrojumo/github-cherry-pick-action from 1.0.9 to 1.0.10 (#6550)"

- core/src/main/java/org/apache/gravitino/metrics/MetricNames.java
- core/src/main/java/org/apache/gravitino/metrics/source/MetricsSource.java
- core/src/main/java/org/apache/gravitino/metrics/source/RelationDatasourceMetricsSource.java
- core/src/main/java/org/apache/gravitino/storage/relational/session/SqlSessionFactoryHelper.java
- core/src/test/java/org/apache/gravitino/metrics/TestExtractMetricNameAndLabel.java
Support metrics for JDBC backend connect pool :
1. activeConnectionCount
2. idleConnectionCount
3. maxConnectionCount
Support metrics for JDBC connection pool
Fix: #6468
No
No need to test
> [#6468] feature(core): add metrics for mysql backend connect pool

- authorizations/authorization-chain/src/main/java/org/apache/gravitino/authorization/chain/ChainedAuthorizationPlugin.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerHelper.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveIT.java
Don't ignore the necessary exception. We should throw necessary exception from underlying system,
Fix: #4620
No.
New uts and existing uts.
> [#4620] improvement(authz): Throw the necessary exception when handling Ranger plugin exception

- .github/workflows/python-integration-test.yml
- .github/workflows/trino-integration-test.yml
Disable the Trino cascading query integration test
Fix: #6595
No
No
> [#6595] fix (trino-connector): Disable the Trino cascading query integration test

- web/web/src/app/metalakes/metalake/rightContent/LinkVersionDialog.js
click submit button to trigger verification of version form, and no required info for alias form item.
Model version alias should be optional
Fix: #6605
N/A
manually
> [#6605] fix(web): fix model version alias to be optional

- authorizations/authorization-chain/src/test/java/org/apache/gravitino/authorization/chain/integration/test/TestChainedAuthorizationIT.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationHadoopSQLPlugin.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerBaseE2EIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveE2EIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerIcebergE2EIT.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerPaimonE2EIT.java
- docs/security/access-control.md
`MODIFY_TABLE` should contain the select table privilege
More proper semantics
Fix: #6011
Correct the document.
Modify the UT.
> [#6011] fix(authz): `MODIFY_TABLE` should contain the select table privilege

- catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/JdbcCatalogPropertiesMetadata.java
- catalogs/catalog-jdbc-common/src/test/java/org/apache/gravitino/catalog/jdbc/TestJdbcCatalogOperations.java
jdbc.pool.test-on-borrow does not work when connecting to JDBC catalog
Fix: #6630
N/A
N/A
> [#6630] fix(jdbc-catalog): jdbc.pool.test-on-borrow does not work when connecting to JDBC catalog

- dev/docker/hive/start.sh
Modify the table structure of the MySQL table for the Hive metastore 
The default chaset `latin1` does not support Chinese. 
Fix: #6612 
N/A
> [#6612] fix(hive-image): Support Chinese in database, table and column commens for Hive catalog

- api/src/main/java/org/apache/gravitino/authorization/SecurableObjects.java
- common/src/main/java/org/apache/gravitino/utils/CollectionUtils.java
- core/build.gradle.kts
- core/src/main/java/org/apache/gravitino/meta/GroupEntity.java
- core/src/main/java/org/apache/gravitino/meta/ModelVersionEntity.java
- core/src/main/java/org/apache/gravitino/meta/RoleEntity.java
- core/src/main/java/org/apache/gravitino/meta/TableEntity.java
- core/src/main/java/org/apache/gravitino/meta/UserEntity.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java
- core/src/test/java/org/apache/gravitino/storage/relational/service/TestRoleMetaService.java
Possible error in the equals method for collection
Fix: #6641
N/A
N/A
> [#6641] fix(core): Possible error in the equals method for collection

- spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/iceberg/GravitinoIcebergCatalog.java
If user set `spark.sql.hive.metastore.jars` to `path` in spark configuration and hive metastore uri is not set explictly, Spark will use Isolated client class loader to load JDBC drivers. which makes Iceberg couldn't load corresponding class loader.
Fix: #6623 
no
test locally
> [#6623] fix(spark): Load JDBC driver explictly to fix `No suitable driver found for  mysql:xx` error

- catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/operation/DatabaseOperation.java
- catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/operation/JdbcDatabaseOperations.java
- catalogs/catalog-jdbc-common/src/test/java/org/apache/gravitino/catalog/jdbc/operation/SqliteDatabaseOperations.java
- catalogs/catalog-jdbc-postgresql/src/main/java/org/apache/gravitino/catalog/postgresql/operation/PostgreSqlSchemaOperations.java
Optimize load database method in JdbcDatabaseOperations
Fix: #6629
N/A
N/A
> [#6629] Improvement(jdbc-catalog): Optimize load database method in JdbcDatabaseOperations

- core/src/main/java/org/apache/gravitino/catalog/CatalogManager.java
- core/src/test/java/org/apache/gravitino/catalog/TestCatalogManager.java
#6667 
Fix: #6667
no
add a new test testForceDropCatalog in TestCatalogManager
> [#6667]fix(core):can force delete invalid catalog

- flink-connector/flink/build.gradle.kts
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/FlinkCommonIT.java
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/FlinkEnvIT.java
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/iceberg/FlinkIcebergCatalogIT.java
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/iceberg/FlinkIcebergHiveCatalogIT.java
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/iceberg/FlinkIcebergRestCatalogIT.java
Add tests for REST Catalog to the Flink connector for Iceberg
Fix: #6368
N/A
N/A
> [#6368] improvement(flink-connector): Add tests for REST Catalog to the Flink connector for Iceberg

- authorizations/authorization-common/src/main/java/org/apache/gravitino/authorization/common/ChainedAuthorizationProperties.java
- authorizations/authorization-common/src/main/java/org/apache/gravitino/authorization/common/ErrorMessages.java
- authorizations/authorization-common/src/main/java/org/apache/gravitino/authorization/common/RangerAuthorizationProperties.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorization.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationHDFSPlugin.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationHadoopSQLPlugin.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java
Reduce repeated strings in Ranger classes, abstract the error message and make them static.
Fix: #6530 
no.
local test.
> [#6530] improvement(authorization): Reduce repeated strings in Ranger classes

- build.gradle.kts
This PR tweaks the build script for coding style consistency.
It also fixes a few nits in the scripts:
- duplicated entries caused by unsorted items
- incorrect dependency items missing leading ":"
See description.
No.
N/A
> [MINOR] refactor: Tweak the build script

- clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/authorization/AccessControlIT.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/SecurableObjectBaseSQLProvider.java
remove privilege_names and privilege_conditions check when delete secruable objects of a role.
Fix: #6682
no
add a integration test case.
> [#6682] fix(authz): Remove `privilege_names` and `privilege_conditions` check when delete securable objects of a role.

- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveE2EIT.java
- core/src/main/java/org/apache/gravitino/hook/CatalogHookDispatcher.java
Delete catalogs if failing to execute post hook actions
Fix: #6716
No.
Add a new IT.
> [#6716] improvement(authz): Delete catalogs if failing to execute post hook actions

- core/src/main/java/org/apache/gravitino/catalog/EntityCombinedFileset.java
- core/src/main/java/org/apache/gravitino/catalog/EntityCombinedModel.java
- core/src/main/java/org/apache/gravitino/catalog/EntityCombinedModelVersion.java
- core/src/main/java/org/apache/gravitino/catalog/EntityCombinedSchema.java
- core/src/main/java/org/apache/gravitino/catalog/EntityCombinedTable.java
- core/src/main/java/org/apache/gravitino/catalog/EntityCombinedTopic.java
- core/src/test/java/org/apache/gravitino/meta/TestEntityCombinedObject.java
Filters out any entries with null keys/values before collection, to prevent potential NullPointerExceptions when accessing entries
Due to the cancellation of the operation to reload the topic to fill in its other properties after the alter operation in https://github.com/apache/gravitino/issues/3729, there is a risk that the value of the downstream property may return null, which in turn could trigger a NullPointerException in the properties() method of the Topic class.
Fix: #6523
no
UT added
> [#6523] fix(core): Filter null prop when init properties

- authorizations/authorization-common/src/main/java/org/apache/gravitino/authorization/common/PathBasedMetadataObject.java
- authorizations/authorization-common/src/test/java/org/apache/gravitino/authorization/common/TestPathBasedMetadataObject.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationHDFSPlugin.java
- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerAuthorizationHDFSPluginIT.java
Avoid binding type `PATH` to `FILESET`. When we store a Hive table, first, we will store the metadata in the MySQL, and then we will store the data in the HDFS location. For Hive, there is a default location for the cluster level. We can also specify other locations for schema and table levels. So a path won't only be fileset. 
Fix: #6698
No.
CI passed.
> [#6694] improvement: Avoid binding type `PATH` to `FILESET`

- common/src/main/java/org/apache/gravitino/auth/KerberosUtils.java
Fix the No key to store error when Running the Spark connector with a Kerberos ticket cache
Fix: #6745
No 
local test.
> [#6745] fix(client,authn): Fix the No key to store error when Running the Spark connector with a Kerberos ticket cache

- catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogOperations.java
Optimize the code path in createFileset and optimize path by using future.
Fix: #6562 
No
No， this is sequence chart of the CreateFileset.
> [#6562] improvement(catalogs): Optimize the code path in createFileset and optimize path

- clients/filesystem-fuse/tests/bin/gravitino_server.sh
Fix the gvfs-fuse test to copy the aws-bundle JAR without a name that contains SNAPSHOT
Fix: #6766
No
Manually test
> [#6766] fix (gvfs-fuse): Fix the test failed when setting the project version without SNAPSHOT

- dev/docker/gravitino/gravitino-dependency.sh
Copy Hadoop Azure bundle jars to the Gravitino Hadoop catalog classpath. 
This a cherry-pick PR to branch-0.8 for #6729 
Hadoop with Azure has been supported since Gravtitino 0.8.0-incubating, we need to add it Hadoop classpath as S3 did.  
Fix: #6729 
N/A
Test Locally.
> [#6729] improvement(docker-image): Copy Hadoop Azure bundles to Gravitino docker image

- web/web/src/app/metalakes/metalake/rightContent/tabsContent/tableView/TableView.js
- web/web/src/components/ConfirmDeleteDialog.js
- web/web/src/lib/api/catalogs/index.js
can be droped while set not in-use false
The user experience is bad: can not be dropped even if set in-use false
Fix: #6747
N/A
manually
> [#6747] improvement(web): can be dropped while set not in-use false

- clients/client-python/gravitino/api/tag/__init__.py
- clients/client-python/gravitino/api/tag/supports_tags.py
- clients/client-python/gravitino/api/tag/tag.py
- clients/client-python/gravitino/exceptions/base.py
This is first part (totally 4 planned) of implementation to the following classes from Java to support Column and its default value, including:
- SupportsTags.java
- Tag.java
- NoSuchTagException.java
- TagAlreadyExistsException.java
We need to support Column and its default value in python client.
#5202 
No
Unit tests
> [#5202] feat(client-python): Support Column and its default value part1

- .github/workflows/access-control-integration-test.yml
- .github/workflows/backend-integration-test.yml
- .github/workflows/build.yml
- .github/workflows/cron-integration-test.yml
- .github/workflows/flink-integration-test.yml
- .github/workflows/frontend-integration-test.yml
- .github/workflows/gvfs-fuse-build-test.yml
- .github/workflows/python-integration-test.yml
- .github/workflows/spark-integration-test.yml
- .github/workflows/trino-integration-test.yml
update dorny/paths-filter@v3 to dorny/paths-filter@v3.0.2
Fix:
> Errordorny/paths-filter@v3 is not allowed to be used in apache/gravitino. Actions in this workflow must be: within a repository that belongs to your Enterprise account, created by GitHub, verified in the GitHub Marketplace, or matching the following: 1Password/load-secrets-action@*, AdoptOpenJDK/install-jdk@*, BobAnkh/auto-generate-changelog@*, DavidAnson/markdownlint-cli2-action@b4c9feab76d8025d1e83c653fa3990936df0e6c8, DavidAnson/markdownlint-cli2-action@v16, EnricoMi/publish-unit-test-result-action@*, JamesIves/github-pages-deploy-action@881db5376404c5c8d621010bcbec0310b58d5e29, JamesIves/github-pages-deploy-action@v4.6.8, JustinBeckwith/linkinator-action@3d5ba091319fa7b0ac14703761eebb7d100e6f6d, …
> [MINOR] fix(CI): update dorny/paths-filter@v3 to dorny/paths-filter@v3.0.2

- clients/client-python/gravitino/api/column.py
- clients/client-python/tests/unittests/test_column.py
This is first part (totally 4 planned) of implementation to the following classes from Java to support Column and its default value, including:
- Column
We need to support Column and its default value in python client.
#5202
No
Unit tests
> [#5202] feat(client-python): Support Column and its default value part1 - Column

- catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopFilesetPropertiesMetadata.java
- catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java
- catalogs/catalog-hive/src/test/java/org/apache/gravitino/catalog/hive/TestHiveCatalog.java
- catalogs/catalog-kafka/src/test/java/org/apache/gravitino/catalog/kafka/integration/test/CatalogKafkaIT.java
- catalogs/catalog-lakehouse-hudi/src/test/java/org/apache/gravitino/catalog/lakehouse/hudi/integration/test/HudiCatalogHMSIT.java
- core/src/main/java/org/apache/gravitino/catalog/PropertiesMetadataHelpers.java
- core/src/main/java/org/apache/gravitino/connector/PropertiesMetadata.java
- core/src/main/java/org/apache/gravitino/connector/PropertyEntry.java
- core/src/test/java/org/apache/gravitino/TestCatalog.java
- core/src/test/java/org/apache/gravitino/catalog/TestCatalogManager.java
- core/src/test/java/org/apache/gravitino/catalog/TestCatalogNormalizeDispatcher.java
- core/src/test/java/org/apache/gravitino/catalog/TestFilesetOperationDispatcher.java
- core/src/test/java/org/apache/gravitino/catalog/TestModelOperationDispatcher.java
- core/src/test/java/org/apache/gravitino/catalog/TestOperationDispatcher.java
- core/src/test/java/org/apache/gravitino/catalog/TestSchemaOperationDispatcher.java
- core/src/test/java/org/apache/gravitino/catalog/TestTableOperationDispatcher.java
- core/src/test/java/org/apache/gravitino/catalog/TestTopicOperationDispatcher.java
- docs/hadoop-catalog.md
property framework supports prefix
some properties with fixed prefixes maybe immutable or required and need to be verified.
Fix: #6750 
no
tests added
> [#6750] improvement(core): property framework supports prefix

- dev/release/release-build.sh
Set correct path to [LICENSE.bin](https://github.com/apache/gravitino/blob/main/web/web/LICENSE.bin) and [NOTICE.bin](https://github.com/apache/gravitino/blob/main/web/web/NOTICE.bin) files in release-build.sh
The two bin files weren't removed after the build.
Fix: #6834 
_None_
Not necessary, you can see where the files are just by browsing them.
> [#6834] fix(release-build): wrong path of license + notice bin files

- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/paimon/FlinkPaimonJdbcBackendIT.java
Add Integration Tests for GravitinoPaimonCatalog with Catalog-backend as JDBC in the Flink
Fix: #6217 
None
org.apache.gravitino.flink.connector.integration.test.paimon.FlinkPaimonJdbcBackendIT
> [#6217] flink-connector: Add Integration Tests for GravitinoPaimonCatalog with Catalog-backend as JDBC in the Flink

- catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/operation/DorisTableOperations.java
use `show backends` to get the count of Doris Backend (BE) nodes
Fix: #6722
N/A
IT
> [#6722] fix(jdbc-doris): use `show backends` to get the count of Doris BE nodes

- core/src/main/java/org/apache/gravitino/storage/relational/session/SqlSessionFactoryHelper.java
Set t`estOnBorrow` and `setTestWhileIdle` of JDBC connection pool from `false` to `true`.
If the configuration is false, there may be connection problems. 
Fix: #6874 
N/A.
The existing tests.
> [#6874] improvement(core): Set `testOnBorrow` to true to avoid possible connection timeout problem

- authorizations/authorization-ranger/src/test/java/org/apache/gravitino/authorization/ranger/integration/test/RangerHiveHdfsE2EIT.java
- catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogOperations.java
- core/src/main/java/org/apache/gravitino/config/ConfigConstants.java
- core/src/main/java/org/apache/gravitino/meta/FilesetEntity.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/FilesetMetaMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/FilesetVersionMapper.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/FilesetVersionSQLProviderFactory.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/FilesetMetaBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/FilesetVersionBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/FilesetVersionPostgreSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/po/FilesetPO.java
- core/src/main/java/org/apache/gravitino/storage/relational/po/FilesetVersionPO.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/FilesetMetaService.java
- core/src/main/java/org/apache/gravitino/storage/relational/utils/POConverters.java
- core/src/test/java/org/apache/gravitino/meta/TestEntity.java
- core/src/test/java/org/apache/gravitino/storage/TestEntityStorage.java
- core/src/test/java/org/apache/gravitino/storage/memory/TestMemoryEntityStore.java
- core/src/test/java/org/apache/gravitino/storage/relational/TestJDBCBackend.java
- core/src/test/java/org/apache/gravitino/storage/relational/service/TestFilesetMetaService.java
- core/src/test/java/org/apache/gravitino/storage/relational/utils/TestPOConverters.java
- scripts/h2/schema-0.9.0-h2.sql
- scripts/h2/upgrade-0.8.0-to-0.9.0-h2.sql
- scripts/mysql/schema-0.9.0-mysql.sql
- scripts/mysql/upgrade-0.8.0-to-0.9.0-mysql.sql
- scripts/postgresql/schema-0.9.0-postgresql.sql
- scripts/postgresql/upgrade-0.8.0-to-0.9.0-postgresql.sql
- add `location_name` column to `fileset_version_info` table
- replace field `FilesetVersionPO filesetVersionPO` in `FilesetPO` with `List<FilesetVersionPO> filesetVersionPOs`
- replace field `storageLocation` of `FilesetEntity` with `storageLocations`
- Compatible with single location
Fix: #6890 
no
CI pass
> [#6890] feat(core): backend storage supports fileset multiple locations

- clients/client-java/src/test/java/org/apache/gravitino/client/TestFilesetCatalog.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestSupportCredentials.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestSupportRoles.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestSupportTags.java
- clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/GravitinoMockServerBase.java
- clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/TestGvfsBase.java
- common/src/main/java/org/apache/gravitino/dto/file/FilesetDTO.java
- common/src/main/java/org/apache/gravitino/dto/requests/FilesetCreateRequest.java
- common/src/main/java/org/apache/gravitino/dto/util/DTOConverters.java
- common/src/test/java/org/apache/gravitino/dto/file/TestFilesetDTO.java
- docs/open-api/filesets.yaml
- server/src/main/java/org/apache/gravitino/server/web/rest/FilesetOperations.java
- server/src/test/java/org/apache/gravitino/server/web/rest/TestFilesetOperations.java
support fileset multiple locations in REST API
support fileset multiple locations in REST API
Fix: #6893 
yes
tests added
> [#6893] feat(server): support fileset multiple locations in REST API

- catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java
- clients/client-java/src/main/java/org/apache/gravitino/client/ErrorHandlers.java
- clients/client-java/src/main/java/org/apache/gravitino/client/FilesetCatalog.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GenericFileset.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestFilesetCatalog.java
- clients/client-python/gravitino/client/fileset_catalog.py
- clients/client-python/gravitino/client/generic_fileset.py
- clients/client-python/gravitino/dto/fileset_dto.py
- clients/client-python/gravitino/dto/requests/fileset_create_request.py
- clients/client-python/gravitino/dto/responses/fileset_response.py
- clients/client-python/gravitino/exceptions/handlers/fileset_error_handler.py
- clients/client-python/tests/integration/test_fileset_catalog.py
- clients/client-python/tests/unittests/mock_base.py
- common/src/main/java/org/apache/gravitino/dto/responses/FilesetResponse.java
Java/Python clients supports fileset multiple locations
Fix: #6894
yes, Java/Python clients support fileset multiple locations
tests added
> [#6894] feat(client): Java/Python clients supports fileset multiple locations

- build.gradle.kts
Fix web license and notice files in the binary release to include all web licenses and use the right files for the META-INF directory in the war file.
To comply with ASF policy - although binary releases are not official.
Fix: #N/A
No.
Locally by creating and inspecting a distribution.
> [Minor] Fix web license and notice files in the binary release

- .asf.yaml
add notification config for discussions
According to the Apache Infrastructure’s official guidelines  
we should set notification config in .asf.yaml
N/A
N/A
> [MINOR] add notification config for discussions

- clients/client-python/gravitino/client/gravitino_version.py
- clients/client-python/tests/unittests/test_gravitino_version.py
In current implementation of `GravitinoVersion.__gt__`, we don't handle the case 
when `version1.minor < version2.minor and version1.patch > version.patch`,
i.e. this will cause `0.6.1` greater than `0.7.0`.
Bug fix.
Fix: #5362 
Yes, bug fixes.
By `TestGravitinoVersion.test_version_compare`
> [#5362] fix(client-python): fix wrong Gravitino version

- core/src/main/java/org/apache/gravitino/catalog/EntityCombinedFileset.java
- core/src/test/java/org/apache/gravitino/catalog/TestEntityCombinedFileset.java
Add back getter method in EntityCombinedFileset that is caused by #6922
It's used by other import project.
N/A
N/A.
> [MINOR] Revert changes that remove getter method in EntityCombinedFileset

- docs/open-api/owners.yaml
Added a required tag to `type` under `OwnerSetRequest`.
`type` in request body is mandatory.
Fix: #6081 
Yes, just OpenAPI docs at https://gravitino.apache.org/docs/0.7.0-incubating/api/rest/set-owner/
> [#6081] docs: add required tag to type in set owner's request body

- api/build.gradle.kts
- clients/client-java/build.gradle.kts
- clients/filesystem-hadoop3-runtime/build.gradle.kts
- clients/filesystem-hadoop3/build.gradle.kts
Exclude the log4j jar in gvfs runtime shading jar to fix the log problem.
The log4j jar shipped with GVFS runtime jar will have a conflict with the environment, which will make the log4j not work, so we should exclude the log4j jar in GVFS runtime jar.
Fix: #6991
No.
> [#6991] fix(gvfs): Exclude log4j in gvfs runtime jar

- api/src/main/java/org/apache/gravitino/model/ModelVersionChange.java
- api/src/test/java/org/apache/gravitino/model/TestModelVersionChange.java
- catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogOperations.java
- catalogs/catalog-model/src/test/java/org/apache/gravtitino/catalog/model/TestModelCatalogOperations.java
- catalogs/catalog-model/src/test/java/org/apache/gravtitino/catalog/model/integration/test/ModelCatalogOperationsIT.java
- clients/cli/src/main/java/org/apache/gravitino/cli/ErrorMessages.java
- clients/cli/src/main/java/org/apache/gravitino/cli/ModelCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RemoveModelVersionProperty.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/SetModelVersionProperty.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestModelCommands.java
- clients/client-java/src/main/java/org/apache/gravitino/client/DTOConverters.java
- clients/client-python/gravitino/api/model_version_change.py
- clients/client-python/gravitino/client/generic_model_catalog.py
- clients/client-python/gravitino/dto/requests/model_version_update_request.py
- clients/client-python/tests/integration/test_model_catalog.py
- common/src/main/java/org/apache/gravitino/dto/requests/ModelVersionUpdateRequest.java
- core/src/test/java/org/apache/gravitino/catalog/TestModelOperationDispatcher.java
- core/src/test/java/org/apache/gravitino/connector/TestCatalogOperations.java
- core/src/test/java/org/apache/gravitino/storage/relational/service/TestModelVersionMetaService.java
Support update properties for model version
Fix: #6816 
user now can set or remove a property from a model version.
local test.
`bin/gcli.sh model set  -m demo_metalake --name model_catalog.schema.model2 --alias test --property "new_property" --value "new_value"`
`bin/gcli.sh model set  -m demo_metalake --name model_catalog.schema.model2 --alias test --property "new_property" --value "update_value"`
`bin/gcli.sh model remove  -m demo_metalake --name model_catalog.schema.model2 --alias test --property "new_property"`
> [#6816] feat(server): Support update properties for model version

- .asf.yaml
Update the `.asf.yaml` file to disable tag protection.
There's a wrong tag needs to be deleted, so we have to disable this temporarily to delete that tag.
No.
> [MINOR] Temporary disable tag protection to delete some wrong tags

- api/src/main/java/org/apache/gravitino/model/ModelVersionChange.java
- api/src/test/java/org/apache/gravitino/model/TestModelVersionChange.java
- catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogOperations.java
- catalogs/catalog-model/src/test/java/org/apache/gravtitino/catalog/model/TestModelCatalogOperations.java
- core/src/test/java/org/apache/gravitino/catalog/TestModelOperationDispatcher.java
- core/src/test/java/org/apache/gravitino/connector/TestCatalogOperations.java
- core/src/test/java/org/apache/gravitino/storage/relational/service/TestModelVersionMetaService.java
Support update URI for model version
Fix: #6813 
User can update the uri of a model version.
local ut test
> [#6813] feat(server): Support update URI for model version

- catalogs/catalog-model/src/test/java/org/apache/gravtitino/catalog/model/integration/test/ModelCatalogOperationsIT.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoOptions.java
- clients/cli/src/main/java/org/apache/gravitino/cli/ModelCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateModelVersionUri.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestModelCommands.java
- clients/client-java/src/main/java/org/apache/gravitino/client/DTOConverters.java
- clients/client-python/gravitino/api/model_version_change.py
- clients/client-python/gravitino/api/types/types.py
- clients/client-python/gravitino/client/generic_model_catalog.py
- clients/client-python/gravitino/dto/requests/model_version_update_request.py
- clients/client-python/tests/integration/test_model_catalog.py
- common/src/main/java/org/apache/gravitino/dto/requests/ModelVersionUpdateRequest.java
Support update URI for model version. 
> This pr add a temporary option for model version update, it will be refactored in the future when add model_version entity.
Fix: #6813 
User can update uri of a model version now.
local test + ut.
original uri
`bin/gcli.sh model update -m demo_metalake --name model_catalog.schema.model2 --version 0 --newuri 's3:///bucket/key' -I`
> [#6813] feat(core): Support update URI for model version.

- core/src/main/java/org/apache/gravitino/listener/api/event/AssociateTagsForMetadataObjectEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/AssociateTagsForMetadataObjectFailureEvent.java
- core/src/main/java/org/apache/gravitino/listener/api/event/AssociateTagsForMetadataObjectPreEvent.java
- core/src/test/java/org/apache/gravitino/listener/api/event/TestTagEvent.java
Add objectType of AssociateTagsForMetadataObjectEvent
Fix: #7011 
No
Manually test
> [#7011] improve (core): Add object type of AssociateTagsForMetadataObjectEvent

- api/src/main/java/org/apache/gravitino/model/ModelChange.java
- api/src/test/java/org/apache/gravitino/model/TestModelChange.java
- catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogOperations.java
- catalogs/catalog-model/src/test/java/org/apache/gravtitino/catalog/model/TestModelCatalogOperations.java
- catalogs/catalog-model/src/test/java/org/apache/gravtitino/catalog/model/integration/test/ModelCatalogOperationsIT.java
- clients/cli/src/main/java/org/apache/gravitino/cli/ModelCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateModelComment.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestModelCommands.java
- clients/client-java/src/main/java/org/apache/gravitino/client/DTOConverters.java
- clients/client-python/gravitino/api/model_change.py
- clients/client-python/gravitino/client/generic_model_catalog.py
- clients/client-python/gravitino/dto/requests/model_update_request.py
- clients/client-python/tests/integration/test_model_catalog.py
- common/src/main/java/org/apache/gravitino/dto/requests/ModelUpdateRequest.java
- core/src/test/java/org/apache/gravitino/catalog/TestModelOperationDispatcher.java
- core/src/test/java/org/apache/gravitino/connector/TestCatalogOperations.java
- core/src/test/java/org/apache/gravitino/storage/relational/service/TestModelMetaService.java
- docs/manage-model-metadata-using-gravitino.md
Support update comment operations for model alteration.
Fix: #6525 
User can update a comment of a model.
local test + ut + it.
`bin/gcli.sh model update -m demo_metalake --name model_catalog.schema.model2 --comment 'new_comment'`
`bin/gcli.sh model update -m demo_metalake --name model_catalog.schema.model2 --comment ''`
> [#6525] feature(core): Support update comment operations for model alteration.

- catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/integration/test/HadoopCatalogIT.java
- core/src/main/java/org/apache/gravitino/catalog/CatalogNormalizeDispatcher.java
- core/src/test/java/org/apache/gravitino/catalog/TestCatalogNormalizeDispatcher.java
support hyphen in catalog name
Fix: #6544
yes, user now can use hyphen in catalog name
tests added
> [#6544] improvement(catalog): support hyphen in catalog name

- build.gradle.kts
Fail to build Iceberg REST catalog Docker image
Fix: #7054 
no
build Iceberg REST server image successfully
> [#7054] fix(build): Fail to build Iceberg REST catalog Docker image

- docs/spark-connector/spark-integration-test.md
Doc spark3.3 to spark-3.3 :
`./gradlew :spark-connector:spark3.3:test --tests "org.apache.gravitino.spark.connector.integration.test.hive.SparkHiveCatalogIT33.testCreateHiveFormatPartitionTable"`
--> `./gradlew :spark-connector:spark-3.3:test --tests "org.apache.gravitino.spark.connector.integration.test.hive.SparkHiveCatalogIT33.testCreateHiveFormatPartitionTable"
`
> [MINOR] fix(docs): Fix typo of `spark-integration-test.md`

- catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
- core/src/main/java/org/apache/gravitino/catalog/SchemaOperationDispatcher.java
- core/src/test/java/org/apache/gravitino/catalog/TestSchemaOperationDispatcher.java
Catch the NonEmptyEntityException exception while dropSchema.
Fix: #6845 
No.
1. Create a schema and a table in MySQL or PG catalog in Gravitino UI
2. Drop the table by mysql client or psql cli
3. Drop the schema in Gravitino UI
4. No exception occurs
> [#6845] fix(core): handle NonEmptyEntityException while dropSchema

- dev/release/do-release.sh
- dev/release/release-build.sh
Optimize the release script
Fix: #7073 
No.
By hand.
> [#7073] improvement(build): Optimize the release script

- spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/iceberg/IcebergPropertiesConstants.java
Title:
```
[#6529 ] fix: Remove incorrect @VisibleForTesting annotation & apply Spotless formatting
```
* * * * *
-   Removed incorrect `@VisibleForTesting` annotation from `ICEBERG_CATALOG_CACHE_ENABLED`.
-   Applied Spotless formatting to multiple files (`README.md`, `docs/`, `gradle-wrapper.properties`, `gradlew`).
* * * * *
-   The `@VisibleForTesting` annotation was incorrectly added to `ICEBERG_CATALOG_CACHE_ENABLED`, which is a public constant and does not require this annotation.
-   Spotless ensures code consistency and formatting, avoiding CI failures.
* * * * *
No, this PR does not introduce any user-facing changes. It only includes formatting fixes and annotation removal.
* * * * *
-   Ran `./gradlew :spark-connector:spark-common:spotlessApply` to format the code.
-   Verified …
> [#6529] fix(core): remove unnecessary @VisibleForTesting annotation from ICEBERG_CATALOG_CACHE_ENABLED

- web/integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/CatalogsPageTest.java
- web/integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/pages/CatalogsPage.java
- web/web/src/app/metalakes/metalake/rightContent/CreateFilesetDialog.js
- web/web/src/app/metalakes/metalake/rightContent/tabsContent/detailsView/DetailsView.js
- web/web/src/components/DetailsDrawer.js
Web UI supports fileset multiple locations
N/A
Fix: #6947
N/A
manually
> [#6947] subtask(web): Web UI supports fileset multiple locations

- spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/hive/GravitinoHiveCatalog.java
- spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/hive/SparkHiveTypeConverter.java
- spark-connector/spark-common/src/test/java/org/apache/gravitino/spark/connector/integration/test/hive/SparkHiveCatalogIT.java
- spark-connector/v3.4/spark/src/main/java/org/apache/gravitino/spark/connector/hive/GravitinoHiveCatalogSpark34.java
- spark-connector/v3.4/spark/src/main/java/org/apache/gravitino/spark/connector/hive/SparkHiveTypeConverter34.java
- spark-connector/v3.4/spark/src/test/java/org/apache/gravitino/spark/connector/TestSparkHiveTypeConverter34.java
Fix: #7046
N/A
SparkHiveCatalogIT.testCreateTableWithTimestamp()
> [#7046] fix(spark-connector): Spark connector fails to parse timestamp data type 

- catalogs/hive-metastore-common/src/main/java/org/apache/gravitino/hive/converter/HiveDataTypeConverter.java
- catalogs/hive-metastore-common/src/test/java/org/apache/gravitino/hive/converter/TestTypeConverter.java
- add case handling to `HiveDataTypeConverter`: if trying to convert gravitino timestamp with timezone to Hive, throws `UnsupportedOperationException`
- add one more test case (timestamp with timezone) to `TestTypeConverter`
Fix: #7098 
No
> [#7098] Throw exception when converting timestamp with timezone to Hive type

- dev/docker/iceberg-rest-server/rewrite_config.py
- docs/iceberg-rest-service.md
add GRAVITINO_CATALOG_BACKEND to IRC docker container
current catalog backend is `JDBC`, we could set it to other backend like `hive`
no
test in local environment.
> [MINOR] docker(iceberg): add GRAVITINO_CATALOG_BACKEND to IRC docker container

- build.gradle.kts
- gradle/wrapper/gradle-wrapper.properties
- Removed the unnecessary ASF license header from `gradle/wrapper/gradle-wrapper.properties`.
- Modified `build.gradle.kts` to add an exclusion for the gradle-wrapper.properties file in the Apache RAT checks.
Fixes #7151
No.
- Executed `./gradlew rat` for rat check
- Executed `./gradlew spotlessCheck`
- Ran `./gradlew clean build` to ensure build integrity.
> [#7151] Improvement(license) : Remove ASF license header from gradle-wrapper.properties

- api/src/main/java/org/apache/gravitino/model/ModelVersionChange.java
- api/src/test/java/org/apache/gravitino/model/TestModelVersionChange.java
- catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogOperations.java
- catalogs/catalog-model/src/test/java/org/apache/gravtitino/catalog/model/integration/test/ModelCatalogOperationsIT.java
- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoOptions.java
- clients/cli/src/main/java/org/apache/gravitino/cli/ModelCommandHandler.java
- clients/cli/src/main/java/org/apache/gravitino/cli/TestableCommandLine.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateModelVersionAliases.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateModelVersionUri.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestModelCommands.java
- clients/client-java/src/main/java/org/apache/gravitino/client/DTOConverters.java
- clients/client-python/gravitino/api/model_version_change.py
- clients/client-python/gravitino/client/generic_model_catalog.py
- clients/client-python/gravitino/dto/requests/model_version_update_request.py
- clients/client-python/gravitino/filesystem/gvfs_base_operations.py
- clients/client-python/tests/integration/test_model_catalog.py
- clients/client-python/tests/unittests/test_gravitino_version.py
- common/src/main/java/org/apache/gravitino/dto/requests/ModelVersionUpdateRequest.java
- core/src/test/java/org/apache/gravitino/connector/TestCatalogOperations.java
- docs/manage-model-metadata-using-gravitino.md
- docs/open-api/models.yaml
Meanwhile, fixed some typos and added reload logic to each model version change test.
Fix: #6814
user now can update aliases of a model version.
local test(ut + it).
original model version
`bin/gcli.sh model update -m demo_metalake --name model_catalog.schema.model2 --newalias  'alias3' --alias test`
`bin/gcli.sh model remove -m demo_metalake --name model_catalog.schema.model2 --removealias "alias1" "alias2" "alias3" --alias "alias1"`
> [#6814] feat(core): Support update aliases for model version

- web/web/src/app/metalakes/metalake/rightContent/MetalakePath.js
- Added a new button on the frontend UI that allows users to easily copy the identity information of a table.
- While running `pnpm prettier . --check`, some formatting in `MetalakePath.js` was automatically adjusted.
- Fixed a typo as well.
Fixes #6592
Yes. Users can now quickly copy the identity string of a table using the new button.
- Ran `pnpm prettier . --check`
- Ran `./gradlew clean build`.
> [#6592] improvement(web): Add copy-to-clipboard button for identity string

- .github/workflows/docker-image.yml
- build.gradle.kts
- dev/docker/build-docker.sh
- dev/docker/ranger/docker-compose.ranger-build.yml
- dev/docker/ranger/ranger-dependency.sh
- docs/docker-image-details.md
Tasks should be done before merging this PR:
Make building ranger-related docker image works again.
This PR includes these changes:
In `dev/docker/ranger/ranger-dependency.sh`:
Tweak some settings to build ranger in Github CI.
In `.github/workflows/docker-image.yml`:
- remove unnecessary GitHub access token input field in `.github/workflows/docker-image.yml`, because this is for downloading ranger from `datastrato's` repository, and now this is not needed.
- Github Action: allow setting docker repo name in workflow_dispatch (default is `apache`), this is needed because developers can use their own Gravitino repo with Github Action to publish docker image to their Docker repo.
In `dev/docker/build-docker.sh`:
- Remove `--use` option while creating `gravitino-builder`, because this will …
> [#7101] Improvement(docker-image): fix ranger docker image build failure in CI

- clients/client-python/gravitino/filesystem/gvfs_storage_handler.py
fix [#7225](https://github.com/apache/gravitino/issues/7225#issue-3085354943)
As the issue described, for s3, oss, abs storage handler, the handler map put a class instead of handler instance, which is obviously wrong and can issues like handler method call missing `self` parameter.
No
I tested on my own machine with remote s3 storage, oss and abs is not tested.
> [#7225]: fix(client-python) minor fix s3a, oss, abs storage handler mapping

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/FilesetDetails.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListFilesets.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListRoles.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/ListTopics.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/RoleDetails.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/TopicDetails.java
- clients/cli/src/main/java/org/apache/gravitino/cli/outputs/PlainFormat.java
- clients/cli/src/main/java/org/apache/gravitino/cli/outputs/TableFormat.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestCliUtil.java
- clients/cli/src/test/java/org/apache/gravitino/cli/output/TestPlainFormat.java
- clients/cli/src/test/java/org/apache/gravitino/cli/output/TestTableFormat.java
Support TableFormat and PlainFormat for Topic, Fileset and Role
Fix: #6799 
`TableFormat` now support Topic, Role and FileSet Entities.
local test.
> [#6799] feat(core): Support TableFormat and PlainFormat for Topic, Fileset and Role

- lineage/src/main/java/org/apache/gravitino/lineage/LineageDispatcher.java
Fix the Javadoc @link reference in
`lineage/src/main/java/org/apache/gravitino/lineage/LineageDispatcher.java`.
Fixes #7208
No.
- Ran `./gradlew :lineage:javadoc` to confirm the Javadoc warning was resolved.
- Ran `./gradlew clean build` to ensure the build passes without errors.
> [#7208] improvement(javadoc): fix java doc @link reference issue

- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/iceberg/GravitinoIcebergCatalogFactory.java
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/utils/FactoryUtils.java
[#7214] fix(docs): resolve Javadoc issues in `:flink-connector:flink:javadoc`
This PR fixes multiple Javadoc generation issues within the `:flink-connector:flink` module. Specifically:
* Fixed incomplete Javadoc comments.
These changes are necessary to ensure:
1. Javadoc can be successfully generated without warnings or errors.
2. Code quality and documentation consistency are maintained.
3. CI builds involving Javadoc generation (especially with `spotlessApply` or similar tasks) pass without failure.
No user-facing changes are introduced. All changes are limited to internal documentation (Javadoc).
* Ran `./gradlew :flink-connector:flink:javadoc` to confirm successful Javadoc generation.
* Verified that `spotlessCheck` and `spotlessApply` pass without formatting or documentation issues. …
> [#7214] Fix Javadoc issues in task :flink-connector:flink:javadoc

- lineage/src/main/java/org/apache/gravitino/lineage/Utils.java
FIX #7222 
In lineage/src/main/java/org/apache/gravitino/lineage/Utils.java the method getJobName uses toString() when it is not needed.
No.
All build tests passed.
> [#7222] fix(lineage): Remove unnecessary toString call in Utils.getJobName

- core/src/main/java/org/apache/gravitino/catalog/OperationDispatcher.java
- core/src/main/java/org/apache/gravitino/storage/relational/utils/SessionUtils.java
- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/store/GravitinoCatalogStore.java
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/integration/test/FlinkEnvIT.java
- spark-connector/spark-common/src/test/java/org/apache/gravitino/spark/connector/integration/test/sql/SQLQueryTestHelper.java
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/GravitinoConnectorPluginManager.java
Fix #7221 
Several files catch `Throwable` when they should catch `Exception`. This is problematic because catching `Throwable` also catches serious JVM errors like `OutOfMemoryError`.
No.
All build tests passed.
> [#7221] Fix exception handling: catch Exception instead of Throwable where appropriate

- catalogs/catalog-common/src/main/java/org/apache/gravitino/catalog/property/PropertyConverter.java
fix javadoc for :catalogs:catalog-common
Fix: #7205
> [#7205] fix: javadoc for :catalogs:catalog-common

- web/web/src/app/metalakes/metalake/rightContent/CreateSchemaDialog.js
Remove redundant code `{activatedCatalogDetail?.properties['catalog-backend']}`
Fixes #7198
Removes redundant text on the “Create new schema” page under the Iceberg catalog section.
- Ran `pnpm prettier . --check`
- Ran `./gradlew clean build`
- User interface testing
> [#7198] fix(web): Removes redundant text on the “Create new schema” page under the Iceberg catalog section

- clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java
This PR addresses [Issue #7249](https://github.com/apache/gravitino/issues/7249), which pointed out unnecessary use of instanceof in exception handling in GravitinoVirtualFileSystem.java.
```
} catch (IOException e) {
if (e instanceof FilesetPathNotFoundException) {
throw (FilesetPathNotFoundException) e;
}
throw e;
}
```
This check is redundant since:
FilesetPathNotFoundException is a subtype of IOException
Both branches simply rethrow the exception
```
} catch (IOException e) {
throw e;
}
```
Or if this block serves no purpose beyond that, it could be safely removed altogether.
> [#7249] Remove unnecessary instanceof check for IOException handling

- .github/workflows/docker-image.yml
- build.gradle.kts
- catalogs/catalog-hive/src/test/java/org/apache/gravitino/catalog/hive/integration/test/ProxyCatalogHiveIT.java
- dev/docker/hive/Dockerfile
- dev/docker/hive/hive-dependency.sh
- dev/docker/kerberos-hive/Dockerfile
- dev/docker/ranger/ranger-dependency.sh
- docs/docker-image-details.md
This PR changed username in `hive`, `kerberos-hive` Dockerfile from `datastrato` to `gravitino`, and added a commit 5d58e1d69247d07093d4ed1aac5748116560d81a to verify the image is built correctly, this commit will be reverted after new version of image is published.
The steps below need to be done before merging this PR:
Rename datastrato to gravitino since we've donating this repo to ASF.
Fix: #5803 
No.
First, execute these steps to build image:
```
./dev/docker/build-docker.sh --platform all --type hive --image <image name and tag> --tag hive-test --latest
./dev/docker/build-docker.sh --platform all --type kerberos-hive --image <image name and tag> --tag kerberos-hive-test --latest
```
Run tests in `ProxyCatalogHiveIT`, `HiveUserAuthenticationIT` to verify that image is built …
> [#5803] feat(docker-image): Change username in `hive` Dockerfile from datastrato to gravitino

- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/CatalogRegister.java
Treat the version check for catalog names with dots as a warning.
Fix: #7255
No
Manually test
> [#7255] improve (trino-connector): Treat the version check for catalog names with dots as a warning.

- catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/operation/DorisTableOperations.java
- catalogs/catalog-jdbc-mysql/src/main/java/org/apache/gravitino/catalog/mysql/operation/MysqlTableOperations.java
- catalogs/catalog-jdbc-oceanbase/src/main/java/org/apache/gravitino/catalog/oceanbase/operation/OceanBaseTableOperations.java
Replaced string Concatenation in SLF4J `LOG.info` statement with built-in formatting in the following files:
1. `catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/operation/DorisTableOperations.java`
2. `catalogs/catalog-jdbc-mysql/src/main/java/org/apache/gravitino/catalog/mysql/operation/MysqlTableOperations.java`
3. `catalogs/catalog-jdbc-oceanbase/src/main/java/org/apache/gravitino/catalog/oceanbase/operation/OceanBaseTableOperations.java`
Using built-in formatting can help in:
1. It Enables **Lazy Evaluation**,  ie, the string will not be constructed if the log is turned off.
2. Improves **consistency** and **best practice** throughout the codebase.
3. avoids concatenation overhead at runtime.
This change was requested in Issue Number #7282.
No, It does not …
> [#7282] improvement(logging): use SLF4J formatting for alter table logs

- catalogs/catalog-common/src/main/java/org/apache/gravitino/credential/CredentialConstants.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClient.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoMetalake.java
- iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/IcebergConfig.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergRequestContext.java
- server/src/main/java/org/apache/gravitino/server/web/rest/TagOperations.java
- trino-connector/integration-test/src/test/java/org/apache/gravitino/trino/connector/integration/test/TrinoConnectorIT.java
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/GravitinoConfig.java
Add missing `@deprecated` javadoc tags.
Fix: #7219
> [#7219] docs: add missing deprecated javadoc tag

- api/src/main/java/org/apache/gravitino/rel/expressions/distributions/Distributions.java
- catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/operation/DorisTableOperations.java
- catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/utils/DorisUtils.java
- catalogs/catalog-jdbc-doris/src/test/java/org/apache/gravitino/catalog/doris/integration/test/CatalogDorisIT.java
- catalogs/catalog-jdbc-doris/src/test/java/org/apache/gravitino/catalog/doris/utils/TestDorisUtils.java
- common/src/main/java/org/apache/gravitino/dto/rel/DistributionDTO.java
- docs/table-partitioning-distribution-sort-order-indexes.md
Doris supports 'DISTRIBUTED BY HASH(dt_date) BUCKETS AUTO'
Fix: #([7185](https://github.com/apache/gravitino/issues/7185))
N/A
org.apache.gravitino.catalog.doris.utils.TestDorisUtils#testDistributedInfoPattern
org.apache.gravitino.catalog.doris.integration.test.CatalogDorisIT#testAllDistributionWithAuto
> [#7185]  Improvement(doris): Doris supports 'DISTRIBUTED BY HASH(columnName) BUCKETS AUTO'

- catalogs/catalog-hadoop/src/main/java/org/apache/gravitino/catalog/hadoop/HadoopCatalogOperations.java
- catalogs/catalog-hadoop/src/test/java/org/apache/gravitino/catalog/hadoop/TestHadoopCatalogOperations.java
- web/web/src/app/metalakes/metalake/rightContent/CreateFilesetDialog.js
Add validation: throw error if StorageLocation is null or blank  `Storage location for name '" + e.getKey() + "' must not be null or blank`
Fixes #7190
No. APIs and behavior are unchanged, only error messages for invalid input are clearer.
- Added new unit tests.
- Verified with `./gradlew clean build`.
> [#7190] fix(catalogs): Validate and filter empty storageLocations in HadoopCatalogOperations

- dev/charts/gravitino-iceberg-rest-server/Chart.yaml
- dev/charts/gravitino-iceberg-rest-server/resources/init.sh
- dev/charts/gravitino-iceberg-rest-server/templates/NOTES.txt
- dev/charts/gravitino-iceberg-rest-server/values.yaml
- dev/charts/gravitino/Chart.yaml
- dev/charts/gravitino/resources/config/init.sh
- dev/charts/gravitino/templates/NOTES.txt
- dev/charts/gravitino/values.yaml
- docs/iceberg-rest-catalog-chart.md
Currently deploy gravitino by Chart , the server log either output to console or file. We'd better support both.
Output to console ,then user can check log by `kubectl logs <pod-name> -n <namespace>` command 
Fix: #7341
N/A
CI
> [#7341] fix(chart): output server log to both console and file

- dev/docker/iceberg-rest-server/rewrite_config.py
The script now only sets config values from init_config if the key does not already exist in config_map, instead of always overwriting existing values.
This allows users to override config values in iceberg-rest-server, which was previously not possible because the script always overwrote user-supplied settings.
> [MINOR] fix: prevent overwriting existing config keys during initialization

- iceberg/iceberg-rest-server/build.gradle.kts
add jwt dependences
Fix: #7387 
no
compile standalone IRC server and verify with oauth configuraitons.
> [#7387] fix(iceberg): standalone Iceberg REST server failed to start with oauth enabled

- core/src/main/java/org/apache/gravitino/storage/relational/JDBCBackend.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java
- server-common/src/main/java/org/apache/gravitino/server/authorization/jcasbin/JcasbinAuthorizer.java
- server-common/src/test/java/org/apache/gravitino/server/authorization/jcasbin/TestJcasbinAuthorizer.java
Currently, the `ROLE_USER_REL` relation in `JDBCBackend` only supports querying users by role, but not querying roles by user. This causes issues in `JcasbinAuthorizer` when trying to load user privileges.
This PR adds support for querying roles by user in the `ROLE_USER_REL` relation by modifying the `listEntitiesByRelation` method in `JDBCBackend`.
Fixes #6786
No.
Ran `./gradlew clean build`
> [#6786] fix(authz): modify querying roles by user in ROLE_USER_REL relation for JcasbinAuthorizer

- core/src/main/java/org/apache/gravitino/cache/CaffeineEntityCache.java
- core/src/test/java/org/apache/gravitino/cache/TestCacheConfig.java
- core/src/test/java/org/apache/gravitino/cache/TestCaffeineEntityCache.java
Add more test case for CaffeineEntityCache.
- The put operation deduplicates between existing and newly added entities.
- Add more test cases for `CaffeineEntityCache`.
Fix: #7452 
no.
local test.
> [#7177] feat(core): Add more test case for CaffeineEntityCache

- clients/client-python/gravitino/dto/rel/__init__.py
- clients/client-python/gravitino/dto/rel/column_dto.py
- clients/client-python/gravitino/dto/rel/expressions/__init__.py
- clients/client-python/gravitino/dto/rel/expressions/function_arg.py
- clients/client-python/gravitino/dto/rel/expressions/literal_dto.py
- clients/client-python/gravitino/dto/rel/partition_utils.py
- clients/client-python/tests/unittests/dto/__init__.py
- clients/client-python/tests/unittests/dto/rel/__init__.py
- clients/client-python/tests/unittests/dto/rel/test_column_dto.py
- clients/client-python/tests/unittests/dto/rel/test_function_arg.py
- clients/client-python/tests/unittests/dto/rel/test_literal_dto.py
- clients/client-python/tests/unittests/dto/rel/test_partition_utils.py
This is the second part (totally 4 planned) of implementation to the following classes from Java to support Column and its default value, including:
- ColumnDTO
- LiteralDTO
- FunctionArg
- PartitionUtils
We implemented the above four classes in one single PR since they have tight dependency to each other.
**NOTE** that we haven't implemented the serdes for `ColumnDTO.default_value` which will be included in the future PR. Its serdes now are dummy ones to always serialize `ColumnDTO.default_value` to `None` and deserialize `ColiumnDTO.default_value` as `Column.DEFAULT_VALUE_NOT_SET`.
We need to support Column and its default value in python client.
#5202 
No
Unit tests
> [#5202] feat(client-python): Add ColumnDTO related classes

- build.gradle.kts
This change ensures that jcstress test artifacts (e.g., `*-jcstress.jar`) are no longer included in the libs folder after running `./gradlew compileDistribution`. 
Fix: #7465 
no
local test.
> [#7465] build(core): Fix Gravitino core jcstress jar should not be in libs folder

- catalogs/catalog-fileset/src/main/java/org/apache/gravitino/catalog/fileset/FilesetCatalogOperations.java
- core/src/main/java/org/apache/gravitino/metalake/MetalakeManager.java
- core/src/test/java/org/apache/gravitino/metalake/TestMetalakeManager.java
Remove old cached System.
To unify the caching architecture, we should remove legacy cache modules that directly proxy the underlying EntityStore, especially those that simply cache raw entity results. For example:
- `MetalakeManager`: its cache is a direct wrapper around EntityStore.
- `FilesetCatalogOperations`: its caching logic is also a shallow reuse of the underlying store.
In contrast, cache modules whose content is not directly sourced from the EntityStore, and which provide additional encapsulation or are relied on by external systems, should be preserved. For example:
- `CatalogManager`: it caches CatalogWrapper objects instead of raw Entity instances, and is externally depended upon.
In summary, the cache cleanup strategy should be based on two principles:
- Whether the cache …
> [#7179] improvement(core): Remove old cached System

- trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-mysql/00006_datatype.sql
- trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-mysql/00006_datatype.txt
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/mysql/MySQLDataTypeTransformer.java
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/util/json/JsonCodec.java
- trino-connector/trino-connector/src/test/java/org/apache/gravitino/trino/connector/catalog/jdbc/mysql/TestMySQLDataTypeTransformer.java
Support mysql JSON type with Trino.
Fix: #5657
no
local integration-test
> [#5657] feat(trino-connector): Support mysql JSON type

- clients/cli/src/main/java/org/apache/gravitino/cli/FullName.java
- clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/TagIT.java
- clients/client-python/tests/integration/containers/base_container.py
- clients/client-python/tests/unittests/auth/test_oauth2_token_provider.py
- docs/cli.md
There are several minor issues in the spelling of variable names etc
"enviroment" in base_container.py
"seperated" in VList.java and FullName.java
“arts” instead of “parts” in FullName.java
“authertication” misspelled in test_oauth2_token_provider.py
“specifed” in docs/cli.md
“retrivedTag” in TagIT.java
spelling issues of the variable names
Fix: #7511
no
just spell check.
> [#7511] fix typo's in code

- clients/client-python/gravitino/dto/rel/expressions/field_reference_dto.py
- clients/client-python/gravitino/dto/rel/expressions/func_expression_dto.py
- clients/client-python/gravitino/dto/rel/expressions/unparsed_expression_dto.py
- clients/client-python/tests/unittests/dto/rel/test_field_reference_dto.py
- clients/client-python/tests/unittests/dto/rel/test_func_expression_dto.py
- clients/client-python/tests/unittests/dto/rel/test_unparsed_expression_dto.py
This is the third part (totally 4 planned) of implementation to the following classes from Java to support Column and its default value, including:
- FieldReferenceDTO
- FuncExpressionDTO
- UnparsedExpressionDTO
We need to support Column and its default value in python client.
#5202
No
Unit tests
> [#5202] feat(client-python): add dto classes for default values

- bin/gravitino-iceberg-rest-server.sh.template
- bin/gravitino.sh.template
server shutdown logic should correctly check for forceKill
The if statement should check for forcekill variable value. Earlier, it was doing a comparison against the string `forcekill` which would always evaluate to true.
Required for correct shutdown of the service
Fix: #7513 
N/A
```
./bin/gravitino.sh start
./bin/gravitino.sh stop
```
(also modified the script to echo some more logs while shutting down. not committed in the patch, done only for local testing)
> [#7513] fix: server shutdown logic should correctly check for forceKill

- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationHDFSPlugin.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationHadoopSQLPlugin.java
- authorizations/authorization-ranger/src/main/java/org/apache/gravitino/authorization/ranger/RangerAuthorizationPlugin.java
This pull request changes the wildcardSearchPolies method's name to wildcardSearchPolicies, serving as a minor spelling fix
Fix: #7593
> [#7593] Renamed wildcardSearchPolies to wildcardSearchPolicies

- trino-connector/integration-test/trino-test-tools/download_jar.sh
This pull request removes extra #!/bin/bash line from the trino-connector/integration-test/trino-test-tools/download_jar.sh file.
Closes #7587
> removed extra bin/bash line

- .github/workflows/backend-integration-test-action.yml
- .github/workflows/backend-integration-test.yml
- core/src/main/java/org/apache/gravitino/listener/EventBus.java
- core/src/main/java/org/apache/gravitino/listener/EventListenerPluginWrapper.java
- core/src/main/java/org/apache/gravitino/listener/api/EventListenerPlugin.java
- core/src/main/java/org/apache/gravitino/listener/api/event/SupportsChangingPreEvent.java
- core/src/test/java/org/apache/gravitino/listener/CountingPreEvent.java
- core/src/test/java/org/apache/gravitino/listener/DummyEventListener.java
- core/src/test/java/org/apache/gravitino/listener/TestEventListenerManager.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/dispatcher/IcebergNamespaceEventDispatcher.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/dispatcher/IcebergTableEventDispatcher.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/dispatcher/IcebergViewEventDispatcher.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergCreateNamespacePreEvent.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergCreateViewPreEvent.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergReplaceViewPreEvent.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergUpdateNamespaceEvent.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergUpdateNamespacePreEvent.java
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/listener/api/event/IcebergUpdateTablePreEvent.java
Adding `transformPreEvent` method to `EventListenerPlugin` to make event listener modify pre-events.
```java
public interface EventListenerPlugin {
default SupportsChangingPreEvent transformPreEvent(SupportsChangingPreEvent preEvent) {
return preEvent;
}
}
```
Fix: #6486 
no
change the iceberg request and it take affects when creating table in local enviroment
> [#6486] feat(iceberg): supports change Iceberg request in pre event listener

- catalogs/catalog-jdbc-mysql/src/main/java/org/apache/gravitino/catalog/mysql/converter/MysqlColumnDefaultValueConverter.java
- catalogs/catalog-jdbc-mysql/src/main/java/org/apache/gravitino/catalog/mysql/converter/MysqlTypeConverter.java
- catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/converter/TestMysqlTypeConverter.java
- integration-test-common/docker-script/init/mysql/init.sql
- trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-mysql/00009_datatype_mapping.sql
- trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-mysql/00009_datatype_mapping.txt
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/mysql/MySQLDataTypeTransformer.java
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/mysql/MySQLExternalDataType.java
- trino-connector/trino-connector/src/test/java/org/apache/gravitino/trino/connector/catalog/jdbc/mysql/TestMySQLDataTypeTransformer.java
Support MySQL external type with Trino.
Fix: #7338
Fix: #7339
no
local integration-test
> [#7338] feat(trino-connector): Support external type with MySQL

- core/src/main/java/org/apache/gravitino/Entity.java
- core/src/main/java/org/apache/gravitino/cache/EntityCacheKey.java
- core/src/test/java/org/apache/gravitino/cache/TestEntityCacheKey.java
The `EntityType ` class has short name variable, but it's duplicated.  Table and Tag both used `ta`. 
And the short name is not used anymore.
This pr is try to clean up related code.
Fix: #7597
No
Use existing tests.
> [#7597] fix: fix EntityType short name duplicate issue

- clients/cli/src/main/java/org/apache/gravitino/cli/GravitinoOptions.java
This PR proposes the removal of duplicated code that appears twice in the CLI module.
Fix: #7639 
None
I verified this patch by reviewing and running the existing test clinets:cli
> [#7639] improvement(cli): remove duplicate owner in CLI

- core/src/main/java/org/apache/gravitino/cache/BaseEntityCache.java
Add a null check before entity type check.
Previously, `validateEntityHasIdentifier` only validates the entity type but doesn't check if the entity is null before accessing its properties, which may cause misleading error messages.
Fix: #7636
No.
> [#7636] add null check to BaseEntityCache validation

- api/src/main/java/org/apache/gravitino/job/SparkJobTemplate.java
Added Missing @Override annotation
Fix: #7641 
None
Execute existing api module test
> [#7641] improvement(api): Missing @Override annotation to the hashCode method of SparkJobTemplate

- clients/client-java/src/main/java/org/apache/gravitino/client/HTTPClient.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestHTTPClient.java
Added a null check for empty headers before adding request headers in HTTPClient.
Closes: [#7589](https://github.com/apache/gravitino/issues/7589)
No
Added a unit test.
> [#7589] fix (clients): check null before adding request headers in HTTPClient

- integration-test-common/src/test/java/org/apache/gravitino/integration/test/container/MySQLContainer.java
Added DB name validation to the createDatabase method to secure DB creation.
Fix: #7585 
No
Tested with unit tests to validate if invalid names are rejected and the names in the TestDatabaseName enum are accepted
> [#7585] feat: add DB name validation to secure DB creation

- clients/client-python/gravitino/utils/http_client.py
Logging configuration moved to module level, handler added only once when module is imported.
The previous logger implementation in `http_client.py` creates a log handler every time a `Response` object is instantiated, which may cause log message duplication and consume unnecessary memory over time.
Fix: #7583 
No.
Existing tests for `client-python`.
> [#7583] remove unused logger in python client

- catalogs/catalog-jdbc-mysql/src/main/java/org/apache/gravitino/catalog/mysql/operation/MysqlTableOperations.java
- catalogs/catalog-jdbc-oceanbase/src/main/java/org/apache/gravitino/catalog/oceanbase/operation/OceanBaseTableOperations.java
Removed the first setProperties insertion inside generateAlterTableSql
When both a table comment and properties were modified in the same operation, the old logic produced two SET TBLPROPERTIES clauses.
Fix: #7665
> [#7665]remove duplicate properties code

- clients/cli/src/main/java/org/apache/gravitino/cli/CommandEntities.java
remove duplicate MODEL in CommandEntities.java
The VALID_ENTITIES set previously contained two entries for 'MODEL'. 
Fix: #7664
Since the removal only affects the internal entity registration logic and does not impact any user-facing behavior or API, no additional tests were required.
> [#7664] remove duplicate MODEL in CommandEntities.java

- core/src/test/java/org/apache/gravitino/storage/memory/TestMemoryEntityStore.java
Add rollback logic to the in-memory test store. A snapshot will be created during transaction execution and will be restored if an exception occurs
Fix: #7584 
No
Tested with unit tests for rollback logic
> [#7584] improvement: Add rollback logic to the in-memory test store

- .github/workflows/chart-test.yaml
- dev/charts/gravitino/resources/config/gravitino.conf
- docs/security/how-to-authenticate.md
1. Gravitino start failed if launched by chart. It caused by wrong number format in conf 
```
gravitino.cache.enabled = true
gravitino.cache.maxEntries = 10000
gravitino.cache.expireTimeInMs = 3.6e+06
gravitino.cache.enableStats = false
gravitino.cache.enableWeigher = true
gravitino.cache.implementation = caffeine
```
2. Skip ' --check-version-increment' , because it makes no sense if this chart doesn't release to public artifactory automatically. BTW check version increment is not convenient during the Gravitino release period
Fix: #7720 
N/A
CI
> [#7720 ] Display numbers in standard format, avoiding scientific notation.

- clients/cli/src/main/java/org/apache/gravitino/cli/ParseType.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestParseType.java
Fix the parsing of whitespace correctly in list and map types in the CLI.
Fix: #7707
No
Added a unit test
> [#7707] Improvement(client-cli): Fix the parsing of whitespace correctly in list and map types in the CLI.

- integration-test-common/src/test/java/org/apache/gravitino/integration/test/util/BaseIT.java
- integration-test-common/src/test/java/org/apache/gravitino/integration/test/util/DownloaderUtils.java
This PR addresses JDBC driver version conflicts in integration tests by implementing automatic driver version conflict detection and cleanup.
Fix: #7696 
No
> [#7696] fix(it): validate driver versions before integration tests

- server/src/main/java/org/apache/gravitino/server/web/filter/GravitinoInterceptionService.java
- server/src/test/java/org/apache/gravitino/server/web/filter/TestGravitinoInterceptionService.java
Include useful info e.g. user, operation, metadata object in the error messages when auth fails.
Fix: #7753 
No.
`org.apache.gravitino.server.web.filter.TestGravitinoInterceptionService`
> [#7753] improve error messages when auth fails

- api/src/main/java/org/apache/gravitino/model/ModelCatalog.java
- catalogs/catalog-model/build.gradle.kts
- catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelCatalogOperations.java
- catalogs/catalog-model/src/main/java/org/apache/gravitino/catalog/model/ModelVersionImpl.java
- catalogs/catalog-model/src/test/java/org/apache/gravtitino/catalog/model/TestModelCatalogOperations.java
- core/src/main/java/org/apache/gravitino/catalog/EntityCombinedModelVersion.java
- core/src/main/java/org/apache/gravitino/catalog/ModelNormalizeDispatcher.java
- core/src/main/java/org/apache/gravitino/catalog/ModelOperationDispatcher.java
- core/src/main/java/org/apache/gravitino/connector/BaseModelVersion.java
- core/src/main/java/org/apache/gravitino/hook/ModelHookDispatcher.java
- core/src/main/java/org/apache/gravitino/listener/ModelEventDispatcher.java
- core/src/main/java/org/apache/gravitino/listener/api/info/ModelVersionInfo.java
- core/src/test/java/org/apache/gravitino/TestModelVersion.java
- core/src/test/java/org/apache/gravitino/catalog/TestModelOperationDispatcher.java
- core/src/test/java/org/apache/gravitino/connector/TestCatalogOperations.java
- core/src/test/java/org/apache/gravitino/listener/api/event/TestModelEvent.java
- core/src/test/java/org/apache/gravitino/meta/TestEntityCombinedObject.java
This PR implements operations for model version with multiple URIs.
Fix: #7382 
No.
UT.
> [#7382] feat(model): Implement operations for model version with multiple URIs

- .github/workflows/build.yml
Increase the timeout time for build task from 30m to 60m.
30m is not enough as the project introduces more modules.
Fix: #7784
N/A.
Exsiting CI.
> [#7784] improvement(CI): Increase timeout time for build pipeline.

- clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoAdminClient.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClient.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClientBase.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClientConfiguration.java
- clients/client-java/src/main/java/org/apache/gravitino/client/HTTPClient.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestGravitinoClientBuilder.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestGravitinoClientConfiguration.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestHTTPClient.java
- common/src/main/java/org/apache/gravitino/utils/MapUtils.java
- docs/how-to-use-java-client.md
Support pass custom http client config when using the Java Gravitino Client. 
- We can config connectionTimeout or socketTimeout and so on.
Fix: #7456
- support http client config
|config      | default | Description |
| ----------- |----------- |----------- |
|gravitino.client.connectionTimeoutMs | null  | An optional http connection timeout in milliseconds|
|gravitino.client.socketTimeoutMs | null | An optional http socket timeout in milliseconds |
- add `withClientConfig` in `org.apache.gravitino.client.GravitinoClientBase.Builder`
```
Map<String, String> properties =
ImmutableMap.of(
"gravitino.client.connectionTimeoutMs", "10", 
"gravitino.client.socketTimeoutMs", "10"
);
GravitinoClient.builder("uri")
.withMetalake("metalake")
.withClientConfig(properties) // add custom client …
```
> [#7456] feat(client-java): Support custom http client config for gravitino client

- common/src/main/java/org/apache/gravitino/auth/ProviderType.java
- dev/charts/gravitino/resources/config/gravitino.conf
- server-common/src/main/java/org/apache/gravitino/server/authentication/OAuthConfig.java
- server/src/main/java/org/apache/gravitino/server/web/ConfigServlet.java
Adding configs required for Azure based oAuth login
These will not cause any problems with the current oAuth as these are just additional configs exposed in /configs endpoint
These changes will be used in future PRs for Azure MSAL based oAuth support in the front end code, through /configs endpoint
Fix: #7538 
This does not introduce user facing changes. Only changing the /configs API response for now
Tested in local deployment.
Enabled Azure oauth by
```
gravitino.authenticators = oauth
gravitino.authenticator.oauth.provider = azure
```
and set
gravitino.authenticator.oauth.azure.client-id , gravitino.authenticator.oauth.azure.authority, gravitino.authenticator.oauth.azure.redirect-uri, …
> [7538] feat(OAuth) : Adding configs for Azure OAuth login

- catalogs/catalog-jdbc-mysql/src/main/java/org/apache/gravitino/catalog/mysql/operation/MysqlTableOperations.java
- catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
- catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/operation/TestMysqlTableOperations.java
- The `primary key` must be `not null`
-  The auto increment `unique key` must be `not null`
Fix: #7807
no
local tests
> [#7807] improvement(mysql-catalog): Add index column not null limitation

- clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/TagIT.java
- server/src/main/java/org/apache/gravitino/server/web/rest/MetadataObjectTagOperations.java
- server/src/test/java/org/apache/gravitino/server/web/rest/TestMetadataObjectTagOperations.java
Use set to remove duplicated tags when list all tags for a metadata object.
We need to eliminate duplicates.
Fix: #7688 
N/A
UT
> [#7688] fix(server): Fix duplicated tags when list tags for a metadata object.

- .github/workflows/access-control-integration-test.yml
- .github/workflows/backend-integration-test.yml
- .github/workflows/build.yml
- .github/workflows/chart-test.yaml
- .github/workflows/cron-integration-test.yml
- .github/workflows/flink-integration-test.yml
- .github/workflows/frontend-integration-test.yml
- .github/workflows/gvfs-fuse-build-test.yml
- .github/workflows/python-integration-test.yml
- .github/workflows/spark-integration-test.yml
- .github/workflows/trino-integration-test.yml
Change the version of `paths-filter` from v3.0.2 to de90cc6fb38fc0963ad72b210f1f284cd68cea36
The commit https://github.com/apache/infrastructure-actions/commit/f65b1b9f5c4a50a7559fed2773a00f6361e1fe56 make v3.0.2 can't works.
Fix: #7886 
N/A
CI
> [#7886] fix(CI): Fix CI action `paths-filter` can't work

- .github/workflows/access-control-integration-test.yml
- .github/workflows/backend-integration-test.yml
- .github/workflows/build.yml
- .github/workflows/chart-test.yaml
- .github/workflows/cron-integration-test.yml
- .github/workflows/flink-integration-test.yml
- .github/workflows/frontend-integration-test.yml
- .github/workflows/gvfs-fuse-build-test.yml
- .github/workflows/python-integration-test.yml
- .github/workflows/spark-integration-test.yml
- .github/workflows/trino-integration-test.yml
Change the version of `paths-filter` from v3.0.2 to de90cc6fb38fc0963ad72b210f1f284cd68cea36
The commit https://github.com/apache/infrastructure-actions/commit/f65b1b9f5c4a50a7559fed2773a00f6361e1fe56 make v3.0.2 can't works.
Fix: #7886 
N/A
CI
> [#7886] fix(CI): Fix CI action `paths-filter` can't work (#7885)

- .github/workflows/backend-integration-test.yml
- .github/workflows/build.yml
- .github/workflows/cron-integration-test.yml
- .github/workflows/flink-integration-test.yml
- .github/workflows/spark-integration-test.yml
- build.gradle.kts
- catalogs/catalog-fileset/src/test/java/org/apache/gravitino/catalog/fileset/integration/test/HadoopUserAuthenticationIT.java
- gradle.properties
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/integration/test/IcebergRestKerberosHiveCatalogIT.java
1. Upgrade Gravitino server server minimal JDK version to 17
2. Remove other version of JDK in CI pipe lines.
We could upgrade the Iceberg version only if we upgrade the IRC and Gravitino server
Fix: #7823 
Yes, the server couldn't run under JDK8, JDK11
UTs and ITs
> [#7823] feat(server): upgrade Gravitino server mini JDK version to 17

- docs/open-api/openapi.yaml
Fix the incorrect path in OpenAPI docs for list partitions.
The existing path has a typo.
Fix: #7888 
Yes, user-facing OpenAPI doc.
Rendering `openapi.yaml`.
> [#7888] fix incorrect path in docs for list partitions

- api/src/main/java/org/apache/gravitino/rel/expressions/literals/Literals.java
- catalogs/catalog-jdbc-common/src/main/java/org/apache/gravitino/catalog/jdbc/converter/JdbcColumnDefaultValueConverter.java
- catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/converter/DorisColumnDefaultValueConverter.java
- catalogs/catalog-jdbc-doris/src/test/java/org/apache/gravitino/catalog/doris/integration/test/CatalogDorisIT.java
- catalogs/catalog-jdbc-mysql/src/main/java/org/apache/gravitino/catalog/mysql/converter/MysqlColumnDefaultValueConverter.java
- catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/integration/test/CatalogMysqlIT.java
- catalogs/catalog-jdbc-oceanbase/src/main/java/org/apache/gravitino/catalog/oceanbase/converter/OceanBaseColumnDefaultValueConverter.java
- catalogs/catalog-jdbc-oceanbase/src/test/java/org/apache/gravitino/catalog/oceanbase/integration/test/CatalogOceanBaseIT.java
- catalogs/catalog-jdbc-postgresql/src/main/java/org/apache/gravitino/catalog/postgresql/converter/PostgreSqlColumnDefaultValueConverter.java
- catalogs/catalog-jdbc-postgresql/src/test/java/org/apache/gravitino/catalog/postgresql/integration/test/CatalogPostgreSqlIT.java
- catalogs/catalog-jdbc-starrocks/src/main/java/org/apache/gravitino/catalog/starrocks/converter/StarRocksColumnDefaultValueConverter.java
- catalogs/catalog-jdbc-starrocks/src/test/java/org/apache/gravitino/catalog/starrocks/integration/test/CatalogStarRocksIT.java
Update DateTimeType column default value formatter.
- TimeType: "HH:mm:ss[.SSSSSS][.SSSSS][.SSSS][.SSS][.SS][.S]"
- TimestampType: "yyyy-MM-dd HH:mm:ss[.SSSSSS][.SSSSS][.SSSS][.SSS][.SS][.S]"
Fix: #7900 
No
local tests
> [#7900] fix(catalogs): Fix jdbc catalogs DateTimeType column load with default value

- docs/security/how-to-authenticate.md
Update authenticate page to fix wordings and typos
Update doc wordings , fix typos
No
Doc changes reviewed
> [MINOR] docs: Fix wordings and some typos on `how-to-authenticate` doc

- server-common/src/main/java/org/apache/gravitino/server/authentication/OAuthConfig.java
- server-common/src/main/java/org/apache/gravitino/server/authentication/ProviderType.java
- server-common/src/test/java/org/apache/gravitino/server/authentication/TestOAuthConfig.java
Move ProviderType from common to server-common, and provide the supported values (default, oidc). Use it to validate the OAuthConfig provider
Minor refactor and validate the config
Fix: #7945
NA
Added unit tests
Tested manually as well:
> [#7945] refactor: Validate Provider type and clarify OAuth provider config supports 'default' and 'oidc'

- authorizations/authorization-common/src/main/java/org/apache/gravitino/authorization/common/PathBasedMetadataObject.java
- authorizations/authorization-common/src/test/java/org/apache/gravitino/authorization/common/TestPathBasedMetadataObject.java
Updated the PathBasedMetadataObject class to:
- Compare the `recursive` flag in `equals()` and `hashCode()` methods.
- Include the `recursive` flag in the `toString()` output.
Previously, the `recursive` flag was not considered in equality checks or hash code generation,
which could lead to incorrect comparisons and inconsistent behavior in hash-based collections.
Additionally, the `toString()` output did not reflect the `recursive` state, making debugging harder.
Fix: #7985 
No user-facing API changes.  
However, objects with different `recursive` flag values will now be treated as unequal.
- Added `testRecursiveFlagAffectsEquality()` to the `TestPathBasedMetadataObject` class.
- Added a case to `testToString()`.
> [#7985] fix(authz): Include recursive flag in hashCode(), equals(), toString()

- clients/client-python/gravitino/api/types/json_serdes/_helper/serdes_utils.py
- clients/client-python/gravitino/dto/rel/expressions/json_serdes/_helper/serdes_utils.py
- clients/client-python/gravitino/utils/serdes.py
This PR is aimed at introducing a `SerdesUtilsBase` class to accommodate shared class variables so that they could be shared across all its sub-classes like `SerdesUtils`. In doing so, we could
- achieve single source of truth against shared class variables,
- facilitate maintenance effort.
The current implementation of `SerdesUtils` in client-python tries to split `JsonUtils` in Java client into various classes listed as follows.
- [gravitino.api.types.json_serdes._helper.serdes_utils.SerdesUtils](https://github.com/apache/gravitino/blob/main/clients/client-python/gravitino/api/types/json_serdes/_helper/serdes_utils.py)
- [gravitino.dto.rel.expressions.json_serdes._helper.serdes_utils.SerdesUtils](https://github.com/apache/gravitino/blob/main/clients/client-python/gravitino/dto/rel/expres …
> [#5199] refactor(client-python): refactor of serdes utils

- clients/client-python/gravitino/client/gravitino_client.py
- clients/client-python/gravitino/client/gravitino_client_base.py
- clients/client-python/gravitino/client/gravitino_client_config.py
- clients/client-python/gravitino/filesystem/gvfs_base_operations.py
- clients/client-python/gravitino/filesystem/gvfs_config.py
- clients/client-python/gravitino/filesystem/gvfs_utils.py
- clients/client-python/gravitino/utils/http_client.py
- clients/client-python/tests/unittests/test_gravitino_client.py
- clients/client-python/tests/unittests/test_gvfs_with_local.py
- docs/how-to-use-gravitino-client.md
- docs/how-to-use-gvfs.md
Support config request timeout for Gravitino Python client
Currently, python client request timeout is a constant  values (10s).
Fix: #7670 
- add `client_config` in `GravitinoClientBase`
- add `client_config_` in  `GVFSConfig`
localhost tests
> [#7670] feat(client-python): Support config request timeout for Gravitino Python client

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/SetOwner.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestOwnerCommands.java
Add a validation method for entity type in SetOwner command
Fix: #7984 
No
Added a UT
> [#7984] Improvement (CLI): add validation method for entity type in SetOwner command

- common/src/test/java/org/apache/gravitino/utils/TestJdbcUrlUtils.java
- core/src/main/java/org/apache/gravitino/storage/relational/session/SqlSessionFactoryHelper.java
Fixes the parameter order when calling JdbcUrlUtils.validateJdbcConfig in SqlSessionFactoryHelper.java. The method now receives driverClass as the first parameter and jdbcUrl as the second, as expected.
Adds comprehensive unit tests in TestJdbcUrlUtils.java covering valid and invalid JDBC configurations.
JdbcUrlUtils.validateJdbcConfig validates the JDBC configuration by checking the driver class name and URL for unsafe parameters. Incorrect parameter order caused validation to run against the wrong values, leading to incorrect results. This fix ensures validation logic works as intended and improves test coverage.
Fix: #7960 
No
Added unit tests for both successful and failure cases in TestJdbcUrlUtils.java. All tests pass.
> [#7960] Improvement (core,common): correct parameter order in SqlSessionFactoryHelper and add unit tests for JdbcUrlUtils.validateJdbcConfig

- core/src/test/java/org/apache/gravitino/storage/memory/TestMemoryEntityStore.java
Previously, the snapshot for rollback was created outside the lock, which could lead to inconsistent state and race conditions in concurrent scenarios.
This change ensures the snapshot is always created while holding the lock, preventing data corruption and ensuring reliable transaction rollback.
Fix: #7977
No
With UTs added earlier
> [#7977] fix: resolve race condition in snapshot creation by adjusting lock usage

- catalogs/catalog-jdbc-mysql/src/main/java/org/apache/gravitino/catalog/mysql/MysqlCatalogCapability.java
- catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/TestMysqlCatalogCapability.java
- catalogs/catalog-jdbc-mysql/src/test/java/org/apache/gravitino/catalog/mysql/integration/test/MysqlCatalogCapabilityIT.java
- catalogs/catalog-jdbc-postgresql/src/main/java/org/apache/gravitino/catalog/postgresql/PostgreSqlCatalogCapability.java
- catalogs/catalog-jdbc-postgresql/src/test/java/org/apache/gravitino/catalog/postgresql/TestPostgreSqlCatalogCapability.java
- catalogs/catalog-jdbc-postgresql/src/test/java/org/apache/gravitino/catalog/postgresql/integration/test/PostgreSqlCatalogCapabilityIT.java
- Added validation for reserved words in PostgreSQL catalog capability.
- Reserved words (like pg_catalog, information_schema) are now checked for both schema and table scopes to prevent naming conflicts.
Prevents users from creating schemas or tables with names that conflict with system catalogs or schemas.
Fix: #7979 
Users will receive an error if they attempt to use reserved names for schemas or tables in PostgreSQL catalogs.
UTs and ITs
> [#7979] Improvement(catalogs): Add reserved words check for MySQL and Postgres

- server/src/main/java/org/apache/gravitino/server/web/filter/GravitinoInterceptionService.java
GravitinoInterceptionService.java there was an error - wrong NameIdentifier was used.
This PR fixes bug when wrong NameIdentifier was used in GravitinoInterceptionService.java
Fix: #8013
No.
1. By running relevant JUnit test.
> Fix metadata confusion in GravitinoInterceptionService

- common/src/test/java/org/apache/gravitino/dto/requests/TestModelVersionUpdatesRequest.java
This PR adds a null check for the updates field in ModelVersionUpdateRequest.validate().
If updates is null, the method now throws an IllegalArgumentException with a clear message instead of triggering a NullPointerException.
This ensures that validation fails gracefully when no updates are provided.
Previously, when updates was null, calling updates.forEach(...) would result in a NullPointerException, which is less informative and harder to debug.
By explicitly checking for null and throwing IllegalArgumentException, the code provides a clear error message and prevents unexpected runtime failures.
Fix: #8009 
No
Added a test to verify that validate() throws IllegalArgumentException when updates is null.
> [#8009] fix: prevent NPE in validate() when ModelVersionUpdatesRequest updates is null

- common/src/main/java/org/apache/gravitino/dto/rel/indexes/IndexDTO.java
- common/src/test/java/org/apache/gravitino/dto/rel/indexes/TestIndexDTO.java
Modified IndexDTO's hashCode() method to include fieldNames in the hash calculation.
The fieldNames is a two-dimensional String[][] array, and each sub-array’s hash is incorporated to ensure more accurate hash codes.
This fix ensures that fieldNames contributes to the hash code, maintaining the contract between equals() and hashCode().
Fix: #8007
No
Added a new test class org.apache.gravitino.dto.rel.indexes.TestIndexDTO to verify the updated hashCode() behavior.
> [#8007] fix: include fieldnames in hashCode

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/TagEntity.java
Title:
Fix tags not being saved for FILESET and MESSAGING entities
Description:
- Updated FILESET and MESSAGING cases to assign the result of associateTags() to tagsToAdd, matching the behavior of RELATIONAL and MODEL cases.
- Ensures that tags are correctly captured and processed for these entity types.
Closes #8039
> [#8039] Assigned tags to tagsToAdd for messaging and fileset

- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/base/JobMetaBaseSQLProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/JobMetaPostgreSQLProvider.java
This PR adds the `AND deleted_at = 0` condition to the sort delete logic in the codebase. This ensures that only non-deleted records are considered during sort operations, preventing deleted records from being included in the sorting process.
Fix: #8032
The current sort delete logic was missing a crucial condition to filter out already soft-deleted records. Without the `AND deleted_at = 0` condition, the sort operation could potentially include records that have been marked as deleted (deleted_at > 0), leading to inconsistent behavior and potential data integrity issues.
This fix ensures that:
1. Soft-deleted records are properly excluded from sort operations
2. Data consistency is maintained across the application
3. The soft delete pattern is correctly implemented throughout the …
> [#8032] fix(core): add soft delete condition to sort delete logic

- web/integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/CatalogsPageTest.java
- web/integration-test/src/test/java/org/apache/gravitino/integration/test/web/ui/pages/CatalogsPage.java
- web/web/src/app/metalakes/metalake/rightContent/tabsContent/TabsContent.js
- web/web/src/app/metalakes/metalake/rightContent/tabsContent/filesetView/FilesetView.js
- web/web/src/lib/api/filesets/index.js
- web/web/src/lib/store/metalakes/index.js
Implements the `FilesetView.js` component to provide a file browser interface for viewing and navigating fileset in the Gravitino Web UI.
- Fixes #7477
- Parent: #6860
add the UI to view files and directories within filesets.
User can use navigation for easy path traversal.
- User test
> [#7477] feat(web): Implement FilesetView component for file browser interface

- iceberg/iceberg-common/src/main/java/org/apache/gravitino/iceberg/common/ops/IcebergCatalogWrapper.java
remove unnecessary injectTableConfig in `IcebergCatalogWrapper`
#6021  moves the the credential injection from `IcebergCatalogWrapper` to `CatalogWrapperForREST#injectCredentialConfig` while loading table. Now the `IcebergCatalogWrapper.injectTableConfig` only performs an unnecessary `loadTableResponse` copy, which should be removed.
No.
cc @FANNG1 Hi, can you please take a look when you have time? Thanks!
> improvement(IRC): remove useless injectTableConfig while loading table.

- api/src/main/java/org/apache/gravitino/Catalog.java
- api/src/main/java/org/apache/gravitino/Schema.java
- api/src/main/java/org/apache/gravitino/file/Fileset.java
- api/src/main/java/org/apache/gravitino/messaging/Topic.java
- api/src/main/java/org/apache/gravitino/model/Model.java
- api/src/main/java/org/apache/gravitino/rel/Table.java
- clients/client-java/build.gradle.kts
- clients/client-java/src/main/java/org/apache/gravitino/client/BaseSchemaCatalog.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GenericFileset.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GenericModel.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GenericPolicy.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GenericSchema.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GenericTopic.java
- clients/client-java/src/main/java/org/apache/gravitino/client/MetadataObjectPolicyOperations.java
- clients/client-java/src/main/java/org/apache/gravitino/client/RelationalTable.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestGravitinoMetalake.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestSupportPolicies.java
- clients/client-java/src/test/java/org/apache/gravitino/client/integration/test/PolicyIT.java
- gradle.properties
Java client supports policy relational operations and add ITs
Fix: #7880 
yes, new feature of Java client
tests added
> [#7880] feat(policy): java client supports policy operations (part-2)

- common/src/main/java/org/apache/gravitino/dto/requests/CatalogCreateRequest.java
- common/src/test/java/org/apache/gravitino/dto/requests/TestCatalogCreateRequest.java
Add null safety checks in CatalogCreateRequest constructor to prevent NullPointerException when type is null and provider is "hadoop". Additionally, add a comprehensive test case to verify the fix works correctly and throws IllegalArgumentException instead of NPE.
- The constructor was vulnerable to NPE when `this.provider.equalsIgnoreCase("hadoop")` was called with a null provider
- When type is null and provider is "hadoop", `CatalogProvider.shortNameForManagedCatalog(type)` would throw NPE
- As mentioned by @justinmclean, relying on validate() call order is brittle and a simple defensive check costs nothing while hardening the code
No, this is purely a defensive programming improvement. The behavior for valid inputs remains unchanged, and invalid inputs now throw clear …
> [#8085] fix: NPE in CatalogCreateRequest constructor when type is null

- core/src/main/java/org/apache/gravitino/StringIdentifier.java
- core/src/test/java/org/apache/gravitino/TestStringIdentifier.java
fix: trim trailing spaces in removeIdFromComment method
- Modified removeIdFromComment method to call trim() on the result
- Added test case testRemoveIdFromCommentTrimsTrailingSpaces to verify the fix
- Ensures that comments with trailing spaces are properly trimmed when removing identifier
This PR fixes the `removeIdFromComment` method in `StringIdentifier.java` to properly trim trailing whitespace when removing identifiers from comments. The method now calls `.trim()` on the result before returning it.
The `removeIdFromComment` method was not handling trailing spaces correctly. When a comment had trailing whitespace (e.g., "This is a comment "), the method would return the comment with those trailing spaces intact instead of a clean, trimmed result. This inconsistency could lead to …
> [#7974] fix: trim trailing spaces in StringIdentifier.removeIdFromComment

- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/DefaultMapperPackageProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/MapperPackageProvider.java
- core/src/main/java/org/apache/gravitino/storage/relational/session/SqlSessionFactoryHelper.java
Change the SPI interface to add the specific mapper list instead of general package name.
Currently, we're using package name to load in all the mapper class to MyBatis configuration, but our package contains lots of classes other than mapper class, so they will also load in unexpected classes to increase the footprint. So here slightly adjust the SPI to avoid load in the unwanted classes.
Fix: #8167 
No.
> [#8167]improve(core): Improve the SPI to load in the specific mapper class

- core/src/main/java/org/apache/gravitino/utils/PrincipalUtils.java
- server/src/test/java/org/apache/gravitino/server/web/rest/TestFilesetOperations.java
Handle JAVA error message as well as excetion messages.
Java error message also needed to be handled.
Fix: #8122
N/A
Existing UTs and test locally
> [#8122] fix(core): Fix unable to handle Java error in doAs

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/CreateFileset.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestFilesetCommands.java
In `CreateFileset.java`, the `handle()` method directly called `properties.get("managed").equals("true")`, which could throw a `NullPointerException` if the `managed` property was missing.  
This PR updates the code to use a null-safe check and defaults to external mode (`Fileset.Type.EXTERNAL`) when the property is not set.
Without this fix, missing `managed` properties could cause NPEs, breaking fileset creation.  
Adding a null-safe check ensures that missing properties are handled gracefully and the command defaults to external mode.
Fixes #8083 
No. Valid requests behave the same. Invalid or missing `managed` properties are now safely handled without throwing exceptions.
- Manually verified locally that creating filesets without the `managed` property defaults to external mode.  
- …
> [#8083] fix: null-safe handling of 'managed' property in CreateFileset.java

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateModelVersionAliases.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestModelCommands.java
display an error if both alias and version are null in UpdateModelVersionAliases
Fix: #8158 
Unit testing
> [8158] improvement: display an error if both alias and version are null in UpdateModelVersionAliases

- clients/cli/src/main/java/org/apache/gravitino/cli/ParseType.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestParseType.java
This PR updates the `ParseType` class to support parsing of nested complex types (e.g. `list(list(integer))`, `map(string,list(integer))`).  
Currently, the CLI only supports simple types or single-level lists/maps.  
It fails for more complex definitions like `list(list(integer))` or `map(string,list(integer))`.  
Fix: #8159
Users can now define more complex schemas in the CLI, such as:
- `list(list(integer))`
- `map(string,list(integer))`
- Added new unit tests:
- `testParseTypeNestedList`
- `testParseTypeMapWithNestedValue`
- Executed existing unit tests
> [#8159] improvement(cli): Use toType() instead of toBasicType() for support more complex types

- docs/trino-connector/catalog-postgresql.md
Update document for uppercase table and column names not supported in trino-connector
Fix: #7355
Update documents
NO
> [#7355] fix (doc): Update document for uppercase table and column names not supported in trino-connector  of PostgreSQL catalog

- clients/client-python/gravitino/dto/rel/sort_order_dto.py
- clients/client-python/tests/unittests/dto/rel/test_sort_order_dto.py
This PR is aimed at implementing class `SortOrderDTO` corresponding to the one in Java client.
We need to support table partitioning, bucketing and sort ordering and indexes
#5199
No
Unit tests
> [#5199] feat(client-python): add sort order DTO

- core/src/main/java/org/apache/gravitino/catalog/EntityCombinedFileset.java
- core/src/test/java/org/apache/gravitino/catalog/TestEntityCombinedFileset.java
In `EntityCombinedFileset.java`, the `properties()` method directly called `hiddenProperties.contains()` without null checking, which could throw a `NullPointerException` if `hiddenProperties` was not initialized. This PR updates the code to initialize `hiddenProperties` with an empty set and adds null-safe handling in the `withHiddenProperties()` method.
Without this fix, calling `properties()` on an `EntityCombinedFileset` instance before setting hidden properties could cause NPEs, breaking fileset property retrieval. Adding proper initialization ensures that the object is always in a valid state and handles missing hidden properties gracefully.
Fixes #8168
No. Valid requests behave the same. Cases where `hiddenProperties` was not explicitly set are now safely handled without throwing …
> [#8168] Fix NPE in EntityCombinedFileset by initializing hiddenProperties field

- spark-connector/spark-common/src/main/java/org/apache/gravitino/spark/connector/utils/SparkPartitionUtils.java
- spark-connector/spark-common/src/test/java/org/apache/gravitino/spark/connector/utils/TestSparkPartitionUtils.java
Checks for null values in toGravitinoLiteral before proceeding to prevent NPE
Improvement to prevent NPE in SparkPartitionUtils.
Fix: #8086
no
Unit testing
> [#8086] improvement(spark): prevent NPE in SparkPartitionUtils 

- mcp-server/mcp_server/main.py
- mcp-server/mcp_server/tools/metadata.py
change the tag of metadata tool to `tag` and `policy` 
metadata tool is used only for `tag` and `policy` 
no
testing whether export metadata tools for tag and policy
> [MINOR] improve(mcp):  change the tag of metadata tool to tag and policy

- clients/client-python/gravitino/filesystem/gvfs_storage_handler.py
- clients/client-python/tests/unittests/test_storage_handler.py
Configurations from GVFS clients will override those from Gravitino server.
Let the user customize their own settings.
Fix: #8205 
N/A.
UT and existing tests.
> [#8205] improvement(client-python): Make GVFS configuration prior to that of catalogs from Gravitino server.

- common/src/main/java/org/apache/gravitino/dto/rel/TableDTO.java
- common/src/test/java/org/apache/gravitino/dto/rel/TestTableDTO.java
Added missing validation to TableDTO.Builder.build() to make sure the table has a non-null, non-empty column list before construction,
Improvement to make sure the table has a non-null, non-empty column list before construction,
Fix: #8196 
no
unit testing
> [#8196]Improvement(TableDto): validation in TableDTO Builder

- core/src/main/java/org/apache/gravitino/lock/TreeLock.java
Fixed log messages in `TreeLock.lock()` and `TreeLock.unlock()` to output the actual lock type (`type`) used.
Reflect the real lock type applied at each node at log.
Fix: #8199
Yes, Log messages will now output the actual lock type in  `TreeLock.lock()` and `TreeLock.unlock()`.  
Verified log output manually during lock/unlock operations.
> [#8199] improvement(core): correct lock type in TreeLock log messages

- clients/client-python/gravitino/api/expressions/indexes/index.py
- clients/client-python/gravitino/api/expressions/indexes/indexes.py
- clients/client-python/gravitino/dto/rel/indexes/__init__.py
- clients/client-python/gravitino/dto/rel/indexes/index_dto.py
- clients/client-python/tests/unittests/dto/rel/test_index_dto.py
This PR is aimed at implementing the class `IndexDTO` corresponding to the Java client.
We need to support table partitioning, bucketing and sort ordering and indexes.
#5199
No
Unit tests
> [#5199] feat(client-python): add index DTO

- clients/filesystem-hadoop3/src/main/java/org/apache/gravitino/filesystem/hadoop/GravitinoVirtualFileSystem.java
Remove redundant operation parameter from LOG.warn call in runWithExceptionTranslation method. The message is already formatted with the operation using String.format(), so passing the operation parameter again to LOG.warn is incorrect and redundant.
This change makes the logging consistent with other catch blocks in the same method.
**Title:** `[#8285] fix(filesystem): remove redundant operation parameter in LOG.warn call`
This PR fixes a redundant parameter issue in the `LOG.warn` call within the `runWithExceptionTranslation` method of `GravitinoVirtualFileSystem.java`. 
**Change made:**
- Removed the redundant `operation` parameter from `LOG.warn(message, operation, e)` 
- Changed it to `LOG.warn(message, e)` to match the correct SLF4J logging pattern
The current code incorrectly …
> [#8285] Fix redundant operation parameter in LOG.warn call

- core/src/main/java/org/apache/gravitino/storage/relational/service/GroupMetaService.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/JobTemplateMetaService.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/ModelMetaService.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/ModelVersionMetaService.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/PolicyMetaService.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/RoleMetaService.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/TableColumnMetaService.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/TableMetaService.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/TagMetaService.java
- core/src/main/java/org/apache/gravitino/storage/relational/service/UserMetaService.java
- core/src/main/java/org/apache/gravitino/storage/relational/session/SqlSessions.java
- core/src/main/java/org/apache/gravitino/storage/relational/utils/SessionUtils.java
- core/src/test/java/org/apache/gravitino/storage/relational/session/TestSqlSession.java
- add sessionCount for lifecycle management
Fix: #7744
no
tests added
> [#7744] improvement(core): allow nested SqlSession call

- core/src/test/java/org/apache/gravitino/storage/relational/service/TestModelMetaService.java
**What changes were proposed in this pull request?**
In `TestModelMetaService.java`, the tests testInsertAndUpdateModelComment and testInsertAndUpdateModelProperties were incorrectly setting the name and comment fields. This PR fixes the assignments so that name and comment are updated correctly according to the test's intent.
**Why are the changes needed?**
Previously, the tests would either overwrite the name with a comment value or keep the comment unchanged, causing the tests to not properly verify updates. Fixing the assignments ensures that comment updates and property updates are correctly tested.
Fixes: #8282
**Does this PR introduce any user-facing change?**
No. This only fixes test behavior.
**How was this patch tested?**
- Corrected field assignments in the affected tests.
- …
> Fix incorrect name/comment assignment in TestModelMetaService tests

- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/GravitinoConnectorFactory.java
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/system/GravitinoSystemConnector.java
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/system/storedprocedure/AlterCatalogStoredProcedure.java
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/system/storedprocedure/CreateCatalogStoredProcedure.java
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/system/storedprocedure/DropCatalogStoredProcedure.java
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/system/storedprocedure/GravitinoStoredProcedure.java
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/system/storedprocedure/GravitinoStoredProcedureFactory.java
A typo was present in the package name, which is a code quality issue that can lead to confusion. This PR corrects the spelling to improve code correctness and maintainability.
Fix: #8284
No, this PR does not introduce any user-facing changes. The changes are purely internal refactoring of package and directory names.
The patch was tested by successfully building the trino-connector module and the entire project using the following Gradle command with JDK 17, which confirmed that the refactoring was applied correctly and did not introduce any compilation errors.
Module-specific build: ./gradlew :trino-connector:trino-connector:build -x test
Full project build and test run: ./gradlew clean build
> [#8284] fix(trino-connector): Correct misspelled package name 'storedprocdure'

- core/src/main/java/org/apache/gravitino/hook/AccessControlHookDispatcher.java
Only` notify the user when a role deletion succeeds.
To prevent errors and only notify the user when a role deletion succeeds.
Fixes: #8113
No.
CI passed
> [#8113] Improvement to only notify the user when a role deletion succeeds

- bundles/gcp/src/main/java/org/apache/gravitino/gcs/credential/GCSTokenProvider.java
- bundles/gcp/src/test/java/org/apache/gravitino/gcs/credential/TestGCSTokenProvider.java
Handle the empty URI path in normalizeUriPath in GCSTokenProvider 
Currently the method normalizeUriPath in GCSTokenProvider.java doesn't handle empty paths correctly.
Fix: #8280 
NO
Unit testing
> [#8280]Improvement(GCSTokenProvider): handle empty uri path

- server/src/main/java/org/apache/gravitino/server/web/rest/CatalogOperations.java
Move success log message inside conditional block to avoid misleading logs in `CatalogOperations.java` .
Fixes #8346
No.
- Ran `./gradlew clean build`
> [#8346] fix(server): fix misleading log message in catalog drop operation

- common/src/main/java/org/apache/gravitino/config/ConfigBuilder.java
- core/src/test/java/org/apache/gravitino/TestConfig.java
Add trim() method on the value string in valudeConvertor in ConfigBuilder.java.
Params with spaces can be parsed correctly. Otherwise it will throw exceptoin.
Fix: #8341 
NO
Unit test added.
>  [#8341]  improvement(config): ake sure ConfigBuilder params with leading/trailing spaces are parsed correctly

- catalogs/hive-metastore-common/src/test/java/org/apache/gravitino/hive/hms/ScriptRunner.java
---
- Updated `ScriptRunner.java` so that `conn.rollback()` is **not always called**.  
- Rollback is now only performed when:  
- `autoCommit` is set to `false`, **and**  
- an exception occurs during script execution.  
- Moved `conn.rollback()` logic from the `finally` block into the `catch` block.  
- Cleaned up control flow to avoid unnecessary rollback calls after successful commits.  
---
---
Previously, `conn.rollback()` was called in the `finally` block regardless of connection mode.  
- When `autoCommit = true`, rollback has no effect and is misleading.  
- When a commit was already performed successfully, rollback was still invoked unnecessarily.  
This change makes rollback behavior **cleaner and safer**, ensuring it is only triggered when actually required.  
---
---
-  No …
> [#8306] Avoid rollback when autocommit is true in ScriptRunner.java

- web/web/src/app/metalakes/metalake/rightContent/LinkVersionDialog.js
- web/web/src/app/metalakes/metalake/rightContent/tabsContent/detailsView/DetailsView.js
- web/web/src/components/DetailsDrawer.js
- web/web/src/lib/utils/index.js
1. Web UI supports model version with multiple URIs
2. support edit aliases
N/A
Fix: #7438
N/A
munually
> [#7438] subtask(UI): Web UI supports model version with multiple URIs

- server/src/main/java/org/apache/gravitino/server/web/rest/CatalogOperations.java
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/iceberg/IcebergCatalogPropertyConverter.java
Title: [#8308] fix(iceberg): throw TrinoException when `catalog-backend` is missing
- Add an explicit check for a missing `catalog-backend` in `gravitinoToEngineProperties(...)` and throw a `TrinoException` with `GravitinoErrorCode.GRAVITINO_MISSING_REQUIRED_PROPERTY`.
- Keep existing backend property validators unchanged.
- No other functional changes.
- Prevent a potential `NullPointerException` when switching on a `null` backend.
- Align behavior with existing code paths and the review request.
Fixes: #8308
- No breaking changes.
- Users now receive a clear error when the required `catalog-backend` property is missing.
- Existing tests pass.
- Manual verification of error message and code.
Files touched:
- `trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connect …
> feat: thrown a TrinoException if catalog-backend is missing #1

- catalogs/catalog-common/src/main/java/org/apache/gravitino/catalog/lakehouse/iceberg/IcebergConstants.java
- docs/iceberg-rest-service.md
- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/provider/DynamicIcebergConfigProvider.java
add default catalog for dynamic config proivder
Fix: #7395  
no
test in local env, after setting `default-catalog-name`, the Spark Iceberg side doesn't need to specify `warehouse`
> [#7395] fix(iceberg): add default catalog for dynamic config proivder for IRC

- clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoClientBase.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoVersion.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestGravitinoVersion.java
- clients/client-python/gravitino/client/gravitino_client_base.py
- clients/client-python/gravitino/client/gravitino_version.py
- clients/client-python/tests/unittests/test_gravitino_version.py
Fix the Gravitino client-side version verification to ignore patch version numbers
Fix: https://github.com/apache/gravitino/issues/4707
NO
UTs
> [#4707] fix (client): Fix the Gravitino client-side version verification to ignore patch version numbers

- api/src/main/java/org/apache/gravitino/exceptions/AuthorizationPluginException.java
- Removed the direct call to `String.format` in `AuthorizationPluginException` constructors.  
- Delegated `(message, args)` directly to `GravitinoRuntimeException`.  
- This ensures messages containing `%` (like `"100% done"`) are not misinterpreted as format specifiers when no args are passed.
Currently, `AuthorizationPluginException` always formats the message string.  
This causes errors when the message includes `%` but no formatting arguments are provided (e.g., `"100% done"`).  
By removing premature formatting and letting the parent class handle it, we avoid these errors and maintain expected behavior.
Fixes: #8390
Yes.  
- Exception messages are now preserved as-is if no formatting arguments are provided.  
- Example: `"100% done"` will no longer cause a …
> [#8390] fix(api): remove premature String.format in AuthorizationPluginException

- bundles/azure/build.gradle.kts
- docs/fileset-catalog-with-adls.md
- docs/fileset-catalog-with-gcs.md
Add more details and fix errors about how to use PySpark to access Azure Blob Storage and GCS via GVFS
For better user experience.
Fix: #8391 
N/A.
Test locally.
> [#8391] fix(docs): Fix error in documents about how to use bundle jars for Azure Blob Storage and GCS

- core/src/test/java/org/apache/gravitino/storage/relational/service/TestOwnerMetaService.java
Removed the redundant invocation of `OwnerMetaService.setOwner(...)` in `TestOwnerMetaService.testDeleteMetadataObject`.
The test invoked `setOwner(...)` twice with the same parameters, causing duplicate rows and an integrity constraint error. 
Fix: #8367  
Related: #7110, #8293
No user-facing changes.
Executed existing unit tests
> [#8367] improvement(core): Remove duplicate setOwner call in TestOwnerMetaService.testDeleteMetadataObject

- clients/client-java/src/main/java/org/apache/gravitino/client/FilesetCatalog.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoMetalake.java
- clients/client-java/src/main/java/org/apache/gravitino/client/GravitinoVersion.java
- clients/client-java/src/main/java/org/apache/gravitino/client/HTTPClient.java
- clients/client-java/src/main/java/org/apache/gravitino/client/MetadataObjectCredentialOperations.java
- clients/client-java/src/main/java/org/apache/gravitino/client/MetadataObjectRoleOperations.java
- clients/client-java/src/main/java/org/apache/gravitino/client/MetadataObjectTagOperations.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestFilesetCatalog.java
- clients/client-java/src/test/java/org/apache/gravitino/client/TestGravitinoVersion.java
- clients/client-python/gravitino/client/fileset_catalog.py
- clients/client-python/gravitino/client/generic_model_catalog.py
- clients/client-python/gravitino/client/gravitino_client_base.py
- clients/client-python/gravitino/client/gravitino_metalake.py
- clients/client-python/gravitino/client/metadata_object_credential_operations.py
- clients/client-python/gravitino/filesystem/gvfs_base_operations.py
- clients/client-python/tests/unittests/test_gravitino_client.py
- clients/filesystem-hadoop3/src/test/java/org/apache/gravitino/filesystem/hadoop/TestGvfsBase.java
- common/src/main/java/org/apache/gravitino/Version.java
- common/src/main/java/org/apache/gravitino/rest/RESTUtils.java
- server-common/src/main/java/org/apache/gravitino/server/web/Utils.java
- server/src/main/java/org/apache/gravitino/server/web/rest/FilesetOperations.java
- server/src/test/java/org/apache/gravitino/server/web/rest/TestFilesetOperations.java
This PR mainly fixes server things:
1. Fix the double encoding issue. Because Java and Python client will automatically encode the query parameters. Doing it manually will encode the string twice, which will lead to unexpected issues.
2. Add missing encoding in the URL.
3. Add a client version number in the header to let the server check and do the action based on the version.
Fix the double encoding problem.
Fix: #8335 
Yes, the change will break the backward compatibility for fileset related interfaces.
Local test.
> [#8335] fix(client): Fix double encoding issue and add missing URL encoding

- .github/workflows/access-control-integration-test.yml
- .github/workflows/python-integration-test.yml
Increase the timeout to 90 minutes for Python and Ranger CI Test.
To make the CI more stable without rerun.
No.
N/A
> [MINOR] improve(CI): Increase the CI timeout for Python and Ranger test

- api/src/test/java/org/apache/gravitino/stats/TestPartitionRange.java
Fix the assertion to make default order compare to `range2.comparator()`
The assertion always true. Make it workable.
No
Unit Test
> [#8380] fix: Fix test in TestPartitionRange

- clients/client-python/gravitino/api/types/json_serdes/base.py
- clients/client-python/gravitino/dto/rel/partitioning/json_serdes/__init__.py
- clients/client-python/gravitino/dto/rel/partitioning/json_serdes/partitioning_serdes.py
- clients/client-python/gravitino/dto/rel/partitioning/partitioning.py
- clients/client-python/gravitino/utils/serdes.py
- clients/client-python/tests/unittests/dto/rel/test_partitioning_serdes.py
This PR is aimed at implementing the following classes corresponding to the Java client.
JsonUtils.java
- PartitioningSerializer
- PartitioningDeserializer
We need to support table partitioning, bucketing and sort ordering and indexes
#5199
No
Unit tests
> [#5199] feat(client-python): add partitioning DTO serdes

- catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/converter/DorisExceptionConverter.java
- catalogs/catalog-jdbc-doris/src/main/java/org/apache/gravitino/catalog/doris/utils/DorisUtils.java
- catalogs/catalog-jdbc-doris/src/test/java/org/apache/gravitino/catalog/doris/converter/TestDorisExceptionConverter.java
- catalogs/catalog-jdbc-doris/src/test/java/org/apache/gravitino/catalog/doris/utils/TestDorisUtils.java
Fixed the `DorisUtils.extractBucketNum()` method to properly handle `BUCKETS AUTO` parsing for `DISTRIBUTED BY RANDOM` statements. The method was incorrectly calling `matcher.find(5)` which advances the matcher position, causing the bucket value extraction to fail and resulting in a `NumberFormatException` when parsing null values.
**Changes:**
- Changed `if (matcher.find(5))` to `if (matcher.group(5) != null)` in `DorisUtils.extractBucketNum()`
- Added test case for `DISTRIBUTED BY RANDOM BUCKETS AUTO` in `TestDorisUtils.testDistributedInfoPattern()`
This fixes a critical bug where Doris table operations fail when encountering `DISTRIBUTED BY RANDOM BUCKETS AUTO` syntax. The root cause was that `matcher.find(5)` advances the matcher position after the initial match, and since there are …
> [#8218] fix(doris): Fix BUCKETS AUTO parsing for RANDOM distribution

- iceberg/iceberg-rest-server/src/main/java/org/apache/gravitino/iceberg/service/CatalogWrapperForREST.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/service/rest/IcebergRestTestUtil.java
- iceberg/iceberg-rest-server/src/test/java/org/apache/gravitino/iceberg/service/rest/TestIcebergConfig.java
passing s3.path-style-access to the client side in Iceberg REST server 
Fix: #8435 
no
adding UT
> [#8435] feat(iceberg): passing s3.path-style-access to the client side in Iceberg REST server

- flink-connector/flink/src/main/java/org/apache/gravitino/flink/connector/utils/TypeUtils.java
- flink-connector/flink/src/test/java/org/apache/gravitino/flink/connector/utils/TestTypeUtils.java
- trino-connector/integration-test/src/test/resources/trino-ci-testset/testsets/jdbc-postgresql/00006_datatype.txt
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/hive/HiveDataTypeTransformer.java
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/iceberg/IcebergDataTypeTransformer.java
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/mysql/MySQLDataTypeTransformer.java
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/postgresql/PostgreSQLDataTypeTransformer.java
- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/util/GeneralDataTypeTransformer.java
- trino-connector/trino-connector/src/test/java/org/apache/gravitino/trino/connector/util/TestDataTypeTransformer.java
Fix: #8215 
No
UT already added.
> [#8215] connector(trino/flink): Support for reading/writing time precision

- clients/client-python/tests/integration/test_gvfs_with_s3.py
Comment the line `fs.operations._catalog_cache.clear()` 
_catalog_cache will not initialized when `ENABLE_FILESET_METADATA_CACHE_DEFAULT` is changed to false.
N/A
> [MINOR] fix(test): Disable `_catalog_cache.clear`  when cache is diabled.

- clients/cli/src/main/java/org/apache/gravitino/cli/Properties.java
- clients/cli/src/test/java/org/apache/gravitino/cli/PropertiesTest.java
Fix delimiters in Properties.java, make sure it split string correct with custom delimiter
Fix: #8409 
no
add unit tests
> [#8409]Fix delimiters in Properties.java

- core/src/test/java/org/apache/gravitino/job/local/TestLocalJobExecutor.java
Correct the LocalJobExecutor test teardown to run after each test 
Fix: #([8486](https://github.com/apache/gravitino/issues/8486))
N/A
N/A
> [#8486] Improvement(core): Correct the LocalJobExecutor test teardown to run after each test

- trino-connector/trino-connector/src/main/java/org/apache/gravitino/trino/connector/catalog/jdbc/JDBCCatalogPropertyConverter.java
- trino-connector/trino-connector/src/test/java/org/apache/gravitino/trino/connector/catalog/jdbc/TestJDBCCatalogPropertyConverter.java
JDBCCatalogPropertyConverter.java converter where the required property set mistakenly includes the password key twice
Fix: #8484
N/A
org.apache.gravitino.trino.connector.catalog.jdbc.TestJDBCCatalogPropertyConverter#testMissingConnectionUrl
> [#8484] Improvement(trino):JDBCCatalogPropertyConverter.java converter where the required property set mistakenly includes the password key twice

- core/src/main/java/org/apache/gravitino/credential/CredentialCacheKey.java
- core/src/test/java/org/apache/gravitino/credential/TestCredentialCacheKey.java
Added a missing space between the `credentialType` and `credentialContext` fields in the `toString()` output of `CredentialCacheKey`, improving its readability.
The missing space made the string representation less readable and could confuse debugging or log parsing. This fix ensures clear separation between fields and improves developer experience while interpreting the output.
Fix: #8511 
Yes—minor formatting improvement seen in log outputs, error messages, or any usage of `toString()` on `CredentialCacheKey`. No behavioral changes.
- Added unit test to verify the spaced output in `toString()` includes `"credentialType: <type> credentialContext:"`.
> [#8511] improvement(core): add missing space in CredentialCacheKey.toString()

- catalogs/catalog-jdbc-postgresql/src/main/java/org/apache/gravitino/catalog/postgresql/converter/PostgreSqlExceptionConverter.java
Update `PostgreSqlExceptionConverter` so that SQLState codes in class "08" (connection errors) are mapped to a more specific `ConnectionFailedException` instead of the generic `GravitinoRuntimeException`.
Previously, PostgreSQL connection-related errors (SQLState class "08") were reported as generic runtime exceptions, making it harder for clients and higher layers to distinguish connection failures from other SQL errors.  
This change improves error handling by returning a more meaningful exception, allowing callers to react appropriately (e.g., retrying connections).
Fix: #8509 
Yes.  
Users interacting with Gravitino via the PostgreSQL catalog will now receive a `ConnectionFailedException` for SQLState class "08" errors instead of a generic `GravitinoRuntimeException`.
N/A
> [#8509] improvement(catalog-postgresql): map SQLState class "08" to ConnectionFailedException

- core/src/main/java/org/apache/gravitino/metrics/MetricNames.java
- server-common/src/main/java/org/apache/gravitino/server/web/HttpServerMetricsSource.java
- server-common/src/test/java/org/apache/gravitino/server/web/TestHttpServerMetricsSource.java
Expose these jetty server thread pool metrics - 
min-threads
max-threads
total-threads
busy-threads
idle-threads
queued-requests
This PR exposes more metrics about jetty server. We can observe if the server is overloaded by checking idle-threads, busy-threads, as well as queued requests.
Fix: #8593
No
1. Unit test added
2. Tested in our staging / production deployment
> [#8593]improve(server): expose more server metrics

- catalogs/catalog-jdbc-oceanbase/src/main/java/org/apache/gravitino/catalog/oceanbase/operation/OceanBaseTableOperations.java
- catalogs/catalog-jdbc-oceanbase/src/test/java/org/apache/gravitino/catalog/oceanbase/operation/TestOceanBaseTableOperations.java
Use of continue instead of return in alterTable method so that empty SQL statements no longer stop processing subsequent changes.
empty SQL statements no longer stop processing subsequent changes in alterTable method 
Fix: #8381
No
Unit testing
> [#8381]Improvement(OceanbaseTableOperations):   empty SQL statements should not stop all SQL statements in alterTable

- core/src/main/java/org/apache/gravitino/storage/relational/mapper/provider/postgresql/ModelMetaPostgreSQLProvider.java
Fixed a missing space in the `insertModelMetaOnDuplicateKeyUpdate` query where the column list directly followed `TABLE_NAME` without whitespace.
Fix: #8664
No user-facing changes.
Executed existing unit tests
> [#8664] improvement(core): add missing space between the table name and column list in insertModelMetaOnDuplicateKeyUpdate query

- clients/client-python/gravitino/api/metadata_object.py
- clients/client-python/gravitino/api/metadata_objects.py
- clients/client-python/gravitino/client/base_schema_catalog.py
- clients/client-python/gravitino/client/generic_fileset.py
- clients/client-python/tests/unittests/test_metadata_objects.py
This PR is aimed at implementing the following classes corresponding to the Java client.
MetadataObjects.java
A refactor of `MetadataObject` and of `MetadataObjectImpl` are included as well to conform with the up-to-date implementation in Java client.
We need to support python client for table operations.
#8627
No
Unit tests
> [#8627] feat(client-python): add metadata objects

- server/src/main/java/org/apache/gravitino/server/web/rest/PolicyOperations.java
- server/src/test/java/org/apache/gravitino/server/web/rest/TestPolicyOperations.java
This PR cherry-picks the fix from the merged pull request #8681 onto the `branch-1.0` maintenance branch.
To apply the important bug fix for `setPolicy` exception handling to the stable `1.0` release branch, ensuring users of that version also benefit from the correction.
Fix: #8661
Yes. The error response returned to an API user when a `disable` policy operation fails is now correctly identified. This aligns the behavior of `branch-1.0` with the `main` branch for this scenario.
- The original change was fully tested with a new unit test in pull request #8681.
- Verified that the commit cherry-picks cleanly onto `branch-1.0`.
- All existing tests in the `:server` module were run against this branch and continue to pass.
> [Cherry-Pick][branch-1.0] [#8661] fix(server): Correct exception handling in setPolicy

- clients/cli/src/main/java/org/apache/gravitino/cli/ParseType.java
- clients/cli/src/test/java/org/apache/gravitino/cli/TestParseType.java
- Added support for parsing `decimal(p)` as `precision=p, scale=0`
- Preserved existing behavior for `decimal(p,s)`
- Updated regex in ParseType to allow spaces after type name
- Added unit tests for `decimal(10)`, case-insensitivity, and invalid inputs
- All unit tests in TestParseType passed locally
This is my first contribution to Gravitino.
Feedback and suggestions are very welcome. Thank you!
> [#8679] cli: support decimal(precision) with default scale=0

- api/src/main/java/org/apache/gravitino/job/JobTemplateChange.java
- api/src/main/java/org/apache/gravitino/job/SupportsJobs.java
- api/src/test/java/org/apache/gravitino/job/TestJobTemplateChange.java
- clients/client-python/gravitino/api/job/job_template_change.py
- clients/client-python/gravitino/api/job/supports_jobs.py
- clients/client-python/tests/unittests/job/__init__.py
- clients/client-python/tests/unittests/job/test_job_template_change.py
- core/src/main/java/org/apache/gravitino/job/JobManager.java
- core/src/main/java/org/apache/gravitino/job/local/LocalJobExecutor.java
Add the Java and Python APIs for job template alteration.
This is the 1st pr of supporting job template alteration.
Fix: #8638 
Yes.
Add UTs.
> [#8638] feat(api): Add Java and Python interface for job template alteration

- api/src/main/java/org/apache/gravitino/stats/PartitionRange.java
- api/src/test/java/org/apache/gravitino/stats/TestPartitionRange.java
This PR adds a `Preconditions.checkArgument` to the `upTo(String, BoundType, SortOrder)` method in `PartitionRange.java` to ensure the `comparator` argument is not null.
The `upTo` method was missing a null check for its `comparator` argument. This was inconsistent with the other factory methods (`downTo`, `between`) in the same class. Without this check, passing a `null` comparator could lead to a `NullPointerException` later in the execution path, making it harder to debug. This change ensures the method fails early with a clear error message.
Fix: #8655
Yes. Calling `PartitionRange.upTo(...)` with a `null` comparator will now immediately throw an `IllegalArgumentException`, which is the intended and consistent behavior for the class.
- Added a new unit test, …
> [#8655] fix(api): Add null check for comparator in PartitionRange

- core/src/main/java/org/apache/gravitino/cache/EntityCacheWeigher.java
- core/src/test/java/org/apache/gravitino/cache/TestCacheConfig.java
Adjust the weight value for the entity `metalake` and `catalog` to prevent it from being evicted easily.  Entities with a higher weight value are more likely to be evicted, so we need to make it smaller for entities with types `metalake` and `catalog`.
Metalakes and catalogs are frequently accessed entities that can always keep them in memory.
Fix: #8697
N/A
UTs
> [#8697] improvement(core): Adjust weight value for entities with type `metalake` and `catalog` in Caffeine cache weighter.

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateModelVersionComment.java
- clients/cli/src/main/java/org/apache/gravitino/cli/commands/UpdateModelVersionUri.java
- clients/cli/src/test/java/org/apache/gravitino/cli/commands/TestUpdateModelVersionAliases.java
- clients/cli/src/test/java/org/apache/gravitino/cli/commands/TestUpdateModelVersionComment.java
- clients/cli/src/test/java/org/apache/gravitino/cli/commands/TestUpdateModelVersionUri.java
- Added validation for alias and version presence in UpdateModelVersionComment, UpdateModelVersionUri, and UpdateModelVersionAliases classes.
- Implemented comprehensive unit tests for validate() and handle() methods, mocking GravitinoClient, Catalog, and ModelCatalog dependencies.
- Tests cover error scenarios when both alias and version are set or both missing, and normal execution paths.
- verify internal method calls and printInformation output messages.
The changes address issue #8727 to improve validation and increase test coverage for core model version command classes. This enhances robustness and reliability in command execution by preventing invalid input parameters and ensuring internal client interactions behave as expected.
Fix: #8727
No direct API changes but improves …
> [#8727] Improvement(commands): Add alias/version validation and handle() tests to model version commands

- common/src/main/java/org/apache/gravitino/dto/requests/PolicyUpdateRequest.java
**Description:**
This Pull Request implements the improvement requested in issue #8731.
**The change:**
A validation check has been added to the **`validate()`** method of the inner class **`UpdatePolicyContentRequest`** (found in `PolicyUpdateRequest.java`) to ensure that the **`policyType` field is not null**.
The check uses `Preconditions.checkArgument(policyType != null, "\"policyType\" must not be null")` to align with the existing validation patterns in the class.
**Closes Issue:** Fixes #8731
> [#8731] fix(policy): PolicyUpdateRequest.validate checks for null policyType

- clients/cli/src/main/java/org/apache/gravitino/cli/commands/DeleteTopic.java
Fixes #8660
Add `NoSuchCatalogException` handling to the `DeleteTopic` command to provide clear error messages when attempting to delete a topic from a non-existent catalog. This aligns the exception handling with other Delete commands in the CLI module (`DeleteFileset`, `DeleteModel`, `DeleteSchema`, etc.).
- The `DeleteTopic.handle()` method was missing explicit handling for `NoSuchCatalogException`, which could result in generic error messages instead of the user-friendly `ErrorMessages.UNKNOWN_CATALOG` message
- All other Delete commands (`DeleteFileset`, `DeleteModel`, `DeleteSchema`, etc.) consistently handle `NoSuchCatalogException` with the same pattern
- This change ensures consistent error messaging across all CLI Delete commands, improving user experience when errors occur
Yes, …
> Add NoSuchCatalogException handling to DeleteTopic command
